### ISSUE TITLE
怎么实现微博里popwindow的动画

### ISSUE THREAD

**Issue by zaaach** [razerdp/BasePopup#10]
![qq 20161206113505](https://cloud.githubusercontent.com/assets/9695127/20912287/49ee488c-bba9-11e6-94aa-2fe0459a76da.gif)
popwindow是从标题栏下边弹出来的，还有个进入动画，点击其他任何地方popwindow会消失，也有消失动画，这个怎么实现的呢？求大神帮帮我

**Comment by razerdp** [comment]
好的，稍后有空我补充一下demo

**Comment by razerdp** [comment]
@zaaach 


demo已经上传，请更新到1.4.4版本。

代码链接[点我](https://github.com/razerdp/BasePopup/blob/master/app/src/main/java/razerdp/demo/popup/SelectFromTopPopup.java)

---

**ps:**

下午抽空研究了一下，发现showAtLocation在match_parent的时候，设置x或者y的offset居然是失效的。。。真的是醉了（毕竟在此之前用showAtLocation基本都能精确定位）

没有办法（源码里面大多数都是private...除非hook掉）

只好加上两个方法了：
`setShowAtDown()`：设置为true则可以使用showAsDropDown

另外增加一个点击popup外部不消失的方法，默认点击外部消失`setDismissWhenTouchOuside()`

**Comment by razerdp** [comment]
另外关于anchorView的一些参考点/位移方法特指
 - `setRelativeToAnchorView()`
 - `setRelativePivot()`

暂时不稳定，如果有这方面的需要，请慎重考虑。。。。

**Comment by razerdp** [comment]
如果问题不大，这个issue由您来关闭了哦

**Comment by zaaach** [comment]
收到，万分感谢，我先研究下

**Comment by LeeCharry** [comment]
1.8.2版本，使用setDismissWhenTouchOuside(false)方法不管用，，仍然消失

**Comment by LeeCharry** [comment]
麻烦看一下

**Comment by razerdp** [comment]
@LeeCharry 好的，麻烦新建一个issue....这个是已经关闭过的了
