### ISSUE TITLE
AutoLocatedPopup setAutoLocatePopup(true)  .setAlignBackground(true)无效

### ISSUE THREAD

**Issue by java02014** [razerdp/BasePopup#101]
### 该问题是怎么引起的？
razerdp.demo.fragment.AutoLocatedPopupFrag下的AutoLocatedPopup，点击左下角的button无法显示出来

### 重现步骤
必现

### 报错信息/系统版本
目前只测试了小米，oppo
```java

```

**Comment by razerdp** [comment]
我看看

**Comment by razerdp** [comment]
@java02014 啊哈，抱歉，是因为最近的一个更新修改了源码，导致的错误。现在改回来了
