### ISSUE TITLE
2.0.9 引用ACTIVITY，使用默认动画，内存泄漏

### ISSUE THREAD

**Issue by weitto** [razerdp/BasePopup#104]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
context在basepopupwindow里面是弱引用。

所以请确认您的activity是否因为别的原因而无法回收

**Comment by weitto** [comment]
经过测试， 把    
DrawWinnerPopup popup = new DrawWinnerPopup(this);
    popup.showPopupWindow();
注释掉，不会出现泄漏，使用就会出现

**Comment by weitto** [comment]
真的是必出啊

public class TestActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test);

        DrawWinnerPopup popup = new DrawWinnerPopup(this);
        popup.showPopupWindow();
    }
}

back键 返回    使用的是leakcanary内存泄漏检测。小米5.0系统

**Comment by weitto** [comment]
使用   compile 'com.github.razerdp:BasePopup:2.0.9'

**Comment by razerdp** [comment]
@weitto 你好，我在新的dev分支建立了改测试demo：https://github.com/razerdp/BasePopup/tree/develop

[相关Activity](https://github.com/razerdp/BasePopup/blob/develop/app/src/main/java/razerdp/demo/DemoLeakcanaryActivity.java)



引入leakcanary，并加入了一个demo，跟您的用法一致，但没有出现泄漏，如果可以，麻烦提供下

系统版本
库版本

**Comment by razerdp** [comment]
我用真机7.0、8.0试过，模拟器5.0、6.0、7.0、8.0也试过，没有leakcanary的提示。
