### ISSUE TITLE
在小米 mix2s 手机上弹出窗口的时候报了一个空

### ISSUE THREAD

**Issue by FFFmark** [razerdp/BasePopup#105]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：9.0
 - 库版本：2.0.6
 - 问题描述/重现步骤：
点击，使窗口弹出时闪退
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/25942811/49429825-77d74180-f7e4-11e8-8930-0d91db040b02.png)
 - 报错信息：
![image](https://user-images.githubusercontent.com/25942811/49429746-40689500-f7e4-11e8-8fa1-395826b934dd.png)
---

**Comment by razerdp** [comment]
你好，针对android p的限制api在2.0.7之后才会有支持，建议您升级到最新版本（2.0.9）

详情更新请看->
https://github.com/razerdp/BasePopup#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97%E5%8E%86%E5%8F%B2%E6%9B%B4%E6%96%B0

**Comment by razerdp** [comment]
issue的要求点写满的话我一般会比较快回复的-V-
