### ISSUE TITLE
弹出时屏幕变暗

### ISSUE THREAD

**Issue by folinwu** [razerdp/BasePopup#106]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：7
 - 库版本：2.0.9
 - 问题描述/重现步骤：PopupWindow弹出时屏幕变暗
 - 问题代码/截图：PopupWindow弹出时，屏幕和之前一样的亮度
 - 报错信息：

---

**Comment by razerdp** [comment]
重复问题[#98](https://github.com/razerdp/BasePopup/issues/98)
