### ISSUE TITLE
键盘遮挡

### ISSUE THREAD

**Issue by baogaolion** [razerdp/BasePopup#107]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：8.0
 - 库版本：BasePopup_Candy:2.1.0-beta5
 - 问题描述/重现步骤：虚拟键盘遮挡 View ,1.x 版本没有这个问题
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/3152351/49684011-6ce42000-fb08-11e8-9fc6-30c2186ec056.png)

**Comment by razerdp** [comment]
你好，键盘问题我目前只适配到露出Edittext为止，下个版本考虑加上指定适配哪个view。

**Comment by razerdp** [comment]
@baogaolion 请更新到2.1.2-alpha2（Candy），已经解决该问题

如果对位移不满意，您还可以通过以下方法进行干预：

```java
setEventInterceptor(new SimplePopupWindowEventInterceptor<InputPopup>() {
            @Override
            public int onKeyboardChangeResult(int keyboardHeight, boolean isKeyBoardVisible, int calculatedOffset) {
                return 0;
            }
        });
```
