### ISSUE TITLE
数据多，popup还是会遮住view全屏显示

### ISSUE THREAD

**Issue by Puppy-Love** [razerdp/BasePopup#108]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
这个是2.1.1代码被dev覆盖的原因~目前版本可以通过`setClipToScreen(false)`解决。

下个版本针对修复。

**Comment by LomoLin** [comment]
使用setClipToScreen(false)，布局显示不全，不使用又会遮盖住描点，请问这个问题要怎么解决呢

**Comment by Puppy-Love** [comment]
@LomoLin 根布局高度match_parent   setClipToScreen(true)

**Comment by LomoLin** [comment]
> @LomoLin 根布局高度match_parent setClipToScreen(true)

谢谢，我试试

**Comment by LomoLin** [comment]
> @LomoLin 根布局高度match_parent setClipToScreen(true)

还是不行，依然会充满屏幕并且遮住描点

**Comment by razerdp** [comment]
你的库版本，以及截图。
尝试更新到最新版本？

**Comment by LomoLin** [comment]
> 你的库版本，以及截图。
> 尝试更新到最新版本？

我用的是2.1.9，我现在的解决方案是动态改变高度

**Comment by LomoLin** [comment]
> 你的库版本，以及截图。
> 尝试更新到最新版本？

2.1.9已经是最新的稳定版本了

**Comment by razerdp** [comment]
那你截个图看看，以及代码，，，简单地说，补充下issue的要求

**Comment by LomoLin** [comment]
> 那你截个图看看，以及代码，，，简单地说，补充下issue的要求

  ##171 已经重新创建一个issue了
