### ISSUE TITLE
showPopupWindow()不能指定位置显示

### ISSUE THREAD

**Issue by BDwuzhou** [razerdp/BasePopup#11]
showPopupWindow(View v)和showPopupWindow(int res)传view对象和id都不起作用

**Comment by razerdp** [comment]
@BDwuzhou 您好，showPopupWindow和showPopupWindow(view)这两个方法默认情况下是以view.getWindow为准，也就是说默认情况下参考的是整个window，而只有您设置了 setRelativeToAnchorView(true);才会与view挂钩。。

不过经过您这么一提，我倒是觉得这是一个优化点。

也就是不传任何东西的时候默认获取window，穿了view之后就默认与view挂钩。。。这个倒是我忽略了

我稍后修复如何，如无意外将会是v1.5.1版本，到时候我会在这里艾特您的。

**Comment by razerdp** [comment]
如果你急着需要，可以先按照上面的方法。。。

参考的demo代码是
https://github.com/razerdp/BasePopup/blob/master/app/src/main/java/razerdp/demo/popup/CommentPopup.java

**Comment by razerdp** [comment]
@BDwuzhou 您好，已经更新到v1.5.1。

**Comment by BDwuzhou** [comment]
多谢大大，问题已经完美解决了

**Comment by razerdp** [comment]
好的
