### ISSUE TITLE
怎么点击popwindow消失popwindow呢

### ISSUE THREAD

**Issue by keien411** [razerdp/BasePopup#111]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：7.0
 - 库版本：2+
 - 问题描述/重现步骤：点击pop
 - 问题代码/截图：popDeliveryInfo.setAllowInterceptTouchEvent(true);
 - 报错信息：没有消失pop

---

我需要点击popwindow消失或者点击外部消失
两个都需要

**Comment by razerdp** [comment]
你好，popup内部的事件应该由您内部解决，比如点了某个View进行dismiss，那么您可以对那个View设置监听，点击的时候dismiss。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by keien411** [comment]
我设置了view的点击事件，但是传递不进来，是不是被拦截了？

**Comment by keien411** [comment]
> 你好，popup内部的事件应该由您内部解决，比如点了某个View进行dismiss，那么您可以对那个View设置监听，点击的时候dismiss。
> 
> Sent with [GitHawk](http://githawk.com)
我设置了view的点击事件，但是传递不进来，是不是被拦截了？
