### ISSUE TITLE
ZXingView 放进 basepopup的Dialog中 相机无法打开

### ISSUE THREAD

**Issue by zl277287818** [razerdp/BasePopup#112]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：5.0
 - 库版本：2.1.2
 - 问题描述/重现步骤：
   BGAQRCode-Android中 ZXingView 放进 basepopup的Dialog中 相机无法打开，放到自己定义的Dialog（XXXDialog extends Dialog）中却没有问题。
 - 问题代码/截图：
 - 报错信息：
   无
---

**Comment by razerdp** [comment]
你好，popupwindow是无法获取windowToken的，而dialog可以获取。所以不太建议放到Popup里。

**Comment by zl277287818** [comment]
好的 收到 谢谢
