### ISSUE TITLE
布局包含输入框的问题

### ISSUE THREAD

**Issue by zl277287818** [razerdp/BasePopup#113]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：5.0
 - 库版本：2.1.4
 - 问题描述/重现步骤：
   当布局里面包含输入框的时候，点击输入框，整个布局会顶上去，如何设置成只顶到输入框的位置呢？
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
#107

issue107有人反馈过键盘适配只能适配到edittext而不能把整个布局弹起，而你这里需要定位到edittext，综合考虑后，为了适配你们的情况，我添加了拦截器，您可以在拦截器实现键盘弹起后的偏移修正，默认弹起整个布局（如果空间足够）


具体请看107的issue，此处我在手机发，所以可能没法link过去。

**Comment by razerdp** [comment]
[#107](https://github.com/razerdp/BasePopup/issues/107)

**Comment by zl277287818** [comment]
好的 谢谢
