### ISSUE TITLE
小米8背景无法全面覆盖

### ISSUE THREAD

**Issue by Zhao187** [razerdp/BasePopup#114]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

你好小米android 8.0无法，背景覆盖全面，标题栏覆盖不到，添加recyclerview之后也是无法全面屏幕，使用的是刘海屏,使用的库是您最近的库，软件马上要上线了，希望能帮忙解决一下。

![image](https://user-images.githubusercontent.com/20716350/50376049-4f53a200-0642-11e9-9d22-95b1e13b4cfc.png)
![image](https://user-images.githubusercontent.com/20716350/50376056-6db99d80-0642-11e9-84e5-499e6a41aae3.png)

**Comment by Zhao187** [comment]
你好我用的不是release版本，更换之后，也就是2.1.4之后使用小米全面屏手机出现了
![image](https://user-images.githubusercontent.com/20716350/50376156-4b288400-0644-11e9-89df-c5c5892c9b09.png)

![wenti](https://user-images.githubusercontent.com/20716350/50376179-ba05dd00-0644-11e9-8d53-e7f443321264.png)

**Comment by razerdp** [comment]
你好，感谢反馈，因为我这里没有刘海屏手机，所以这个bug可能需要你的配合，可以加一下群或者我的qq：164701463……我们直接联系应该可以更快的修复它^o^

**Comment by razerdp** [comment]
你好，请更新到candy 2.1.5-alpha试试。~该版本与release相差的是本次的修复，我在as的模拟器模拟过了，暂无别的bug，（双显示屏凹凸暂不适配）可以当成release使用

**Comment by razerdp** [comment]
candy最新版已经fixed

测试手机：小米6X，android 8.0.1 手势全面屏。

**Comment by razerdp** [comment]
2.1.5 relese已修复

**Comment by Zhao187** [comment]
嗯嗯好的
