### ISSUE TITLE
popwindow显示多种view问题

### ISSUE THREAD

**Issue by KayeJing** [razerdp/BasePopup#115]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：无要求
 - 库版本：2.1.4
 - 问题描述/重现步骤：我的popwindow会根据参数显示不同的view 所以需要在onCreateContentView（）中判断  但是onCreateContentView会优先在构造方法第一步运行 导致参数为空
 - 问题代码/截图：

 - 报错信息： UncaughtException detected: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

---

**Comment by razerdp** [comment]
目前版本可以继承QuickPopup来实现延迟初始化，（调用callinitiInternal方法），这算是一个后门，不过目前没有打算开放延迟加载的功能。

你这个需求可以考虑加到拦截器里通过拦截器实现，下一个candy版会加上的^o^

感谢支持。

**Comment by razerdp** [comment]
candy 2.1.5-alpha2支持延迟加载。
