### ISSUE TITLE
依赖后编译不过

### ISSUE THREAD

**Issue by wl386123298** [razerdp/BasePopup#116]
###
 - 系统版本：Android studio 3.2.1
 - 库版本：2.1.4
 - 问题描述/重现步骤：包依赖后发现源码中很多类依赖错误，导致无法使用
 - 问题代码/截图：![pic](https://i.loli.net/2018/12/24/5c2087ed884b9.png)
 - 报错信息：源码中无法导入库中对应的类，导致编译不通过，但是这些类实际是存在的

---

**Comment by razerdp** [comment]
你好，我刚在我的另一个项目测试过了，没有出现你所说的问题。

https://github.com/razerdp/FriendCircle/blob/master/circle_base_library/build.gradle#L45

以及，您是否使用过candy，详见README的注意事项

**Comment by wl386123298** [comment]
因为我的项目是用koltin，也可能是我的IDE挂了，我正在实验

**Comment by razerdp** [comment]
kt没影响的，我们群里有几位用kt的也是一直这么用~

**Comment by wl386123298** [comment]
确定是我的ide问题了，不好意思。close吧
