### ISSUE TITLE
setAlignBackground为什么无效呢

### ISSUE THREAD

**Issue by 574085757** [razerdp/BasePopup#117]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：6.0
 - 库版本：2.1.4
 - 问题描述/重现步骤：
 - 问题代码/截图：
 //创建筛选条件选择框
                if (null == filtratePopup) {
                    filtratePopup = FiltratePopup(activity)
                    filtratePopup!!.setAlignBackground(true)
                    filtratePopup!!.onDismissListener = object : BasePopupWindow.OnDismissListener() {
                        override fun onDismiss() {
                            //dismiss事件
                            setSelectImgAndColor(tv_home_filtrate, false)
                        }
                    }
                }
                //创建城市筛选框
                if (!filtratePopup!!.isShowing) {
                    setSelectImgAndColor(tv_home_filtrate, true)
                    //show
                    filtratePopup!!.showPopupWindow(ll_home_center)
                }
 - 报错信息：
ll_home_center上方背景也变暗了
---

**Comment by razerdp** [comment]
布局方便贴出来吗

**Comment by 574085757** [comment]
> 布局方便贴出来吗

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:orientation="vertical"
              android:background="@color/white"
              android:layout_width="match_parent"
              android:layout_height="@dimen/qb_px_300">
    <View style="@style/LineStyle"/>
    <include
            android:visibility="gone"
            layout="@layout/layout_status"/>

    <android.support.v4.widget.NestedScrollView
            android:scrollbars="vertical"
            android:fadeScrollbars="false"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1">
        <LinearLayout
                android:paddingTop="@dimen/qb_px_12"
                android:paddingLeft="@dimen/qb_px_24"
                android:paddingRight="@dimen/qb_px_24"
                android:paddingBottom="@dimen/qb_px_12"
                android:orientation="vertical"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1">
            <TextView
                    android:id="@+id/tv_filtrate_school_nature"
                    android:textColor="@color/color_6F5D5B"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="@dimen/qb_px_12"
                    android:text="@string/school_nature"/>
            <com.google.android.flexbox.FlexboxLayout
                    android:id="@+id/flexbox_nature"
                    app:flexWrap="wrap"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">
            </com.google.android.flexbox.FlexboxLayout>
            <TextView
                    android:id="@+id/tv_filtrate_school_feature"
                    android:layout_marginTop="@dimen/qb_px_24"
                    android:textColor="@color/color_6F5D5B"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="@dimen/qb_px_12"
                    android:text="@string/school_feature"/>
            <com.google.android.flexbox.FlexboxLayout
                    android:id="@+id/flexbox_feature"
                    app:flexWrap="wrap"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">
            </com.google.android.flexbox.FlexboxLayout>
            <TextView
                    android:id="@+id/tv_filtrate_school_auth"
                    android:layout_marginTop="@dimen/qb_px_24"
                    android:textColor="@color/color_6F5D5B"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="@dimen/qb_px_12"
                    android:text="@string/platform_auth"/>
            <LinearLayout
                    android:layout_marginTop="@dimen/qb_px_12"
                    android:gravity="center_vertical"
                    android:orientation="horizontal"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">
                <TextView
                        android:textSize="@dimen/qb_px_14"
                        android:textColor="@color/color_2D1F1D"
                        android:text="@string/platform_auth"
                        android:layout_width="0dp"
                        android:layout_weight="1"
                        android:layout_height="wrap_content"/>
                <Switch
                        android:id="@+id/switch_auth"
                        android:checked="false"
                        android:padding="@dimen/qb_px_8"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"/>

            </LinearLayout>

        </LinearLayout>
    </android.support.v4.widget.NestedScrollView>

    <View style="@style/LineStyle"/>
    <LinearLayout
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="@dimen/qb_px_48">
        <TextView
                android:id="@+id/tv_filtrate_reset"
                android:gravity="center"
                android:text="@string/reset"
                android:textColor="@color/color_2D1F1D"
                android:textSize="@dimen/qb_px_16"
                android:background="?android:attr/selectableItemBackground"
                android:layout_weight="1"
                android:layout_width="@dimen/qb_px_0"
                android:layout_height="match_parent"/>
        <View android:layout_height="match_parent"
              android:layout_width="@dimen/qb_px_1"
              android:background="@color/color_EEEEEE"/>
        <TextView
                android:id="@+id/tv_filtrate_complete"
                android:gravity="center"
                android:text="@string/complete"
                android:textColor="@color/color_FF6F00"
                android:textSize="@dimen/qb_px_16"
                android:background="?android:attr/selectableItemBackground"
                android:layout_weight="1"
                android:layout_width="@dimen/qb_px_0"
                android:layout_height="match_parent"/>

    </LinearLayout>

</LinearLayout>

**Comment by razerdp** [comment]
额，你可以加群具体问一下吗。。。这里交流有点慢。。。

**Comment by 574085757** [comment]
> 额，你可以加群具体问一下吗。。。这里交流有点慢。。。

好的
