### ISSUE TITLE
用的最新beta版还是适配问题

### ISSUE THREAD

**Issue by nigelly** [razerdp/BasePopup#118]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by nigelly** [comment]
背景模糊会改变状态了为灰色，而不使用背景模糊，则没关系，

**Comment by razerdp** [comment]
请按照issue模板写，不排除部分手机无法获取状态栏颜色，那时候我会获取默认的windowbackgroun使用。
