### ISSUE TITLE
5.0机型上背景对齐无效

### ISSUE THREAD

**Issue by blackbai11** [razerdp/BasePopup#119]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by blackbai11** [comment]
Nexus 5X API 22 
库版本：2.14
背景对齐功能在高版本有效，低版本不起作用
![1](https://user-images.githubusercontent.com/17706160/50440639-15301c00-0932-11e9-9ade-b00510ac8a7a.png)
![2](https://user-images.githubusercontent.com/17706160/50440641-1b25fd00-0932-11e9-87ea-d927da7373ef.png)

**Comment by razerdp** [comment]
感谢反馈-V-

在2.1.5开始对背景蒙层进行了重构~并对这个问题进行了修复

在收到您的这个issue的时候，我打开了模拟器进行测试，在2.1.5开始没有问题呢-V-

具体可以看看更新日志：[**更新日志**](https://github.com/razerdp/BasePopup#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97-%E5%8E%86%E5%8F%B2%E6%9B%B4%E6%96%B0)

**Comment by razerdp** [comment]
您可以下载最新的代码进行验证

ps：2.1.5目前看起来是可以发布release了，但元旦后看情况再发，期间尽可能收集问题-V- 

感谢支持

**Comment by blackbai11** [comment]
哦哦，抱歉，正在用正式版，没注意2.15的更新

**Comment by blackbai11** [comment]
您好，我看见代码由mBackgroundView.offsetTopAndBottom(contentTop);
改为了mBackgroundView.layout(left, top, right, bottom);这种方式，
请教下offsetTopAndBottom在低版本失效的原因是什么？我打印的值是起作用了，是否是时间上的刷新问题？

**Comment by razerdp** [comment]
offset可能会导致多次offset，因为我在layout里面调用的（PopupDecorViewProxy#layoutWithIntercept#Line:453）之前对于多次offset有个判断，就是上一次offset跟本次offset比较（事实上，我debug的时候也发现是走到那个方法的，失效的原因我猜测可能是不同版本内部实现有点不一样，因为在layout里面执行，所以可能会放弃这次的操作）

在2.1.5我review code的时候发现我蠢了，既然都得到了contentView的left/top等信息，那为啥我不直接layout而要offset，因此从2.1.5开始直接layout。

**Comment by blackbai11** [comment]
了解了，多谢指教，另祝您节日愉快~
