### ISSUE TITLE
Popup 弹出的时候，虚拟导航栏的会跟随显示。

### ISSUE THREAD

**Issue by will746** [razerdp/BasePopup#120]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：Android8.0+
 - 库版本：Release 2.1.4  
 - 问题描述/重现步骤： Popup 弹出的时候，虚拟导航栏的会跟随显示。展示Demo也一样，有办法去除么？ 
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/16059548/50472398-94d1ef80-09f3-11e9-86d8-67ef97427bd4.png)

 - 报错信息：

---

**Comment by razerdp** [comment]
[**#59**](https://github.com/razerdp/BasePopup/issues/59)

这个问题当前不好解决。。。因为在我的测试中（demo有个全屏的activity），使用官方的也会出现这个问题，而我确实解决过这个问题，但是导致了部分开发者向我询问为什么popup出现后虚拟导航栏不见了。。。。

也就是说，默认没有导航栏而弹出后有导航栏以及默认有导航栏而弹出后没有导航栏这两部分的用户都有需求。。。正因为头疼于此，所以我这边一直没有去开启修复的方法。

**Comment by will746** [comment]
好吧。。。。

**Comment by lsqbeyond** [comment]
为何不加一个开关呢

**Comment by razerdp** [comment]
@lsqbeyond   ya，在2.1.5我也考虑过加上这方面的控制。

不过目前这个适配还不稳定，所以我得多测测之后才能发release。

**Comment by razerdp** [comment]
@will746 
@lsqbeyond 

candy 2.1.8-beta1 修复了这个问题，目前还在测试中，如果出现了问题请务必反馈一下哈~

**Comment by lly7690** [comment]
@razerdp 弹出POPUPWINDOW的时候还是会弹出导航栏（虚拟键），是要做什么设置吗？
