### ISSUE TITLE
全面屏幕无法覆盖

### ISSUE THREAD

**Issue by baogaolion** [razerdp/BasePopup#121]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：8.1.0
 - 库版本：'com.github.razerdp:BasePopup_Candy:2.1.5-alpha'；
 - 问题描述/重现步骤：遮罩层无法覆盖全屏，下面空出了；
 - 问题代码/截图：![screenshot_2018-12-29-13-55-34-054](https://user-images.githubusercontent.com/3152351/50534064-bbb63000-0b71-11e9-9ac2-76d2f1d404e3.png)

 - 报错信息：

---

**Comment by razerdp** [comment]
请更新到2.1.5-beta4

这个其实全面屏目前适配了小米的，不过因为越来越多人回复说这个问题，因此打算往2.1.5里面除了适配常见的，同时放开api让开发者指定-V-

**Comment by razerdp** [comment]
话说，请问你的是小米或者华为之一吗。。。

**Comment by razerdp** [comment]
请更新到2.1.5-prerelease

**Comment by razerdp** [comment]
2.1.5 release fixed

**Comment by baogaolion** [comment]
> 请更新到2.1.5-beta4
> 
> 这个其实全面屏目前适配了小米的，不过因为越来越多人回复说这个问题，因此打算往2.1.5里面除了适配常见的，同时放开api让开发者指定-V-

辛苦啦
