### ISSUE TITLE
全屏問題

### ISSUE THREAD

**Issue by michaelleeeee** [razerdp/BasePopup#124]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：
 - 库版本：2.1.5
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：
新版本宽度直接设置MATCH_PARENT右面还是会有边距，直接获取屏幕宽度（像素）设置大小是没问题的；

---

**Comment by razerdp** [comment]
有图片么。。。。目前我没有遇到过你的这个问题，所以不清楚你的描述。

**Comment by michaelleeeee** [comment]
![_20190102170451](https://user-images.githubusercontent.com/20056632/50585643-f5a86e80-0eb0-11e9-822e-f32ffbcb4109.png)
![_20190102170559](https://user-images.githubusercontent.com/20056632/50585644-f6410500-0eb0-11e9-8043-b9455addbb10.png)

**Comment by razerdp** [comment]
如果布局是match_parent，那么Java代码务必保证是用**createPopupById**

如果还存在，那么请问您是否根布局设置了marginRight

以及，是否设置了`setAllowInterceptTouchEvent(false)`

我需要了解这两部分内容以确保是否bug...

**Comment by michaelleeeee** [comment]
![_20190102171805](https://user-images.githubusercontent.com/20056632/50586028-baa73a80-0eb2-11e9-9e21-47850490a99e.png)
![_20190102171837](https://user-images.githubusercontent.com/20056632/50586029-bb3fd100-0eb2-11e9-9ee8-7099528b6fb6.png)
![_20190102171912](https://user-images.githubusercontent.com/20056632/50586030-bc70fe00-0eb2-11e9-8296-c5afad424b86.png)
