### ISSUE TITLE
当设置setAllowInterceptTouchEvent(true)时，会导致Gravity和offset失效

### ISSUE THREAD

**Issue by feimenggo** [razerdp/BasePopup#125]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：
 - 库版本：2.1.5
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：在没有设置setAllowInterceptTouchEvent(false)时，Gravity和offset都正常显示，但在设置setAllowInterceptTouchEvent(true)之后，Gravity和offset失效了。
---

**Comment by feimenggo** [comment]
在setAllowInterceptTouchEvent(false)时，这是我想要的效果：
![Uploading 设置前.png…]()
setAllowInterceptTouchEvent(true)之后，变成了这个样子：
![default](https://user-images.githubusercontent.com/12608693/50627158-29e16500-0f6d-11e9-95b6-f05ceb735431.png)
代码如下，两种创建方式都有这个问题：
![default](https://user-images.githubusercontent.com/12608693/50627194-572e1300-0f6d-11e9-8776-431eec383925.png)

**Comment by razerdp** [comment]
噢~是quickpopupbuilder吗，，我稍后查一下

**Comment by feimenggo** [comment]
创建类来继承的方式也一样有问题

**Comment by razerdp** [comment]
![1](https://user-images.githubusercontent.com/11629986/50628869-f1458980-0f74-11e9-8720-4affa62d7ce0.png)
![2](https://user-images.githubusercontent.com/11629986/50628873-f7d40100-0f74-11e9-804b-f6584d39b3a1.png)

为了方便复现，我用了demo的autoLocated来重现您的操作，发现似乎正常诶。。。

**Comment by razerdp** [comment]
补一个跟你api一样的图：
![tim 20190103164629](https://user-images.githubusercontent.com/11629986/50629345-27840880-0f77-11e9-9bb0-82a720539791.png)

**Comment by razerdp** [comment]
为了更方便的交流，可以加一下群。。。答案0
