### ISSUE TITLE
弹窗之后重复锁屏开屏, 弹窗视图会消失

### ISSUE THREAD

**Issue by FreeLoopC** [razerdp/BasePopup#127]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：5.1
 - 库版本：2.1.4
 - 问题描述/重现步骤：弹窗之后重复锁屏开屏, 弹窗视图会消失
 - 问题代码/截图：弹窗之后重复锁屏开屏, 弹窗视图会消失, 实际上弹窗是存在的, 只不过视图看不见了
 - 报错信息：无

---

**Comment by razerdp** [comment]
你好，请更新一下，另外我在本地模拟器测试并没有这个问题
![adfa](https://user-images.githubusercontent.com/11629986/50752363-f4988800-1288-11e9-9bbd-29d349015a48.gif)

api22
