### ISSUE TITLE
GridLayoutManager显示问题

### ISSUE THREAD

**Issue by xzm1102207843** [razerdp/BasePopup#129]
老哥问个问题，LinearLayoutManager宽带自动填充全屏， GridLayoutManager 显示如图，有办法填充剩余部分？GridLayoutManager 目前用的SDK自带的，需要自定义 GridLayoutManager 还是在你的popup设置什么东西。

 - 问题代码/截图：
![770e9376c2aa196b6816183d850185cb](https://user-images.githubusercontent.com/16155051/50961091-e2754e80-1501-11e9-89c0-97116517800d.jpg)
![d3d8bf99ef8002337f14b3236bedaab8](https://user-images.githubusercontent.com/16155051/50961095-e5703f00-1501-11e9-9e8d-4eceb4f21726.jpg)

**Comment by razerdp** [comment]
popup最外部布局宽度应是match_parent，或者你把布局文件贴出来

**Comment by xzm1102207843** [comment]
popup布局跟你demo的SlideFromTopPopup2布局一模一样，只不过目前解决方案是给popup最外部布局设置了background。如果暂时没有其它方法，我就关闭了。

**Comment by razerdp** [comment]
其实popup的contentView现在应该是填满屏幕宽度的。。。只是可能你的recyclerview的item并没有那么多，没法填满，所以正如你所说，给背景一个颜色。

**Comment by xzm1102207843** [comment]
嗯嗯 thanku
