### ISSUE TITLE
V1.4.5之后，怎么设置demo中点赞的效果

### ISSUE THREAD

**Issue by ping999** [razerdp/BasePopup#13]
如题，demo还是老版本，新的版本中没有setRelativePivot，那么怎么设置点赞的popup

**Comment by razerdp** [comment]
@ping999  setRelativePivot已经放弃了，使用showPopupWindow(View v)会自行将popup的view与目标的View左上角对齐（如果可以完整显示的情况下）。

接下来可以通过两种方式完成popup相对于view的偏移。

 - 第一种是覆写popup的showPopupWindow(View v)，在里面setOffsetX()或者Y，详情demo：
https://github.com/razerdp/BasePopup/blob/master/app/src/main/java/razerdp/demo/popup/CommentPopup.java

 - 第二种是popup.setOnBeforeShowCallback()【v1.5.0之后添加的回调】，在beforeShow里面设置offset，然后return ture就可以showpopup（retrun false则不showpopup，该回调用于调用show之前的特殊处理的）

**Comment by razerdp** [comment]
@ping999 第二个demo例子：https://github.com/razerdp/BasePopup/blob/master/app/src/main/java/razerdp/demo/fragment/SlideFromTopPopupFrag.java

另外demo一直都是新的。。。。。毕竟我的测试都在那里- -请pull一下

**Comment by ping999** [comment]
OK，谢谢
