### ISSUE TITLE
popub match_parent时有右边距

### ISSUE THREAD

**Issue by okayFan** [razerdp/BasePopup#132]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：MIUI 10.0
 - 库版本：2.1.6
 - 问题描述/重现步骤：popub match_parent时有右边距
 - 问题代码/截图：
![index](https://user-images.githubusercontent.com/20924164/51014627-be6a4980-15a3-11e9-8af9-682f9ec291b3.png)
![index 1](https://user-images.githubusercontent.com/20924164/51014656-dc37ae80-15a3-11e9-86fe-71ec4346793c.png)

 - 报错信息：

---

**Comment by razerdp** [comment]
请提供一下布局和代码

**Comment by razerdp** [comment]
布局请截全一点。。之前群里也有一位跟你类似的，他的问题是其他手机没问题，好像也是MIUI出的问题，他的布局是宽度match_parent，高度wrap_content，然后发现如果高度写死一个值，那么宽度没问题，否则的话会出现右边边距。

我这边虚拟机测试没问题，手头上也没有MIUI 10的手机，所以目前来说需要你提供完整的布局，我这边找那位朋友尝试重现

**Comment by okayFan** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    android:orientation="vertical"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:background="@color/colorWhite"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <LinearLayout
        android:gravity="center_horizontal"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="64dp">

        <TextView
            android:layout_marginTop="30dp"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="日报表"
            android:textColor="@color/colo_171B2E"
            android:textSize="@dimen/dimen_17"
            android:id="@+id/tv_title"
            android:drawableRight="@mipmap/ic_top_report"
            android:drawablePadding="7dp"
            />


    </LinearLayout>

    <android.support.v7.widget.RecyclerView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/rv_time"
        />





</LinearLayout>

**Comment by okayFan** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    android:id="@+id/ll_frame"
    android:paddingLeft="15dp"
    android:paddingRight="15dp"
    android:gravity="center_vertical"
    android:layout_width="match_parent"
    android:layout_height="44dp"
    xmlns:android="http://schemas.android.com/apk/res/android">

    <TextView
        android:id="@+id/tv_frame"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="时段报表"
        android:textSize="@dimen/dimen_14"
        android:textColor="@color/colo_FF171A2E"
        />

    <TextView
        android:id="@+id/tv_tip"
        android:layout_width="0dp"
        android:layout_weight="1"
        android:layout_height="wrap_content"
        android:text="(展示选择时间段内每日时段平均数据)"
        android:textSize="@dimen/dimen_12"
        android:layout_marginLeft="2dp"
        android:textColor="@color/colo_999999"
        />


    <ImageView
        android:id="@+id/iv_frame"
        android:background="@mipmap/ic_checked"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />



</LinearLayout>

**Comment by razerdp** [comment]
最外层那个呢

**Comment by okayFan** [comment]
晕，我直接复制的，怎么最后面都把我截取了，
最后面都是 以
</LinearLayout>结尾，没有其他了

**Comment by razerdp** [comment]
最重要的是那个噗

**Comment by okayFan** [comment]
</LinearLayout>

**Comment by okayFan** [comment]
![image](https://user-images.githubusercontent.com/20924164/51072520-f99c7380-169c-11e9-8db7-fd86424303d9.png)

**Comment by okayFan** [comment]
最后都是这个  LinearLayout结尾了

**Comment by okayFan** [comment]
上面的popub的布局，下面的popub里面recycleview的布局

**Comment by razerdp** [comment]
那个，，你加群吧。。。我找你debug一下~  答案0

**Comment by okayFan** [comment]
这是测试反馈给我的，我自己的测试手机也没畏难而退

**Comment by razerdp** [comment]
。。。噗，那就蛋疼了，，，我也想找到这个问题的原因，感觉像是8.0的坑，然而是出现在部分手机上的

**Comment by razerdp** [comment]
经讨论，部分机型会出现match_parent后测量不准的问题，暂时修复方案：setWidth(getScreenWidth())，设置宽度为屏幕宽度。
