### ISSUE TITLE
设置autoLocated为true后，如何监听切换时的状态？

### ISSUE THREAD

**Issue by sicelex** [razerdp/BasePopup#133]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：Android 9.0
 - 库版本：2.1.6
 - 问题描述/重现步骤：设置autoLocated为true后，当屏幕不足以显示时，切换到镜像位置时能否提供一个监听器来监听这次改变，并且给出监听后的方向？
 - 问题代码/截图：无
 - 报错信息：无

---

**Comment by razerdp** [comment]
basepopup内有

onAnchorTop和onAnchorBottom方法，你重写即可（该方法可能会多次回调哦。。。。）

**Comment by razerdp** [comment]
回调多次的问题在2.1.7 release已经fixed
