### ISSUE TITLE
部分设备会有空指针

### ISSUE THREAD

**Issue by panyingdaoz** [razerdp/BasePopup#134]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低
 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
现在最新版本已经是2.1.7了。。。。

**Comment by razerdp** [comment]
另外请把重现步骤写一下

**Comment by panyingdaoz** [comment]
这是一款电视设备，电视是一米云电视型号是SP35811.21和SP35861.22，我是用来实现退出密码框的，当点击退出弹出密码框是就会这样。

**Comment by razerdp** [comment]
更新到2.1.7试试
