### ISSUE TITLE
关于对齐方式的问题，已解决

### ISSUE THREAD

**Issue by 1458883958** [razerdp/BasePopup#136]
昨天关于背景对其的问题已经解决拉，失效原因：
 pop.setPopupGravity(Gravity.TOP|Gravity.CENTER_HORIZONTAL);
 pop.setAlignBackgroundGravity(Gravity.BOTTOM);
 pop.setAlignBackground(true);  //此行代码应该放置在pop.setAlignBackgroundGravity(Gravity.BOTTOM);之前。

解决：
将 pop.setAlignBackground(true);放在 pop.setAlignBackgroundGravity(Gravity.BOTTOM);之前设置，否则不生效。

**Comment by razerdp** [comment]
ya，不过这里似乎存在了一个bug，这两行应该不限制顺序的。。。下个版本修正一下
