### ISSUE TITLE
关于 QuickPopupBuilder 的使用

### ISSUE THREAD

**Issue by wenchaosong** [razerdp/BasePopup#137]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本： 模拟器 8.0
 - 库版本： com.github.razerdp:BasePopup:2.1.7
 - 问题描述/重现步骤： QuickPopupBuilder 方法里怎么调用 dismiss
 - 问题代码/截图：
 - 报错信息：

--
不知道怎么在 QuickPopupBuilder 的 withClick 点击事件中调用 dismiss 关闭窗口的方法

**Comment by razerdp** [comment]
emmm，quickpopupbuilder在最后的build或者show方法后返回的就是QuickPopup对象，您可以操控最后返回的对象，就像alertdialogbuilder最后返回的是dialog对象一样。。。

builder的文档会去更新的-V-

**Comment by zyw745293** [comment]
我也有这个疑问，比如我用QuickPopupBuilder做了一个是否删除记录的确认弹窗，需要点击取消时关闭弹窗，却没有对应的方法。
QuickPopupBuilder.with(getContext())
                        .contentView(R.layout.dialog_confirm)
                        .config(new QuickPopupConfig()
                                .gravity(Gravity.CENTER)
                                .withClick(R.id.tv_dialog_cancel, new View.OnClickListener() {
                                    @Override
                                    public void onClick(View v) {
                                        dismiss();  //此方法无效
                                    }
                                })
                        )
                        .show();

**Comment by razerdp** [comment]
> 我也有这个疑问，比如我用QuickPopupBuilder做了一个是否删除记录的确认弹窗，需要点击取消时关闭弹窗，却没有对应的方法。 QuickPopupBuilder.with(getContext()) .contentView(R.layout.dialog_confirm) .config(new QuickPopupConfig() .gravity(Gravity.CENTER) .withClick(R.id.tv_dialog_cancel, new View.OnClickListener() { @OverRide public void onClick(View v) { dismiss(); //此方法无效 } }) ) .show();

withClick有三个参数的方法，第三个参数就是是否点击关闭。
