### ISSUE TITLE
貌似不支持ScrolLView？

### ISSUE THREAD

**Issue by sicelex** [razerdp/BasePopup#139]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：9.0
 - 库版本：2.1.7
 - 问题描述/重现步骤：在NestedScrollView中使用参照的位置是AnchorView的下方，滑动ScrollView后，AnchorView的位置已经改变，但PopupView的位置还是停留在原地
 - 问题代码/截图：![问题截图](https://s2.ax1x.com/2019/01/17/kpfi7t.jpg)
 - 报错信息：

---

**Comment by razerdp** [comment]
请看wiki#linkto，或者手动update

**Comment by sicelex** [comment]
hao

> 请看wiki#linkto，或者手动update

好的，我尝试一下，非常感谢你！

**Comment by sicelex** [comment]
成功解决，非常感谢！
