### ISSUE TITLE
SlideFromTopPopup 和actionBar的问题

### ISSUE THREAD

**Issue by dyfan** [razerdp/BasePopup#14]
SlideFromTopPopupfrag中，pop显示的时候，点击action上的menu，pop不会消失，但是双击两次pop会消失，这个界面除了popwindow空白点击处，可以正常消失，其他地方都有这个问题，但是不容易发现。不知道是不是bug，项目中用了您的一部分代码，现在点击pop的布局，可以有消息动画，可是点击别的地方，就没有消失动画了。

**Comment by razerdp** [comment]
@dyfan  请更新到v1.5.2  这个原因在于popup用了自己的dismiss，而我使用的是popup，没有覆写dismiss方法，现在解决了，谢谢反馈

**Comment by razerdp** [comment]
@dyfan 如果没什么大问题，这个issue由您关闭了哦

**Comment by dyfan** [comment]
那个，还有一个小问题，就是你在外部不小心双击了以后，动画就没效果了。麻烦了咯。

**Comment by dyfan** [comment]
好像是双击外部的话isExitAnimaPlaying就会变为true的原因。

**Comment by razerdp** [comment]
好的，我明天解决一下

**Comment by razerdp** [comment]
@dyran 请更新到1.6.0

这次dismiss操作完全收拢到proxy，但是也受basepopup的控制（准确的说是接口的控制）

**Comment by dyfan** [comment]
好的，那这个lssues我就自己关闭了。感谢。
