### ISSUE TITLE
EditText无法粘贴

### ISSUE THREAD

**Issue by qtqitian** [razerdp/BasePopup#140]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by qtqitian** [comment]
Edittext无法粘贴

**Comment by razerdp** [comment]
popup里面的view无法获得windowToken，所以粘贴的popup是无法显示的，也就无法粘贴。

**Comment by razerdp** [comment]
https://issuetracker.google.com/issues/36984016
