### ISSUE TITLE
我集成你的POPUPWINDOW后，弹出POPUPWINDOW时，虚拟按键（导航栏）会自己弹出来再缩回去！求解决！

### ISSUE THREAD

**Issue by lly7690** [razerdp/BasePopup#141]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：Android4.4
 - 库版本：'com.github.razerdp:BasePopup_Candy:2.1.8-beta1'
 - 问题描述/重现步骤：我集成你的POPUPWINDOW后，弹出POPUPWINDOW时，虚拟按键（导航栏）会自己弹出来再缩回去！求解决！
 - 问题代码/截图：
public class XXXXXXPopupWindow extends BasePopupWindow{
public XXXXXXPopupWindow(final Context context) {
        super(context,MATCH_PARENT,MATCH_PARENT);
        //业务代码
}

    @Override
    protected Animation onCreateDismissAnimation() {
        return null;
    }

    @Override
    public View onCreateContentView() {
        return createPopupById(R.layout.dialog_xxxxxx);
    }
}
   BASEACTIVITY基类加了
Window _window;

        _window = getWindow();

        WindowManager.LayoutParams params = _window.getAttributes();
        params.systemUiVisibility = View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                |View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                |View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
                |View.SYSTEM_UI_FLAG_FULLSCREEN;
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
        _window.setAttributes(params);
        if (Build.VERSION.SDK_INT < 19) { // lower api
            View v = this.getWindow().getDecorView();
            v.setSystemUiVisibility(View.GONE);
        } else if (Build.VERSION.SDK_INT >= 19) {
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
            View decorView = this.getWindow().getDecorView();
            int uiOptions = View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY | View
                    .SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION;
            decorView.setSystemUiVisibility(uiOptions);

        }

 - 报错信息：无

---

**Comment by lly7690** [comment]
除了POPUPWINDOW，SPINNER也会这样，4.4以上版本能解决此问题吗？

**Comment by razerdp** [comment]
spiner其实也是用的popupwindow。

这个问题其实跟全屏activity在触摸后弹出了navigationBar的问题一样，一般来说得在focusChange里面设置隐藏。

而basepopup这里监听了uichange但没法监听focuschange

**Comment by lly7690** [comment]
那有没有替代POPUPWINDOW的解决方案？（要能像POPUPWINDOW能同时弹出多个，还能指定弹出位置，不弹出NAVIGATIONBAR且不会弹出又缩回）

**Comment by razerdp** [comment]
@lly7690  更新到 2.1.8-beta2

**Comment by lly7690** [comment]
修复了？

**Comment by lly7690** [comment]
牛逼！解决了！谢谢！不过请问是怎么解决的呢？

**Comment by lly7690** [comment]
另外为什么原来旧版本的宽度都变成MATCH_PARENT了？

**Comment by lly7690** [comment]
beta4又会弹出NAVIGATIONBAR了 改回BETA2发现BETA2有个BUG   点击EDITTEXT 不能弹输入法

**Comment by razerdp** [comment]
@lly7690 

beta2该问题已经发现并修复
beta4是发布的版本没有install导致没应用到新的代码
更新到beta5

**Comment by lly7690** [comment]
哦 好的我马上试试

**Comment by lly7690** [comment]
真的是大神 好牛逼！又修复了！谢谢大神！膜拜！么么哒！祝你新年快乐 万事如意 财源滚滚！

**Comment by lly7690** [comment]
但是还有一个问题：弹出POPUPWINDOW原来导航栏那个位置导航栏是没了但是遮罩没有，是原色

**Comment by razerdp** [comment]
什么意思，，，话说，你进群聊吧- -感觉你那里太多问题了

**Comment by lly7690** [comment]
QQ群是？

**Comment by lly7690** [comment]
加了  备注lly7690

**Comment by aaronzc** [comment]
> 但是还有一个问题：弹出POPUPWINDOW原来导航栏那个位置导航栏是没了但是遮罩没有，是原色

这个问题是怎么解决的？我也遇到了同样的问题，试了各种方式也没搞定，怎么让遮罩全屏呢？
