### ISSUE TITLE
为什么原来旧版本的宽度都变成MATCH_PARENT了？

### ISSUE THREAD

**Issue by lly7690** [razerdp/BasePopup#142]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：android 4.4
 - 库版本：'com.github.razerdp:BasePopup_Candy:2.1.8-beta2'
 - 问题描述/重现步骤：从2.0.9换到CANDY2.1.8-beta2后自己设的宽度全部变成MATCH_PARENT
 - 问题代码/截图：
super(context, ScreenUtils.dip2px(context,420),WRAP_CONTENT);
setPopupGravity(Gravity.CENTER_HORIZONTAL|Gravity.TOP);
 - 报错信息：无
---

**Comment by lly7690** [comment]
![image](https://user-images.githubusercontent.com/17976067/51515378-69a1bb00-1e4e-11e9-931c-03c264893e7d.png)没有写额

**Comment by razerdp** [comment]
额，好吧，大概知道你的意思。。。

构造器写宽高已经不太适合了，你应该在构造器里调用setWidth()，另外，布局默认会解析你的xml，比如你的xml根布局写了match_parent，那么basepopup会解析为match_parent，也就是出现了覆盖了你的操作的问题。

所以你可以考虑setWidth()或者在xml里面直接写大小。

这个构造器传入宽高在之前我考虑过才想着不支持的，不过现在想了下，似乎可以加回来，可以考虑下个beta版本增加。

**Comment by lly7690** [comment]
哦好的谢谢大神

**Comment by razerdp** [comment]
我现在去修改下，如果你不想改动代码，那等一会的beta版本吧

**Comment by lly7690** [comment]
哦，好的谢谢大神  感激不尽！么么哒！

**Comment by lly7690** [comment]
可以了 谢谢大神！么么哒！

**Comment by lly7690** [comment]
beta4又会弹出NAVIGATIONBAR了

**Comment by razerdp** [comment]
不要发到这个问题里

**Comment by razerdp** [comment]
我检查下，，可能是没执行install
