### ISSUE TITLE
onPlus6上测试，设置偏移量dp单位不适配，Popup.setOffsetX(getResources().getDimensionPixelSize(R.dimen.dp_10));

### ISSUE THREAD

**Issue by zj614android** [razerdp/BasePopup#143]
onPlus6上测试，设置偏移量dp单位不适配，Popup.setOffsetX(getResources().getDimensionPixelSize(R.dimen.dp_10));

basepop库版本2.1.2

一加6规格：
尺寸： 6.28 英寸
分辨率： 2280 x 1080
比例: 19:9
材质：Optic AMOLED
支持 sRGB，DCI-P3 显示
玻璃: 2.5D Corning® Gorilla® Glass 5

个人感觉是全面屏问题

**Comment by razerdp** [comment]
更新到最新版本

**Comment by zj614android** [comment]
> 更新到最新版本

感谢楼主回复，回头我试了再来回复，我用另外一种方案实现了目前的需求。这个issue先关闭吧。

**Comment by zj614android** [comment]
测试环境小米8

测试代码：
    QuickPopup show = QuickPopupBuilder.with(this)
        .contentView(R.layout.popup_normal)
        .config(new QuickPopupConfig()
            .clipChildren(true)
            .gravity(Gravity.CENTER_HORIZONTAL | Gravity.TOP)
            .backgroundColor(android.R.color.transparent)
        )
        .show(mView);
    TextView tv = show.findViewById(R.id.tv_text);
    tv.setText("haha");
    show.setOnDismissListener(new BasePopupWindow.OnDismissListener(){

        @Override
        public void onDismiss(){
            
        }
    });
    show.setAllowDismissWhenTouchOutside(false);
    new Handler().postDelayed(new Runnable() {
        @Override
        public void run() {
            show.dismiss();
        }
    },5000);


错误现象：
我设置了方向，(Gravity.CENTER_HORIZONTAL | Gravity.TOP)，在小米8上弹出的位子被抬高。

**Comment by zj614android** [comment]
// 项目地址：https://github.com/razerdp/BasePopup
    api 'com.github.razerdp:BasePopup:2.1.8'

**Comment by razerdp** [comment]
。。你加群吧，答案是0 - -感觉又是一个全面屏问题，但是小米8之前我是测试过了
