### ISSUE TITLE
在popwindow内部调用callInit函数无效

### ISSUE THREAD

**Issue by zhengdaone** [razerdp/BasePopup#146]
- 系统版本：6.0
 - 库版本：2.0.8
 - 问题描述/重现步骤：我想通过调用recreatePage()模拟点击事件，这段代码先调用dissmiss来使popwindow消失，再调用重写的showPopupWindow(View anchorView)来实现popwindow重新渲染。
但是不成功。如果是调用destroyPage()，再手动点击绑定了showPopupWindow(View anchorView)事件的按钮使popwindow打开，就会重新渲染。
 - 问题代码/截图：
package carbon.pinyi.com.phone.component.filterpopwindow;

import android.animation.Animator;
import android.content.Context;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.Animation;
import android.view.animation.OvershootInterpolator;
import android.view.animation.TranslateAnimation;
import android.widget.ExpandableListView;
import android.widget.ListAdapter;

import carbon.pinyi.com.phone.infrastructure.utils.LayoutUtils;
import carbon.pinyi.com.phone.service.business.listener.HandleNetworkError;
import razerdp.basepopup.BasePopupWindow;

/**
 * Created by zhengda on 2018-11-04.
 */

public abstract class BaseFilterPopWindow extends BasePopupWindow implements HandleNetworkError {
    private Context context;
    private int width;
    private int height;
    private boolean isDestroyed = true;
    private View anchorView;

    public BaseFilterPopWindow(Context context) {
        super(context);
    }

    public BaseFilterPopWindow(Context context, int w, int h) {
        super(context, w, h, false);
        this.context = context;
        this.width = w;
        this.height = h;
    }

    public BaseFilterPopWindow(Context context, int w, int h, boolean initImmediately) {
        super(context, w, h, false);
        this.context = context;
        this.width = w;
        this.height = h;
    }

    void setListViewHeight(ExpandableListView listView) {
        LayoutUtils.setListViewHeight(listView);
    }

    @Override
    public void recreatePage() {
        this.dismiss();
        this.showPopupWindow(anchorView);
    }

    @Override
    public void destroyPage() {
        this.dismiss();
        this.isDestroyed = true;
    }

    @Override
    public void showPopupWindow() {
        callInit(context, width, height);
        super.showPopupWindow();
    }

    @Override
    public void showPopupWindow(int anchorViewResid) {
        callInit(context, width, height);
        super.showPopupWindow(anchorViewResid);
    }

    @Override
    public void showPopupWindow(View anchorView) {
        callInit(context, width, height);
        super.showPopupWindow(anchorView);
        this.anchorView = anchorView;
    }

    @Override
    protected void callInit(Context context, int w, int h) {
        if (this.isDestroyed) {
            super.callInit(context, w, h);
            setBackPressEnable(true);
            setAllowDismissWhenTouchOutside(true);
            setAlignBackground(true);
            this.isDestroyed = false;
        }
    }
}

 - 报错信息：无具体报错信息。现象是调用recreatePage()后popwindow重新渲染，但是渲染完成后又变成了之前的状态。闪现了一下。

**Comment by razerdp** [comment]
callInit是给quickpopup用的…

你应该更新到最新版本，并阅读readme和wiki…有update()方法或者delayInit供延迟加载。

2.0.8已经太旧了

**Comment by razerdp** [comment]
额，请问你为什么要再初始化一遍，一般来说初始化之后就不允许再初始化了，因为那样会生成两个对象，就好比你在A里面new A()，两个都不是同一个对象。

**Comment by zhengdaone** [comment]
### 我的需求是这样的
我使用你的库做筛选框的弹窗。筛选框里面有很多组件，其中一些组件绑定的数据会通过发送网络请求获取，有的时候会有网络相关的异常抛出导致数据获取失败。异常产生时app会弹出一个错误消息页面，提供用户刷新和返回2种操作。返回会调用dismiss（）使弹窗隐藏，刷新会使弹窗重新加载。
### 现在的问题是
用户点击返回，再次打开弹窗能重新渲染。但是我使用代码模拟这个操作不能成功。
![image](https://user-images.githubusercontent.com/18456026/51880182-41b3d980-23b1-11e9-8d71-aaee6ffb4b7b.png)
![image](https://user-images.githubusercontent.com/18456026/51880187-47112400-23b1-11e9-8a9b-82969634a9e0.png)

**Comment by zhengdaone** [comment]
并且在最新版还不支持重复init了。。。

**Comment by razerdp** [comment]
update()就是

**Comment by zhengdaone** [comment]
update（）似乎达不到Activity提供的recreate()的效果

**Comment by razerdp** [comment]
考虑再三后，还是不加入recreate()方法，抱歉。
