### ISSUE TITLE
一个快捷dismiss的问题

### ISSUE THREAD

**Issue by ping999** [razerdp/BasePopup#15]
习惯的拼写new XxPopup(content,new OnclickListener{"点击操作"}).showPopupWindow;，请问下如何在“点击操作”中直接dismiss当前popup。

**Comment by razerdp** [comment]
你的意思是同一个clicklistener可以决定show和dismiss吗。

如果是的话可以使用isShowing()获取是否正在展示。
```java
if(isShowing()){
    dismiss()
}else{
    showPopupWindow()
｝
```

**Comment by ping999** [comment]
不是的，我的意思是希望一个popup能一行代码写完，
eg：new Popup().showPopupWindow();
这个时候popup中一些控件点击事件就不能直接dismiss。
如果按照正常的编写，
eg: Popup popup;    popup  = new Popup().showPopupWindwon();
正常的编写popup中控件点击事件就可以popup.dismiss();
我的问题的直接new Popup中的点击事件如何dismiss？

**Comment by razerdp** [comment]
你的意思是new Popup().showPopupWindow()后，外部不用再调用dismiss()来控制popup的dismiss吗？（也就是说不希望把popup放到一个成员变量的位置，而是随用随new对吧）

如果是这样的话，那就把dismiss的控制权放到你写的popup里面，也就是在你的popup里面进行点击事件的传递。

**Comment by ping999** [comment]
是的，不希望他成为一个成员变量，那么问题也来了，这个popup相当于一个方法直接使用了，如何在一个方法中直接调用该方法内的方法。

**Comment by razerdp** [comment]
大概明白你的意思了

首先我需要跟你说明一点的是，这个库其实是个抽象类，这意味着使用它仅仅是为了用内部的辅助方法而已。

实际上你是可以进行任何定制的。


根据你的需求，除了不想把popup用作成员变量外，还想同时控制其状态，但因为它是局部变量，而普通的clickListener可能不能满足需求。

既然如此，其实你可以继承这个clickListener然后定制您的需求的。

比如写一个Popup：
```java
/**
 * Created by 大灯泡 on 2017/2/24.
 */

public class TestPopup extends BasePopupWindow {

    private OnTestPopupClickListener listener;

    View clickToDismissView;

    public TestPopup(Activity context) {
        super(context);
    }

	//自行定义构造器
    public TestPopup(Activity context, OnTestPopupClickListener onTestPopupClickListener) {
        super(context);
        this.listener = onTestPopupClickListener;
		
		//clickToDismissView的findView略过。
        clickToDismissView.setOnClickListener(innerClickListener);
    }
    
    private View.OnClickListener innerClickListener=new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            if (listener!=null){
                listener.onInnerPopupClick(TestPopup.this);
            }
        }
    };
	
	
    public interface OnTestPopupClickListener {
        void onInnerPopupClick(TestPopup popup);
    }

  其他必须实现的方法，略。。
}
```


对于外部来说，就是这样子用了：
```java
new TestPopup(this, new TestPopup.OnTestPopupClickListener() {
           @Override
           public void onInnerPopupClick(TestPopup popup) {
               popup.dismiss();
           }
       }).showPopupWindow();
```

**Comment by ping999** [comment]
`
    public PayPopup(Activity context, final OnClickListenerInterface alipayClickListenerInterface,final OnClickListenerInterface wechatClickListenerInterface) {
        super(context);
        setPopupWindowFullScreen(true);
        mPopupView.findViewById(R.id.alipay).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                dismiss();
                alipayClickListenerInterface.clickDismissPopup();
            }
        });
        mPopupView.findViewById(R.id.wechatPay).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                dismiss();
                wechatClickListenerInterface.clickDismissPopup();
            }
        });
        showPopupWindow();
    }`
感谢您的指点，
问一个题外的问题，这是我构造的方法，如果接口不作为变量使用会引发意想不到的问题嘛，还是这样也可以

**Comment by razerdp** [comment]
没问题的。

我那边listener作为一个变量是习惯而已，因为考虑到可能会有其他的view用到这个listener回调。

**Comment by ping999** [comment]
好的，感谢！

**Comment by razerdp** [comment]
另外其实我比较建议用链式调用的方式

因为你的构造器是传入了两个listener的，也许这个popup只用到1个，但每次new都得光顾两个，所以其实那两个listener的传入可以抽成方法，返回PayPopup自身。

比如：

```java
  PayPopup{
        public PayPopup(Activity context){
            //构造器，使用原来的
        }
        
        public PayPopup regAliPayClickListener(final OnClickListenerInterface alipayClickListenerInterface){
            mPopupView.findViewById(R.id.alipay).setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    dismiss();
                    alipayClickListenerInterface.clickDismissPopup();
                }
            });
        }
        
        //微信也一样。。。
        
        
    }
```

你最后可以做到这样：

new PayPopup(context).regAliPayClickListener(new OnClickListenerInterface{
   //do something
}).regWeChatClickListener(new OnClickListenerInterface{
  //do something
}).showPopupWindow();

**Comment by razerdp** [comment]
没什么问题的话，你来关闭issue吧
