### ISSUE TITLE
示例项目clone下来后很多界面无法显示弹窗

### ISSUE THREAD

**Issue by shixiuwen** [razerdp/BasePopup#150]
- 系统版本：Android 8.1（手机型号：华为nova3，小米Mix3）
 - 库版本：2019.2.20 引入项目，直接从github中clone
 - 问题描述/重现步骤：想看一些弹窗的显示效果，示例项目clone下来后很多界面无法显示弹窗，是需要什么参数配置吗？
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
额，什么意思，很多界面无法显示弹窗？能否详细说明一下

**Comment by razerdp** [comment]
抱歉，我也发现了这个问题，是我的项目配置有个地方失误了。~我立马改一下

**Comment by razerdp** [comment]
请重新pull一下

**Comment by shixiuwen** [comment]
好的，感谢回复!
