### ISSUE TITLE
适配问题

### ISSUE THREAD

**Issue by wenchaosong** [razerdp/BasePopup#151]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：模拟器和真机都有
 - 库版本： com.github.razerdp:BasePopup:2.1.8
 - 问题描述/重现步骤：结合 'me.jessyan:autosize:1.1.2' 这个适配的库使用会有适配问题
 - 问题代码/截图：
![f3ade881-8a0c-41af-b588-22da87eb0e5d](https://user-images.githubusercontent.com/16938075/53563857-4f1ada00-3b90-11e9-9368-45a59d5540b8.png)

 - 报错信息：

---

### 重点来了
如果写死布局的高度,那么适配没有问题,如果是 match_parent 或者 wrap_content 就会有适配的问题

**Comment by razerdp** [comment]
这个问题实际上是由于你使用了适配库导致的，包括头条方案，这些对第三方的库皆有影响，暂时来说我不针对这部分用户适配。

**Comment by wenchaosong** [comment]
@razerdp 我知道你的意思,我暂时也没看你源码实现,不过用其他的库是不存在这个适配问题的,从1.x 用到 2.x 版本,难道因为这个适配就要弃用了吗

**Comment by razerdp** [comment]
这倒不至于，暂时来说不适配是因为我还没想到一个比较好的方法来减少适配成本，比如说适配的方式我选择全popup通用呢还是每个popup自行实现呢这样子的，所以我也收到过相关的反馈，也是一直在思考，可以关注下candy版本的更新，如无意外在2.1.9-release发布的时候会有一套低成本兼容方案的

**Comment by wenchaosong** [comment]
哦

**Comment by razerdp** [comment]
@wenchaosong 

我对比过几种适配方案，说实话，各家都有各家的api，由于修改density这种方式实在是太粗暴了，假如说我去适配，我也只能是修改这个值，这与头条适配方案又冲突了，假设说我提供一个api让你传入density，又或者我提供adapter等等，无论如何对于使用者来说，这无疑是不可取的。

因为假如说这次适配了这位的库，下次有用了别家的库又来问我没有适配，在下次又有用了另一家的。。。为了解决各种各样的适配方案，我只能提供api让用户把他们适配方案的density返回给我，从另一个角度来说，等同于我把适配的压力转嫁给了用户，这是很不明智的。

就如谷歌不可能为了头条去适配一样。。。

所以最终我还是决定不加入这方面的适配了，我仔细阅读了以下你这个库的issue，找到这里，
https://github.com/JessYanCoding/AndroidAutoSize/issues/13，就目前来说，你可以在showPopup之前`cancelAdapt`针对BasePopup取消适配或者autoConvertDensityBaseOnWidth来找到一个可行的值。

Basepopup不予以适配，整体而言我还是遵循官方api使用。

**Comment by xuminmin0405** [comment]
我这边用了头条适配，但是他的解决方案效果实在太差，我用：getPopupWindow().setWidth(AutoSizeUtils.dp2px(context,360));
设置了PopupWindow的宽度，但setHeight不起作用。
