### ISSUE TITLE
QuickPopupBuilder创建出的弹框在性能弱点的手机上弹出动画有问题

### ISSUE THREAD

**Issue by blackbai11** [razerdp/BasePopup#152]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：红米3，小米4等手机（性能好的手机无此问题）
 - 库版本：2.18
 - 问题描述/重现步骤：通过QuickPopupBuilder快捷创建的弹框，如果是性能稍差的手机，默认的动画时间内，入场动画很不流畅，瞬间出来的感觉（性能强的手机不受影响）。出场动画正常。通过加长动画时间，发现入场动画正常，由此判断此创建方式弹出时性能或有问题。
 - 问题代码/截图：
 - 报错信息：

---

**Comment by blackbai11** [comment]
可参考2.18 Demo中DemoFullScreenActivity中使用QuickPopupBuilder创建的例子，我测试了公司几个测试机均有此问题

**Comment by razerdp** [comment]
该问题在我的一个低配手机上也出现过，然而同时期我测试哪怕是直接往windowmanager添加一个view，在我addView后播放动画也是很不流畅的，就像卡了一下然后一下子出来一样。

暂时来说，考虑大大多数手机都是可以正常的，因此对于小部分低配机来说，该问题目前无解。

至于你说弹出时性能的问题，实际上弹出的方法跟原生PopupWindow方法并无区别，都是通过windowmanager.addView实现，然后播放动画。

你可以尝试使用原生的popup作为对比，看看原生的跟basepopup两者的动画效果，在我的低配机上，两者一样卡顿。。。。

如果在您那边原生表现更好的话，希望可以您那边提供trace文件以供参考（附件直接拖到github评论即可上传【可能需要压缩】）

**Comment by blackbai11** [comment]
但是同样的手机，通过继承BasePopupWindow创建的弹框动画很流畅，只在通过QuickPopupBuilder方式下创建的才有问题，因此猜测是QuickPopupBuilder创建方式的问题

**Comment by razerdp** [comment]
噗，事实上，，，quickpopupbuilder创建的popup还是集成BasePopupWindow的，详情可以看看QuickPopup源码。。。做的仅仅是简单的getter而已~

**Comment by blackbai11** [comment]
我通过您的qq群朋友圈私聊了你，给你发了两种创建方式的效果视频

**Comment by razerdp** [comment]
已解决，问题出现在于QuickPopupConfig默认使用popupwindow渐入动画，而在6.0上window的动画和view的动画一起进行的时候，似乎会有bug，现版本已经默认API=N的时候默认不开启渐入动画。

请更新到【Candy】2.1.9-beta3
