### ISSUE TITLE
设置拦截事件后，背景层消失（背景模糊变成白色）

### ISSUE THREAD

**Issue by 1458883958** [razerdp/BasePopup#153]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：8.0
 - 库版本：2.1.5
 - 问题描述/重现步骤：设置拦截事件后，背景层消失（背景模糊变成白色）

 - 问题代码/截图：pop.setAllowInterceptTouchEvent(false);
 - 报错信息：

---

**Comment by razerdp** [comment]
请更新到2.1.8，该问题在更新日志里有注明，请查阅。
