### ISSUE TITLE
Title：调用showPopupWindow()之后立马调用dismiss()，弹窗无法消失

### ISSUE THREAD

**Issue by shixiuwen** [razerdp/BasePopup#155]
Content:
 - 库版本：2.1.8
 - 问题描述/重现步骤：网络请求之前，调用showPopupWindow()显示loading，网络请求结束之后调用dismiss()停止loading，请求速度较慢的时候能够成功dismiss，但是如果很快的话则无法dismiss，我到本项目中的DemoActivity中创建了一个DemoPopup，在onCreate的最后执行以下代码，弹窗无法消失

```java
DemoPopup demoPopup = new DemoPopup(this);
demoPopup.showPopupWindow();
demoPopup.dismiss();
```

 - 问题代码/截图：dismiss()在showPopupWindow()之后立马执行，无法成功dismiss
 - 报错信息：无报错信息

---

**Comment by razerdp** [comment]
如果你有去读过源码，，估计可以看到，onCreate中showPopup实际上是不能成功的(windowToken还没添加)，在basepopup里采取的是post方式进行3次左右的尝试。此时你进行dismiss实际上是无效的。。。

这个问题可以解决，我这边在稍后的2.1.9-release里面针对该问题进行修改一下。

**Comment by razerdp** [comment]
ps - -模拟器上无法重现

**Comment by shixiuwen** [comment]
好的，感谢回复~

**Comment by Jiang00** [comment]
@razerdp 请问这个问题怎么解决，数据请求太快导致dismiss调用太早，然后弹窗没消失

**Comment by razerdp** [comment]
@Jiang00 建议你判断isshowing后再dismiss

**Comment by Jiang00** [comment]
@razerdp isshowing返回的是false，之后才弹出弹窗，showPopupWindow的时候三次重试有终止重试的方法么，

**Comment by razerdp** [comment]
@Jiang00 现在的版本已经没有重试了。。。。你的版本是多少

**Comment by Jiang00** [comment]
@razerdp 2.2.7

**Comment by Jiang00** [comment]
@razerdp 我试下最新版本的

**Comment by Jiang00** [comment]
@razerdp 2.2.11也同样的问题

**Comment by razerdp** [comment]
如果你show了之后立马dismiss，是会有这个问题。你另外提个issue吧，应该可以优化

**Comment by Jiang00** [comment]
@razerdp 好的谢谢
