### ISSUE TITLE
设置弹窗为圆角时该如何取消圆角下的背景？？？？

### ISSUE THREAD

**Issue by DewenCui** [razerdp/BasePopup#156]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
您可以设置background的drawable([**wiki-setbackground**](https://github.com/razerdp/BasePopup/wiki/API#setbackgroundint-drawableids))，你的drawable对应好你的圆角部分，然后通过alignBackgroundGravity进行背景对齐。[**wiki-setAlignBackgroundGravity**](https://github.com/razerdp/BasePopup/wiki/API#setAlignBackgroundGravityint-gravity)

**Comment by DewenCui** [comment]
setAlignBackgroundGravity在自定义的Popup中不能使用啊

**Comment by razerdp** [comment]
什么意思，自定义的popup？这是BasePopupWindow的api怎么可能不能用。。。
