### ISSUE TITLE
背景对齐方式，点击事件被遮盖

### ISSUE THREAD

**Issue by 1277379283** [razerdp/BasePopup#158]
- 系统版本：android 7.0
 - 库版本：2.1.9
 - 问题描述/重现步骤：
   弹出popup层 背景对齐上半部分 点击事件完全失效！必须先关闭这个 popup
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/13748217/54413682-89a87900-4731-11e9-849e-a9e68661fe0f.png)
代码配置如下：
![image](https://user-images.githubusercontent.com/13748217/54413715-a775de00-4731-11e9-9011-0ff59672f365.png)

 - 报错信息：

---

**Comment by 1277379283** [comment]
sorry，已经解决了，是我粗心了，看到了这个属性 setAllowInterceptTouchEvent(boolean touchable)；再次感谢作者文档写的很细致！（*＾-＾*）

**Comment by razerdp** [comment]
intercept默认拦截
