### ISSUE TITLE
请问下如何根据绝对坐标定位popupwindow啊

### ISSUE THREAD

**Issue by cervy** [razerdp/BasePopup#16]

**Comment by razerdp** [comment]
绝对坐标的话，大概你只能通过setOffsetX和setOffsetY来定了。
我们这里并不提供绝对坐标的方法（事实上也不打算提供，因为分辨率不同，[x,y]坐标需要处理（比如乘以dpi什么的））。

如果用setOffsetX可以在调用showPopupWindow之前set，也可以通过setOnBeforeShowCallback在回调里面设置

**Comment by razerdp** [comment]
另外，在调用showPopupWindow(View v)方法的时候，内部我已经帮你把popup与锚点view进行左上角（View原点）对齐【popup显示空间不足除外】。

这算是一个参考点吧。

**Comment by cervy** [comment]
非常感谢你的思路
