### ISSUE TITLE
在9.0的手机上使用Gravity.CENTER_HORIZONTAL|Gravity.BOTTOM，左右两边对不齐，左边有间隔，其它版本手机没问题。

### ISSUE THREAD

**Issue by zxm1243** [razerdp/BasePopup#160]
在9.0的手机上使用Gravity.CENTER_HORIZONTAL|Gravity.BOTTOM，左右两边对不齐，左边有间隔，其它版本手机没问题。

**Comment by razerdp** [comment]
请补全issue详情

**Comment by zxm1243** [comment]
![image](https://user-images.githubusercontent.com/18133705/54745067-9d595100-4c03-11e9-9318-6dada5640bbf.png)
左边会有边距

**Comment by razerdp** [comment]
是否用了头条适配之类的框架？

**Comment by zxm1243** [comment]
使用了头条适配

**Comment by razerdp** [comment]
此类适配方案不在本库兼容范围内，详情看：[**#151**](https://github.com/razerdp/BasePopup/issues/151)

你可以看看你的适配方案的库里面有没有针对PopupWindow的方案，BasePopup不对适配方案做兼容，因为我只是老老实实调用系统Api，假如我兼容适配方案，也是修改的density，那这里就会导致头条类的适配方案又失效了，因此本库不做兼容。
