### ISSUE TITLE
popupwindow不拦截KEYCODE_BACK

### ISSUE THREAD

**Issue by Jiang00** [razerdp/BasePopup#161]
- 系统版本：Android 7.0
 - 库版本： 2.1.8
 - 问题描述/重现步骤： popupwindow弹出时拦截了KEYCODE_BACK,我想让它不拦截,按back建直接到activity处理,但是又不想影响到其他的dialog,所以不能在activity重写方法,请问有设置选项么
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
BasePopupWindow内部有onDispatchKeyEvent()方法，override即可

**Comment by Jiang00** [comment]
@Override
    public boolean onDispatchKeyEvent(KeyEvent event) {
        return false;
    }

    @Override
    public boolean onBackPressed() {
        return false;
    }
这两个方法都试了,还是不行,我断点看是走到了PopupDecorViewProxy里面dispatchKeyEvent返回了true

**Comment by razerdp** [comment]
如果你需要处理keyEvent，请返回true，否则走popupDecorviewProxy实现的方法。

**Comment by Jiang00** [comment]
谢谢,我找到解决方案了
