### ISSUE TITLE
能否添加androidx库的版本？

### ISSUE THREAD

**Issue by Dobiy** [razerdp/BasePopup#162]
能否添加androidx库的版本？

**Comment by razerdp** [comment]
在这个问题之前，我想问下，目前androidX有不适配的么？

**Comment by Dobiy** [comment]
> 在这个问题之前，我想问下，目前androidX有不适配的么？

没有，可以开启android.enableJetifier=true来把第三方库迁移到Androidx，只是有时候定位到源码看懂红色，个人有点强迫症。。。

**Comment by razerdp** [comment]
噗，，其实basepopup都是系统的方法，与androidX没有很大的关系，所以不影响哦，support等库也没引用（compileOnly方式）
