### ISSUE TITLE
No package ID ff found for ID 0xffffffff.

### ISSUE THREAD

**Issue by AndyLeeBlue** [razerdp/BasePopup#164]
- 系统版本：Android 9.0 华为10，没有测试模拟器
 - 库版本：2.1.8
 - 问题描述/重现步骤：不影响显示
 - 问题代码/截图：按readme方式写的简单调用，位于fragment中，项目是AndroidX的
 - 报错信息：log显示多行No package ID ff found for ID 0xffffffff

W/dio.testdemo: Accessing hidden field Landroid/widget/PopupWindow;->mWindowManager:Landroid/view/WindowManager; (light greylist, reflection)
E/dio.testdemo: No package ID ff found for ID 0xffffffff.
D/OpenGLRenderer:   HWUI Binary is  enabled
D/OpenGLRenderer: disableOutlineDraw is true
E/dio.testdemo: No package ID ff found for ID 0xffffffff.
E/dio.testdemo: No package ID ff found for ID 0xffffffff.
E/dio.testdemo: No package ID ff found for ID 0xffffffff.
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/HwAppInnerBoostImpl: asyncReportData com.example.testdemot,1,2,2,9 interval=1801
D/OpenGLRenderer:   HWUI Binary is  enabled
    disableOutlineDraw is true
W/InputMethodManager: startInputReason = 1
D/HwAppInnerBoostImpl: asyncReportData com.example.testdemot,1,1,4,0 interval=1889
E/dio.testdemo: No package ID ff found for ID 0xffffffff.
E/dio.testdemo: No package ID ff found for ID 0xffffffff.

**Comment by razerdp** [comment]
【低优先级】，请补充issue信息

**Comment by AndyLeeBlue** [comment]
修改了描述

**Comment by razerdp** [comment]
你好，可以的话运行下demo，是否存在这个问题。如果demo没报，有可能跟androidX有关，但我目前没有头绪。。。这个问题除了大量的log外有没有其他地方影响到使用？

**Comment by jqorz** [comment]
> 你好，可以的话运行下demo，是否存在这个问题。如果demo没报，有可能跟androidX有关，但我目前没有头绪。。。这个问题除了大量的log外有没有其他地方影响到使用？

你好，我的项目中也遇到了这个问题，机器是MIUI10，Android6.0，没有使用androidX，不影响实际使用，只是打印了警告日志，日志信息为

> “W/ResourceType: No known package when getting name for resource number 0xffffffff”

运行demo再次测试仍有此现象存在。

**Comment by AndyLeeBlue** [comment]
V/AudioManager: playSoundEffect   effectType: 0
V/AudioManager: querySoundEffectsEnabled...
I/BasePopup:   (BasePopupWindowProxy.java:178) #tryToProxyWindowManagerMethod：
    cur api >> 28
I/BasePopupWindowProxy:   (BasePopupWindowProxy.java:203) #troToProxyWindowManagerMethodBeforeP：
    尝试代理WindowManager成功
I/zerdp.basepopu: jit_compiled:[OK] android.content.res.TypedArray android.content.res.Resources$Theme.obtainStyledAttributes(int, int[]) @ /system/framework/framework.jar
I/BasePopup:   (BasePopupWindowProxy.java:178) #tryToProxyWindowManagerMethod：
    cur api >> 28
I/BasePopupWindowProxy:   (BasePopupWindowProxy.java:203) #troToProxyWindowManagerMethodBeforeP：
    尝试代理WindowManager成功
I/WindowManagerProxy:   (WindowManagerProxy.java:57) #addView：
    WindowManager.addView  >>>  PopupDecorView
      (WindowManagerProxy.java:93) #applyHelper：
    applyHelper  >>>  全屏
I/WindowManagerProxy:   (WindowManagerProxy.java:93) #applyHelper：
    applyHelper  >>>  全屏
D/OpenGLRenderer:   HWUI Binary is  enabled
    disableOutlineDraw is true
D/HwAppInnerBoostImpl: asyncReportData razerdp.basepopup,2,1,1,0 interval=132
I/BasePopup:   (PopupDecorViewProxy.java:699) #getScreenWidth：
    autoSize  width = 1080
E/zerdp.basepopu: No package ID ff found for ID 0xffffffff.
I/BasePopup:   (PopupDecorViewProxy.java:705) #getScreenHeight：
    autoSize  height = 2280
I/BasePopup:   (PopupDecorViewProxy.java:699) #getScreenWidth：
    autoSize  width = 1080
E/zerdp.basepopu: No package ID ff found for ID 0xffffffff.
I/BasePopup:   (PopupDecorViewProxy.java:705) #getScreenHeight：
    autoSize  height = 2280
I/BasePopup:   (PopupDecorViewProxy.java:699) #getScreenWidth：
    autoSize  width = 1080
E/zerdp.basepopu: No package ID ff found for ID 0xffffffff.
I/BasePopup:   (PopupDecorViewProxy.java:705) #getScreenHeight：
    autoSize  height = 2280
I/BasePopup:   (PopupDecorViewProxy.java:699) #getScreenWidth：
    autoSize  width = 1080
E/zerdp.basepopu: No package ID ff found for ID 0xffffffff.
I/BasePopup:   (PopupDecorViewProxy.java:705) #getScreenHeight：
    autoSize  height = 2280
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/HwAppInnerBoostImpl: asyncReportData razerdp.basepopup,2,2,1,8 interval=203
I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
I/zerdp.basepopu: jit_compiled:[OK] android.graphics.ColorFilter android.graphics.Paint.setColorFilter(android.graphics.ColorFilter) @ /system/framework/framework.jar
D/OpenGLRenderer:   HWUI Binary is  enabled
D/OpenGLRenderer: disableOutlineDraw is true
I/zerdp.basepopu: jit_compiled:[OK] android.graphics.Rect android.graphics.Rect$1.createFromParcel(android.os.Parcel) @ /system/framework/framework.jar
W/InputMethodManager: startInputReason = 1
I/BasePopup:   (PopupDecorViewProxy.java:699) #getScreenWidth：
    autoSize  width = 1080
E/zerdp.basepopu: No package ID ff found for ID 0xffffffff.
I/BasePopup:   (PopupDecorViewProxy.java:705) #getScreenHeight：
    autoSize  height = 2280
I/BasePopup:   (PopupDecorViewProxy.java:699) #getScreenWidth：
    autoSize  width = 1080
E/zerdp.basepopu: No package ID ff found for ID 0xffffffff.
I/BasePopup:   (PopupDecorViewProxy.java:705) #getScreenHeight：
    autoSize  height = 2280
D/HwAppInnerBoostImpl: asyncReportData razerdp.basepopup,2,1,2,0 interval=393
D/HwAppInnerBoostImpl: asyncReportData razerdp.basepopup,2,1,3,0 interval=647


运行的demo，上面是完整的《从底部上滑》的后台打印，手机系统和版本同上

**Comment by razerdp** [comment]
emm，忽然想到一个可能，您可以尝试更新到2.1.9或者candy渠道的最新版看看是否还会打印这个问题。

该问题有可能出现在PopupDecorViewProxy里面，大概81行那里，通过findViewById找到一个不存在该ID的View，而默认值就View.NO_ID，也就是-1，而0xfffffff其实就是-1。。。有可能出现在这里。

**Comment by razerdp** [comment]
2.1.9并没有对contentView进行设置id，在其之后就有。目前应该更新到candy里面。

**Comment by jqorz** [comment]
> 2.1.9并没有对contentView进行设置id，在其之后就有。目前应该更新到candy里面。

我使用的就是2.1.9版本，会打印此信息

**Comment by razerdp** [comment]
@jqorz  更新到candy的最新版看看

**Comment by jqorz** [comment]
之前的2.1.9release版和2.2.0-alpha3都会打印此日志，showPopup时就会打印

**Comment by razerdp** [comment]
@jqorz @AndyLeeBlue 
该问题实际上是寻找navigationbar时所打印出来的日志，属于系统警告，并无大碍，不过可以过滤

详情代码：[**PopupUiUtils#L76**](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/util/PopupUiUtils.java#L76)

**Comment by razerdp** [comment]
该问题下一个版本尝试修复，ps，下一个版本将会对measure等方式进一步优化，所以可能比较久。

**Comment by razerdp** [comment]
fixed in 2.2.0-alpha4
