### ISSUE TITLE
根布局使用wrap_content无法显示完全，使用match_parent，点击底部无法消失的兼容处理（已解决）

### ISSUE THREAD

**Issue by jqorz** [razerdp/BasePopup#165]
项目代码最初使用的是RelativeLayout嵌套RecyclerView，其中RelativeLayout高度为wrap_content，出现的情况是，当数据过多时，底部会超出屏幕。
看了Q/A里的一个问题"根布局高度match_parent和wrap_content的区别"，为了保证数据过多时，数据会超出屏幕导致RecyclerView无法滑动到最底部，把根布局的高度改为了match_parent。但是此时如果数据过少，会出现点击列表下方区域，Popup仍无法消失的问题。为了兼容，对RelativeLayout设置setOnTouchListener监听，当Touch根布局的RelativeLayout时，dismiss该Popup。
特此记录此问题防止后面的人遇到了。

**Comment by razerdp** [comment]
ya，由于relatview是match_parent的，因此相当于popup撑满了整个屏，所以点击任意范围都是属于popup内部而非外部，因此不会dismiss。

关于wrap_content和match_parent，其实是因为popup允许超出屏幕布局而不得不这么这么做，按照原来的意思是无论是wrap_content还是match_parent，都是会限制在屏幕内的。。。

关于这一个问题，近期正在进行第N次优化&重构，可能下一个版本会解决。

感谢支持-V-

**Comment by razerdp** [comment]
已加入[QA-issueRef](https://github.com/razerdp/BasePopup/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E4%B8%BA%E4%BB%80%E4%B9%88%E8%AE%BE%E7%BD%AEsetallowintercepttoucheventfalse%E5%90%8E%E8%92%99%E5%B1%82%E6%88%96%E8%80%85%E8%83%8C%E6%99%AF%E6%A8%A1%E7%B3%8A%E9%83%BD%E6%B6%88%E5%A4%B1%E4%BA%86)

**Comment by jqorz** [comment]
> 已加入[QA-issueRef](https://github.com/razerdp/BasePopup/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E4%B8%BA%E4%BB%80%E4%B9%88%E8%AE%BE%E7%BD%AEsetallowintercepttoucheventfalse%E5%90%8E%E8%92%99%E5%B1%82%E6%88%96%E8%80%85%E8%83%8C%E6%99%AF%E6%A8%A1%E7%B3%8A%E9%83%BD%E6%B6%88%E5%A4%B1%E4%BA%86)

其实wrap_content是符合大部分使用场景的，但是由于数据过多，而里面的RecyclerView超出了屏幕，无法正常滑动到最底部，只能选择用match_parent进行处理。看了下代码，也许是因为PopupDecorViewProxy的layoutWithIntercept函数，bottom错误导致的。^-^

**Comment by jqorz** [comment]
> ya，由于relativeView是match_parent的，因此相当于popup撑满了整个屏，所以点击任意范围都是属于popup内部而非外部，因此不会dismiss。
> 
> 关于wrap_content和match_parent，其实是因为popup允许超出屏幕布局而不得不这么这么做，按照原来的意思是无论是wrap_content还是match_parent，都是会限制在屏幕内的。。。
> 
> 关于这一个问题，近期正在进行第N次优化&重构，可能下一个版本会解决。
> 
> 感谢支持-V-

其实wrap_content是符合大部分使用场景的，但是由于数据过多，而里面的RecyclerView超出了屏幕，无法正常滑动到最底部，只能选择用match_parent进行处理。看了下代码，也许是因为PopupDecorViewProxy的layoutWithIntercept函数，bottom错误导致的。^-^
