### ISSUE TITLE
QA完善

### ISSUE THREAD

**Issue by razerdp** [razerdp/BasePopup#166]

**Comment by SmallWinter** [comment]
大佬，有时间考不考虑加入一个类似蒙层的功能，就是pop弹出的时候的backgroundcolor，除了指定区域或View没有蒙层或背景，保持原有状态，其他地方有蒙层的效果。感谢大佬，大佬辛苦了！！

**Comment by razerdp** [comment]
这种我们有写过：

https://github.com/AndroidFriendsGroup/TipsView

但不考虑放到popup里，因为作为一个基础弹窗库，不适宜加太多的东西，加太多的话只会让这个库越来越束手束脚，反而不好用了。

同时BasePopup的BackGroundView是支持自定义的，建议自定义解决~

**Comment by lovemianhuatang** [comment]
能否添加一个侧边筛选抽屉弹窗  右滑关闭的那种  类似DrawerLayout

**Comment by razerdp** [comment]
@lovemianhuatang 弄是可以弄，但是没必要内置，可以自行实现。

**Comment by lovemianhuatang** [comment]
方便出一个demo吗？

**Comment by razerdp** [comment]
@lovemianhuatang 可以，等下次正式版发布吧，会集成到demo中，近期先准备正式版的库和完善文档，到时候写了该例会在文档中注明的。

**Comment by lovemianhuatang** [comment]
大概什么时候？  我看你昨晚有重大更新

**Comment by razerdp** [comment]
最近几天吧，这两天我都在弄

**Comment by lovemianhuatang** [comment]
好的  弄完了@我一下

**Comment by razerdp** [comment]
嗯，我现在也在重构，同时在直播，感兴趣可以去看看进度哈哈

https://live.bilibili.com/724896

**Comment by lovemianhuatang** [comment]
ok

**Comment by huangjingf** [comment]
请问有支持databinding 跟最新的viewbinding的打算吗？

**Comment by razerdp** [comment]
@huangjingf 

2.2.2之后可以尝试在onViewCreated中绑定，，，至于能否支持我也没试过。

**Comment by razerdp** [comment]
该issue转移到：[#265 ](https://github.com/razerdp/BasePopup/issues/265)
