### ISSUE TITLE
平板上横屏显示时蒙层宽度无法充满屏幕，会留下一个虚拟导航的高度的距离，2.0.4版本

### ISSUE THREAD

**Issue by cc365774016** [razerdp/BasePopup#167]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
请更新到最新版本

**Comment by cc365774016** [comment]
我刚刚下载了DEMO来试，还是出现蒙层不能全屏，竖屏显示蒙层就能全屏显示

**Comment by razerdp** [comment]
好的，我看看，另外请补充issue模板信息

**Comment by lerooooooooy** [comment]
同有这个问题

**Comment by lerooooooooy** [comment]
好像是屏幕适配引起的，我把屏幕适配去掉就正常了

**Comment by razerdp** [comment]
@lerooooooooy 如果用了头条类适配方案，本库不会去适配头条的适配。详见QA

**Comment by razerdp** [comment]
问题出在这里:
[PopupUiUtils.java#L125](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/util/PopupUiUtils.java#L125)

对于平板而言，在横屏状态下navigation居然处于底部，也因此导致了这个问题。

**Comment by razerdp** [comment]
please update to candy ver 2.2.1.190517

here is test screenshot


onPhone：

![](https://user-images.githubusercontent.com/11629986/57903125-3b356900-789f-11e9-935f-60cc5ffac439.png)


onPad：

![](https://user-images.githubusercontent.com/11629986/57903140-44bed100-789f-11e9-87fb-a6500b8e1c74.png)
