### ISSUE TITLE
在Dialog中弹出BasePopup显示不正常

### ISSUE THREAD

**Issue by JackLauu** [razerdp/BasePopup#168]
- 系统版本：不限
 - 库版本：2.1.8
 - 问题描述/重现步骤：在AlertDialog或者DialogFragment中彈出basePopup的时候，basePopup会显示到底层，这样就看不见了。
 - 问题代码/截图： 无
 - 报错信息：无

**Comment by razerdp** [comment]
请更新到2.1.9，2.1.9的版本更新中已经有该问题的描述。
