### ISSUE TITLE
列表子布局设置居中，显示结果向右偏移

### ISSUE THREAD

**Issue by Yifpro96** [razerdp/BasePopup#169]
- 系统版本：8.0
 - 库版本：Release 2.1.9
 - 问题描述/重现步骤：RecyclerView 子布局 TextView，设置宽度 match_parent，并设置文本居中，在小米8和模拟器 Pixel 2 XL 中显示结果文本向右偏移，在华为 nova 3e 中显示正常，更换为 Candy 2.2.0 并调用 setMaxWidth(screenWidth) 后，均显示正常
 - 问题代码/截图：
`<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/tv"
    android:layout_width="match_parent"
    android:layout_height="36dp"
    android:gravity="center"
    android:background="@color/white"
    android:textSize="15dp" />`

`class FinanceFilterPopup(context: Context, val data: List<String>) : BasePopupWindow(context, true) {

    private val mAdapter by lazy { PopupContentAdapter(R.layout.item_finance_filter, data) }
    private var mOnItemClickListener: ((Int) -> Unit)? = null
    private lateinit var recyclerView: RecyclerView

    override fun onCreateContentView(): View {
        val view = createPopupById(R.layout.view_finance_filter)
        recyclerView = view.findViewById(R.id.recyclerView)
        mAdapter.setOnItemClickListener { _, _, position ->
            mOnItemClickListener?.invoke(position)
        }
        recyclerView.run {
            layoutManager = LinearLayoutManager(context)
            adapter = mAdapter
            addItemDecoration(DividerItemDecoration(context, DividerItemDecoration.VERTICAL))
        }
        return view
    }

    fun setOnItemClickListener(listener: (Int) -> Unit): FinanceFilterPopup {
        mOnItemClickListener = listener
        return this
    }

    init {
        delayInit()
    }

}`

`if (mDateFilterPopup == null) {
    val list = arrayListOf("今天", "近7天", "近30天")
    mDateFilterPopup = FinanceFilterPopup(context, list).apply {
        setOnItemClickListener { position ->
            when (position) {
                0 -> mEntity.A_OrderDate = "0"
                1 -> mEntity.A_OrderDate = "1"
                else -> mEntity.A_OrderDate = "2"
            }
            tvFilterDate.text = list[position]
            if(position != list.lastIndex)requestDataWithResetStatus()
            dismiss()
        }
        popupGravity = Gravity.BOTTOM or Gravity.CENTER_HORIZONTAL
        setBackgroundColor(0)
    }
}
mDateFilterPopup?.showPopupWindow(filterConditions)`
 - 报错信息：

---

**Comment by razerdp** [comment]
rv的父布局呢，是match_parent么

**Comment by Yifpro96** [comment]
> rv的父布局呢，是match_parent么

是的，漏了说明 rv，抱歉

**Comment by razerdp** [comment]
有用头条的适配么

**Comment by Yifpro96** [comment]
用了

**Comment by razerdp** [comment]
本库不适配头条适配方案。。。。

**Comment by Yifpro96** [comment]
好的，谢谢

**Comment by LeeeeeYao** [comment]
兄弟 最后怎么解决的

**Comment by yoyiyi** [comment]
兄弟 最后怎么解决的

**Comment by LeeeeeYao** [comment]
//不设置会让内容向右偏移
int width = ArmsUtils.getScreenWidth(mContext);
getPopupWindow().setWidth(width);
初始化里面 设置宽度


------------------ 原始邮件 ------------------
发件人: "yoyiyi(soleil雪寂)"<notifications@github.com>;
发送时间: 2019年7月28日(星期天) 晚上7:57
收件人: "razerdp/BasePopup"<BasePopup@noreply.github.com>;
抄送: "李垚"<245937033@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [razerdp/BasePopup] 列表子布局设置居中，显示结果向右偏移 (#169)




兄弟 最后怎么解决的
