### ISSUE TITLE
使用recyclerview做布局，数据太多，显示充满整个屏幕并且覆盖住anchorview

### ISSUE THREAD

**Issue by LomoLin** [razerdp/BasePopup#171]
- 系统版本：Android 9
 - 库版本：2.1.9
 - 问题描述/重现步骤：继承BasePopupWindow，设置布局文件，布局文件包含一个recycyerview控件，设置数据后，show
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/3785432/55716875-a1baa200-5a2a-11e9-9ac7-865bda8b49f6.png)
- 报错信息：

**Comment by razerdp** [comment]
贴一下布局和代码~

**Comment by LomoLin** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@drawable/public_bg_round_5_fff">

    <TextView
            android:id="@+id/tvPreDay"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/product_list_pre_day"
            android:textColor="@color/public_color_888888"
            android:textSize="@dimen/public_font_14sp"
            android:paddingLeft="@dimen/public_13dp"
            android:paddingTop="@dimen/public_17dp"/>

    <TextView
            android:id="@+id/tvCurrentDay"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/public_color_555555"
            android:textSize="@dimen/public_font_17sp"
            android:layout_marginTop="@dimen/public_15dp"
            android:layout_centerHorizontal="true"
            tools:text="02-27"/>

    <TextView
            android:id="@+id/tvNextDay"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/product_list_next_day"
            android:textColor="@color/public_color_888888"
            android:textSize="@dimen/public_font_14sp"
            android:paddingTop="@dimen/public_17dp"
            android:paddingRight="@dimen/public_12dp"
            android:layout_alignParentRight="true"/>

    <View
            android:id="@+id/popupDivider"
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:background="@color/public_color_eeeeee"
            android:layout_marginTop="@dimen/public_15dp"
            android:layout_below="@id/tvCurrentDay"/>

    <android.support.v7.widget.RecyclerView
            android:id="@+id/rcvMealSonList"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingLeft="@dimen/public_13dp"
            android:paddingRight="@dimen/public_12dp"
            android:layout_below="@id/popupDivider"/>

</RelativeLayout>`

**Comment by LomoLin** [comment]
`
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@drawable/public_bg_round_5_fff">

    <TextView
            android:id="@+id/tvPreDay"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/product_list_pre_day"
            android:textColor="@color/public_color_888888"
            android:textSize="@dimen/public_font_14sp"
            android:paddingLeft="@dimen/public_13dp"
            android:paddingTop="@dimen/public_17dp"/>

    <TextView
            android:id="@+id/tvCurrentDay"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/public_color_555555"
            android:textSize="@dimen/public_font_17sp"
            android:layout_marginTop="@dimen/public_15dp"
            android:layout_centerHorizontal="true"
            tools:text="02-27"/>

    <TextView
            android:id="@+id/tvNextDay"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/product_list_next_day"
            android:textColor="@color/public_color_888888"
            android:textSize="@dimen/public_font_14sp"
            android:paddingTop="@dimen/public_17dp"
            android:paddingRight="@dimen/public_12dp"
            android:layout_alignParentRight="true"/>

    <View
            android:id="@+id/popupDivider"
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:background="@color/public_color_eeeeee"
            android:layout_marginTop="@dimen/public_15dp"
            android:layout_below="@id/tvCurrentDay"/>

    <android.support.v7.widget.RecyclerView
            android:id="@+id/rcvMealSonList"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingLeft="@dimen/public_13dp"
            android:paddingRight="@dimen/public_12dp"
            android:layout_below="@id/popupDivider"/>

</RelativeLayout>
`

**Comment by LomoLin** [comment]
代码就是集成BasePopupwindow，实现简单的show和dismiss

**Comment by LomoLin** [comment]
> 噗，有一个很重要的父布局哦~那个没贴出来-V-

我贴出来了，奇怪，编辑的时候有显示，发布之后就没显示出来

**Comment by LomoLin** [comment]
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@drawable/public_bg_round_5_fff">`

**Comment by LomoLin** [comment]
父布局就是这样子的

**Comment by razerdp** [comment]
java代码呢

**Comment by Tomcater** [comment]
我也遇到了同样的问题 布局文件跟他大同小异。popwindow只设置了
setPopupGravity(Gravity.TOP);
setAlignBackground(true);
setAlignBackgroundGravity(Gravity.BOTTOM);
这三个属性

**Comment by LomoLin** [comment]
> 我也遇到了同样的问题 布局文件跟他大同小异。popwindow只设置了
> setPopupGravity(Gravity.TOP);
> setAlignBackground(true);
> setAlignBackgroundGravity(Gravity.BOTTOM);
> 这三个属性

java代码也和他差不多，然后调用show和dismiss @razerdp

**Comment by LomoLin** [comment]
`init {
        setAlignBackground(true)
        popupGravity = Gravity.TOP
        setAlignBackgroundGravity(Gravity.BOTTOM)
    }

    override fun onCreateContentView(): View {
        return createPopupById(R.layout.product_layout_popup_set_meal_son)
    }`

**Comment by LomoLin** [comment]
我是用kotlin实现的

**Comment by razerdp** [comment]
是用的showPopupWindow(view)方法的对吧。。

如果还是有问题的话，我这周末重现一下，，

确认一下，anchor在底部，popup需要显示在其上面对吧？

**Comment by LomoLin** [comment]
> 是用的showPopupWindow(view)方法的对吧。。
> 
> 如果还是有问题的话，我这周末重现一下，，
> 
> 确认一下，anchor在底部，popup需要显示在其上面对吧？

对的

**Comment by razerdp** [comment]
最近在重构这个库，所以修复比较慢哈~
