### ISSUE TITLE
delayInit后isAllowInterceptTouchEvent=false  isAllowDismissWhenTouchOutside=false 无效

### ISSUE THREAD

**Issue by q996467794** [razerdp/BasePopup#176]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：8.0
 - 库版本：2.1.9
 - 问题描述/重现步骤：
设置delayInit 在构造方法调用delayInit(),在onCreateContentView中设置
isAllowInterceptTouchEvent=false  
isAllowDismissWhenTouchOutside=false
无效
取消delayInit在构造方法设置
isAllowInterceptTouchEvent=false  
isAllowDismissWhenTouchOutside=false
就有效

 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
delayinti会重走一次初始化方法哦~所以会被默认的参数覆盖掉。

**Comment by q996467794** [comment]
kotlin用的我有点蒙了 在里面定义了一个adapter如果写在init{}后面的话在onCreateContentView里用就会是null
