### ISSUE TITLE
isShowing始终为false

### ISSUE THREAD

**Issue by q996467794** [razerdp/BasePopup#177]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：8.0
 - 库版本：2.1.9
 - 问题描述/重现步骤：
在子类中写了个toggle方法，打算用isShowing判断结果isShowing始终返回false
 - 问题代码/截图：
fun toggle(target: View){
        LogUtils.e(isShowing)
        if (isShowing){
            dismiss()
        }else{
            showPopupWindow(target)
        }
    }
 - 报错信息：

---

**Comment by razerdp** [comment]
如果是在onCreate这里showpopup，则有可能会造成这个情况，因为windowToken还没准备好，popup并无show出来。

**Comment by q996467794** [comment]
我是在DialogFragment中按钮的点击监听调用的toggle方法

**Comment by razerdp** [comment]
0.0 解决了么？

**Comment by q996467794** [comment]
> 0.0 解决了么？

没有，换了实现方法了

**Comment by Qiang11** [comment]
老哥用什么方式实现的

**Comment by q996467794** [comment]
> 老哥用什么方式实现的

下拉的形式换成弹窗的形式了
