### ISSUE TITLE
当 popup显示的时候,键盘无法弹起,

### ISSUE THREAD

**Issue by open9527** [razerdp/BasePopup#179]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：8.0
 - 库版本：2.1.9
 - 问题描述/重现步骤：主界面 一个recycleview列表+底部输入框, 右边显示popup,设置了setAllowInterceptTouchEvent(false);
        setAllowDismissWhenTouchOutside(false);
        setBackPressEnable(true);
        setBackgroundColor(0);

当 popup显示的时候,键盘无法弹起,
 - 问题代码/截图：

 - 报错信息：无;

---

**Comment by razerdp** [comment]
popup抢占了焦点。

basepopu.getpopupwindow.setfocusable(false)试下

**Comment by open9527** [comment]
> popup抢占了焦点。
> 
> basepopu.getpopupwindow.setfocusable(false)试下

谢谢,问题解决了.

**Comment by chenwuwen** [comment]
我的popup是继承自BasePopupWindow的
然后使用：
  PreviewPopup previewPopup = new PreviewPopup(context);
  previewPopup.getPopupWindow().setFocusable(false);
  previewPopup.showPopupWindow();
发现弹出popup后 EditText无法获取焦点，即使手动获取焦点,键盘也弹不出来
然后我注释掉中间的previewPopup.getPopupWindow().setFocusable(false); 
虽然键盘不会自动弹出，但是手动获取焦点还是可以自动弹出的，这是怎么回事

**Comment by razerdp** [comment]
@chenwuwen 你需要注意的是edittext在哪里。

这个问题中的edittext是在外面的，不是在popup里，因为popup会抢占焦点，所以才说不让popup获取焦点

但你的问题应该是edittext在popup里面，如果不能focusable，那肯定是无法获取的，哪怕你点击了也是禁止的。

**Comment by razerdp** [comment]
可以去查询了解一下WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE

**Comment by chenwuwen** [comment]
我现在可以让editText获取焦点了，代码如下：
EditText editText = previewPopup.getContentView().findViewById(R.id.preview_input);
editText.setFocusable(true);
editText.setFocusableInTouchMode(true);
editText.requestFocus();
焦点是获取了，但是键盘不会自动弹出，我使用如下代码
 Activity activity = previewPopup.getContext();
                activity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE);
还用了下面的代码：
 InputMethodManager imm = (InputMethodManager) context.getSystemService(Context.INPUT_METHOD_SERVICE);
                imm.showSoftInput(editText, InputMethodManager.SHOW_IMPLICIT);

但是不起作用，然后我手动点击是可以弹出键盘的
我在考虑是否借助模拟点击，可这样的话，代码实在不优雅

**Comment by razerdp** [comment]
如果需要键盘自动弹出。。wiki就有
https://github.com/razerdp/BasePopup/wiki/API#setautoshowinputmethodedittext-edittext-boolean-autoshow

**Comment by chenwuwen** [comment]
> 如果需要键盘自动弹出。。wiki就有
> https://github.com/razerdp/BasePopup/wiki/API#setautoshowinputmethodedittext-edittext-boolean-autoshow

好气哦，只看了readme,没看wiki 浪费好多时间，已解决

**Comment by Qiang11** [comment]
quickPopupHeader?.dismissAnimation = getTranslateVerticalAnimation(0f, -1f, 250)
 quickPopupHeader?.isOutSideTouchable = true
quickPopupHeader?.setBackground(null)
quickPopupHeader?.showPopupWindow(view)

我的是这么设置的当有退出动画的时候  点击popWindow外面的EditText可以获取焦点但是软键盘一直无法弹出
