### ISSUE TITLE
v1.6.3 的改动似乎没有效果。

### ISSUE THREAD

**Issue by yeqinfu** [razerdp/BasePopup#18]
anima view在pop的布局设置为其中的子view。并不能精确位置。小米miui8（android7.0） 。
有的地方anima view就是和pop的view相同，可以精确位置。但是有的地方就是不行。

**Comment by razerdp** [comment]
请问popup根布局是match_parent吗，另外可以看看具体布局吗（包括截图哦）

7.0的popup showAsDropdown有坑（api24，据说25又恢复正常了。。。）。似乎跟测量有关（match_parent时失效）。

[GoogleCode](https://code.google.com/p/android/issues/detail?id=221001)

1.6.2修复时我的不完美修复方案是强制把popup的height设置为wrap_content（并没有采取code推荐的showAtLocation）

具体在demo中的`SlideFromTopPopupFrag.java`，就是我当时测试的例子，在as的模拟器中6.0和7.0表现完全不同（具体地说就是7.0位置无法精确定位）。修复后测试通过了。

1.6.3是为了强制规定animaView必须是popup的子控件，因为有小伙伴把popup根布局作为animaView返回导致位置计算有问题。返回相同时会在构造方法中抛异常。

**Comment by yeqinfu** [comment]
我写了两个pop，popA的布局：
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical">

    <LinearLayout
        android:id="@+id/popup_anima"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <RelativeLayout

            android:layout_width="match_parent"
            android:layout_height="@dimen/x247"
            android:background="@color/white">

            <View
                android:id="@+id/view1"
                android:layout_width="match_parent"
                android:layout_height="1dp"
                android:layout_alignParentTop="true"
                android:background="@color/beijingdise"/>


            <android.support.v7.widget.RecyclerView
                android:id="@+id/popcomp_recyclerView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_below="@+id/view1"
                android:layout_marginTop="@dimen/x24"
                android:background="@color/white"/>
        </RelativeLayout>

        <View
            android:layout_width="match_parent"
            android:layout_height="@dimen/x1"
            android:background="@color/beijingdise"/>
    </LinearLayout>

</LinearLayout>

=====================================================
popB的布局：
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    >


    <RelativeLayout
        android:id="@+id/popup_anima"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

        <View
            android:id="@+id/view1"
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:layout_alignParentTop="true"
            android:background="@color/beijingdise"/>


        <android.support.v7.widget.RecyclerView
            android:id="@+id/popcomp_recyclerView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/view1"
            android:layout_marginTop="@dimen/x24"
            />
    </RelativeLayout>
</LinearLayout>

=======================================================

popA的代码和popB的代码几乎一样。唯一区别是popup_anima的子view中，一个直接包裹RecyclerView 一个没有直接包裹。直接包裹RecyclerView会出现位置不精确的问题，再用一个父布局包裹RecyclerView就没有了。亲测有效，miui8（android7.0）

**Comment by yeqinfu** [comment]
测试机型小米5 miui8（android7） 
并不是说执行动画的popup_anima view需要一层外裹，而是在popup_anima里面的每个子view都必须是精确值，不能有wrap_content，根据我的测试是这样的结论。

**Comment by razerdp** [comment]
不是很清楚你的描述。。。加个QQ：164701463  我向你了解一下如何

**Comment by razerdp** [comment]
TODO:

  - 针对api=24的showAsDropdown时，popupview大小为match_parent的问题
  - 优化，使popupView和animaView返回一样时进行处理，而非抛出异常
  - 【优先级低】：wiki文档以及部分方法名修正
