### ISSUE TITLE
平板旋转的时候，无法跟随图标

### ISSUE THREAD

**Issue by JackLauu** [razerdp/BasePopup#180]
- 系统版本：不限
 - 库版本：2.1.9
 - 问题描述/重现步骤：在平板上某个图标上弹出BasePopupWindow的时候，平板发生旋转的时候，BasePopupWindow的位置不变，就无法吸附到图标上。我这边实现了简单的处理，将一个0x0宽高的DummyView添加到popup的ContentView，在DummyView中检测onConfigureChanged的时候dismiss BasePopupWindow。不知道能否有更好的实现，就是能屏幕旋转的时候自动追踪图标进行吸附？
 - 问题代码/截图：无
 - 报错信息：无

**Comment by razerdp** [comment]
旋转这一块当初确实没有想到过，因为实际上本库只是对系统的PopupWindow进行拓展修复，并没有破坏其根本，如果系统没适配的话，我稍后研究并适配~

你可以提供你的例子吗，比如视频图片什么的。

**Comment by razerdp** [comment]
candy 2.2.0-beta2已修复
