### ISSUE TITLE
自动定位问题

### ISSUE THREAD

**Issue by coderlzx** [razerdp/BasePopup#181]
- 系统版本：华为P9  7.0
 - 库版本：2.2.0-alpha4
 - 问题描述/重现步骤：打开Demo，选择自动定位Popup页面，点击左下角按钮，弹窗没有显示在按钮上方，还是直接显示在下方导致看不到
 - 问题代码/截图：
 - 报错信息：
![image](https://user-images.githubusercontent.com/3348827/57231766-c74cc280-704d-11e9-91d8-219b9a199beb.png)

---

**Comment by coderlzx** [comment]
同样在小米mix2s手机上出现该问题，系统9.0

**Comment by razerdp** [comment]
测量和layout近期处于重构之中，请关注最新代码~目前暂时不会发布任何版本，旧版本的问题将在下一个candy一并修复

**Comment by razerdp** [comment]
fixed in candy 2.2.0-beta
