### ISSUE TITLE
关联View设置Gravity.Top后无法贴合View上部显示

### ISSUE THREAD

**Issue by coderlzx** [razerdp/BasePopup#182]
- 系统版本：华为P9  7.0
 - 库版本：2.2.0-alpha4
 - 问题描述/重现步骤：以view为锚点，设置Gravity.Top，没有现在在按钮边缘上部，而是有一定间隔。大概原因是因为计算内容视图的高度出了问题，跟方向无关，应该跟是否相对View显示popup的标志位有关。最近我也在研究这个库，打算研究透彻之后重构一遍，锲合自身框架使用习惯，但目前这个问题跟上个问题，应该是计算内容视图大小的算法中还是存在问题。希望作者早日修复，感谢！
 - 问题代码/截图：
 - 报错信息：
![image](https://user-images.githubusercontent.com/3348827/57232223-b8b2db00-704e-11e9-960f-b3aff8ea1009.png)

---

**Comment by razerdp** [comment]
该问题已经发现并处于重构中，目前的代码已经修复。

**Comment by razerdp** [comment]
准确的说，跟测量模式相关~

**Comment by razerdp** [comment]
https://github.com/razerdp/BasePopup/commit/c2f5a90fe820c9d5a4a0bff060fa1d10b224123e#diff-df6e5808dc3d705719e4698f9290458eL286

实际原因可以查看diff文件，目前我经过debug发现我在写的时候。

上一个问题其实是上一次重构后，当剩余可用空间为0的时候，我把高度也直接设为了0导致的。

本次修复可以看看diff~

感谢支持-V- 有啥idea欢迎交流哈

**Comment by razerdp** [comment]
fixed in candy 2.2.0-beta

**Comment by coderlzx** [comment]
好的，可以留个联系方式加个好友吗？

**Comment by razerdp** [comment]
加群吧，答案是0，私人方式我不留在这里了。。。

**Comment by coderlzx** [comment]
对了，重构版本计划是什么时候发布啊？

**Comment by razerdp** [comment]
已经发了呀。。。 candy 2.2.0-beta

**Comment by razerdp** [comment]
更新日志也有写。。。

**Comment by coderlzx** [comment]
好的，谢啦，之前没留意
