### ISSUE TITLE
设置模糊背景，必须继承AppCompatActivity吗？

### ISSUE THREAD

**Issue by baobrother** [razerdp/BasePopup#185]
popupWindow.setBlurBackgroundEnable(true);

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;

**Comment by baobrother** [comment]
我这里用的是FragmentActivity，设置模糊背景报错

**Comment by razerdp** [comment]
没有要求。不过这个错估计是因为你的包没有appcompactactivity的原因吧，因为一般都带support包，所以很少会出现这种问题。

**Comment by baobrother** [comment]
哦，我导入的androidx的包

**Comment by razerdp** [comment]
下个版本我修改为FragmentActivity就可以了。

**Comment by razerdp** [comment]
2.2.0开始拆分支持库，请留意readme更新~

**Comment by razerdp** [comment]
请更新到2.2.0，并添加相关依赖包
