### ISSUE TITLE
can not blur the whole screen on tablet landscape

### ISSUE THREAD

**Issue by BinghuiZ** [razerdp/BasePopup#186]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：8.1
 - 库版本：2.2.0
 - 问题描述/重现步骤：畫面不能完全被模糊
 - [问题代码/截图：](https://ibb.co/8x1d6nS)
 - 报错信息：

---
使用demo app
android emulator nexus 7

**Comment by razerdp** [comment]
有具体图片吗，以及demo的哪个fragment重现。

**Comment by razerdp** [comment]
噢，我看到链接了。

**Comment by razerdp** [comment]
same as #167 

will be fixed next ver

**Comment by razerdp** [comment]
问题出在这里:
[PopupUiUtils.java#L125](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/util/PopupUiUtils.java#L125)

对于平板而言，在横屏状态下navigation居然处于底部，也因此导致了这个问题。

**Comment by BinghuiZ** [comment]
look forward to the updated version

**Comment by razerdp** [comment]
okay,Please pay attention to the update of the candy version and [readme#updatelog](https://github.com/razerdp/BasePopup#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97-%E5%8E%86%E5%8F%B2%E6%9B%B4%E6%96%B0) (language zh-cn)

**Comment by razerdp** [comment]
please update to candy ver 2.2.1.190517

here is test screenshot


onPhone：

![](https://user-images.githubusercontent.com/11629986/57903125-3b356900-789f-11e9-935f-60cc5ffac439.png)


onPad：

![](https://user-images.githubusercontent.com/11629986/57903140-44bed100-789f-11e9-87fb-a6500b8e1c74.png)
