### ISSUE TITLE
在横屏应用点出弹框，然后在有弹框的情况下，点击菜单栏键，退回到桌面后，再重新回到应用，出现弹窗变形错位甚至失去焦点的问题。

### ISSUE THREAD

**Issue by wanpeiyu** [razerdp/BasePopup#188]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：8.1.0
 - 库版本：2.2.0
 - 问题描述/重现步骤：在横屏应用点出弹框，然后在有弹框的情况下，点击菜单栏键，退回到桌面后，再重新回到应用，出现弹窗变形错位甚至失去焦点的问题。
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
请补全issue要求，包括截图

**Comment by wanpeiyu** [comment]
步骤一：在横屏应用点出弹框
![IMG_20190517_152136 1](https://user-images.githubusercontent.com/8409128/57914147-506ac180-78b8-11e9-8354-9df9b31a38cb.jpg)
步骤二：然后在有弹框的情况下，点击菜单栏键，退回到桌面后
![IMG_20190517_153005 2](https://user-images.githubusercontent.com/8409128/57914382-b9ead000-78b8-11e9-8750-690728a93e49.jpg)
步骤三：再重新回到应用，出现弹窗变形错位甚至失去焦点的问题。如下图
![IMG_20190517_152324 2](https://user-images.githubusercontent.com/8409128/57914296-8dcf4f00-78b8-11e9-9d23-e55c36ebd03c.jpg)

**Comment by wanpeiyu** [comment]
用原生PopupWindow 不会出现这种问题 。麻烦作者了

**Comment by wanpeiyu** [comment]
> 请补全issue要求，包括截图

以补充截图

**Comment by razerdp** [comment]
这是我在本地模拟器模拟的效果，无法重现该问题。请问是否某类手机的问题？尝试过别的手机吗

![dfdf](https://user-images.githubusercontent.com/11629986/57914871-24ecd480-78c2-11e9-8e4e-c4c0ce5730f0.gif)

**Comment by wanpeiyu** [comment]
vivo1725 出现频率最高  三星S8偶尔会出现  华为P20不是必现 但是也有复现的概率

**Comment by wanpeiyu** [comment]
尤其是在应用全屏 弹框也是全屏的情况下 复现率高 小窗口的弹窗复现率低

**Comment by razerdp** [comment]
噢~大概了解了。

如无意外，我估计这类手机都是在点出后台程序的时候都会旋转屏幕，触发了BasePopup的调整。

而我刚刚看了下代码，发现一个问题就是我写了针对模糊的适配，却没有非模糊状态的适配，可能是个bug，

你可以试试加上背景模糊后再次重现，看能否复现

**Comment by razerdp** [comment]
另外，大概问题我也定位到了~稍后candy版本修复

**Comment by wanpeiyu** [comment]
谢谢~

**Comment by wanpeiyu** [comment]
尝试了加了背景模糊 还是存在这个问题 。我朋友用的2.1.4版本库 只是去掉了setPopupGravity(Gravity.CENTER)后没有出现这个问题，但是出现了新的问题是弹框里面的控件会出现焦点遗失的问题。 看了下源码应该是这个方法有点问题 private void tryToShowPopup(View v, boolean positionMode, boolean abortAnimate) {}

**Comment by razerdp** [comment]
目前，你先用着setOutSideTouchable(true)吧~感觉像是系统内部的问题。

触发了measure，横屏状态结果以竖屏来measure，导致了这个问题。outSideTouchable则不采取basepopup内部layout的方式，采取系统默认的方式测量，应该可以暂时修复这个问题

**Comment by wanpeiyu** [comment]
我们先找到了其它的方法 但是你的这个方法业务不允许 还是希望up主提供最终的解决办法

**Comment by razerdp** [comment]
我刚刚用了不完美的方式暂时修复，你可以依赖candy的最新版

**Comment by wanpeiyu** [comment]
我试试看~

**Comment by razerdp** [comment]
经过反复测试，发现了在popupdecorProxy里，当你横屏切home的时候，因为手机会产生一个旋转，触发了measure，而此刻app内还是横屏的，但是传过来的是width和height都是竖屏的值，从而导致了【横屏状态下测量了竖屏的值】。

因此暂时来说不完美的解决方案就是根据这两个值把他们换回来~

至于完美解决方案估计得花点时间去挖的很深的源码才行。。。。不过就目前来说应该可以用，因为这种情况可能较少

**Comment by wanpeiyu** [comment]
感谢 感谢~感谢up主

**Comment by wanpeiyu** [comment]
up主，使用了你的candy包，今天充分测试之后还是发现了问题。当点击菜单键 到应用列表的时候再点击home键，然后触发了横竖屏幕的切换，这个时候用你昨天的包能解决当前问题，但是直接点击home键退回到主屏再回到应用还是会出现高宽值传错的情况。  然后还出现了新的问题。
![videotogif_2019 05 18_11 22 46 1](https://user-images.githubusercontent.com/8409128/57964419-7303e580-795f-11e9-81ce-dfa80fe84611.gif)
这个问题应该是绘制没有考虑到状态栏的高度

**Comment by razerdp** [comment]
请更新到最新版本再测试一下~
