### ISSUE TITLE
最新candy包还是出现横竖屏幕切换问题~

### ISSUE THREAD

**Issue by wanpeiyu** [razerdp/BasePopup#189]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：vivo 8.1  三星 8.1
 - 库版本：candy2.1.1.190517
 - 问题描述/重现步骤：up主，使用了你的candy包，今天充分测试之后还是发现了问题。当点击菜单键 到应用列表的时候再点击home键，然后触发了横竖屏幕的切换，这个时候用你昨天的包能解决当前问题，但是直接点击home键退回到主屏再回到应用还是会出现高宽值传错的情况。 然后还出现了新的问题。
这个问题应该是绘制没有考虑到状态栏的高度
 - 问题代码/截图：
![videotogif_2019 05 18_11 22 46 1](https://user-images.githubusercontent.com/8409128/57965642-0f82b380-7971-11e9-9e74-8d939eb42d56.gif)
 - 报错信息：

---

**Comment by razerdp** [comment]
如果绘制没有考虑到状态栏的高度，那么一开始就不会显示正确。

**Comment by razerdp** [comment]
输入法问题，特别横屏下，建议不需要去适配输入法，setAdjustInputMethod(false)
