### ISSUE TITLE
当我popup高度不固定时显示不完整。

### ISSUE THREAD

**Issue by xiaochout4** [razerdp/BasePopup#190]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：android 9.0
 - 库版本：2.2.0
 - 问题描述/重现步骤：实现一个从底部弹出的输入框，设置高度为最大，同时设置距离顶部150dp补丁。结果就是弹出的键盘会把布局顶上去。这是从2.0.8版本升级到2.2.0出现的一个问题。
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/27763120/58062943-e6e7fd00-7bae-11e9-92df-0a8b1ebd2648.png)
![image](https://user-images.githubusercontent.com/27763120/58063037-26164e00-7baf-11e9-98e7-059cabc18baa.png)
![image](https://user-images.githubusercontent.com/27763120/58063060-34fd0080-7baf-11e9-9418-f651999edb16.png)

 - 报错信息：无

---

**Comment by razerdp** [comment]
键盘默认会对齐到popup的底部，而你是全屏的- -当然会顶上去。。。关闭键盘适配即可。

**Comment by razerdp** [comment]
setAdjustInputMethod(false)
