### ISSUE TITLE
三星note4输入法会挡住输入框

### ISSUE THREAD

**Issue by Jibinghao** [razerdp/BasePopup#191]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：android6.0
 - 库版本：2.1.5
 - 问题描述/重现步骤：输入法会输入框给挡住了
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/12150259/58140851-91295880-7c73-11e9-8d61-d15da8caf4e9.png)
![image](https://user-images.githubusercontent.com/12150259/58140875-aacaa000-7c73-11e9-946d-d8bd4a612755.png)

 - 报错信息：

---

**Comment by razerdp** [comment]
更新到新版

**Comment by Jibinghao** [comment]
这回复速度 吓到我了 我试试看

**Comment by Jibinghao** [comment]
更新到2.2.0，原来不会有边距的手机（华为8.0），现在有边距了。安装最新的demo，没有适配成功，都勾选上了。
![image](https://user-images.githubusercontent.com/12150259/58141366-bcad4280-7c75-11e9-8564-f9cab7ef4dc2.png)
![image](https://user-images.githubusercontent.com/12150259/58141373-c59e1400-7c75-11e9-906b-6934f220e338.png)

**Comment by razerdp** [comment]
嗯，稍后candy版本修复

**Comment by razerdp** [comment]
你好，请更新到 Candy渠道最新版试试~

**Comment by razerdp** [comment]
2.2.1.190522
