### ISSUE TITLE
popupwindow设置跟随软键盘弹起,布局偏移量过高

### ISSUE THREAD

**Issue by Roben1016** [razerdp/BasePopup#192]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：Android 6.0.1
 - 库版本：2.2.0
 - 问题描述/重现步骤：根据demo写的一个类似微信评论的弹出框, demo中的从底部上滑的输入法样式, 在Nexus 5手机上输入框和软键盘之间有条缝隙(高度和底部虚拟导航栏一样高).代码也比较简单,一个输入框一个ImageView一个Button
 - [问题代码/截图：
![微信图片_20190522204601](https://user-images.githubusercontent.com/15700182/58175543-ed6f9500-7cd2-11e9-8e7c-787f228333e4.jpg)

 - 报错信息：

---

**Comment by Roben1016** [comment]
但是在这个手机上运行demo时, demo是没有问题的.

**Comment by razerdp** [comment]
更新到candy最新版看看

**Comment by Roben1016** [comment]
> 更新到candy最新版看看

我找到点问题, 我的主题是没有ActionBar和windowNoTilte的, 我把这两个主题的属性删除后, 没有间隙了, 但这两个属性我是需要的

**Comment by razerdp** [comment]
新版candy就是针对这类问题去解决的

**Comment by Roben1016** [comment]
更新到candy版本没问题了, 不知道什么时候能上稳定版

**Comment by Roben1016** [comment]
> 新版candy就是针对这类问题去解决的

更新到candy版本没问题了, 不知道什么时候能上稳定版

**Comment by razerdp** [comment]
至少3次稳定迭代及多次测试后，目前就先用着糖果吧^o^candy目前来说还挺稳定（除了更新较多，也没啥毛病）

**Comment by Roben1016** [comment]
> 至少3次稳定迭代及多次测试后，目前就先用着糖果吧^o^candy目前来说还挺稳定（除了更新较多，也没啥毛病）

好的
