### ISSUE TITLE
setAutoLocatePopup如何判断显示的位置用以更换动画

### ISSUE THREAD

**Issue by q996467794** [razerdp/BasePopup#193]
- 系统版本：9.0
 - 库版本：2.1.9
 - 问题描述/重现步骤：在一个可滚动的list中使用设置了autoLocatePopup对应的动画应该根据
向上弹出或者向下弹出更改,可是目前好像无法判断是会向上弹出还是向下弹出
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
- -对应动画 可不会根据方向改变的哦~

**Comment by razerdp** [comment]
autolocatepopup只能帮您定位，无法帮您更改动画的。

如果需要修改动画，请在定位回调中设置动画，onAnchorTop/Bottom。

**Comment by ithomasoft** [comment]
大神好，定位回调这里指的是什么意思？我在代码中直接继承onAnchorTop/Bottom没有回调，应该在什么位置调用这个方法

**Comment by razerdp** [comment]
在之前的版本中BasePopup有onAnchorTop/onAnchorBottom方法，这两个方法的意思是popup显示在anchor上方或者下方，在这里可以修改动画，但在之前的版本中是有点问题的，所以在现在版本去除掉了，同时我现在正在迭代这一部分的逻辑，在之后的版本会重新开放出来。

之后会有个方法回调告知Popup会显示在anchor的什么位置，并且是在执行动画之前的，到时候就可以修改动画了。

**Comment by ithomasoft** [comment]
> 显示在anchor的什么位置，并且是在执行动画之前的，到时候

好的，谢谢。
