### ISSUE TITLE
动画失效

### ISSUE THREAD

**Issue by q996467794** [razerdp/BasePopup#194]
- 系统版本：9.0
 - 库版本：2.1.9
 - 问题描述/重现步骤：根据您的建议我打算在onAnchorTop/onAnchorBottom更改动画，但是我使用变量存放动画后通过onCreateShowAnimation/onCreateDismissAnimation return并未生效，
变量始终为null
 - 问题代码/截图：
private fun createVerticalAnimation(fromY: Float, toY: Float): Animation {
        val animation = TranslateAnimation(
            Animation.RELATIVE_TO_SELF,
            0f,
            Animation.RELATIVE_TO_SELF,
            0f,
            Animation.RELATIVE_TO_SELF,
            fromY,
            Animation.RELATIVE_TO_SELF,
            toY
        )
        animation.duration = 150
        animation.interpolator = DecelerateInterpolator()
        return animation
    }

    private var showPopAnimation = createVerticalAnimation(1f, 0f)
    private var dismissPopAnimation = createVerticalAnimation(0f, 1f)

    override fun onCreateShowAnimation(): Animation {
        return showPopAnimation
    }

    override fun onCreateDismissAnimation(): Animation {
        return dismissPopAnimation
    }

   override fun onAnchorTop() {
        showPopAnimation = createVerticalAnimation(1f, -1f)
        dismissPopAnimation = createVerticalAnimation(-1f, 1f)
    }

    override fun onAnchorBottom() {
        showPopAnimation = createVerticalAnimation(1f, 0f)
        dismissPopAnimation = createVerticalAnimation(0f, 1f)
    }
 - 报错信息：

---

**Comment by razerdp** [comment]
create只会初始化一次，请使用setAnimation，覆盖初始化的动画，具体看wiki.

**Comment by q996467794** [comment]
onAnchorTop/onAnchorBottom 调用 setShowAnimation/setDismissAnimation 只有dismiss动画生效是什么问题呢？

**Comment by q996467794** [comment]
我尝试更新版本到2.2.0，并添加BasePopup-compat-androidx 结果AutoLocatePopup失效 始终在向下显示，并且show dismiss动画都失效

**Comment by razerdp** [comment]
提供下截图。

**Comment by q996467794** [comment]
![微信图片_20190527112005](https://user-images.githubusercontent.com/7836227/58393484-87d42d80-8071-11e9-810c-761b83f9c29c.png)

**Comment by razerdp** [comment]
是否配置过什么。。。在demo里很正常。

至于show 的动画，确实可能会设置无效，因为在调用show 的时候就已经把动画传进去，而onAnchorTop/Bottom则是在layout的时候应用的。所以会导致dismiss的时候生效，show的时候不生效。

至于自动定位，是经过测试的，似乎没有问题。


![Popo截图2019527112313](https://user-images.githubusercontent.com/11629986/58393613-f913e080-8071-11e9-8c90-18277f7a983b.png)

**Comment by q996467794** [comment]
2.1.9升级到2.2.0把setAllowInterceptTouchEvent /  setAllowDismissWhenTouchOutside这两个过时方法替换没有修改其他配置

**Comment by razerdp** [comment]
setAllowInterceptTouchEvent 注意修改前后的布尔值。

在之前allowintercept(true)意味着外部不可点击
之后更名为outSideTouchable(true)，此时意味着外部可点击。

 不过理论上不影响。。。有没有配置过clipToScreen

**Comment by q996467794** [comment]
setAllowInterceptTouchEvent已经取反过了，没有配置过clipToScreen
isAllowInterceptTouchEvent = true
isAllowDismissWhenTouchOutside = true
setBackgroundColor(Color.TRANSPARENT)
isAutoLocatePopup = true
popupGravity = Gravity.CENTER_HORIZONTAL or Gravity.BOTTOM
只配置过这些

**Comment by razerdp** [comment]
2.2.2.2  新版本尝试一下
