### ISSUE TITLE
RROR: Manifest merger failed with multiple errors, see logs 

### ISSUE THREAD

**Issue by liuxuesong001** [razerdp/BasePopup#195]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：2.2.0
 - 库版本：android x
 - 问题描述/重现步骤： 添加依赖直接报错
 - 问题代码/截图：只添加了就报错了
    //BasePopup androidx支持库
   implementation 'com.github.razerdp:BasePopup-compat-androidx:{$latestVersion}'
 - 报错信息：
RROR: Manifest merger failed with multiple errors, see logs 
---

**Comment by razerdp** [comment]
详细报错呢？
