### ISSUE TITLE
你刚刚修改什么东西了吗

### ISSUE THREAD

**Issue by mengbixiusi** [razerdp/BasePopup#198]
No original dex files found for dex location /data/app/

**Comment by mengbixiusi** [comment]
我项目中用的两个popup都报错了,我确定没改过东西
No original dex files found for dex location /data/app/R$id

**Comment by razerdp** [comment]
请安issue模版提出issue，其次我没有发布新版也就是没有更改任何东西。

**Comment by mengbixiusi** [comment]
好的. 可能我太着急了,不好意思




------------------ 原始邮件 ------------------
发件人: "WeiChaoFeng"<notifications@github.com>;
发送时间: 2019年6月10日(星期一) 下午4:25
收件人: "razerdp/BasePopup"<BasePopup@noreply.github.com>;
抄送: "mengbixiusi"<791966765@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [razerdp/BasePopup] 你刚刚修改什么东西了吗 (#198)




请安issue模版提出issue，其次我没有发布新版也就是没有更改任何东西。
