### ISSUE TITLE
android 7.0 华为系列手机有问题，showAs……的这个

### ISSUE THREAD

**Issue by yxyaxng** [razerdp/BasePopup#20]
就跟没修复一样，图片上传不了，点击slide,右上，展示跟左上一样，左下，右下都没反应

**Comment by LichFaker** [comment]
同样遇到该问题， 同时在7.x 的系统上（华为nova、一加3）均点击无响应，之后黑屏

**Comment by wuming2** [comment]
貌似是只修复了showAsDropDown(View)，只要传入Gravity不是(Gravity.TOP | Gravity.START)应该就有问题

**Comment by dyfan** [comment]
+1
