### ISSUE TITLE
被键盘顶起后，点击弹窗内容区域也会消失

### ISSUE THREAD

**Issue by coderlzx** [razerdp/BasePopup#200]
- 系统版本：不区分
 - 库版本：
 - 问题描述/重现步骤：被键盘顶起后，点击弹窗内容区域也会消失
 - 问题代码/截图：
经检查是ignoreTarget.getGlobalVisibleRect(bounds);获取的坐标值有问题
 - 报错信息：

---

**Comment by coderlzx** [comment]
忘写了库版本Candy2.2.1

**Comment by razerdp** [comment]
曾经有个issue对于全屏Popup要求点击非子控件区域也可以dismiss，因此默认情况下点了非子控件的时候会dismiss()，请设置[**setoutsidedismiss(false)**](https://github.com/razerdp/BasePopup/wiki/API#setoutsidedismissboolean-outsidedismiss)解决。

**Comment by coderlzx** [comment]
![image](https://user-images.githubusercontent.com/3348827/59255894-61171900-8c65-11e9-8c1a-38483dc8a4a1.png)
点击ne内容区域弹窗会消失
