### ISSUE TITLE
小米note3上底部右边飞出屏幕了

### ISSUE THREAD

**Issue by langlangsAgo** [razerdp/BasePopup#201]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：8.1.0
 - 库版本：2.2.0
 - 问题描述/重现步骤：底部弹出pop右边显示不全,按照BlurSlideFromBottomPopupFrag这个类同样写的
 - 问题代码/截图：
![微信图片_20190618110639](https://user-images.githubusercontent.com/20237865/59650675-6fab8600-91b9-11e9-893c-739ca56656b2.png)

 - 报错信息：

---

**Comment by razerdp** [comment]
用了头条类适配方案吗？

**Comment by langlangsAgo** [comment]
是的 用了那个适配

**Comment by razerdp** [comment]
去看常见问题，里面有说。

**Comment by langlangsAgo** [comment]
好的 3Q
