### ISSUE TITLE
Spinner Inside a BasePopUpWindow Crash the App

### ISSUE THREAD

**Issue by Zulqurnain** [razerdp/BasePopup#202]
**Android Version:** 28
**Build Version:** 28.0.3
**Library Version :** 2.2.1
**Androidx Support version:** 1.1.0-alpha04

### Build.gradle:
```
 // BasePopup main library
    implementation 'com.github.razerdp:BasePopup:2.2.1'
    //BasePopup androidx support library (for the above two supported androidX versions)
    implementation 'com.github.razerdp:BasePopup-compat-androidx:2.2.1'
```

**Steps to reproduce:**

Just Add a Spinner Inside any XML View and create a QuickPopUp or Use it inside BasePop , when click on Spinner App gets crashed error is

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@83b35f3 is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:685)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:319)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
        at android.widget.PopupWindow.invokePopup(PopupWindow.java:1273)
        at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1120)
        at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1079)
        at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1058)
```

**Interesting fact** is non spinner pop ups are also not working like i also tried to use [MaterialSpinner](https://github.com/jaredrummler/MaterialSpinner) but it didn't worked either same error.

**Comment by razerdp** [comment]
I can not reproduce this problem....

Demo Gif here:

![fdfd](https://user-images.githubusercontent.com/11629986/60241763-9f0f7080-98e6-11e9-9c5e-0b8399c0a59c.gif)


Xml:

![微信截图_20190627141934](https://user-images.githubusercontent.com/11629986/60241797-b3536d80-98e6-11e9-9aad-1485382b0006.png)

**Comment by Zulqurnain** [comment]
You need to pass activity context in dialog for this issue to reproduce

**Comment by razerdp** [comment]
could you provide some example code for that?
