### ISSUE TITLE
DismissAnimator使用AnimatorSet导致消失动画失效

### ISSUE THREAD

**Issue by tpnet** [razerdp/BasePopup#203]
- 系统版本：Android6.0
 - 库版本：20190611
 - 问题描述/重现步骤：在onCreateDismissAnimator里面return的类是AnimatorSet会导致消失动画不生效。
 - 问题代码/截图：目前最新代码，列表弹窗ListPopup，就有这样的问题
![image](https://user-images.githubusercontent.com/17380722/60342579-72da1980-99e4-11e9-9fe5-2addfc7b0c34.png)

 - 报错信息：没有

---

**Comment by tpnet** [comment]
大佬，有空看吗

**Comment by razerdp** [comment]
暂时来说，你先给animatorset设置duration

**Comment by tpnet** [comment]
好的呢
