### ISSUE TITLE
Apk瘦身问题。

### ISSUE THREAD

**Issue by kelinZhou** [razerdp/BasePopup#204]
- 库版本：2.2.1
请问，可不可以将高斯模糊的两个.so文件（librsjni.so和libRSSupport.so）分离出来，让开发者自行确定要不要使用。因为这两个.so文件加起来一共有1.5M以上了，还是有点大的。对于apk瘦身有严格要求的开发者来说1.5M确实有点大。况且这个功能并不是所有人都用的到。
![image](https://user-images.githubusercontent.com/19147545/60493640-d2d00900-9cdf-11e9-8fe5-e9290fe18f47.png)

希望您能考虑我的建议，谢谢。

**Comment by razerdp** [comment]
当你不配置gradle的时候，就会采用java的fastblur，这两个是gradle配置后生成的renderscript的so包。不配置renderscript即可

**Comment by kelinZhou** [comment]
renderscriptTargetApi 26
renderscriptSupportModeEnabled true
上面这两个的问题吗？

**Comment by kelinZhou** [comment]
我把他们注掉或将值改为false都试过了，那个librsjni_androidx.so消失了，而这那两个so文件依然存在。

**Comment by razerdp** [comment]
删掉生成的so试试，因为已经生成过一次了。把renderscriptTargetApi 和renderscriptSupportModeEnabled 都去掉

**Comment by kelinZhou** [comment]
删掉？打包之前是没有的，打包之后才出现的。我把renderscriptTargetApi 和renderscriptSupportModeEnabled 都去掉依然会出现这两个.so文件。

**Comment by razerdp** [comment]
emmm，有个问题，你是不用了别的库，比如glide-Transformations

**Comment by kelinZhou** [comment]
稍等我看看

**Comment by kelinZhou** [comment]
![image](https://user-images.githubusercontent.com/19147545/60559036-d2864b00-9d7d-11e9-8eb0-a76042c0d330.png)
这里我的glide依赖。

**Comment by razerdp** [comment]
我刚刚其实测试过了，如果引用了类似glide-Transformations的库，因为他gradle里强配置了rsblur [链接](https://github.com/wasabeef/glide-transformations/blob/master/transformations/build.gradle#L10)

而BasePopup一开始就考虑到这个，所以都是让用户在app module里配置的，如果不配置是不会有相关的lib产生，所以你可以排查下可能有关联的库

![微信截图_20190703105732](https://user-images.githubusercontent.com/11629986/60560218-889f6400-9d81-11e9-812b-e9aa0e1d5002.png)
![微信截图_20190703105821](https://user-images.githubusercontent.com/11629986/60560220-89d09100-9d81-11e9-923d-23fcfac56531.png)

**Comment by kelinZhou** [comment]
好的，我知道了  我在排查一下，谢谢您了。
