### ISSUE TITLE
放在底部，被虚拟栏遮挡

### ISSUE THREAD

**Issue by wlxfxy** [razerdp/BasePopup#206]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：8.1.0
 - 库版本：2.2.1
 - 问题描述/重现步骤：要把popupwindow放在界面底部，然后在Nubianx611j手机上被虚拟栏遮挡。
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
截图谢谢。

**Comment by wlxfxy** [comment]
![微信图片_20190705113742](https://user-images.githubusercontent.com/15390552/60696629-2ed1a200-9f19-11e9-84e4-d408b4e7333d.png)

**Comment by razerdp** [comment]
代码贴一下

**Comment by wlxfxy** [comment]
在代码中
 BottomSelectPop bottomSelectPop=new BottomSelectPop(this);
 bottomSelectPop.showPopupWindow(activityShopInfo);
activityShopInfo是界面的顶层布局Linearlayout
在xml中：
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/white"
    android:layout_gravity="bottom">

    <TextView
        android:id="@+id/pop_select_camera"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_horizontal"
        android:text="拍照"
        android:textSize="16sp"
        android:textColor="@color/black_28"
        android:paddingTop="12dp"
        android:paddingBottom="12dp">
    </TextView>
    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="@color/gray_f4"/>
    <TextView
        android:id="@+id/pop_select_pic"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_horizontal"
        android:text="相册"
        android:textSize="16sp"
        android:textColor="@color/black_28"
        android:paddingTop="12dp"
        android:paddingBottom="12dp">
    </TextView>
</LinearLayout>

**Comment by razerdp** [comment]
。。。当调用showPopupWindow(view)的时候，会跟这个view产生关联，其位置是参考这个view的方向的。

**Comment by razerdp** [comment]
详情请看wiki和demo，如果是以屏幕为参考，只需要有gravity并调用showPopupWindow无参方法即可。

**Comment by wlxfxy** [comment]
好的，解决问题了，谢谢
