### ISSUE TITLE
初始化设置宽高显示不正常的问题

### ISSUE THREAD

**Issue by kelinZhou** [razerdp/BasePopup#207]
- 库版本：2.2.1
 - 问题描述/重现步骤：在构造中传入宽度为MATCH_PARENT 高度为屏幕的二分之一，结果宽度变成了屏幕的二分之一而高度变成了屏幕的宽度。
![image](https://user-images.githubusercontent.com/19147545/60791967-5897fc80-a197-11e9-8870-faf55c082e04.png)
如图，宽度为MATCH_PARENT的话，右侧不应该有空隙才对。
最终找到如下代码，故意将宽度和高度翻转了，不知道是什么意思。
不知道是不是我的姿势有什么问题，还请指教。

![image](https://user-images.githubusercontent.com/19147545/60792166-ca704600-a197-11e9-8c2f-d204cfdd4c91.png)

---

**Comment by kelinZhou** [comment]
验证过  宽度如果不使用MATCH_PARENT的话就是正常的。

**Comment by razerdp** [comment]
got，感谢回应，当时那个问题其实是解决 注释里面的issue的，导致这个问题可能是因为match_parent在第一次measure的时候，size会是一个超大的值，因此刚好触发了这个问题。

这里是我的锅，相当于我制造了一个bug，不过目前没有很好地解决方案，这个修复可能会去掉，如果你急的话我可以先打candy包，等后续我找到比较完美的解决方案再针对这一块进行修正

**Comment by kelinZhou** [comment]
我已经通过自己计算屏幕宽度的方式暂时解决了，等待你的后续更新吧。

**Comment by razerdp** [comment]
candy 2.2.2最新版已修复，该问题比较严重，主要是修复#188 引入的新问题，可以先更新到candy版本，后续修复了#188 后一并发布release

**Comment by mtj956052456** [comment]
![image](https://user-images.githubusercontent.com/24516875/63499192-f2262e00-c4f9-11e9-95da-ce6238c6dfd8.png)
引入依赖失败?

**Comment by razerdp** [comment]
candy后是冒号。

**Comment by mtj956052456** [comment]
打扰了...

**Comment by mtj956052456** [comment]
我可以撤回  这个问题么....

**Comment by mtj956052456** [comment]
打扰了~~
