### ISSUE TITLE
When open a Toast from Dialog, dialog background become transparent

### ISSUE THREAD

**Issue by Zulqurnain** [razerdp/BasePopup#208]
I'm using following versions:
```
// BasePopup main library
    implementation 'com.github.razerdp:BasePopup_Candy:2.2.1.190611'//2.2.1'
    //BasePopup androidx support library (for the above two supported androidX versions)
    implementation 'com.github.razerdp:BasePopup_Candy-compat-androidx:2.2.1.190522'//2.2.1'
```
demo bug
-----------

![IMG20190715172439](https://user-images.githubusercontent.com/5487047/61216190-269e1180-a726-11e9-88b1-bb0f5c869769.gif)

EDIT
====

TestDialog.java
--------------

```
public class TestDialog extends BasePopupWindow {
    
    
    public TestDialog(Context context) {
        super(context);
        View v = getContentView();
        
        v.findViewById(R.id.btn).setOnClickListener(vv -> {
            Toast.makeText(context, "something on this feild", Toast.LENGTH_SHORT).show();
        });
    }
    
    @Override
    public View onCreateContentView() {
        return createPopupById(R.layout.dialog_layout_test);
    }
}
```

dialoh_layout_test.xml
--------------------
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:gravity="center"
    android:layout_height="match_parent">
    <androidx.appcompat.widget.LinearLayoutCompat
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:background="@color/white">

        <Button
            android:id="@+id/btn"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_margin="10dp"
            android:layout_weight="1"
            android:text="Something"
            />

    </androidx.appcompat.widget.LinearLayoutCompat>
</LinearLayout>
```
This is the minimal example creating this issue , try showing this dialog and click on "something" button

**Comment by razerdp** [comment]
could you provide some detail code to reproduce?

**Comment by razerdp** [comment]
I can't reproduce this problem here.

GIF：
![aaaaa](https://user-images.githubusercontent.com/11629986/61459137-a6ceac00-a99e-11e9-9a91-4b521cdb29a1.gif)

At the same time, I noticed that the version you used is candy 2.2.1.The current latest version is Release 2.2.1.

You can upgrade to the latest version and try again

>//BasePopup main project
implementation 'com.github.razerdp:BasePopup:2.2.1'
>//BasePopup androidx support library
implementation 'com.github.razerdp:BasePopup-compat-androidx:2.2.1'


Finally, I am very sorry that the English documents have not been updated in time. I will synchronize the Chinese and English documents as soon as possible.

**Comment by razerdp** [comment]
English document has updated

[**README_EN**](https://github.com/razerdp/BasePopup/blob/master/README_V2_EN.md)

**Comment by Zulqurnain** [comment]
Maybe this issue is solved it in latest release , i'll try this and if issue persists i'll reopen this issue
