### ISSUE TITLE
setOutSideTouchable（true）显示不正常

### ISSUE THREAD

**Issue by Kingnewspring** [razerdp/BasePopup#210]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：android p
 - 库版本：release 2.2.1
 - 问题描述/重现步骤：调用setOutSideTouchable（true）方法，再showPopupWindow（view)时，位置发生偏移，去掉该方法或者setOutSideTouchable（false）则正常显示。
 - 问题代码/截图：
![微信图片_20190727222844](https://user-images.githubusercontent.com/11664870/61995671-feb39400-b0bd-11e9-8176-81388d0703d5.png)
![微信图片_20190727222855](https://user-images.githubusercontent.com/11664870/61995674-070bcf00-b0be-11e9-996c-253955d32969.png)

调用代码如下：  
```         
            productPop = new ProductPop(getActivity(), condictionDataList);
            productPop.setOutSideDismiss(true);
            productPop.setPopupGravity(Gravity.BOTTOM);
            productPop.setBackgroundColor(0);
            productPop.setOutSideTouchable(true);
            productPop.showPopupWindow(container);
```

 - 报错信息：

---

**Comment by razerdp** [comment]
fixxed

**Comment by razerdp** [comment]
问题已记录并测试，测试Demo请下载BasePopup的Demo

现在Demo已经进行了大翻新，我会对issue进行修复性测试，请随时留意新的Demo哦~

![device-2019-09-22-132709](https://user-images.githubusercontent.com/11629986/65382651-da320c00-dd3c-11e9-9942-f59a53b5b8b6.png)

**Comment by love-311** [comment]
请问上面这个问题已经提交版本了吗？

**Comment by love-311** [comment]
这边Android 9 小米 8手机上，最新的candy版本与稳定版本都会出现上面的问题，看上面大佬貌似已经修复过了，怎么最新的版本都还是一样的问题呢，麻烦解答一下了~

**Comment by razerdp** [comment]
先不要用candy，你看看demo是否有你所说的问题，目前的candy是二次重构的版本。

**Comment by love-311** [comment]
demo 里面看起来的确是修复了，我研究一下你的demo怎么不会有这个问题了，感谢~

**Comment by lieweisi** [comment]
请问是否修复了这个问题，我查看demo里面的，好像是把setPopupGravity(Gravity.RIGHT);放在构造方法中，我按照demo的写法并没有效果，我设置的是靠右，还是会靠左并且高度混乱。

**Comment by lieweisi** [comment]
> demo 里面看起来的确是修复了，我研究一下你的demo怎么不会有这个问题了，感谢~

请问你的可以了吗？

**Comment by love-311** [comment]
> > demo 里面看起来的确是修复了，我研究一下你的demo怎么不会有这个问题了，感谢~
> 
> 请问你的可以了吗？

是的，具体我记得不是很清楚了，你可以尝试看看demo的这个地方，应该能发现问题所在~

**Comment by razerdp** [comment]
@lieweisi 你需要留意库的版本。。。针对这个问题修复的是candy版本的库（而且现在candy版本也在重构中），如果你依赖了问题版本就没有修复了。

当前popup仍在重构中，相对而言稳定没有很大问题的是最新的release版本，下一个版本将会把issue中标记了的全部解决了。

**Comment by lieweisi** [comment]
> @lieweisi 你需要留意库的版本。。。针对这个问题修复的是candy版本的库（而且现在candy版本也在重构中），如果你依赖了问题版本就没有修复了。
> 
> 当前popup仍在重构中，相对而言稳定没有很大问题的是最新的release版本，下一个版本将会把issue中标记了的全部解决了。

好的，希望到时候suuport包也可以使用或者提供解决方案，感谢！

**Comment by razerdp** [comment]
@lieweisi support在下一版已经放弃了。。。

**Comment by lieweisi** [comment]
> @lieweisi support在下一版已经放弃了。。。

尴尬，那是否可以提供个现版本的解决方案
