### ISSUE TITLE
当设置popWindow外部区域可以响应，isShowing一直返回false

### ISSUE THREAD

**Issue by Qiang11** [razerdp/BasePopup#212]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---
当不设置退出动画时 
quickPopupHeader?.isOutSideTouchable = true
quickPopupHeader?.setBackground(null)
quickPopupHeader?.showPopupWindow(view)

isShowing一直返回false
当设置退出动画就正常了
quickPopupHeader?.dismissAnimation = getTranslateVerticalAnimation(0f, -1f, 250)
quickPopupHeader?.isOutSideTouchable = true
quickPopupHeader?.setBackground(null)
quickPopupHeader?.showPopupWindow(view)

**Comment by razerdp** [comment]
请补充版本等信息

**Comment by Qiang11** [comment]
2.2.1

**Comment by razerdp** [comment]
你的isShowing是在哪里调用的？应该跟动画无关。

**Comment by Qiang11** [comment]
mDemoPopup = new DemoPopup(getContext());
        mDemoPopup.setPopupGravity(Gravity.BOTTOM | Gravity.CENTER_HORIZONTAL);
        mDemoPopup.setOutSideTouchable(true);
        mDemoPopup.setBackground(null);
        mDemoPopup.showPopupWindow(vh.popupShow);

        vh.btnClickMe.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mDemoPopup.isShowing()){
                    mDemoPopup.dismiss();
                }else {
                    mDemoPopup.showPopupWindow();
                }
            }
        });

和OutSideTouchPopupFrag这个设置一样，这个这样用也不行，加个退出动画就可以了

**Comment by razerdp** [comment]
噢，是这样的。

basepopu默认情况下点击外部是会dismiss的，当您添加退出动画，则点击外部会在退出动画播放后才会真正的dismiss，而您现在是没有退出动画意味着只要点的是popup外部，则立即dismiss，此时isShowing也理应为false。

时序大概是这样的：点击外部->popup响应外部事件->dismiss（没有动画）->响应点击的popup事件。


所以如果您想自己管理的话，请设置outSideDismiss(false)

**Comment by Qiang11** [comment]
这么设置的点击外部空白区域之类的，怎么关闭呢，，，大佬

**Comment by razerdp** [comment]
那你这么弄我这没办法给你处理。。。。

**Comment by razerdp** [comment]
首先点击外部就已经关闭了，你却要求我点击外部时告诉我没有关闭。

**Comment by Qiang11** [comment]
唉 我们目前有这个需求，点击外部关闭popWindow，外面有个按钮控制popWindow的显示或者是关闭，，，多谢大佬解答，，，目前我就加个退出动画吧

**Comment by razerdp** [comment]
basepopup里面我预留了outsideTouch方法，或许你可以在这里入手
