### ISSUE TITLE
Honor Play 9.0系统不能不能覆盖状态栏

### ISSUE THREAD

**Issue by mtj956052456** [razerdp/BasePopup#214]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/24516875/62598230-48e91080-b91b-11e9-9aea-75ab654f963f.png)

 - 报错信息：

---

**Comment by razerdp** [comment]
补全信息。

**Comment by mtj956052456** [comment]
系统版本：9.0

库版本：2.1.5

问题描述/重现步骤：状态栏不能全覆盖 , 但是下载的Demo可以 , 我尝试着用一个新的项目 , 但结果还是不能覆盖全屏幕

**Comment by razerdp** [comment]
更新到最新版试试

**Comment by mtj956052456** [comment]
晕了  果然是库版本没有用到最新的,可是Tag没有看到最新的版本,jitpack也找不到

**Comment by mtj956052456** [comment]
库2.1.9版本  解决了问题

**Comment by razerdp** [comment]
最新2.2.1…你看readme

**Comment by mtj956052456** [comment]
谢谢   看到了  最新2.2.2  如果能加上Tags就好了

**Comment by razerdp** [comment]
以readme为准
