### ISSUE TITLE
在Popup上的按钮,如果获取popup所在的Fragment或者activity

### ISSUE THREAD

**Issue by chenwuwen** [razerdp/BasePopup#215]
Popup上的按钮的view,在使用
NavController navController = Navigation.findNavController(v);
方法时会报错，版本是：implementation 'com.github.razerdp:BasePopup:2.2.1'

**Comment by razerdp** [comment]
popup上的view的context皆是appcontext来的，本身不具备windowToken。你可以通过popup的context完成。

**Comment by chenwuwen** [comment]
感谢：问题解决了，使用了popup上的view的context。
具体代码如下：
    Activity activity = (Activity) context;
    View view = activity.findViewById(Fragment或者Activity上的一个View的Id);

**Comment by chenwuwen** [comment]
> popup上的view的context皆是appcontext来的，本身不具备windowToken。你可以通过popup的context完成。

我实现了我的目的，但是又出现一个情况，就是我点击了popup上的按钮，实现了页面的跳转，但是popup还会显示，我的目的是不让其显示，但是我没法调用Dismiss方法
