### ISSUE TITLE
软键盘不会顶起布局

### ISSUE THREAD

**Issue by elmliu** [razerdp/BasePopup#216]
- 系统版本：7.0
 - 库版本：2.1.9
 - 问题描述/重现步骤：
点击editText后，软键盘弹出，但布局并没有被顶起<br/>
popup的定位方式是，我在活动布局根节点CoordinatorLayout中添加了一个FrameLayout位于其底部，之后调用showPopupWindow(bottomFramelayout); 且popup的layout_gravity="top"<br/>
最初尝试layout_gravity="bottom"和showPopupWindow(); 但是并没有显示弹窗，可能是因为这个活动本身没有布局文件，继承了父类的原因吗？ 
 - 问题代码/截图：
![0](https://user-images.githubusercontent.com/35032015/63109013-c61b2200-bfba-11e9-82a3-fbf48e010e64.png)
![1](https://user-images.githubusercontent.com/35032015/63109026-c9aea900-bfba-11e9-9e63-2f3e379418a1.png)

 - 报错信息：

---

**Comment by razerdp** [comment]
更新到最新版2.2.1吧
