### ISSUE TITLE
请问一下怎么做点击事件的跳转

### ISSUE THREAD

**Issue by androidscx** [razerdp/BasePopup#22]
在继承了BasePopup的内部做点击事件  怎么跳转?????

**Comment by androidscx** [comment]
可以打吐司 但是怎么实现跳转?

**Comment by razerdp** [comment]
@androidscx 你的跳转具体指什么，，，onClick事件自行处理呀。。。。而且可以打toast，意味着点击事件响应了，那么之后的逻辑你平时怎么写现在也就怎么写咯
