### ISSUE TITLE
华为平板M6 弹窗弹不出来

### ISSUE THREAD

**Issue by lly7690** [razerdp/BasePopup#221]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：9
 - 库版本：2.2.1
 - 问题描述/重现步骤：弹窗弹不出来
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
描述太简单，没有任何参考意义，请提供详细信息
