### ISSUE TITLE
当显示在底部的时候 ，popupwindow在虚拟键的下面

### ISSUE THREAD

**Issue by qiangzengli** [razerdp/BasePopup#222]
- 系统版本：   模拟器   API 28
 - 库版本： 2.2.0
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/38590285/64074576-a0db2300-ccdf-11e9-9dfc-584be717abc7.png)

---

**Comment by razerdp** [comment]
请展示一下主题和代码/布局
