### ISSUE TITLE
不同机型，弹框ui显示不完全，适配问题？

### ISSUE THREAD

**Issue by paihuai00** [razerdp/BasePopup#223]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本： 华为mate20x Android 9.0、Pixel2xl  Android 10 （均出现UI整体右偏问题）

 - 库版本：com.github.razerdp:BasePopup:2.2.1
 - 问题描述/重现步骤：集成BasePopupWindow，createPopupById 实现布局
 - 问题代码/截图：

public class GroupTypePopupWindow extends BasePopupWindow {

    public GroupTypePopupWindow(Context context) {
        super(context);
    }

    @Override
    public View onCreateContentView() {
        return createPopupById(R.layout.dialog_group_filter_type);
    }
}

//--------调用----------
GroupTypePopupWindow mGroupFilterPopupWindow = new GroupTypePopupWindow(this);
        mGroupFilterPopupWindow.setClipToScreen(true);
        mGroupFilterPopupWindow.setOnDismissListener(new BasePopupWindow.OnDismissListener() {
            @Override
            public void onDismiss() {
                //.....
            }
        });

mGroupFilterPopupWindow.showPopupWindow(mRlSelectType);

 - 问题：出现适配问题，整体UI向右移动，导致显示不完全，麻烦看下，是我代码有问题吗？如下图

---
![image](https://user-images.githubusercontent.com/20215838/64469494-c8117480-d165-11e9-8c71-45e5313c267b.png)
![image](https://user-images.githubusercontent.com/20215838/64469532-5dad0400-d166-11e9-9b19-038d5912dc08.png)

**Comment by razerdp** [comment]
是否用了autosize之类的？

**Comment by paihuai00** [comment]
是的，适配用的是“me.jessyan:autosize:1.1.2”，跟这个有影响m?

**Comment by razerdp** [comment]
请看常见问题
