### ISSUE TITLE
想实现autocompletetextview类似的EditText模糊查找数据功能

### ISSUE THREAD

**Issue by ZhongXiaoBei** [razerdp/BasePopup#224]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---
想实现autocompletetextview类似的EditText模糊查找数据功能，弹出popupwindow后EditText的键盘输入事件被popwindow拦截了

**Comment by razerdp** [comment]
当前版本可以使用getPopupWindow().setFocusable(false)，下个版本我将会修复这个问题

**Comment by ZhongXiaoBei** [comment]
界面布局：底部放一个EditText，想实现效果EditText输入内容后能模糊查找本地数据库内容。popupwindow里的内容是recycleview的，popupwindow的xml文件high是wrap_content，如果recycleview数据过多popupwindow高度会顶到屏幕上边缘。
问题：
1、一开始popupwindow内容比较多，popupwindow的高度是从屏幕上边缘到底部的EditText上边缘，随着EditText内容输入变多，popupwindow的内容变少而popupwindow的高度变成从屏幕上边缘开始包裹内容，而不是已EditText为标准向上显示，调用的是showPopupWindow(edittext)；
尝试先调用pop.dismiss()后调用pop.showPopupWindow(edittext)，但是popupwindow不显示。
2、如何设置popupwindow高度？在xml里layout_height=wrap_content，marginTop = 50dp，popupwindow在内容很多时并不是距离上部分50d，高度变的很小。

**Comment by razerdp** [comment]
麻烦截图描述，顺便补充详细信息。

**Comment by razerdp** [comment]
好的，我追踪一下，下个版本修复后再在这里标记

**Comment by ZhongXiaoBei** [comment]
好的，谢谢大佬

**Comment by razerdp** [comment]
@ZhongXiaoBei 

问题已经修复了~ 库版本：candy 2.2.3.20200406


修复结果如下：

![ezgif-7-5e2259b99fe4](https://user-images.githubusercontent.com/11629986/78574235-49e09200-785c-11ea-891a-ecad57fb0d0d.gif)
