### ISSUE TITLE
BasePopup 中弹出 BasePopup 显示异常或者报错

### ISSUE THREAD

**Issue by wr1024** [razerdp/BasePopup#225]
- 系统版本：Android 8.1.0  oppo A5
 - 库版本：2.2.1
 - 问题描述/重现步骤： 
    Activity下先弹窗PopupWindow，然后PopupWindow上再点击按钮弹出PopupWindow，显示异常或者报错：  当设置showPopupWindow(view)时，报错：android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@74731d5 is not valid; is your activity running?

 
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
popupwindow里面的view是没有windowToken的，不可以让其作为anchorView。

**Comment by wr1024** [comment]
> popupwindow里面的视图是没有windowToken的，不可以让其作为anchorView。

那么如何在PopupWindow中使用PopupWindow呢？

**Comment by razerdp** [comment]
你可能需要手动计算offset，不过这个也许可以作为一个后续功能。。。我考虑加入到下一个版本中

**Comment by razerdp** [comment]
该问题在candy 2.2.8解决了~

【Candy】2.2.8.0817 (2020/08/17)
支持BasePopup使用BasePopup内的AnchorView弹窗
