### ISSUE TITLE
Android Q 上出现奔溃，百分之百复现

### ISSUE THREAD

**Issue by WDevaloper** [razerdp/BasePopup#227]
- 系统版本：Android Q
 - 库版本：    2.1.1
 - 问题描述/重现步骤：100%
 - 问题代码/截图：无
 - 报错信息：
Accessing hidden field Landroid/widget/PopupWindow;>mOnScrollChangedListener:Landroid/view/ViewTreeObserver$OnScrollChangedListener; (greylist-max-p, reflection, denied)

**Comment by razerdp** [comment]
请更新到最新版本

**Comment by razerdp** [comment]
不排除这个可能，当前暂时没去管AndroidQ，不过BasePopup并没有反射过任何ScrollChangeListener，你那边有更详细的报错么
