### ISSUE TITLE
不易用

### ISSUE THREAD

**Issue by addappcn** [razerdp/BasePopup#23]
上手难难，demo很好，但是用到项目里根本不行 主要是显示在某个view 的方位

**Comment by limjiregister** [comment]
不知为何，点击toolbar左边的item，总是弹出在toolbar的左下方。而不是在右边。求看到这个疑问的解惑一下

**Comment by razerdp** [comment]
@addappcn 显示在某个view主要是依靠两个
1 - showPopupWindow(View v)，也就是你必须把view传进去，然后内部会将popup与anchorView的锚点对齐（左上角）
2 - 你需要设定offset，可以在继承BasePopupWindow后覆写showPopupWindow，也可以用OnBeforeShowCallback 在show之前调用。

@limjiregister 有没有具体demo或者例子，截图也好。

**Comment by addappcn** [comment]
你写的用起来不是太易懂那就把注释写清楚，用了你的这个东西  我感觉我做了几年android开发 都一无是处了。真的，也许我真的没有看懂代码。

**Comment by razerdp** [comment]
@addappcn 嗯，谢谢你的提议，我会慢慢加上注释的。
