### ISSUE TITLE
update不起作用

### ISSUE THREAD

**Issue by yoyiyi** [razerdp/BasePopup#230]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：安卓9.0
 - 库版本：2.2.1
 - 问题描述/重现步骤：
问题：
作者您好，使用您的库，再使用过程中遇到一些问题。
更改popup高度，不起作用
1.popup布局里面有recyclerview
2.填充rv的数据售，有点击按钮，可以删除rv的item
3.使用update() 或者update(width,height-item的高度)
4.popup的布局高度都不会改变
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
好的，该问题今晚收录到demo中测试~

ps，在2.2.2中我们重构了measure/layout，同时针对update会有一次针对性优化，估计到时候发布release的时候可以修复您所说的问题。

感谢支持

**Comment by razerdp** [comment]
您好，经测试，您的issue无法重现，该测试用例已添加到Demo中，请留意更新。

另外，在demo中，并不需要调用update，布局都会跟随修正的。

![ezgif-4-5f5bd938929e](https://user-images.githubusercontent.com/11629986/66413594-43e33300-ea2a-11e9-91d8-95b8c8c34afc.gif)

**Comment by yoyiyi** [comment]
您好，已找到原因，在popup中不能使用 mAdapter.notifyItemRemoved()，而是要 使用mAdapter.notifyDataSetChanged()

**Comment by razerdp** [comment]
应该不影响的，demo中就是notifyitemremove。（从gif图删除item有动画也能看得出）

**Comment by yoyiyi** [comment]
这就奇怪了，我把notifyitemremove换成notifyDataSetChanged就可以了，唯一不同我那个popup是从底部一个button上从下往上弹出来，
