### ISSUE TITLE
basepopup显示位置会下滑

### ISSUE THREAD

**Issue by sivanhe** [razerdp/BasePopup#231]
- 系统版本：android 9（红米miui 10.3.5）
 - 库版本：库demo
 - 问题描述/重现步骤：快速入门/朋友圈评论/设置/选中outsidetouchable/确定/点击评论/点击图片/再次点击图片退出
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/30306863/67137730-58b29880-f26c-11e9-9e61-afe9caf901c4.jpg)

 - 报错信息：评论在最下方显示

-另：1、有时demo朋友圈设置outsidetouchable后返回，再次进入朋友圈，点击评论，会自动下滑
2、quickpopup有类似问题，当输入法显示时，点击quickpopup，其会下滑到输入法上部

---

**Comment by razerdp** [comment]
1
