### ISSUE TITLE
razerdp.basepopup.BasePopupSupporterManager$BasePopupSupporterProxy.attachLifeCycle(razerdp.basepopup.BasePopupWindow, java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by Christine-YNG** [razerdp/BasePopup#235]
- 库版本：2.2.1
 - 问题代码/截图：
java.lang.NullPointerException: Attempt to invoke virtual method 'razerdp.basepopup.BasePopupWindow razerdp.basepopup.BasePopupSupporterManager$BasePopupSupporterProxy.attachLifeCycle(razerdp.basepopup.BasePopupWindow, java.lang.Object)' on a null object reference
	at razerdp.basepopup.BasePopupWindow.attachLifeCycle(BasePopupWindow.java:1741)
	at razerdp.basepopup.BasePopupWindow.initView(BasePopupWindow.java:415)
	at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:397)
	at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:379)
	at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java
:369)
	at com.aico.smartegg.dialog.AlertPopup.<init>(AlertPopup.java:19)

**Comment by razerdp** [comment]
1 - 请检查是否加上了compat包
2 - 请贴上您使用的代码

**Comment by Christine-YNG** [comment]
> 1 - 请检查是否加上了compat包
> 2 - 请贴上您使用的代码

-  我加了androidX包
new AlertPopup(this,
                 getResources().getString(R.string.KeyPowerMode),
                getResources().getString(R.string.KeyUserSettingPowerSaveHelp))
                .showPopupWindow();
public class AlertPopup extends BasePopupWindow{

    public AlertPopup(Context context, String title, String content) {
        super(context);
    }

    @Override
    public View onCreateContentView() {
        return createPopupById(R.layout.layout_alertview);
    }
}

**Comment by razerdp** [comment]
系统版本呢

**Comment by Christine-YNG** [comment]
> 系统版本呢

9.0

**Comment by razerdp** [comment]
无法复现

**Comment by Christine-YNG** [comment]
> 无法复现

 public BasePopupWindow(Context context, int width, int height, boolean delayInit) {
        mContext = new WeakReference<Context>(context);
        if (!delayInit) {
            initView(width, height);
        } else {
            mDelayInitCached = new DelayInitCached();
            mDelayInitCached.width = width;
            mDelayInitCached.height = height;
        }
    }
我对比了一下github上下载下来的源码
implement引入的代码少了这一行 BasePopupComponentManager.getInstance().init(context);

**Comment by LinXueyuanStdio** [comment]
在悬浮窗里启动PopupWindow，复现成功。。虽然这不符合 PopupWindow 的使用场景

**Comment by razerdp** [comment]
attachLifeCycle这个方法已经被我重构了。。。

**Comment by AlexLiuSheng** [comment]
解决了么

**Comment by razerdp** [comment]
别急，最近我才开始继续撸BasePopup

**Comment by razerdp** [comment]
fixed on 2.2.2

**Comment by LPLuck** [comment]
已经解决了吗   是什么原因造成的啊

**Comment by razerdp** [comment]
忘了，去看2.2.2提交记录，另外版本已经迭代到2.2.10了，相关更新日志请查看文档。

**Comment by LPLuck** [comment]
2.2.2的日志上没写解决了235这个问题，我的项目还没用AndroidX，只能用2.2.1以下的版本吧。

**Comment by razerdp** [comment]
@LPLuck  是的，2.2.2开始必须使用AndroidX了，该方法从2.2.2开始去除掉了（伴随着去除掉扩展组件）。如果项目还没使用AndroidX，这边建议您尽快升级哦~如果因为某些原因无法升级，那BasePopup目前可能无法满足你的需求了。
