### ISSUE TITLE
布局中如何使用kotlinx？ 

### ISSUE THREAD

**Issue by playscforever** [razerdp/BasePopup#237]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
跟你在activity里使用差不多的，你可以在构造器里用

**Comment by playscforever** [comment]
@razerdp 
试了好多次，都不行，有空了能麻烦写个简单的例子看看吗

**Comment by razerdp** [comment]
你能提供下你的代码吗，我这边如果要写使用案例可能要等下一个重构版本完成后

**Comment by razerdp** [comment]
无后续反馈，关闭。
