### ISSUE TITLE
关于在Android7.0下showPopupWindow不显示的问题的解决方案

### ISSUE THREAD

**Issue by WhyYouDoNotUpSky** [razerdp/BasePopup#24]
这是Android7.0 的 popupWindow.showAsDropDown()的bug
解决办法：
下载up主的代码，把lib这个module导入自己的项目（为了修改代码）
修改razerdp.basepopup.BasePopupWindow.java下的tryToShowPopup方法为下面的样子
原谅我不会排版😢
 private void tryToShowPopup(View v) {
        try {
            int offset[];
            //传递了view
            if (v != null) {
                offset = calcuateOffset(v);
                if (showAtDown) {
                    **if (Build.VERSION.SDK_INT < 24) {
                        mPopupWindow.showAsDropDown(v, offset[0], offset[1]);
                    } else {
                        // 获取控件的位置，安卓系统>7.0
                        int[] location = new int[2];
                        v.getLocationOnScreen(location);
                        mPopupWindow.showAtLocation(v, Gravity.NO_GRAVITY, offset[0], offset[1] +
                                location[1] + v.getHeight());
                    }**
                } else {
                    mPopupWindow.showAtLocation(v, popupGravity, offset[0], offset[1]);
                }
            }
           ................
        }
 }
> [参考文章：http://blog.csdn.net/ithe1001/article/details/56281750](http://blog.csdn.net/ithe1001/article/details/56281750)

>

**Comment by razerdp** [comment]
@WhyYouDoNotUpSky  谢谢您提供的思路呢。。。然而事实上，在库里面我就处理过。。

[PopupWindowProxy : Line80](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/PopupWindowProxy.java)

**Comment by razerdp** [comment]
@WhyYouDoNotUpSky 您好，更新到1.8.0试试
