### ISSUE TITLE
QuickPopupBuilder 链式调用设置了 backpressEnable(false) 返回键还是可以用

### ISSUE THREAD

**Issue by huangdianxin** [razerdp/BasePopup#240]
- 系统版本：Android6.0（华为P9plus）
 - 库版本：2.2.1
 - 问题描述/重现步骤：在QuickPopupBuilder 链式调用设置了 backpressEnable(false) 返回键还是可以用
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/10191627/69002027-7a627680-0923-11ea-97c2-2bcf17d499e6.png)

如果使用自定义 BasePopupWindow 的方式就不会出现这个问题。
![image](https://user-images.githubusercontent.com/10191627/69002045-ca413d80-0923-11ea-91fb-069dbb9133a1.png)

 - 报错信息：
无

---

**Comment by razerdp** [comment]
已经在candy修复了，下个版本发布
