### ISSUE TITLE
PopupWindow位于activity上层

### ISSUE THREAD

**Issue by love-311** [razerdp/BasePopup#241]
不知道作者有没有发信微信朋友圈的做法跟作者的可能不同，微信朋友圈应该没有使用PopupWindow，具体可以从微信朋友圈展开之后还可以滑动，而作者的朋友圈其实popup弹出之后是无法滑动的，不知道作者对于此有没有什么见解~

**Comment by razerdp** [comment]
demo就有展示，设置外部可点击和点击外部不dismiss就可以滑了。

**Comment by love-311** [comment]
哇~大佬这么迟不睡的呀~感谢答复~我可以理解设置外部可点击和外部点击外部不dismiss就可以滑动，可是微信的效果并不是不dismiss的滑动，而是dismiss滑动同时进行的呢，而且大佬你的demo我看貌似不dismiss之后这个popup是固定留在了原地，而没有跟随移动呢，飘在那感觉很奇怪

**Comment by razerdp** [comment]
跟随也是可配置的，linkto(View)即可。这些以后我会在文档补充

**Comment by love-311** [comment]
好的，感谢分享~

**Comment by razerdp** [comment]
GIF：在Demo中就有哦，不过目前还有一点点的小问题
![ezgif-6-6d91d8a631de](https://user-images.githubusercontent.com/11629986/69496599-be024500-0f0e-11ea-9a68-be2bfb477a5b.gif)
