### ISSUE TITLE
Release 2.2.1 Service Popup 失效

### ISSUE THREAD

**Issue by Robert-dev0317** [razerdp/BasePopup#242]
當Activity位於當前畫面時行為正常
Activity不在當前畫面Service PopupWindow 失效
Context使用的是ApplicationContext
錯誤訊息:

android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?

**Comment by razerdp** [comment]
activity不在当前页的具体意思是？

**Comment by Robert-dev0317** [comment]
當APP開啟時Activity存在於頁面沒問題
當跳回去桌面Lanuncher  Service在背景執行
這時候沒辦法popup

WeiChaoFeng <notifications@github.com> 於 2019年11月24日 週日 下午10:59寫道：

**Comment by razerdp** [comment]
问题已修复，将会在release 2.2.2发布 ，demo过程如下（该测试用例已经加入到demo中）：

![ezgif-1-6447e0da63f0](https://user-images.githubusercontent.com/11629986/74310702-bda87600-4da8-11ea-9640-9a292ff1ffc8.gif)

**Comment by razerdp** [comment]
fixed in candy 2.2.2.200212
