### ISSUE TITLE
onCreateContentView设计错误

### ISSUE THREAD

**Issue by haohaozaici** [razerdp/BasePopup#243]
- 系统版本：无关
 - 库版本：2.2.0
 - 问题描述/重现步骤：
通过继承BasePopupWindow并实现onCreateContentView()方法来创建PopupWindow，子类的部分在onCreateContentView()调用时没有初始化
 - 问题代码/截图：
```java
public class DemoPopup extends BasePopupWindow {
    RecyclerViewAdapter adapter = new Adapter();
    public DemoPopup(Context context) {
        super(context);
    }

    @Override
    public View onCreateContentView() {
        ...
        // 这里adapter并没有被初始化，不符合通常情况下类初始化的预期行为
        recyclerView.setAdapter(adapter);
        return view;
    }
}
```

问题分析：
默认情况下onCreateContentView()在BasePopupWindow的构造方法中调用，但这里子类实现的onCreateContentView()方法只能在运行时确定，该方法操纵的成员还没有初始化。参考：[构造器内部多态方法的行为](https://lingcoder.github.io/OnJava8/#/book/09-Polymorphism?id=%e6%9e%84%e9%80%a0%e5%99%a8%e5%86%85%e9%83%a8%e5%a4%9a%e6%80%81%e6%96%b9%e6%b3%95%e7%9a%84%e8%a1%8c%e4%b8%ba)

**Comment by razerdp** [comment]
详情参考Android的Fragment#onCreateView()
