### ISSUE TITLE
传入activity,当activity被回收一直显示泄露,之前就有人提出这个问题，望给出解决方案

### ISSUE THREAD

**Issue by WDevaloper** [razerdp/BasePopup#244]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/55203085/69301669-04774b80-0c52-11ea-9b88-ffe1e46f1fd2.png)

 - 报错信息：

---

**Comment by razerdp** [comment]
请补全信息谢谢

**Comment by razerdp** [comment]
其次，所有context都是weakreference.

**Comment by WDevaloper** [comment]
![memory (2)](https://user-images.githubusercontent.com/55203085/69321357-ec1d2600-0c7d-11ea-8f4d-e34b79164a5c.PNG)
这是引用部分截图

**Comment by razerdp** [comment]
1，我会持续关注这个问题的，刚好现在第三次重构，另外你测试过多次gc后还有泄漏吗？有没有代码供参考

**Comment by WDevaloper** [comment]
是的，我重复好多次GC，还是会有泄露的情况，谢谢你的回复

**Comment by razerdp** [comment]
问题泄漏原因在这次的重构中已经解决了，，我多次通过profilter进行检查，发现已经没有泄漏了。

![1](https://user-images.githubusercontent.com/11629986/74223251-47950800-4cf1-11ea-90b7-704abe8ed30a.png)
![2](https://user-images.githubusercontent.com/11629986/74223272-4b288f00-4cf1-11ea-8c11-7a1e5e3f6e6f.png)
