### ISSUE TITLE
连续多次弹出弹窗会卡死

### ISSUE THREAD

**Issue by Andy957** [razerdp/BasePopup#245]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
请补充信息。

**Comment by Andy957** [comment]
用的是模拟器，安卓5.0，多次new，然后show，就卡死了，破模拟器没有日志
![smiling-face-with-open-mouth-and-cold-sweat_1f605](https://user-images.githubusercontent.com/52651185/69425500-f9addb00-0d65-11ea-8914-363d226e8862.png)

**Comment by razerdp** [comment]
首先不太建议多次new，如果是同一个反复使用那就应该考虑当作成员变量使用了，其次没有日志很难跟踪啊

**Comment by Andy957** [comment]
我要的是不同的弹窗，每次内容都不一样，很多的个那种

**Comment by razerdp** [comment]
用真机试试，然后最好有日志可以追踪。

**Comment by razerdp** [comment]
无后续反馈，关闭。
