### ISSUE TITLE
使用BasePopup实现列表页筛选菜单

### ISSUE THREAD

**Issue by hlla** [razerdp/BasePopup#246]
- 系统版本：9.0 8.0
 - 库版本：2.2.2.191101
 - 问题代码/截图：使用BasePopup实现类似下图这样的筛选菜单，通过setAlignBackground(true)可以实现popup上方不需要背景，下方需要背景。但切换的时候（比如说现在正显示着全城popup，点击智能排序, 希望直接显示智能排序的popup），但实际上点击的还是全城popup的背景，全城popup消失，需要再次点击智能排序，才可以显示智能排序popup.
可不可以做到不需要背景的地方不拦截外部响应事件，需要背景的地方拦截外部响应事件。
![Screenshot_20191129-161909](https://user-images.githubusercontent.com/7305059/69854438-1c8b4280-12c4-11ea-9c4b-a4cb891086a7.png)

**Comment by zzl313703419** [comment]
setOutSideTouchable(true);可以响应pop外部事件
