### ISSUE TITLE
底部虚拟按键会遮挡一部分布局

### ISSUE THREAD

**Issue by eternallyjie** [razerdp/BasePopup#248]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：Android 8.1.0，EMUI 8.2.0，华为畅享9
 - 库版本：2.2.1
 - 问题描述/重现步骤：如果我指定了setPopupGravity(Gravity.BOTTOM);手机底部有虚拟按键的情况下，底部虚拟按键会遮挡一部分布局。如下图
 - 问题代码/截图：
![Screenshot_20191213_135352](https://user-images.githubusercontent.com/30895476/70776698-c5539a80-1db8-11ea-93c0-51c078a6ad46.jpg)
![Screenshot_20191213_135422](https://user-images.githubusercontent.com/30895476/70776711-ca184e80-1db8-11ea-9c07-05f4904f3d9c.jpg)

 - 报错信息：

---

**Comment by razerdp** [comment]
关于底部导航栏这一块已经重构了，在下个版本会放出。

**Comment by eternallyjie** [comment]
> 关于底部导航栏这一块已经重构了，在下个版本会放出。

好的，我现在都是不设置Gravity，直接在popup的布局根部宽高都是match_parent来解决的。

**Comment by byc4426** [comment]
> 关于底部导航栏这一块已经重构了，在下个版本会放出。
BasePopup_Candy:2.2.2.200203     修复了吗
 android:layout_gravity="bottom"  时
showPopupWindow()   没弹出窗口，再新开一个Activity返回时才弹出窗口

**Comment by byc4426** [comment]
> 关于底部导航栏这一块已经重构了，在下个版本会放出。

BasePopup_Candy:2.2.2.200203 修复了吗
android:layout_gravity="bottom" 时
showPopupWindow() 没弹出窗口，再新开一个Activity返回时才弹出窗口

**Comment by razerdp** [comment]
BasePopup_Candy:2.2.2.200203
确实是存在问题的，该问题也修复了，不过我还没打包，因为同时发现另一个问题，一并修复后我再在这里回复哈~
