### ISSUE TITLE
关于setPopupWindowFullScreen后输入框的问题

### ISSUE THREAD

**Issue by ZeroYaw** [razerdp/BasePopup#249]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：android8.0 华为p9
 - 库版本：2.2.1
 - 问题描述/重现步骤：非全屏模式输入框的位置好像有点问题，同时设置这两个属性的时候是这种效果，不设置模式的话又会挡住部分EditText ：setAdjustInputMethod(true,WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN)
setPopupWindowFullScreen(false)
请问有什么好的解决办法吗

 - 问题代码/截图：http://172.93.47.15/issue.jpg

 - 报错信息：

---

**Comment by razerdp** [comment]
该问题已经很早就注意到了~在更新日志里也标明了cady的更新，具体文档里也有手册更新
https://www.kancloud.cn/razerdp/basepopup/1277045

请等待下一个版本的发布哦（最近比较忙，没法去迭代。。。）
