### ISSUE TITLE
Android7.0下showPopupWindow(v)不显示的问题

### ISSUE THREAD

**Issue by hshare** [razerdp/BasePopup#25]
java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity

PopupWindowProxy.class  87行

父布局：android.support.design.widget.CoordinatorLayout

**Comment by hshare** [comment]
PopupWindowProxy.class 86行修改如下：
Activity activity = scanForActivity(anchor.getContext());


private Activity scanForActivity(Context cont) {
        if (cont == null)
            return null;
        else if (cont instanceof Activity)
            return (Activity)cont;
        else if (cont instanceof ContextWrapper)
            return scanForActivity(((ContextWrapper)cont).getBaseContext());

        return null;
    }

**Comment by razerdp** [comment]
谢谢你的贡献呢~
不过方便的话能否提交一个pull request呢，如果不方便的话我这边帮你补上，然后注名吧
