### ISSUE TITLE
Popup 不显示 ,

### ISSUE THREAD

**Issue by open9527** [razerdp/BasePopup#250]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

当在启动页的主题中 配置这个属性 

然后在SplashActivity的onCreate 中直接显示Popup ,汇导致无法显示出来

---

**Comment by open9527** [comment]
android:background 这个属性(怎么提交github 不显示出来)

**Comment by razerdp** [comment]
当前onCreate显示只是单纯的 延迟显示，并不能保证一定显示，因为onCreate里act并不一定完成显示，所以我们无法保证。

**Comment by open9527** [comment]
> 当前onCreate显示只是单纯的 延迟显示，并不能保证一定显示，因为onCreate里act并不一定完成显示，所以我们无法保证。

但是,onResume 中也不会显示出来,不是没显示,我感觉是被android:background 覆盖了

**Comment by razerdp** [comment]
那你贴一下代码和图片吧

**Comment by open9527** [comment]
> 那你贴一下代码和图片吧
SplashActivity 👍 

public class SplashActivity extends AppCompatActivity {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);
    }

    @Override
    protected void onResume() {
        super.onResume();
        QuickPopupBuilder.with(this)
                .contentView(R.layout.dialog_bottom)
                .config(new QuickPopupConfig()
                        .gravity(Gravity.BOTTOM)
                )
                .show();

    }

activity_splash:
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">

    <data>

    </data>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@mipmap/splash">

    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>

dialog_bottom:

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="300dp"
    android:background="@color/color_80_000"
    android:layout_gravity="bottom">

    <TextView
        android:id="@+id/tv_share"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:textColor="@color/color_333"
        android:textSize="18sp"
        tools:text="分享" />

</androidx.constraintlayout.widget.ConstraintLayout>


stytle:

  android:theme="@style/SplashTheme"

<resources>

    
    <style name="AppTheme" parent="CommonAppTheme">
        
        <item name="colorPrimary">@color/color_fff</item>
        
        <item name="colorPrimaryDark">@color/color_fff</item>
        
        <item name="colorAccent">@color/color_ff6699</item>
        
        <item name="android:windowBackground">@color/color_fff</item>
        
        <item name="android:textColor">@color/color_333</item>
        
        <item name="android:textColorHint">@color/color_999</item>
        
        <item name="windowActionModeOverlay">true</item>
        <item name="android:windowContentOverlay">@null</item>
        
        <item name="actionModeBackground">@color/color_fff</item>
        
        <item name="android:textAllCaps">false</item>
        
        
        
        <item name="android:overScrollMode">never</item>

    </style>

    
    <style name="SplashTheme" parent="CommonAppTheme">
        <item name="android:windowFullscreen">true</item>
                <item name="android:background">@mipmap/splash</item>

        
        <item name="android:windowDisablePreview">false</item>
    </style>
</resources>

**Comment by maogedadada** [comment]
我也遇到了，oppo r9m 欢迎页无法显示view

**Comment by razerdp** [comment]
仍然无法重现，希望提供demo测试

**Comment by razerdp** [comment]
请尝试最新版本，如继续无反馈，本issue将会在5天后关闭。

**Comment by razerdp** [comment]
无后续反馈，关闭。
