### ISSUE TITLE
不支持AnimatorSet动画么？

### ISSUE THREAD

**Issue by pengjunhong** [razerdp/BasePopup#251]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
支持，文档有写，烦请去看一看。

**Comment by pengjunhong** [comment]
我已经看了至少4-5遍 可是还是没找到，哎

**Comment by pengjunhong** [comment]
文档是否就是wiki那份？

**Comment by razerdp** [comment]
readme下，有手册，跳转就是了。

**Comment by razerdp** [comment]
wiki也行，不过可能乱一点。

**Comment by pengjunhong** [comment]
那里面讲的 也只有Animation 和Animator这两个返回值的呀，demo也看了 没有AnimatorSet这个返回值不是

**Comment by pengjunhong** [comment]
动画这块不是很了解 有其他操作 恳请指点下

**Comment by razerdp** [comment]
animationset就是animation的子类…………

**Comment by pengjunhong** [comment]
明白了，谢谢
