### ISSUE TITLE
根布局设置match_paren 最底部的view会被导航栏遮挡

### ISSUE THREAD

**Issue by m511386374** [razerdp/BasePopup#252]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：6.0
 - 库版本：2.2.2
 - 问题描述/重现步骤：根布局设置match_paren 最底部的view会被导航栏遮挡
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/19544200/71553836-14ecc400-2a51-11ea-95e0-d3e41d5a9d6e.png)
![image](https://user-images.githubusercontent.com/19544200/71553840-1e762c00-2a51-11ea-89d4-0b21b7fa1a9e.png)

![image](https://user-images.githubusercontent.com/19544200/71553914-5d58b180-2a52-11ea-96ed-a8259efbfb1c.png)

 - 报错信息：

---

**Comment by razerdp** [comment]
2.2.2还没发布的哦。。。仍在重构中。
