### ISSUE TITLE
大佬求助，popup中能不能设置只有部分布局适应输入法，而不是整体布局。

### ISSUE THREAD

**Issue by yoyiyi** [razerdp/BasePopup#254]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：
1.popup底部有一个edittext，
2.打开popup时候，只需要这个edittext，在输入法顶部。关闭输入法，这个editext依旧落到底部。
3.现在弹出popup时候，是整个布局都晚上顶了。。
---

**Comment by razerdp** [comment]
支持，2.2.2开始支持

具体请看手册

demo也有

https://www.kancloud.cn/razerdp/basepopup/1277045

**Comment by yoyiyi** [comment]
`  setAdjustInputMode(R.id.rl_bottom, FLAG_KEYBOARD_ALIGN_TO_VIEW or FLAG_KEYBOARD_ANIMATE_ALIGN)`
大佬，设置了，貌似不起作用，还是整个布局都往上顶了，底部布局往上移动，他的整个父布局都往上移动了。

**Comment by yoyiyi** [comment]
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginTop="@dimen/dp70"
                android:background="@drawable/shape_white_left_right_corner_5_bg"
                android:orientation="vertical">
......
  <RelativeLayout
        android:id="@+id/rl_bottom"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:background="@color/cl_white"
        android:minHeight="@dimen/dp49">
      <EditText/>
      ......
  </RelativeLayout>
</RelativeLayout>
`
大概是这种布局，父布局距离顶部70dp，按照设置了，整个父布局都往上移了

**Comment by razerdp** [comment]
你的布局高度都是match_parent啊。。。我还真没试过match的情况，。

**Comment by yoyiyi** [comment]
把父布局改成高改成 wrap_content 也还是一样，整个布局往上顶

**Comment by razerdp** [comment]
额，，，这么好玩？
你的库版本是多少

**Comment by yoyiyi** [comment]
2.2.2.190916

**Comment by razerdp** [comment]
用最新的candy试试

**Comment by yoyiyi** [comment]
更新191101，还是老样子。暂时只能写两个popup，点击底部，弹出另外一个popup

**Comment by razerdp** [comment]
有demo重现吗

**Comment by razerdp** [comment]
无法重现。

**Comment by kulong51** [comment]
此问题最新版本 basePopup_candy = '2.2.3.20200304'
还是一样，把自己写的popupwindow 不会出现

**Comment by razerdp** [comment]
@kulong51 最好能提供下demo，因为我尝试过确实无法重现。

**Comment by kulong51** [comment]
好的，有空我写demo给你



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WeiChaoFeng <notifications@github.com&gt;
发送时间: 2020年5月7日 11:46
收件人: razerdp/BasePopup <BasePopup@noreply.github.com&gt;
抄送: kulong51 <547253857@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[razerdp/BasePopup] 大佬求助，popup中能不能设置只有部分布局适应输入法，而不是整体布局。 (#254)





 
@kulong51 最好能提供下demo，因为我尝试过确实无法重现。
