### ISSUE TITLE
怎么实现列表呀

### ISSUE THREAD

**Issue by jackerjin** [razerdp/BasePopup#256]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
自行实现。

**Comment by jackerjin** [comment]
> 自行实现。

 @Override
    public View onCreateContentView() {
        return createPopupById(R.layout.popup_option_input);
    }
不知道怎么初始化把recyclerView的值放进去

**Comment by razerdp** [comment]
你可以看看demo，这就是一个类，你在任何地方都可以设置数据，或者你自己暴露方法给外部都可以的，就跟你在activity里写recyclerview一样。。。
