### ISSUE TITLE
在给基类activity设置完字体大小scale之后， 弹出的pop出现问题 现象是弹出正常的pop，一闪而过，然后如下图所示

### ISSUE THREAD

**Issue by skyyanyujiangnan** [razerdp/BasePopup#258]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：9
 - 库版本：   implementation 'com.github.razerdp:BasePopup:2.1.9'
 - 问题描述/重现步骤：
在项目基类中重写：
   @Override
    public Resources getResources() {
        Resources res = super.getResources();
        Configuration config = res.getConfiguration();
        config.fontScale=2；//1 设置正常字体大小的倍数
        res.updateConfiguration(config, res.getDisplayMetrics());
        return res;

    }

 - 问题代码/截图：
 - 报错信息：
![image](https://user-images.githubusercontent.com/13703216/72231920-fbbf4800-35f8-11ea-9a1a-b0b43c6600af.png)

---

**Comment by razerdp** [comment]
更新到最新版本看看？

**Comment by razerdp** [comment]
没有后续反馈，关闭。
