### ISSUE TITLE
在小米9或者k20或小米mix2 上弹窗不显示，用的版本为AndroidX 2.2.1

### ISSUE THREAD

**Issue by jackerjin** [razerdp/BasePopup#259]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
...我自己的测试就就是k20

**Comment by jackerjin** [comment]
> 。。。我自己的测试机就是k20哦


    public TopMenuPopup(Context context, List<ProductModuleMenuBean.DataBean> dataBeans, String productId, String productType) {
        super(context);
        ButterKnife.bind(this, getContentView());
        this.mDatas = dataBeans;
        this.mContext = context;
        setPopupGravity(Gravity.BOTTOM);
        final LinearLayoutManager linearLayoutManager = new LinearLayoutManager(mContext,
                LinearLayoutManager.VERTICAL, false);
        mRecyclerView.addItemDecoration(new RecycleViewDivider(mContext, DividerItemDecoration.VERTICAL,
                0, mContext.getResources().getColor(R.color.background_manage)));
        mRecyclerView.setLayoutManager(linearLayoutManager);
        topMenuAdapter = new TopMenuAdapter(mContext);
        mRecyclerView.setAdapter(topMenuAdapter);
        topMenuAdapter.replaceData(dataBeans);
        topMenuAdapter.setOnItemClickListener((adapter, view, position) -> {
            switch (dataBeans.get(position).getName()) {
                case "返修":
                    toTask(dataBeans.get(position).getId(), productId, productType);
                    break;
                case "故障上报":
                    toTask(dataBeans.get(position).getId(), null, null);
                    break;
                case "添加设备":
                    sendMessage(dataBeans.get(position).getName());
                    break;
                case "设备更换":
                    sendMessage(dataBeans.get(position).getName());
                    break;
                case "关联子设备":
                    sendMessage(dataBeans.get(position).getName());
                    break;
                case "编辑":
                    sendMessage(dataBeans.get(position).getName());
                    break;
                case "取消关联":
                    sendMessage(dataBeans.get(position).getName());
                    break;
                case "历史记录":
                    sendMessage(dataBeans.get(position).getName());
                    break;
            }
        });
    }
调用：
 private void dropDialog() {
        new TopMenuPopup(this, productModuleDatas, id, "station").linkTo(ivRightIcon).showPopupWindow(ivRightIcon);
    }
，确实没有显示

**Comment by razerdp** [comment]
是在onCreate()里显示吗

**Comment by jackerjin** [comment]
> 是在onCreate()里显示吗

不是，在点击事件里

**Comment by razerdp** [comment]
emmm....要不做个demo工程，我更容易debug

**Comment by jackerjin** [comment]
> emmm....要不做个demo工程，我更容易debug

是这样，如果是写死的数据，能够显示，只有列表的不能显示

**Comment by jackerjin** [comment]
> emmm....要不做个demo工程，我更容易debug
是这样，应该是popupWindow和miui11正式版有冲突，我觉得哈，你之前k20能运行应该不是在最新的miui系统上，建议你在最新的系统上试试，点击弹窗会很快的显示一个弹窗然后消失，但透明度还是半透明的状态

**Comment by razerdp** [comment]
MIUI 11.0.3 稳定版

检查更新已经是最新版本了。

**Comment by jackerjin** [comment]
> MIUI 11.0.3 稳定版
> 
> 检查更新已经是最新版本了。

您在拿小米手机或者远程调试机测测吧，我真的解决不了这个问题，就是弹窗一闪而过，我看别人也有问这个问题的

**Comment by razerdp** [comment]
@jackerjin 请更新到最新版candy试试

**Comment by jackerjin** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WeiChaoFeng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 晚上7:31
收件人:&nbsp;"razerdp/BasePopup"<BasePopup@noreply.github.com&gt;;
抄送:&nbsp;"前晋"<956959794@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [razerdp/BasePopup] 在小米9或者k20或小米mix2 上弹窗不显示，用的版本为AndroidX 2.2.1 (#259)




@jackerjin 请更新到最新版candy试试

**Comment by razerdp** [comment]
无后续反馈，关闭。
