### ISSUE TITLE
适配Android 10，tryToHookWindowManager() 中有灰名单SDK

### ISSUE THREAD

**Issue by leanderli** [razerdp/BasePopup#260]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：Android 10
 - 库版本：最新
 - 问题描述/重现步骤：在Android 10 上使用BasePopupWindow
 - 问题代码/截图：
    Field fieldScroll = PopupWindow.class.getDeclaredField("mOnScrollChangedListener");
 - 报错信息：
Accessing hidden field Landroid/widget/PopupWindow;->mOnScrollChangedListener:Landroid/view/ViewTreeObserver$OnScrollChangedListener; (greylist-max-p, reflection, denied)
---

**Comment by razerdp** [comment]
该问题已经修复了，现在的代码里就有，但因为没重构完，暂时无法发布版本。

**Comment by leanderli** [comment]
希望尽快发布，另外组件很好用。 1838487641 邮箱：1838487641@qq.com 签名由 网易邮箱大师 定制 在2020年01月20日 09:30，WeiChaoFeng 写道： 该问题已经修复了，现在的代码里就有，但因为没重构完，暂时无法发布版本。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by razerdp** [comment]
可能没那么快，，这次会全方位重构。。。而我也就最近才有时间开始

**Comment by leanderli** [comment]
> 可能没那么快，，这次会全方位重构。。。而我也就最近才有时间开始

大概多久时间，春节期间会更新吗。

**Comment by razerdp** [comment]
春节放假诶。。。不想碰代码了噗，这两天我都在重构，看能否尽快，，如无意外我觉得可能2月份吧

**Comment by leanderli** [comment]
> 春节放假诶。。。不想碰代码了噗，这两天我都在重构，看能否尽快，，如无意外我觉得可能2月份吧

好吧

**Comment by razerdp** [comment]
请更新到最新candy验证

**Comment by leanderli** [comment]
好的
