### ISSUE TITLE
大佬发版吗 2.2.2 等的花儿都谢了

### ISSUE THREAD

**Issue by xchengDroid** [razerdp/BasePopup#261]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
candy昨晚已发，2.2.2仍在调试中，估计这两天发吧

**Comment by razerdp** [comment]
你可以用candy帮忙测试哦~收集到更多的bug信息有助于更好的调试，

**Comment by xchengDroid** [comment]
谢谢 大佬辛苦
