### ISSUE TITLE
错误: 无法访问LifecycleObserver 找不到androidx.lifecycle.LifecycleObserver的类文件

### ISSUE THREAD

**Issue by 18075523968** [razerdp/BasePopup#264]
- 系统版本：
 - 库版本：implementation 'com.github.razerdp:BasePopup:2.2.2.1'
                 implementation 'com.github.razerdp:BasePopup-compat-androidx:2.2.1'
 - 问题描述/重现步骤: 
                 按照文档引入组件,然后快说入门创建和展示,编写完代码 启动项目报错
 - 问题代码/截图：
 - 报错信息：
错误: 无法访问LifecycleObserver 找不到androidx.lifecycle.LifecycleObserver的类文件
---

**Comment by razerdp** [comment]
你的项目依赖了androidx了吗

**Comment by 18075523968** [comment]
谢谢 是没有升级anroidx
