### ISSUE TITLE
未来计划&意见记录小本本

### ISSUE THREAD

**Issue by razerdp** [razerdp/BasePopup#265]
BasePopup维护至今已趋向于稳定，后续开发除了一些抽象功能迭代外，基本不会有很大的改动。

考虑到BasePopup是一个抽象层的东西，具象化的实现需要用户自行定义，在快速开发的项目中可能需要个人去详细定制，然而如果对于常见的弹窗来说，其实是可以由库来提供而不需要重新造轮子的。

在[**问卷调查**](https://wj.qq.com/s2/5468287/c24f/)中，我们开展了BasePopup工具库的计划的调研，到目前为止约有78%的用户支持该计划。（虽然参与调查的人仅仅十多个~）

![image](https://user-images.githubusercontent.com/11629986/76279244-e8fb8380-62c8-11ea-82bd-ebcd1df27f3c.png)

同时也收集到一些关于工具库或者BasePopup的建议，本Issue开启的目的是记录下这些建议，我们将在后续安排到计划之中。

现在初步计划新的工具库暂时命名为：**BasePopup-Extension**，为了保证基础库的纯净，将会与基础库分开，工具库的内容主要包含各种日常的弹窗（如Loading、对话框、选择框），当然，这一切都是建立在BasePopup的基础上。

**【ps：日期选择、城市联动等不在考虑范围内，因为市面上有更多这种轮子，你可以轻易地把他们写到BasePopup中作为您的布局控件使用】**

如果您对【BasePopup-Extension】或者【BasePopup】有任何的建议或意见，欢迎在调查问卷中留言，或者在本issue中留言，本issue会持续更新作为一个记录。（个人比较建议在调查问卷中留言，除了有机会拿到红包外，我在后台看统计更加方便）

Best wish.

**Comment by razerdp** [comment]
一楼：作者留坑用作【BasePopup-Extension】计划记录

**Comment by razerdp** [comment]
二楼：作者留坑用作【BasePopup】意见记录

**Comment by GMF018** [comment]
Extension新加功能点需求建议
(1)添加带有箭头的Pop.如可以通过锚点view设置箭头大小，位置，弹框圆角。
(2)下拉列表选择。

**Comment by Yetland** [comment]
对于显示的位置而言，个人感觉可以学习ConstraintLayout中的对齐方式，比如top_toBottomOf/top_toTopOf/start_toStartOf/start_toEndOf。这样的形式，比起边对齐+位置会更加明了

**Comment by razerdp** [comment]
@Yetland 这个需求很早之前在群里已经讨论过，并且也尝试过开发，但是遇到两个问题：
1 - 如果按照这种api，我会考虑用ConstraintLayout来用作basepopup的decorproxy，但由于最外层必须是ViewGroup，因此需要多嵌套一层，同时ConstraintLayout并非内置在AndroidX包内，需要额外依赖，不符合BasePopup不依赖基础组件外的任何组件设定。

2 - 如果改为这种调用，将会出现 new Popup().setLeftToLeft().setTopToTop().setxxxToxxx()。。。会显得又长又臭。

综上，最后不考虑这种方式。

**Comment by pfyuan** [comment]
![image](https://user-images.githubusercontent.com/44466203/99927641-fdad7800-2d80-11eb-8692-dc1aa8593b81.png)
部分android10的系统点击显示pupwindow崩溃

**Comment by razerdp** [comment]
@pfyuan 请先更新到最新版，并开issue提交问题

**Comment by pfyuan** [comment]
@razerdp  更新版本了 ，这个问题还能出现吗

**Comment by razerdp** [comment]
> @razerdp 更新版本了 ，这个问题还能出现吗

应该不会，因为不再hack使用黑灰名单了。

**Comment by jerry9433** [comment]
可以添加下滑关闭弹窗的功能吗

**Comment by razerdp** [comment]
> 可以添加下滑关闭弹窗的功能吗

您可以自己实现，框架提供的话自由度没那么高，比如有的人喜欢按照滑动百分比，有的人喜欢按照滑动距离，还有的人喜欢按照滑动速度等等。我们提供的是最顶层的抽象，而不是最具体的实现。

**Comment by qiushui95** [comment]
扩展库是放弃了么？我看半年没有反应了

**Comment by razerdp** [comment]
> 扩展库是放弃了么？我看半年没有反应了

没有呢，只不过最近有点忙，代码一直没提交，同时也在反复推倒重来，所以进度比较慢

**Comment by qiushui95** [comment]
> > 扩展库是放弃了么？我看半年没有反应了
> 
> 没有呢，只不过最近有点忙，代码一直没提交，同时也在反复推倒重来，所以进度比较慢

好的，期待中。

**Comment by Yetland** [comment]
我的意思就是这个，对外部是使用ConstraintLayout那种比较明了的对齐方式，但是内部还是你原来的那套逻辑。只是增加了一套api，使用更方便。

**Comment by razerdp** [comment]
> 我的意思就是这个，对外部是使用ConstraintLayout那种比较明了的对齐方式，但是内部还是你原来的那套逻辑。只是增加了一套api，使用更方便。

嗯嗯，如果我有时间（不懒）的话就去弄一下

**Comment by razerdp** [comment]
> 我的意思就是这个，对外部是使用ConstraintLayout那种比较明了的对齐方式，但是内部还是你原来的那套逻辑。只是增加了一套api，使用更方便。

这存在个问题，就是多个view的时候，就不好弄了，例如topToBottom(view1)，bottomToTop(view2)，这种。因为basepopup目前只是针对单view锚定，目前也没见到什么弹窗支持多view锚定。

**Comment by qiushui95** [comment]
> > 我的意思就是这个，对外部是使用ConstraintLayout那种比较明了的对齐方式，但是内部还是你原来的那套逻辑。只是增加了一套api，使用更方便。
> 
> 这存在个问题，就是多个view的时候，就不好弄了，例如topToBottom(view1)，bottomToTop(view2)，这种。因为basepopup目前只是针对单view锚定，目前也没见到什么弹窗支持多view锚定。

最后拿多个锚点生成左上角的x,y。比如，startToStart(view1),endToStart(view2),那么弹窗的中心点x左边就是(view1.x+view2.x)/2;startToStart(view1),endToEnd(view2),那么弹窗的中心点x左边就是(view1.x+view2.x+view2.width)/2;

**Comment by razerdp** [comment]
> > > 我的意思就是这个，对外部是使用ConstraintLayout那种比较明了的对齐方式，但是内部还是你原来的那套逻辑。只是增加了一套api，使用更方便。
> > 
> > 
> > 这存在个问题，就是多个view的时候，就不好弄了，例如topToBottom(view1)，bottomToTop(view2)，这种。因为basepopup目前只是针对单view锚定，目前也没见到什么弹窗支持多view锚定。
> 
> 最后拿多个锚点生成左上角的x,y。比如，startToStart(view1),endToStart(view2),那么弹窗的中心点x左边就是(view1.x+view2.x)/2;startToStart(view1),endToEnd(view2),那么弹窗的中心点x左边就是(view1.x+view2.x+view2.width)/2;
> 就是计算稍显麻烦

这对popup的大小都将会有限制。而且真的挺复杂的

**Comment by qiushui95** [comment]
> > > > 我的意思就是这个，对外部是使用ConstraintLayout那种比较明了的对齐方式，但是内部还是你原来的那套逻辑。只是增加了一套api，使用更方便。
> > > 
> > > 
> > > 这存在个问题，就是多个view的时候，就不好弄了，例如topToBottom(view1)，bottomToTop(view2)，这种。因为basepopup目前只是针对单view锚定，目前也没见到什么弹窗支持多view锚定。
> > 
> > 
> > 最后拿多个锚点生成左上角的x,y。比如，startToStart(view1),endToStart(view2),那么弹窗的中心点x左边就是(view1.x+view2.x)/2;startToStart(view1),endToEnd(view2),那么弹窗的中心点x左边就是(view1.x+view2.x+view2.width)/2;
> > 就是计算稍显麻烦
> 
> 这对popup的大小都将会有限制。而且真的挺复杂的

复杂就不做。自己计算比你计算工作了少多了。还是抓紧把扩展库做了（期待）。

**Comment by tianchenxingzi** [comment]
可以增加弹窗的管理类吗？比如说可以判断现在有哪几个弹窗在显示，可以拿到具体某个弹窗的对象这种

**Comment by razerdp** [comment]
> 可以增加弹窗的管理类吗？比如说可以判断现在有哪几个弹窗在显示，可以拿到具体某个弹窗的对象这种

这个应该交由您自己实现，因为管理器这东西很多人都有不同的需求。

目前popupunsafe提供了一些方法，允许拿到目前所有在显示的popup，具体请看看相关代码

**Comment by tianchenxingzi** [comment]
> > 可以增加弹窗的管理类吗？比如说可以判断现在有哪几个弹窗在显示，可以拿到具体某个弹窗的对象这种
> 
> 这个应该交由您自己实现，因为管理器这东西很多人都有不同的需求。
> 
> 目前popupunsafe提供了一些方法，允许拿到目前所有在显示的popup，具体请看看相关代码

我看有关闭所有弹窗的方法，但是某些情况掉这个方法会崩溃。日志如下



java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
    at java.util.LinkedList$ListItr.next(LinkedList.java:888)
    at razerdp.basepopup.BasePopupUnsafe.dismissAllPopup(BasePopupUnsafe.java:38)

**Comment by Yetland** [comment]
> > 我的意思就是这个，对外部是使用ConstraintLayout那种比较明了的对齐方式，但是内部还是你原来的那套逻辑。只是增加了一套api，使用更方便。
> 
> 这存在个问题，就是多个view的时候，就不好弄了，例如topToBottom(view1)，bottomToTop(view2)，这种。因为basepopup目前只是针对单view锚定，目前也没见到什么弹窗支持多view锚定。

原理不都是一样的吗？即使是多个View，最终需要的只是坐标(x,y)。最后的高度和宽度计算用以前的那套就可以了吧？

**Comment by razerdp** [comment]
> > > 我的意思就是这个，对外部是使用ConstraintLayout那种比较明了的对齐方式，但是内部还是你原来的那套逻辑。只是增加了一套api，使用更方便。
> > 
> > 
> > 这存在个问题，就是多个view的时候，就不好弄了，例如topToBottom(view1)，bottomToTop(view2)，这种。因为basepopup目前只是针对单view锚定，目前也没见到什么弹窗支持多view锚定。
> 
> 原理不都是一样的吗？即使是多个View，最终需要的只是坐标(x,y)。最后的高度和宽度计算用以前的那套就可以了吧？

这个问题我发过群里讨论过了，后面一致认为没必要弄~绝大部分情况下用不上的说

**Comment by razerdp** [comment]
> > > 可以增加弹窗的管理类吗？比如说可以判断现在有哪几个弹窗在显示，可以拿到具体某个弹窗的对象这种
> > 
> > 
> > 这个应该交由您自己实现，因为管理器这东西很多人都有不同的需求。
> > 目前popupunsafe提供了一些方法，允许拿到目前所有在显示的popup，具体请看看相关代码
> 
> 我看有关闭所有弹窗的方法，但是某些情况掉这个方法会崩溃。日志如下
> 
> java.util.ConcurrentModificationException
> at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
> at java.util.LinkedList$ListItr.next(LinkedList.java:888)
> at razerdp.basepopup.BasePopupUnsafe.dismissAllPopup(BasePopupUnsafe.java:38)

请提个新issue

**Comment by KnightGuard** [comment]
有没有考虑过靠下弹窗的虚拟键适配呢

**Comment by razerdp** [comment]
> 有没有考虑过靠下弹窗的虚拟键适配呢

什么意思

**Comment by githeer** [comment]
popupwindow 的 setFocusable（false）  导致isshowing不起作用，然后点击会 消失再显示，这个有解决思路不，望指教

**Comment by guodonghuang** [comment]
输入法问题，在横屏的时候回失效，布局顶不上去，麻烦修复一下。静待佳音。

**Comment by razerdp** [comment]
> 输入法问题，在横屏的时候回失效，布局顶不上去，麻烦修复一下。静待佳音。

请看手册-输入法

**Comment by guodonghuang** [comment]
> > 输入法问题，在横屏的时候回失效，布局顶不上去，麻烦修复一下。静待佳音。
> 
> 请看手册-输入法

copy it！3q

**Comment by lv823063712** [comment]
作者有计划开发Jetpack Compose UI 的BasePop么,纯好奇,因为现在在用ComposeUI开发

**Comment by razerdp** [comment]
> 作者有计划开发Jetpack Compose UI 的BasePop么,纯好奇,因为现在在用ComposeUI开发

木有该打算~
