### ISSUE TITLE
背景设置为0，显示popupwindow，状态栏的图标全变白

### ISSUE THREAD

**Issue by Moster1h** [razerdp/BasePopup#266]
- 系统版本：Android8.1.0
 - 库版本：2.2.2.2
 - 问题描述/重现步骤：
第一个问题：背景设置为0，显示popupwindow，状态栏的图标全变白
第二个问题：设置setPopupWindowFullScreen为False时，弹出的popupwindow会显示非常大的间距
 - [问题代码/截图]：

> 正常状态

![S00310-16511811](https://user-images.githubusercontent.com/55750427/76295429-8d90bc00-62ef-11ea-9e38-76403fa27bbc.jpg)

> 第一个问题

![S00310-16355362](https://user-images.githubusercontent.com/55750427/76294675-42c27480-62ee-11ea-86b5-089cc8fa1f60.jpg)

> 第二个问题

![S00310-16414037](https://user-images.githubusercontent.com/55750427/76294683-448c3800-62ee-11ea-92a5-996b3315bce4.jpg)

 - 报错信息：无报错

---

**Comment by razerdp** [comment]
对于问题1，我们是不会对状态栏修改的，请问您状态栏图标为黑色是做过什么操作吗（比如日间/夜间切换）？

第二个问题，setPopupWindowFullScreen()实际上指的是是否覆盖状态栏，如果为false的情况下，意味着popup不覆盖状态栏，其测量和布局会下移一个状态栏的高度。（这个方法已经在最新的candy中修改了，称为`setOverlayStatusbar`，并且修复了下移高度过多的问题）

**Comment by razerdp** [comment]
补充：问题1在模拟器上的测试结果：

![image](https://user-images.githubusercontent.com/11629986/76296296-f298e180-62f0-11ea-912e-125fbe5f66a3.png)

**Comment by razerdp** [comment]
补充2：问题二在Candy最新版的测试结果（ver. 2.2.3.20200304）：
![image](https://user-images.githubusercontent.com/11629986/76296556-41df1200-62f1-11ea-8ea6-7196fbbd7c3d.png)

**Comment by razerdp** [comment]
补充3：问题2在Release的测试结果（ver.2.2.2.2）：

该bug已确认并修复，后续放出。

![image](https://user-images.githubusercontent.com/11629986/76296654-7521a100-62f1-11ea-9aa2-a92b7bb3d92e.png)

**Comment by Moster1h** [comment]
主要想解决第一个问题
状态栏图标颜色是用工具类修改的

这是显示WIndow的代码
```
        windowDownloadOperation
                .setBackground(0)
                .setPopupGravity(Gravity.LEFT|Gravity.BOTTOM)
                .setOffsetX(UIManager.Instance().dip2px(16))
                .setAutoLocatePopup(true)
                .showPopupWindow(view);
```
2.2.2.2版会出现状态栏的图标颜色改变的bug

**Comment by Moster1h** [comment]
这是Style
![Snipaste_2020-03-10_17-15-00](https://user-images.githubusercontent.com/55750427/76297397-b8c8da80-62f2-11ea-995f-20da96f17c02.png)

**Comment by razerdp** [comment]
第一个问题我本地无法复现哇。。。详情看上面的截图，模拟器版本跟你一样8.1.0

能否提供一下你设置黑色图标的工具类地址或代码。

上面我的测试代码如下：

```java
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            View decorView = getWindow().getDecorView();
            int vis = decorView.getSystemUiVisibility();
            vis |= View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;
            decorView.setSystemUiVisibility(vis);
        }
```

**Comment by Moster1h** [comment]
这是修改状态栏图标颜色的方法对Android8.0以下版本无效
```
    /**
     * Set the status bar's light mode.
     *
     * @param window      The window.
     * @param isLightMode True to set status bar light mode, false otherwise.
     */
    public static void setStatusBarLightMode(@NonNull final Window window,
                                             final boolean isLightMode) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            View decorView = window.getDecorView();
            int vis = decorView.getSystemUiVisibility();
            if (isLightMode) {
                vis |= View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;
            } else {
                vis &= ~View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;
            }
            decorView.setSystemUiVisibility(vis);
        }
    }
```

**Comment by razerdp** [comment]
![image](https://user-images.githubusercontent.com/11629986/76297644-24ab4300-62f3-11ea-931c-6a8035fc6fe5.png)

![image](https://user-images.githubusercontent.com/11629986/76297655-2a088d80-62f3-11ea-910a-2b4680d60cfa.png)


现在代码、主题一样了。。。仍然无法复现，我这边继续保持黑色的图标。

会不会跟系统相关，你的手机品牌和系统提供一下？

**Comment by Moster1h** [comment]
魅族16th

**Comment by Moster1h** [comment]
有window显示完和关闭的监听吗

**Comment by razerdp** [comment]
关闭有，显示的回调暂时不开放。

**Comment by Moster1h** [comment]
的确是手机品牌问题，我用模拟器测试了一下，但是2.2.1版本没有这个bug

**Comment by razerdp** [comment]
刚拿了三台手机包括云真机测试都无法复现问题一，另外我手上也没有魅族，，所以对于问题一暂时来说我也没有办法去debug....

2.2.1和2.2.2对于window的flag改动是没有任何变化的

**Comment by Moster1h** [comment]
你把changStatusIconColler改为下面的，重新测试一下。
```
public void changStatusIconColler() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            View decorView = getWindow().getDecorView();
            int vis = decorView.getSystemUiVisibility();
            vis &= ~View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;
            decorView.setSystemUiVisibility(vis);
        }
    }
```

**Comment by razerdp** [comment]
> 你把changStatusIconColler改为下面的，重新测试一下。
> 
> ```
> public void changStatusIconColler() {
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
>             View decorView = getWindow().getDecorView();
>             int vis = decorView.getSystemUiVisibility();
>             vis &= ~View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;
>             decorView.setSystemUiVisibility(vis);
>         }
>     }
> ```

这样改动的话图标本来就是白的

**Comment by Moster1h** [comment]
你再弹窗会变成黑的

**Comment by razerdp** [comment]
木有。。。。

**Comment by razerdp** [comment]
![sdfsd](https://user-images.githubusercontent.com/11629986/76299691-7d300f80-62f6-11ea-837c-6770475263ae.gif)

**Comment by Moster1h** [comment]
我给你录个屏

**Comment by razerdp** [comment]
稍等，你加一下我qq:164701463，我拉你进群康康吧

**Comment by Moster1h** [comment]
你直接说群吧！加你QQ要答案！

**Comment by razerdp** [comment]
对喔。。那加我微信razerdp

我们的群是微信群来的
