### ISSUE TITLE
isShowing()' on a null object reference

### ISSUE THREAD

**Issue by TxcA** [razerdp/BasePopup#267]
- 系统版本：Android 10
 - 库版本：2.2.2.2
 - 问题描述/重现步骤：
**Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean razerdp.basepopup.PopupWindowProxy.isShowing()' on a null object reference**

```java
        if (loadingPopup != null && loadingPopup.isShowing()) {
            loadingPopup.dismiss();
        }
```

**Fix:**
```java
    /**
     * PopupWindow是否处于展示状态
     */
    public boolean isShowing() {
          return mPopupWindow == null ? false : mPopupWindow.isShowing();
    }
```

**Comment by razerdp** [comment]
一般来说，popup的回收只有activity已经destroy之后才会发生，或者是lazypopup中，请问您是否符合上述两种情况之一？

不过这里确实会存在这个问题，感谢指出~

**Comment by razerdp** [comment]
@TxcA fixed in 【Candy 2.2.3.20200311】
