### ISSUE TITLE
有类似activity的onResume()生命周期的方法么?

### ISSUE THREAD

**Issue by open9527** [razerdp/BasePopup#268]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：2.2.2.2
 - 问题描述/重现步骤：
 popupwindows中有编辑框,然后键盘弹起, 点击popupwindows中的按钮会有跳到A界面,
这个时候键盘会消失,但是A界面关闭后我需要popupwindows的键盘弹起
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
2.2.2开始完全迁移到AndroidX了，你可以使用Lifecycle的特性去实现，比如

![TIM截图20200311164138](https://user-images.githubusercontent.com/11629986/76398078-33f3c480-63b7-11ea-9b5c-20324855f40a.png)
