### ISSUE TITLE
pop的Y的offset有问题啊

### ISSUE THREAD

**Issue by zktzktzkt** [razerdp/BasePopup#27]
描述功能：让pop显示在某个view的上方
         SlideFromBottomPopup slideFromBottomPopup = new SlideFromBottomPopup(PopUpBottomSheetActivity.this);
                slideFromBottomPopup.setOffsetY(DisplayUtil.dip2px(80, PopUpBottomSheetActivity.this));
                slideFromBottomPopup.showPopupWindow(ll_bottom);、

80dp的时候就会显示在ll_bottom下面，90dp的时候就会显示在ll_bottom上面，反正很明显，offset计算的有问题

**Comment by razerdp** [comment]
您好，确实是有点问题，下一个版本我会修复

**Comment by razerdp** [comment]
@zktzktzkt 您好，更新到1.8.0试试
