### ISSUE TITLE
在dialogfragment中mHelper.prepare(v, positionMode) 会造成泄漏

### ISSUE THREAD

**Issue by hyl87** [razerdp/BasePopup#270]
- 系统版本：2.2.2.2
 - 报错信息：
   泄漏原因是 innershowinfo 持有了anchorview,anchorview 是fragment view

**Comment by razerdp** [comment]
确实会持有view，但是在activity finish之后会统一释放。

**Comment by razerdp** [comment]
详情请看BasePopupHelper#clear()
