### ISSUE TITLE
优化！！ popup消失后不会自动隐藏输入法

### ISSUE THREAD

**Issue by SmallWinter** [razerdp/BasePopup#271]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：10.0.
 - 库版本：com.github.razerdp:BasePopup:2.2.2.2
 - 问题描述/重现步骤：setAutoShowInputMethod正常，主要是当poup消失时不会自动隐藏输入法了，以前的版本一直正常，属于优化范畴，请大佬考虑完善。大佬辛苦！
 - 问题代码/截图：无
 - 报错信息：无

---

**Comment by razerdp** [comment]
我的红米k20，android 10，无法重现。

请贴上手机系统、牌子，另外下载本工程demo，常见例子->输入法适配 看看是否重现。

**Comment by SmallWinter** [comment]
手机型号（真机）：华为荣耀10（COL-AL10） Android版本：9.0 （EMUI:9.1.0）
另外，还有个模拟机 Android 10.0 , Pixel C API 29， 也是同样情况。
大佬辛苦！！

**Comment by razerdp** [comment]
模拟器仍然无法重现。

![123123](https://user-images.githubusercontent.com/11629986/76723381-05dcfe80-6782-11ea-8c3c-03b1c00d703c.gif)

**Comment by SmallWinter** [comment]
大佬是不是用的Candy版本，如果是这样，那我等新的稳定版发布再更新。

**Comment by razerdp** [comment]
华为荣耀10，android 9，云真机仍然无法重现。
![12321321](https://user-images.githubusercontent.com/11629986/76723626-e72b3780-6782-11ea-916f-b92ed7bb7306.gif)

**Comment by razerdp** [comment]
是的，最新版本。（candy）

**Comment by SmallWinter** [comment]
那不用试了，我用的稳定版，期待新的稳定版发布，大佬辛苦！

**Comment by razerdp** [comment]
你用candy测试一下吧

**Comment by SmallWinter** [comment]
👌好滴

**Comment by SmallWinter** [comment]
大佬，微信能通过下不，我发视频给你看

**Comment by SmallWinter** [comment]
刚升级到Candy版本了，最新的，还是一样的

**Comment by razerdp** [comment]
经过跟进讨论，发现可能是系统关闭keyboard的问题，也许是某些系统的原因，可以采取自行关闭输入法的方式来解决。
