### ISSUE TITLE
尝试使用update和linkTo都失效！！！

### ISSUE THREAD

**Issue by MrHuangZW** [razerdp/BasePopup#272]
- 系统版本：7.0
 - 库版本：2.1.9
 - 问题描述/重现步骤：顶部有个可手动设置可视化的View，然后这个可视化的view下面有一个View，然后我弹窗依附在下面这个view上面，然后弹窗显示的时候，我设置顶部view可视，然后下面的view会被顶下，但弹窗不会跟随向下移动
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
请更新到最新版本再试试。

目前版本的demo测试结果如下：【无法复现】

![ezgif-2-eca6c01d0c73](https://user-images.githubusercontent.com/11629986/77048122-e8699800-6a00-11ea-9bad-1394b0866745.gif)

**Comment by razerdp** [comment]
另：补充相同测试环境：

模拟器（Android 7.0）

![kkk](https://user-images.githubusercontent.com/11629986/77048565-a3923100-6a01-11ea-8018-19ba93f32e29.gif)

**Comment by MrHuangZW** [comment]
感谢大佬，我更新到最新包尝试下

**Comment by MrHuangZW** [comment]
最新版本没有出现问题，再次感谢大佬
