### ISSUE TITLE
不能在Dialog中使用

### ISSUE THREAD

**Issue by jay-lan** [razerdp/BasePopup#273]
作者大大您好，我在对话框中使用了这个popup，但是popupWindow显示在了dialog后面，您应该是将popupWindow添加在activity中的decorView上的吧，不知道能不能适配一下对话框呢

**Comment by razerdp** [comment]
请问你的版本是多少呢

如果是2.2.2之前，需要添加组件才能适配
2.2.2版本开始new的时候把dialog传入即可

**Comment by jay-lan** [comment]
我刚好用的2.2.1版本，换成最新版后已经解决了，非常感谢
