### ISSUE TITLE
 createPopupById(R.layout.drawer_sell_analysis);空指针

### ISSUE THREAD

**Issue by Founder005** [razerdp/BasePopup#274]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：2.2.2
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---使用createPopupById获取view的时候报null，但是R.layout.drawer_sell_analysis这个布局是存在的，不知道为啥找不到，有些没有问题有些有就找不到，但是布局我看都没问题，而且这个布局是从另一个项目直接复制的，另一个项目也用的basepop就没问题

**Comment by razerdp** [comment]
贴一下错误报告，试试clean大法。。。

**Comment by Founder005** [comment]
`java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.appcompat.widget.AppCompatTextView com.drumbeat.terminal.res.widget.DrumOptionView.getTvStart()' on a null object reference`
我clean，rebuild，重启大法都用过了

**Comment by Founder005** [comment]
`   optionDate = findViewById(R.id.option_date);` 在构造方法里findviewbyid，debug的时候发现optionDate 指向的是null，然后就在createPopupById也打了断点，发现是这个方法返回的是null，很奇怪。这个DrumOptionView optionDate 使我们自定义的view，应该没有问题，因为别的popwin也用了，没问题，就是部分找不到，也不知道为啥，debug也能看到createPopupById(R.layout.drawer_sell_analysis)这个布局指向的地址，就是返null

**Comment by razerdp** [comment]
你可以尝试不用popup，随便找个地方inflate试试，看看会不会是空的
然后查看下R文件导入是否正确，会不会存在两个布局xml，又或者ide抽风了等等。。。。

**Comment by razerdp** [comment]
这个问题大概率跟basepopup无关。。。因为create里面其实就是一个简单的inflate而已

**Comment by Founder005** [comment]
不啊好意思，找到了，还是我这的布局问题，另一个自定义view的名称变了，我没改，这也会导致createPopupById返回null。多谢坐着提出的方法，我在actvity里inflate了下，然后debug发现报的是布局108行的错误才发现最后一个控件的名称没有改。是我太粗心了

**Comment by razerdp** [comment]
下次遇到类似问题可以同样办法排除哦~
