### ISSUE TITLE
可能是内存泄露

### ISSUE THREAD

**Issue by qiushui95** [razerdp/BasePopup#275]
- 系统版本：
 - 库版本：2.2.2.2
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---
项目中发现内存泄露，查看内存信息发现是BasePopup产生的。
具体情况如下，我继承自BaseLazyPopupWindow(Fragment),fragment会作为ownerAnchorParent被保存起来，最后也没有释放。但是会绑定宿主activity的lifecycle(我感觉应该绑定fragment的lifecycle),这样在一个页面一个Activity的情况下不会出现问题，但是我的app是单activity 多fragment 的，这样就会出现泄露。不知道我分析的对不对。感谢开源

**Comment by qiushui95** [comment]
经测试 使用BaseLazyPopupWindow(Context)方式不会出现问题

**Comment by razerdp** [comment]
@qiushui95 感谢提出，确实可能存在这种问题，。。。。这是我这边的锅-V- 

不过经你这么一说，忽然觉得对于依附dialog的popup而言，理论上dialog销毁了的话popup也要销毁，然而dialog没有lifecycle，这种情况就没法处理了。。。（只能拿到它的activity作为lifecycle监听），最终又会走到你这个问题上（activity不关闭）

**Comment by qiushui95** [comment]
@razerdp 能否直接传入lifecycle，因为fragment有两个lifecycle，一个是它本身的lifecycle，一个是viewLifecycleOwner.lifecycle

**Comment by qiushui95** [comment]
如果没有传入，再去查找。

**Comment by razerdp** [comment]
emmm，我们以自身lifecycle为准，因为lifecycle在这里的用途就是为了在destroy中可以置空防止仍然引用着导致的泄漏。

该修复已经完成，稍后提交到dev分支~

感谢提出意见-V-

**Comment by razerdp** [comment]
刚刚测试的时候发现一个问题，在于DialogFragment，当DialogFragment dismiss后，fragment被remove掉，触发了lifecycle的destroy。

这里会导致一个问题，如果这个popup想复用，但是由于上面的情况已经触发destroy进行置空，最终导致了这个popup已经是个不能用的示例，也就无法复用了。。。。

**Comment by razerdp** [comment]
candy:【2.2.3.20200404】
优化decorView寻找方式，释放引用优化
添加LifeCycle绑定方法(bindLifecycleOwner())
添加Api展示

添加了bindLifecycleOwner方法，允许用户切换lifecycleowner~

**Comment by qiushui95** [comment]
-V-
