### ISSUE TITLE
在华为9.0的机型上弹窗内容会被底部导航栏遮住

### ISSUE THREAD

**Issue by 211885646** [razerdp/BasePopup#276]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：Android 9.0
 - 库版本：2.2.2
 - 问题描述/重现步骤：在华为9.0的机型 [带底部导航栏的,弹窗会被导航栏挡住或者挡住导航栏,但是作者的demo中又可以在导航栏上显示出来,demo我都快翻烂了,而且捐赠了也找不到作者群的联系方式,实属无奈,来此请求帮助,给个群的联系方式也好  哭哭哭~~~
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
支付宝我回复了的说…你加我微信razerdp吧
