### ISSUE TITLE
软键盘无法顶起布局

### ISSUE THREAD

**Issue by fuyifang** [razerdp/BasePopup#277]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
8.1
 - 库版本：
 - 问题描述/重现步骤：
试过了setAdjustInputMode的所有方法都不行
 - 问题代码/截图：
<img width="361" alt="issuse1" src="https://user-images.githubusercontent.com/11673500/78858952-706f1a80-7a60-11ea-99d1-f3545654098b.png">
<img width="372" alt="issues2" src="https://user-images.githubusercontent.com/11673500/78858955-72d17480-7a60-11ea-96cd-4715b718beaf.png">

 - 报错信息：
软键盘无法顶起布局
---

**Comment by fuyifang** [comment]
PurchaseHammerDialog purchaseHammerDialog = new PurchaseHammerDialog(SmashEggActivity.this);
                            purchaseHammerDialog.setHammerNum(eggCoin);
                            purchaseHammerDialog.setAdjustInputMode( BasePopupWindow.FLAG_KEYBOARD_IGNORE_OVER);
                            purchaseHammerDialog.setOutSideTouchable(true);
                            purchaseHammerDialog.setPopupGravity(Gravity.BOTTOM);
                            purchaseHammerDialog.setBackground(0);
                            purchaseHammerDialog.showPopupWindow();

**Comment by razerdp** [comment]
https://www.yuque.com/razerdp/basepopup/hxd29e#b70a7b8f

请看文档。

**Comment by fuyifang** [comment]
> https://www.yuque.com/razerdp/basepopup/hxd29e#b70a7b8f
> 
> 请看文档。

设置过了 还是没法顶起。。

      PurchaseHammerDialog purchaseHammerDialog = new PurchaseHammerDialog(SmashEggActivity.this);
                            purchaseHammerDialog.setHammerNum(eggCoin);

                            purchaseHammerDialog.setAdjustInputMode(R.id.edt_number,BasePopupWindow.FLAG_KEYBOARD_ALIGN_TO_ROOT | BasePopupWindow.FLAG_KEYBOARD_ANIMATE_ALIGN);
                            purchaseHammerDialog.setAutoShowInputMethod(true);
                            purchaseHammerDialog.setOutSideTouchable(true);
                            purchaseHammerDialog.setPopupGravity(Gravity.BOTTOM);
                            purchaseHammerDialog.setBackground(0);

                            purchaseHammerDialog.showPopupWindow();

**Comment by razerdp** [comment]
你的activity的manifest配置是怎样的

**Comment by fuyifang** [comment]
> 你的activity的manifest配置是怎样的

默认的，我的activity样式是dialog的 有影响吗？

**Comment by razerdp** [comment]
主要是看windowSoftInputMode

**Comment by fuyifang** [comment]
> 主要是看windowSoftInputMode

我设置过了adjustPan 和adjustResize  都不行

**Comment by razerdp** [comment]
那你可以提供一个demo供我测试吗，或者进入BasePopupHelper#GlobalLayoutListener，在onGlobalLayout()中断点调试，看看有没有走进去。

**Comment by fuyifang** [comment]
> GlobalLayoutListener

有走进去  我写demo放github吧

**Comment by razerdp** [comment]
嗯嗯，因为有的情况我本地测试的时候是无法覆盖的，所以针对一些特殊的情况需要麻烦你写下demo了~

写好后在这里通知我就行-V-

**Comment by fuyifang** [comment]
> 嗯嗯，因为有的情况我本地测试的时候是无法覆盖的，所以针对一些特殊的情况需要麻烦你写下demo了~
> 
> 写好后在这里通知我就行-V-

https://github.com/fuyifang/BasePopDemo

**Comment by razerdp** [comment]
该问题是activity的decorView没有回调到globallistener的原因，问题在于dialog样式的activity。其window大小与decorview一致，键盘弹出的时候不会影响到整体宽高，因此无法监听。

**Comment by razerdp** [comment]
算是个bug吧，我迟点看看怎么弄

**Comment by fuyifang** [comment]
> 算是个bug吧，我迟点看看怎么弄

好的 thx

**Comment by razerdp** [comment]
经过研究。。。以目前的api来说，暂时无解。。。

**Comment by Yetland** [comment]
> 经过研究。。。以目前的api来说，暂时无解。。。

我现在也出现了edittext不会被顶起的情况，需要这么修改可以暂时避免出现该问题？

**Comment by razerdp** [comment]
@Yetland 

你的是什么情况，也是在dialog下弹出？以及检查下manifest对应activity的softinputmode

**Comment by br3ant** [comment]
横屏的pad 也出现同样问题，各种api都设置了也无效

**Comment by razerdp** [comment]
@br3ant https://www.yuque.com/razerdp/basepopup/hxd29e#234fb92b

横屏默认不适配的。请看文档。

**Comment by hunter524** [comment]
Activity 设置 windowSoftInputMode 属性为 adjustResize 会导致window 变小。

导致 KeyboardUtils 中
boolean isVisible = keyboardRect.height() > (screenHeight >> 2) && isOpen();
这个条件判断不过，导致键盘无法显示。
建议去除  (screenHeight >> 2) contentView 或者 DecorView 高度一半的判断。 @razerdp

**Comment by razerdp** [comment]
@hunter524 

screenheight是decor或者content哦，这两个会变化吗

有没有一个demo证明，因为这里涉及比较大。。。。

**Comment by razerdp** [comment]
我在#224的demo页面进行了测试，发现。。。screenheight没有变化。

**Comment by hunter524** [comment]
我问题描述有点问题，键盘可以正常弹出，但是你在 BasePopupHelper#GlobalLayoutListener#onGlobalLayout  的上述判断位置存在问题 设置 adjustResize 会导致 Activity content 高度减小，从而你得出的键盘高度会为负值或者比content 高度的 1/4 小。因此
boolean isVisible = keyboardRect.height() > (screenHeight >> 2) && isOpen(); 
会出错，导致弹窗不会上移从而键盘遮挡弹窗的输入框。见 demo:
https://github.com/hunter524/BasePopup/tree/bug_report
bug_report 分支
@razerdp

**Comment by razerdp** [comment]
@hunter524 

hi，根据你的demo，我在我这边进行了复现。

【相关提交】：https://github.com/razerdp/BasePopup/commit/2ee32270b34045c39e88ee02d5c7bdcc5dd845e2

【复现现场Gif】：
![12321321](https://user-images.githubusercontent.com/11629986/87568623-86901500-c6f8-11ea-81d3-b27ac8d55860.gif)

经过对比，，我这边似乎无法重现您的问题。

**Comment by hunter524** [comment]
lineage os :Android 9 
使用 搜狗输入法
重现现场
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/7456580/87617874-fc24d100-c74a-11ea-99c1-90252a428c65.gif)

**Comment by razerdp** [comment]
@hunter524  讨论转移到 https://github.com/razerdp/BasePopup/issues/315

根据gif，仍未复现。

为了方便测试，我提交了新分支：[branch:issue_277](https://github.com/razerdp/BasePopup/tree/issue_277)

**Comment by 05youxi** [comment]
输入法默认横屏不适配，如果配置才能适配横屏所有输入框呢

**Comment by 05youxi** [comment]
输入法默认横屏不适配，如何配置才能适配横屏所有输入框呢

**Comment by razerdp** [comment]
> 输入法默认横屏不适配，如何配置才能适配横屏所有输入框呢

你可以自己继承BasePopup，里面设置横屏输入法适配的flag，然后所有此类popup都继承你实现的就可以了
