### ISSUE TITLE
被软键盘顶起之后 按返回键取消软键盘 布局还是被顶起来的样子下不去

### ISSUE THREAD

**Issue by JamesGZM** [razerdp/BasePopup#28]
设置了  setAutoShowInputMethod(true); 和getInputView()

**Comment by JamesGZM** [comment]
setPopupWindowFullScreen(true); 设置了全屏会出现这个问题

**Comment by razerdp** [comment]
@JamesGZM 

近期我会去排查这个问题

**Comment by tpnet** [comment]
@razerdp  @JamesGZM 大佬解决了吗，我现在也是这样子的情况，急急急

**Comment by tpnet** [comment]
@JamesGZM  在1.8.7，然后布局修改一下，EditText用 RelativeLayout包裹，可以，没问题

**Comment by razerdp** [comment]
@tpnet @JamesGZM 建议暂时用着1.8.7，1.8.8我今天修复好了，待会我再自测下看看有没有其他问题再发布1.8.9。。。。如果还有什么问题欢迎提交issue~

**Comment by razerdp** [comment]
@JamesGZM @tpnet  请更新到1.8.9

**Comment by tpnet** [comment]
setPopupWindowFullScreen(true); 之后，Popup收缩不了，，，  @razerdp  还是存在这个问题，1.8.7和最新的1.8.9-beta2 都存在

**Comment by razerdp** [comment]
@tpnet popup收缩不了？指的是什么，目前来说我测试api22~25没有发现popup动画无法执行的问题，布局也正常恢复

**Comment by tpnet** [comment]
setPopupWindowFullScreen(true); 之后 ，，然后键盘弹起来，键盘再收缩，，popup没有收缩，在半空中，，，
@razerdp

**Comment by razerdp** [comment]
@tpnet 加我QQ 164701463吧。。。issue联系太慢

**Comment by tpnet** [comment]
@razerdp 有问题，加不了

**Comment by razerdp** [comment]
看起来应该是全屏跟SOFT_INPUT_ADJUST_RESIZE冲突的问题。。。。暂时没有很好的解决方案，期待有更好的方案

**Comment by loveJYQ** [comment]
大佬，getInputView();这个怎么用！有点看不懂啊....求大佬指教

**Comment by razerdp** [comment]
2.0版本后一般不会出现该问题（除非设置了fullscreen）
