### ISSUE TITLE
直接dissmiss()，导致首次show()，失效

### ISSUE THREAD

**Issue by GMF018** [razerdp/BasePopup#281]
- 系统版本：随意
 - 库版本：2.2.1
 - 问题描述/重现步骤:在某些骚操作的情况 ，如未判断是否isShowing()下，直接去调用dissmiss(),会导致首次show()的时候无效，再次点击show() 之后正常。
 - 希望在dismiss() 的时候做些优化，如未显示，或者pop在某些情况杀死或者动画之类，调用dissmiss()之后依然能够显示正常。

**Comment by razerdp** [comment]
fixed in candy 2.2.3-dev01
pending release.
