### ISSUE TITLE
设置从底部弹出时改变弹框高度，弹框位置偏移

### ISSUE THREAD

**Issue by liutengsay1221** [razerdp/BasePopup#282]
弹框从底部按钮顶部弹出，改变弹框中的view VISIABLE 或者 GONE 弹框位置发生了偏移

**Comment by razerdp** [comment]
请补充信息。

**Comment by liutengsay1221** [comment]
系统版本：
8.1
库版本：
问题描述/重现步骤：
问题代码/截图：
![超级截屏_20200422_121234](https://user-images.githubusercontent.com/7866511/79939888-d1501700-8492-11ea-96bd-3df39fcbab3e.png)
![超级截屏_20200422_121256](https://user-images.githubusercontent.com/7866511/79939894-d44b0780-8492-11ea-9acf-d48d5d1cb02b.png)

**Comment by liutengsay1221** [comment]
在语音控件没有显示之前是正常的，在显示之后整体弹框下移了

**Comment by razerdp** [comment]
库版本。。。是多少

**Comment by liutengsay1221** [comment]
2.2.0

**Comment by razerdp** [comment]
更新到最新版试试。
