### ISSUE TITLE
一个全屏的popupwindow，输入框在顶部，在使用2.2.1版本的时候正常，在使用Candy版本的时候，软键盘会将popupwindow部分区域顶出屏幕，导致输入框看不到了

### ISSUE THREAD

**Issue by zzzsssbo** [razerdp/BasePopup#283]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：android 10
 - 库版本：Candy:2.2.3-dev01
 - 问题描述/重现步骤：
一个全屏的popupwindow，输入框在顶部，在使用2.2.1版本的时候正常，在使用Candy版本的时候，软键盘会将popupwindow部分区域顶出屏幕，导致输入框看不到了，怎么设置输入框弹起不顶起布局。
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/17812840/80171501-291a8980-861d-11ea-8e6e-7eafd2c5c2d5.png)
![image](https://user-images.githubusercontent.com/17812840/80171524-359ee200-861d-11ea-9fdb-98f8faf673a7.png)

 - 报错信息：

---

**Comment by razerdp** [comment]
这是因为在2.2.2之后我取消了对match_parent的判断了。

之前的版本当你的popup高度是match_parent的时候我会忽略掉键盘适配的，后来去掉了，因为有的人match_parent的情况下，还真要对齐底部。。。。

你的情况就是属于这种情况了，说实话，足够显示的时候不需要适配输入法。所以我才会去掉的

**Comment by zzzsssbo** [comment]
那我这种的话现在该怎么处理不让布局被顶上去呢

**Comment by razerdp** [comment]
https://www.yuque.com/razerdp/basepopup/hxd29e

请看文档。

**Comment by zzzsssbo** [comment]
好的，谢谢
