### ISSUE TITLE
关于系统5.0和5.1的状态栏问题

### ISSUE THREAD

**Issue by MrHuangZW** [razerdp/BasePopup#285]
下图为理想效果图
![1588733463(1)](https://user-images.githubusercontent.com/24773777/81134501-8ac8e500-8f87-11ea-97d9-f6f830321a8e.jpg)
理想效果图应该入上图所示，但在5.0的系统上，状态栏直接覆盖了弹窗，而在5.1的系统中，弹窗直接覆盖了状态栏。
下图为5.0
![1588733701(1)](https://user-images.githubusercontent.com/24773777/81134680-1478b280-8f88-11ea-8572-6bea82593dde.jpg)
下图为5.1
![1588733761(1)](https://user-images.githubusercontent.com/24773777/81135017-29097a80-8f89-11ea-8e73-4b75e6409ed8.jpg)

7.0系统则正常
![1588734139(1)](https://user-images.githubusercontent.com/24773777/81135052-48080c80-8f89-11ea-8139-4361d3acca46.jpg)

 - 系统版本：5.0 , 5.1
 - 库版本：2.2.2.2
 - 问题描述/重现步骤：
 - 问题代码/截图：
     setBackground(R.drawable.B2000000);
        setPopupGravity(Gravity.RIGHT);
        setPopupWindowFullScreen(true);
        setShowAnimation(AnimationUtils.loadAnimation(context, R.anim.anim_right_in));
        setDismissAnimation(AnimationUtils.loadAnimation(context, R.anim.anim_right_out));
 - 报错信息：

---

**Comment by razerdp** [comment]
5.0和5.1这两个系统官方的popup一直都是有很蛋疼的问题。。。我后面去重现一下

**Comment by MrHuangZW** [comment]
嗯嗯，谢谢大佬了

**Comment by razerdp** [comment]
candy最新版试试

**Comment by razerdp** [comment]
release 2.2.4 已经发布，本issue **【理论修复】** 已被包含，但由于没有回应，我无法得知是否正常，因此当作弃单关闭。
具体信息请到README或文档查阅新版本更新内容
