### ISSUE TITLE
位置偏移

### ISSUE THREAD

**Issue by xiaoyanger0825** [razerdp/BasePopup#286]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：android 10，华为p20
 - 库版本：2.2.3
 - 问题描述/重现步骤：
    在2.2.2.2版本中位置是正确的，升级了2.2.3后位置往上偏移了。但是在其他系统的手机上2.2.3版本没有偏移。
 - 问题代码/截图：
`    .setPopupGravity(Gravity.START or Gravity.TOP)
            .setOffsetX(20.toIntPx())
            .setOffsetY(5.toIntPx())
            .showPopupWindow(view)
`
![image](https://user-images.githubusercontent.com/18342788/81550283-9581e080-93b2-11ea-8e5d-9bd245156a05.png)
![image](https://user-images.githubusercontent.com/18342788/81550370-ad596480-93b2-11ea-9044-2fbe56120ecf.png)
麻烦看下是否是兼容性问题，感谢。
 - 报错信息：
无
---

**Comment by razerdp** [comment]
我手上没有华为p20机子喔…等我迟点看看有没有云真机。

另外请查看下偏移大小是否为状态栏高度，同时主题也提供下，当然最好能有demo

**Comment by xiaoyanger0825** [comment]
感谢。我这里发现在Activity里面是正常的，不会偏移。但是我这里的anchorView是在BottomSheetFragment里面，就会出现向上偏移。我在源码中获取锚点view位置的方法进行断点，发现2.2.2.2版本和2.2.3版本的结果不一致：
![image](https://user-images.githubusercontent.com/18342788/81785630-1666e680-9531-11ea-8674-c78893e09653.png)
![image](https://user-images.githubusercontent.com/18342788/81785654-1cf55e00-9531-11ea-971c-904e153ca01b.png)
另外，我这个页面的Activity内容是沉到状态栏下边的，我测试了2.2.3版本位置偏移的大小确实就是状态栏的大小。
是否是获取锚点view位置的方式改了后对状态栏适配需要修改？但是其他的部分继续又没有发生偏移。麻烦作者再看下，感谢。

**Comment by razerdp** [comment]
能给我一个重现demo吗，在模拟器上我无法复现

**Comment by br3ant** [comment]
Xiaomi note7 pro 也有同样的问题

2.2.2.2 正常 2.2.3 位置偏移

 popupGravity = Gravity.CENTER or Gravity.END
 offsetX = ToolUtils.dp2px(R.dimen.dp_10)

横屏下把刘海的高度也计算进去了，左侧黑边是刘海的宽度

![Screenshot_2020-06-28-11-24-10-157_com datedu ppt](https://user-images.githubusercontent.com/16162804/85937043-68719900-b932-11ea-801a-04940600b34a.jpg)

**Comment by razerdp** [comment]
ya，我看了下其实就是issue作者提出的那一段代码内部实现的不同，candy已经修正回来了，不过一直没发版，想等动画迭代好了一起发

**Comment by razerdp** [comment]
@xiaoyanger0825 
@br3ant 

我刚刚提交了candy的test版本（未重构完，只是为了验证这个问题），位置获取方法回退到2.2.2的

麻烦查看下能否正常

candy版本：2.2.4.test

**Comment by razerdp** [comment]
release 2.2.4 已经发布，本issue修复 **【讲道理】** 已被包含，但由于没有人回应我测试版本问题，因此当作弃单关闭。
具体信息请到README或文档查阅新版本更新内容
