### ISSUE TITLE
DataBinding

### ISSUE THREAD

**Issue by Jinhaihan** [razerdp/BasePopup#287]
作者大大您好，目前BasePopup的功能已经可以满足绝大部分需求了，非常感谢！
现在BasePopup的onCreateContentView使用的是自身`createPopupById(lauout);`
这点对于MVVM的工程来说，有点不太和谐，是否有计划在未来加入data Binding功能呢

**Comment by razerdp** [comment]
暂无此计划。因为对于basepopup来说，createPopupById是能解析到xml的关键.

**Comment by Jinhaihan** [comment]
> 暂无此计划。因为对于basepopup来说，createPopupById是能解析到xml的关键.

好的谢谢，目前的功能也完全够用了哈哈哈，作者辛苦了！
