### ISSUE TITLE
release版2.2.3 QuickPopupBuilder怎么修改contentView的内容

### ISSUE THREAD

**Issue by huozhihao** [razerdp/BasePopup#288]
release版2.2.3 QuickPopupBuilder怎么修改contentView的内容？
2.2.1的时候的api setOnConfigApplyListener被删了？？？

**Comment by razerdp** [comment]
QuickPopupBuilder用于简单的显示，并不适合是用作复杂逻辑。

**Comment by huozhihao** [comment]
> QuickPopupBuilder用于简单的显示，并不适合是用作复杂逻辑。

大佬回复的真及时，有时候是很简单的显示 但是某个字段要根据业务显示不同的值，现在只能显示个定死的布局，如果contentView能直接设view也比现在灵活很多啊

**Comment by razerdp** [comment]
ya，现在没有直接提供view，但是quickpopupbuilder在调用show的时候返回的是QuickPopup，你可以通过它getContentView()，得到的就是你传入的id的view

至于`setOnConfigApplyListener`，初期是为了让大家可以自己定义自己的quickpopupconfig，后来觉得没这个必要于是去掉了。

**Comment by huozhihao** [comment]
> ya，现在没有直接提供view，但是quickpopupbuilder在调用show的时候返回的是QuickPopup，你可以通过它getContentView()，得到的就是你传入的id的view
> 
> 至于`setOnConfigApplyListener`，初期是为了让大家可以自己定义自己的quickpopupconfig，后来觉得没这个必要于是去掉了。

吆西 懂了懂了 感谢大佬🙏
