### ISSUE TITLE
点击位置偏移

### ISSUE THREAD

**Issue by xin-xavier** [razerdp/BasePopup#289]
- 系统版本：Vivo IQOO Android 10 (在多个手机上出现这个问题)
 - 库版本：2.2.3
 - 问题描述/重现步骤：
弹窗底部有两个Button,点击上半部分没反应，点击下半部分才会运行 onClick()
 - 问题代码/截图：
![Uploading QQ图片20200523111503.jpg…]()
addToShoppingCart.setOnClickListener(this);
seeDetails.setOnClickListener(this);

setAdjustInputMethod(true);
setAdjustInputMode(R.id.commodityNum,FLAG_KEYBOARD_ALIGN_TO_VIEW | FLAG_KEYBOARD_ANIMATE_ALIGN);
setPopupGravity(Gravity.BOTTOM);

case R.id.addToShoppingCart:
    break;
case R.id.seeDetails:
    break;
 - 报错信息：无
---

**Comment by razerdp** [comment]
图看不到

**Comment by razerdp** [comment]
另外你可以贴一下布局，。

**Comment by xin-xavier** [comment]
哦哦，这个我通过修改布局解决了，用的是RelativeLayout，兄弟布局的一个控件我用GONE隐藏了---可能是这里让兄弟布局的位置改变了，我换成INVISIBLE就好了，抱歉打扰 and BasePopupWindow 很好用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WeiChaoFeng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 中午11:45
收件人:&nbsp;"razerdp/BasePopup"<BasePopup@noreply.github.com&gt;;
抄送:&nbsp;"柏舟"<642375398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [razerdp/BasePopup] 点击位置偏移 (#289)





 
图看不到

**Comment by xin-xavier** [comment]
> 另外你可以贴一下布局，。

**Comment by razerdp** [comment]
感谢支持~
