### ISSUE TITLE
7.0显示问题

### ISSUE THREAD

**Issue by dyfan** [razerdp/BasePopup#29]
![image](https://user-images.githubusercontent.com/15817271/27670378-1fb59d60-5cbf-11e7-9dd1-3d18b918b7f2.png)
还有located pop 左右点击left|top才是正常的,点击bottom下面两个不显示,点击right|top确显示在左边,我感觉位置都不是很正确.

**Comment by razerdp** [comment]
您好，更新到1.8.0试试

**Comment by dyfan** [comment]
AutoLocatedPopup显示的位置还是不对和View有一定的距离,上传不了图片,怎么提供给您呢.

**Comment by razerdp** [comment]
如果你是看我的例子，则是因为我有offsetY

showPopupWindow(View v)调用的时候，会判断这个popup是否可以完整显示，如果可以，就会正常显示在底部，不能的话就会显示在anchorView的上面，我这里设置了offsetY，所以确实是有一定距离的（250px）

[AutoLocatedPopup L47](https://github.com/razerdp/BasePopup/blob/master/app/src/main/java/razerdp/demo/popup/AutoLocatedPopup.java)

**Comment by dyfan** [comment]
粗心了,没仔细查看源码.thanks
