### ISSUE TITLE
在popup中原本对Activity设置的flag无效

### ISSUE THREAD

**Issue by huangjingf** [razerdp/BasePopup#290]
- 系统版本：5.1
 - 库版本：2.2.3
 - 问题描述/重现步骤：我们开发的是在定制化系统上开发的，在初始化BaseActivity可以对window addFlags（3），这样在用户按home键的时候我们能够在onKeyDown里面捕获，从而实现屏蔽home键的功能；
如果当前popup弹出的话，就没办法屏蔽home键了，我翻遍了issue，其中你提到了这种原因是因为焦点问题导致flag重置，当前popup是单独一个window需要特殊处理；
我尝试在构造方法中根据传入的context转activity对window addflag，但是失败了；目前不知道怎么解决该问题，恳请答复。
 - 问题代码/截图：

Activity中
```java
 @Override
    public void onAttachedToWindow() {
        //屏蔽home键
        this.getWindow().addFlags(3);
        super.onAttachedToWindow();
    }
```

BaseDialog
```java
public class BaseDialog extends BaseLazyPopupWindow {

    public BaseDialog(Context context) {
        super(context);
    }

    @Override
    public View onCreateContentView() {
        return null;
    }

    @Override
    protected Animation onCreateDismissAnimation() {
        Animation showAnimation = new AlphaAnimation(1f, 0);
        showAnimation.setDuration(200);
        return showAnimation;
    }
}
```

Dialog代码
```java
public class SpinnerDialog extends BaseDialog {

    private OnItemClick onItemSelected;
    private ArrayList<String> dataList = new ArrayList<>();

    public SpinnerDialog(Context context) {
        super(context);
    }

    @Override
    public View onCreateContentView() {
        return createPopupById(R.layout.dialog_spinner);
    }

    public SpinnerDialog setSpinnerData(ArrayList<String> dataList) {
        this.dataList = dataList;
        return this;
    }
  //。。。。。。
｝
```

Dialog使用
```java
  public void showSpinner() {
            ArrayList<String> devNameList = new ArrayList<>(Arrays.asList("A", "B"));
            new SpinnerDialog(activity).setSpinnerData(devNameList).setConfirmClick((dialog, pos) -> {
                dialog.dismiss();
                ToastUtils.show("选择项为:" + devNameList.get(pos));
            }).showPopupWindow();
        }
```

 - 报错信息：

**Comment by razerdp** [comment]
问题已知，并且在candy中已修复。

修复版本及内容：https://www.yuque.com/razerdp/basepopup/woxkbm
commit diff：https://github.com/razerdp/BasePopup/commit/1a2b5112adba3e89bf4bd2b87fed1a8aca2a0cd6#diff-9992a8de2d0b495db6f9f508442920c2

bug原因：

一般来说，这个问题只有在全屏情况下会出现，原因在于为了防止全屏activity出现焦点变化导致导航栏出现，我会在popup显示之前去掉焦点（防止抢夺activity焦点），然后设置windowflag（虽然popup没有自己的window，但是往hieraryview添加的时候还是会跟windowflag有关的）

在2.2.3之前的版本中，由于代码bug，实际上是无法判断是否全屏的，cuo'wu'dai'ma'ru'x错误代码如下截图

![微信截图_20200529105402](https://user-images.githubusercontent.com/11629986/83215969-c035ac80-a19a-11ea-8861-6d649c0c57ce.png)

在2.2.3修复了，但又引出的另一个问题，就是systemUiViwiblity的问题，由于全屏判断被修复，因此在popupwindow显示之后，我会对windowflag进行还原，使popup的systeui和activity的保持一致，但是在2.2.3版本中，没有获取activity的flag，而被强制设置了库的flag，因此导致您的flag被覆盖

![微信截图_20200529105455](https://user-images.githubusercontent.com/11629986/83216105-0ee34680-a19b-11ea-8dee-62d7e0f24dd7.png)

以上就是问题原因，该问题已被修复

 该解答同样适合 #291 

感谢指正-V- 请尝试一下新的版本哦~

**Comment by huangjingf** [comment]
好的，谢谢，我试试。
