### ISSUE TITLE
状态栏消失

### ISSUE THREAD

**Issue by keybalabala** [razerdp/BasePopup#291]
- 系统版本：5.0/8.0·
 - 库版本：2.2.3
 - 问题描述/重现步骤：使用的BaseLazyPopupWindow，在部分手机上，fragment弹出pop状态栏消失，2.2.2.2版本则不会出现该问题
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
您好，请查看 #290  的回答~

**Comment by keybalabala** [comment]
接入支付宝的时候，支付宝在清单文件需要配置
<supports-screens
        android:anyDensity="true"
        android:largeScreens="true"
        android:normalScreens="true"
        android:resizeable="true"
        android:smallScreens="true" />
2.2.4.0512和2.2.4.0517中都会导致Manifest merger failed！，需要去除  android:normalScreens="true"，这个会不会导致支付宝适配有什么问题

**Comment by keybalabala** [comment]
<supports-screens
        android:anyDensity="true"
        android:largeScreens="true"
        android:normalScreens="true"
        android:resizeable="true"
        android:smallScreens="true" />

**Comment by keybalabala** [comment]
。。这段代码发不出来。。发图片吧
<img width="174" alt="微信截图_20200529112635" src="https://user-images.githubusercontent.com/22448830/83217854-4a800f80-a19f-11ea-9e5b-73e0b05979cb.png">

**Comment by keybalabala** [comment]
`    <supports-screens
        android:anyDensity="true"
        android:largeScreens="true"
        android:resizeable="true"
        android:smallScreens="true" />`

**Comment by razerdp** [comment]
basepopup没有设置这个哦~

**Comment by keybalabala** [comment]
支付宝有设置这个属性，其中的android:normalScreens="true"和Candy版本有冲突，会报错Manifest merger failed，这个是什么原因导致的呢

**Comment by keybalabala** [comment]
支付宝有设置这个属性，其中的android:normalScreens="true"和Candy版本有冲突，会报错Manifest merger failed，这个是什么原因导致的呢？
支付宝的完整配置是
`    <supports-screens
        android:anyDensity="true"
        android:largeScreens="true"
        android:normalScreens="true"
        android:resizeable="true"
        android:smallScreens="true" />`

**Comment by razerdp** [comment]
不清楚呢，，这个值默认就是true的，而且basepopup确实没有配置该项

manifest：https://github.com/razerdp/BasePopup/blob/dev/lib/src/main/AndroidManifest.xml
