### ISSUE TITLE
popwindow内部又Recycleview抢占焦点问题

### ISSUE THREAD

**Issue by 15901316237** [razerdp/BasePopup#295]
系统版本安卓8.0
库版本最新版的
我这边是有个婆婆window内部有一个Recycleview，然后我想实现点击pop背景让pop消息现在不起作用是不是Recycleview抢占了焦点<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/rootView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"

    android:focusable="true"
    android:focusableInTouchMode="true"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/ivClose"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="right"
        android:layout_marginRight="15dp"
        android:layout_marginTop="80dp"
        android:background="@mipmap/icon_black_close"
        android:padding="10dp" />

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/recycler"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="20dp" />

<>
package com.hk.faceyoo.module.main.album;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.util.Log;
import android.view.Gravity;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;

import androidx.recyclerview.widget.RecyclerView;

import com.blankj.utilcode.util.ToastUtils;
import com.chad.library.adapter.base.BaseQuickAdapter;
import com.hk.faceyoo.R;
import com.hk.faceyoo.api.StampApi;
import com.hk.faceyoo.http.HttpManager;
import com.hk.faceyoo.http.RequestCallback;
import com.hk.faceyoo.model.Empty;
import com.hk.faceyoo.model.face.StampEntity;
import com.hk.faceyoo.module.main.album.adapter.SelectedStampAdapter;
import com.hk.faceyoo.module.mine.adapter.MyStampListAdapter;
import com.hk.faceyoo.module.mine.stampcenter.GiveAwayFriendsActivity;
import com.hk.faceyoo.module.mine.stampcenter.MyStampListActivity;
import com.hk.faceyoo.utils.Event;
import com.leochuan.CenterSnapHelper;
import com.leochuan.ScaleLayoutManager;

import org.greenrobot.eventbus.EventBus;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import razerdp.basepopup.BaseLazyPopupWindow;
import razerdp.basepopup.BasePopup;
import razerdp.basepopup.BasePopupWindow;

public class SelectedStampPop extends BasePopupWindow implements View.OnClickListener {
    private static final String TAG = SelectedStampPop.class.getName();
    private RecyclerView recyclerView;
    private TextView tvAffixSeal, tvGive,
            tvExchangeOut;
    private SelectedStampAdapter adapter;
    private List<StampEntity> mList = new ArrayList<>();
    private ScaleLayoutManager scaleLayoutManager;
    private String contactCodes;
    private LinearLayout linearLayout;
    private ImageView ivClose;
    private int CurrentPosition;
    private TextView tv_empty;

    public SelectedStampPop(Context context, String contactCode) {
        super(context);
        contactCodes = contactCode;
        Log.d(TAG, "SelectedStampPop: " + contactCodes);
        setBackground(R.color.transparent_background);
        setOutSideTouchable(false);
        setPopupGravity(Gravity.CENTER);
        setAutoLocatePopup(true);
        setOutSideDismiss(true);
        getStampList(contactCodes);
    }

    @Override
    public View onCreateContentView() {
        View rootview = createPopupById(R.layout.fragment_selected_stamp);
        recyclerView = rootview.findViewById(R.id.recycler);
        tvAffixSeal = rootview.findViewById(R.id.tvAffixSeal);
        tvGive = rootview.findViewById(R.id.tvGive);
        tvExchangeOut = rootview.findViewById(R.id.tvExchangeOut);
        linearLayout = rootview.findViewById(R.id.rootView);
        ivClose = rootview.findViewById(R.id.ivClose);
        tv_empty = rootview.findViewById(R.id.tv_empty);
        linearLayout.setOnClickListener(this::onClick);
        tvAffixSeal.setOnClickListener(this::onClick);
        ivClose.setOnClickListener(this::onClick);
        tvGive.setOnClickListener(this::onClick);
        tvExchangeOut.setOnClickListener(this::onClick);
        tv_empty.setOnClickListener(this::onClick);
        adapter = new SelectedStampAdapter(mList);

        scaleLayoutManager = new ScaleLayoutManager.Builder(getContext(), -60)
                .setMinScale(0.8f)
                .setMoveSpeed(0.45f)
                .build();

        recyclerView.setLayoutManager(scaleLayoutManager);
        recyclerView.setAdapter(adapter);
        CenterSnapHelper centerSnapHelper = new CenterSnapHelper();
        centerSnapHelper.attachToRecyclerView(recyclerView);
        CurrentPosition = scaleLayoutManager.getCurrentPosition();
        adapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                ToastUtils.showShort("点击了适配器");
            }
        });
        return rootview;
    }

    @Override
    public void onClick(View v) {
        switch (v.getId()) {
            case R.id.tvAffixSeal:
                getStampSeal(adapter.getItem(CurrentPosition).getCode());
                break;
            case R.id.tvGive:
                Intent intent = new Intent(getContext(), GiveAwayFriendsActivity.class);
                Bundle bundle = new Bundle();
                bundle.putSerializable("stampEmpty", adapter.getItem(CurrentPosition));
                intent.putExtras(bundle);
                getContext().startActivity(intent);
                dismiss();
                break;
            case R.id.tvExchangeOut:
                getStampSwap(adapter.getItem(CurrentPosition).getCode());
                dismiss();
                break;
//跟布局的点击不起作用
            case R.id.rootView:
            case R.id.ivClose:
            case R.id.tv_empty:
                dismiss();
                break;
        }
    }

  
}

**Comment by razerdp** [comment]
如你所见，根布局就是match_parent的，这意味着你点哪里都是点到了contentView而不是【你所认为的外部】，那当然不会消失。

能看到背景看起来是这样：

//根布局match
linearlayout{
  child{
     //child距离顶部一定距离
     //根布局没有背景颜色下那当然能看到底下那层，但是你的点击事件必定是到了根布局那
     marginTop = 20dp
  }
}

**Comment by 15901316237** [comment]
我想让背景图的空白区域也能消失如何实现呢

**Comment by 15901316237** [comment]
我的布局 上面有个recycle 下面是一个线性布局 中间有很大的空白区域，产品需求是点击pop的任何空白区域都能让他消失

**Comment by 15901316237** [comment]
但是我给整体的rootview也加了点击监听了

**Comment by 15901316237** [comment]
> 如你所见，根布局就是match_parent的，这意味着你点哪里都是点到了contentView而不是【你所认为的外部】，那当然不会消失。
> 
> 能看到背景看起来是这样：
> 
> //根布局match
> linearlayout{
> child{
> //child距离顶部一定距离
> //根布局没有背景颜色下那当然能看到底下那层，但是你的点击事件必定是到了根布局那
> marginTop = 20dp
> }
> }我的布局 上面有个recycle 下面是一个线性布局 中间有很大的空白区域，产品需求是点击pop的任何空白区域都能让他消失
但是我给整体的rootview也加了点击监听了

**Comment by razerdp** [comment]
我把你的布局拉下来试过，没有你的问题。
