### ISSUE TITLE
backpressEnable(false)无效 & QuickPopupBuilder添加KeyEventListener

### ISSUE THREAD

**Issue by cc365774016** [razerdp/BasePopup#296]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：10.0
 - 库版本：2.2.3
 - 问题描述/重现步骤：2.2.3最新DEMOQuickPopupBuilder 设置了backpressEnable(false)没生效
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
got~ 
已查验，确实有这个问题，，，问题产生原因：

QuickPopup里面的相关设置被我误删了，感谢提出~

稍后candy版本我加一下

**Comment by cc365774016** [comment]
好的。谢谢。

**Comment by razerdp** [comment]
candy 0618 再试试

**Comment by cc365774016** [comment]
好的

**Comment by cc365774016** [comment]
在新的candy版本测试可以了

**Comment by cc365774016** [comment]
但是现在测试发现如何重写了系统返回键，系统返回键不会响应

**Comment by razerdp** [comment]
什么意思

**Comment by cc365774016** [comment]
onBackPressedInternal() DEMO里的这个方法不会执行，如果设置了backpressEnable(false)

**Comment by razerdp** [comment]
那是肯定的，事件优先传递到popupwindow，在popupwindow内被我消耗了，自然不会再往下传。

否则的话弹窗没消失却把activity关掉了，这会出大问题的

**Comment by cc365774016** [comment]
这样的话，很多时候是点击返回键不需要弹窗消失，但是需要去监听系统返回键。

**Comment by cc365774016** [comment]
那popup弹出的时候，框架有提供返回键的监听吗？

**Comment by razerdp** [comment]
有的，在basepopup内有 `onBackPressed`回调

具体的你可以查看api文档

https://www.yuque.com/razerdp/basepopup/api

**Comment by cc365774016** [comment]
QuickPopupBuilder能增加一个方法传入keyEventLisener，可以自己重写返回键的处理，而不用自定义类去重写onBackPressed

**Comment by razerdp** [comment]
可以，不过不建议过度依赖quickpopup，因为这个东西创建的初衷只是用来快速展示一些纯展示类的弹窗。

**Comment by razerdp** [comment]
另外如果实在是喜欢链式的话其实可以自己封装的，，，basepopup跟他的命名一样，它只负责高度的抽象，不会有很多细节实现的，因为越多的细节对用户就有越多的约束~

**Comment by cc365774016** [comment]
好的

**Comment by razerdp** [comment]
* **【未发布版本】** （2020/07/02）
    * 优化BasePopupHelper代码
    * 增加OnKeyboardChangeListener，该监听允许用户监听键盘显示、关闭事件，同时回调键盘大小
    * 增加KeyEventListener，允许用户外部监听并处理传递到BasePopup的KeyEvent [#296](https://github.com/razerdp/BasePopup/issues/296)
    * 动画优化（进度70%）

**Comment by razerdp** [comment]
https://www.yuque.com/razerdp/basepopup/woxkbm
