### ISSUE TITLE
issue测试页面的 #224bug

### ISSUE THREAD

**Issue by AndMy** [razerdp/BasePopup#297]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：华为p9 plus
 - 库版本：发布【Candy】- 2.2.4.0517
 - 问题描述/重现步骤：有视频
 - 问题代码/截图：软键盘挡住输入框了，这儿适配了么，未适配的话可忽略
 - 报错信息：视频连接 https://gitee.com/andmy/other/blob/master/video/VID_20200618_165621.mp4

---

**Comment by razerdp** [comment]
你好，这里的问题实际不是popup的，这个输入框其实是activity的，并不在popup中，而且由于softinputmode的原因，点击输入框的时候整体上移，通过decorview获取键盘高度失效，因此体现出挡住输入框，同时点击事件实际上也无法传递，我当时测试过，点击事件其实被键盘dialog挡住了。。。

这我也很无奈，所以issue 224这里的测试页面才会是输入框在中间。

这个问题跟popup无关，而且popup只能管到popup内的输入法适配而无法干预外面的控件

**Comment by razerdp** [comment]
不过我看了下，似乎popup会挡住外部输入框倒是真，。。。这个问题我看看

**Comment by AndMy** [comment]
嗯嗯，我在咨询一个问题，下面有个图片
![图片](https://user-images.githubusercontent.com/7222340/85092292-f73c3280-b21b-11ea-8750-e5c076a3e411.png)

**Comment by razerdp** [comment]
目前的api其实并不支持高亮。

因为高亮理论上是需要您自己实现的（我提供的api可能无法最大程度覆盖所有使用场景），蒙层设为透明，然后自己添加view来实现。

后续可以考虑要不要basepopup蒙层提供支持。

先说回来，你这里并不是规则的图形哦，要高亮的话可能要自己处理下轮廓~

**Comment by AndMy** [comment]
嗯嗯，好的，局部阴影好像不能实现这个效果

**Comment by razerdp** [comment]
![ezgif-5-25e99ddad118](https://user-images.githubusercontent.com/11629986/85111478-fb317a00-b246-11ea-8165-a4eee9e09a96.gif)

提到的#224问题已经修复

修复diff：

https://github.com/razerdp/BasePopup/commit/1509837a65013677e46ef96d479192bb63f50b08#diff-df6e5808dc3d705719e4698f9290458eR641

本次修复没有提包，因为我正在重构动画相关内容
