### ISSUE TITLE
从2.2.1升级到2.2.3后蒙层点击都无法关闭弹窗了

### ISSUE THREAD

**Issue by huwencheng** [razerdp/BasePopup#298]
从2.2.1升级到2.2.3后蒙层点击都无法关闭弹窗了，请问是什么原因导致的？

**Comment by razerdp** [comment]
请确保你的popup布局不是填满整个窗口的，很多时候看到蒙层不一定就是点到它。

**Comment by huwencheng** [comment]
已经找到问题了，我得基类是继承support包导致的问题，现已改为appcompat包，已无此问题，感谢。

**Comment by razerdp** [comment]
额，能分享下问题具体原因吗，我看要不要写到常见问题里，帮到其他的人

**Comment by huwencheng** [comment]
好像不是这个导致的，具体我这边在分析下

**Comment by woosiyuan** [comment]
同问
