### ISSUE TITLE
【BasePopup需求提单】

### ISSUE THREAD

**Issue by razerdp** [razerdp/BasePopup#299]
BasePopup迭代至今日益完善，因此对于我个人而言，大多数时候都只是日常维护，bug修复。新功能已经几乎没有什么想法添加了。

但是BasePopup作为一个高度抽象的基类，对于大家的实现虽说几乎没有限制，但还是有那么一点约束，也许是api没有开放，也许是某种功能缺失等等。

然而就我个人来说，我是无法以个人的能力来应对无止境的需求，因此开了这个issue来听取大家的建议或者需求，如果通过了将会加入到后续开发计划中。

当然，为了保证BasePopup的抽象及稳定性，如果您的需求是类似于“ios弹框”、“多级选择”、“城市选择”等等具象化实现的需求，那么**请不要再这里提交**，您可以去[未来计划&意见记录小本本](https://github.com/razerdp/BasePopup/issues/265)提交您的具体需求，后续会在扩展库中加入通过了的具体需求。

在此，希望您提交的建议或者是需求是基于BasePopup框架通用层面而非某个具体实现。

> 举个例子：允许蒙层高亮某个View

--- 

当您的需求提交到本issue后，该issue将会进入以下流程：

1. 作者初审：我会对您的需求进行审核，在评定对现有框架影响后会决定能否进入下一流程，在这一步中请允许我拒绝某些影响较大、不合规或长期任务的需求。

2. 投票：当初审通过后，我会在本帖一楼进行当前需求投票的公示，投票以新建issue并通过emoji性质决定是否通过。

3. 加入需求清单：在需求通过前面两个流程后，您的这个需求将会加入到需求清单中，如果改需求正在开发，则会在readme中公示，您可以在dev分支中看到相关提交。

请允许我用这么笨笨的方法进行投票、跟单，因为我没有精力去弄个tracker。。。。

最后，请不要催促需求完成日期，因为这是一个开源工程，并不是一个商业工程，我们的初衷是让BasePopup更加的完善，而不是为了您的需求而加班加点。

**Comment by razerdp** [comment]
【一楼需求公示】
当前开发：动画迭代

需求投票：[允许蒙层高亮一个或多个其依附的View](https://github.com/razerdp/BasePopup/issues/300)

后续需求列表：无

**Comment by smileToWxm** [comment]
能加个软键盘变化的监听吗？我好像没有找到对应的api

**Comment by razerdp** [comment]
> 能加个软键盘变化的监听吗？我好像没有找到对应的api

当前有这个监听，但是没有开放出来。如果有需要可以开放

**Comment by smileToWxm** [comment]
> > 能加个软键盘变化的监听吗？我好像没有找到对应的api
> 
> 当前有这个监听，但是没有开放出来。如果有需要可以开放

可以开放出来吗，当前需要对键盘的变化做一些布局处理

**Comment by razerdp** [comment]
> > > 能加个软键盘变化的监听吗？我好像没有找到对应的api
> > 
> > 
> > 当前有这个监听，但是没有开放出来。如果有需要可以开放
> 
> 可以开放出来吗，当前需要对键盘的变化做一些布局处理

可以开放但是得等到下个版本哦。。。因为我不能为了你这个需求立马打个包。。。而目前candy仍在迭代。

**Comment by smileToWxm** [comment]
> > > > 能加个软键盘变化的监听吗？我好像没有找到对应的api
> > > 
> > > 
> > > 当前有这个监听，但是没有开放出来。如果有需要可以开放
> > 
> > 
> > 可以开放出来吗，当前需要对键盘的变化做一些布局处理
> 
> 可以开放但是得等到下个版本哦。。。因为我不能为了你这个需求立马打个包。。。而目前candy仍在迭代。

可以的，谢谢楼主

**Comment by razerdp** [comment]
@smileToWxm candy已经开放
请留意更新日志：https://github.com/razerdp/BasePopup/tree/dev#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97-%E5%8E%86%E5%8F%B2%E6%9B%B4%E6%96%B0

**Comment by razerdp** [comment]
@smileToWxm 

release 2.2.4 已经发布，您的需求已被包含。
具体信息请到README或文档查阅新版本更新内容

**Comment by FrankLove** [comment]
作者你好，请问链式调用里面不能在点击item后让popuwindow消失吗，比如说弹出一个上传图片选择的popuwindow，如果用户点击了拍照或者相册，popuwindow应该要消失的，但是用链式调用好像没看到这个处理

**Comment by razerdp** [comment]
@FrankLove 
withClick有三种的，请调用参数最多的那个
withClick(int viewId, View.OnClickListener listener, boolean dismissWhenClick)

**Comment by FrankLove** [comment]
@razerdp 尴尬，居然没看到有这个重载方法。。。

**Comment by razerdp** [comment]
该贴终结= =
