### ISSUE TITLE
【需求投票 7.31截止】允许蒙层高亮一个或多个其依附的View

### ISSUE THREAD

**Issue by razerdp** [razerdp/BasePopup#300]
需求：允许蒙层高亮一个或多个其依附的View
描述：我觉得好像不用描述，，，大概都懂
可能遇到的难点：
  * 显示不规则View的处理
  * 提供接口让用户自定义
  * 多个弹窗下，新弹窗的蒙层是否保留上一个弹窗的高亮，防止新弹窗蒙层覆盖上一级弹窗的高亮

**Comment by razerdp** [comment]
本投票在7.31截止

您可以通过emoji：👍 表示赞成，或 👎 表示反对

投票最终以emoji数量准，总数低于20个则无效。

**Comment by huwencheng** [comment]
个人感觉这个自己业务层可以控制，界面每次最多显示一个弹窗，弹完再接着显示下一个

**Comment by razerdp** [comment]
> 个人感觉这个自己业务层可以控制，界面每次最多显示一个弹窗，弹完再接着显示下一个

其实一开始我也觉得应该自己实现，我们支持这个功能其实意义不大。。。

**Comment by lhkzx007** [comment]
可以作为扩展项目来支持,想用就引用

**Comment by razerdp** [comment]
是的，可以考虑放到扩展库里

**Comment by razerdp** [comment]
无人问津。。关闭。

**Comment by lhkzx007** [comment]
哈哈哈
