### ISSUE TITLE
怎么让布局从屏幕底部弹出?

### ISSUE THREAD

**Issue by q88qaz** [razerdp/BasePopup#302]
怎么让布局从屏幕底部弹出?

**Comment by razerdp** [comment]
这个问题请查看demo实现

**Comment by q88qaz** [comment]
demo写的太绕了，真心看不明白

**Comment by razerdp** [comment]
现在版本下，可以是这样：
gravity = bottom
然后在onCreateShowAnimator中返回getDefaultSlideFromBottomAnimationSet

**Comment by razerdp** [comment]
目前我也在迭代动画这一部分，以后会用起来简便很多

**Comment by razerdp** [comment]
当前版本的指引已经补充：

https://www.yuque.com/razerdp/basepopup/rp56q4
