### ISSUE TITLE
BasePopup的生命周期是怎样的？

### ISSUE THREAD

**Issue by q88qaz** [razerdp/BasePopup#303]
onViewCreated()方法走完之后怎么初始化数据不符？
在onViewCreated()这个方法里面访问context为null，无法进行数据初始化等操作

**Comment by razerdp** [comment]
请补充详细描述

**Comment by q88qaz** [comment]
onViewCreated()方法走完之后怎么初始化数据部分？
在onViewCreated()这个方法里面访问context为null，无法进行数据初始化等操作
给各个空间赋值，进行网络数据请求，请问怎么执行？

**Comment by q88qaz** [comment]
super(context);
方法执行后，context何时不为null?当我在onViewCreated()方法里面访问context时，报null exception

**Comment by razerdp** [comment]
context在你创建了对象之后都不会为null，另外，要你补充完整的信息是指根据issue模板进行补充，如系统版本，库版本之类的。。否则我很难获取有效信息啊

**Comment by razerdp** [comment]
没有补充，无法重现
