### ISSUE TITLE
布局里面我放的ViewPager，是不是不支持ViewPager布局？不支持嵌套Fragment？

### ISSUE THREAD

**Issue by q88qaz** [razerdp/BasePopup#304]
报错代码
java.lang.IllegalArgumentException: No view found for id 0x7f070121 (com.zyhl.basepopu:id/view_pager) for fragment GiftListFragment{8738d59 (de3f379c-92e0-4dd2-b74e-8666d96bf3ce) id=0x7f070121}

**Comment by razerdp** [comment]
系统popup本身就不支持fragment，自然而然我也不支持，因为我是对系统的popup进行优化，而非彻底改造

**Comment by q88qaz** [comment]
……一时语塞，折腾半天发现徒劳了o(╯□╰)o

**Comment by q88qaz** [comment]
大哥，如果要嵌套fragment，你认为用什么好？dialog吗？

**Comment by razerdp** [comment]
dialog可以的
