### ISSUE TITLE
kotlin中，继承BasePopupWindow后不能直接获取控件啊

### ISSUE THREAD

**Issue by TianGuisen** [razerdp/BasePopup#305]
好尴尬的要findviewbyid,dialogframgent是可以在kotlin中直接获取控件。

**Comment by razerdp** [comment]
请补充详细信息

**Comment by TianGuisen** [comment]
就是kotlin，在activity，fragment，dialogfragment中可以通过导入import kotlinx.android.synthetic....，就可以不用findviewByid或者butnif去获取控件，直接通过布局id获取控件。
但是BasePopupWindow，必须要findviewByid或者butnif去获取控件，不能使用kotlin的这个特性

**Comment by razerdp** [comment]
暂时不能。

**Comment by br3ant** [comment]
打开kotlin实验属性     
androidExtensions {
        experimental = true
}
继承 LayoutContainer
实现     
override val containerView: View?
        get() = contentView 
就可以了
