### ISSUE TITLE
键盘弹起的情况下，弹出BasePopup，popup在键盘下面，被键盘遮挡

### ISSUE THREAD

**Issue by joker-fu** [razerdp/BasePopup#306]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
 - 库版本：
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
请补充详细信息。
只有一句话是无法debug的
