### ISSUE TITLE
关于MIUI小白条及类似的“全面屏手势提示线”覆盖问题描述

### ISSUE THREAD

**Issue by razerdp** [razerdp/BasePopup#307]
在测试机更新到MIUI12后，我发现了小白条的存在，起初认为没什么，但在用了一些应用后发现其实大家都对这个并没有适配，比如TIM：
![device-2020-06-29-151007](https://user-images.githubusercontent.com/11629986/85983875-d85b4e80-ba1a-11ea-81c1-7c91437ab47f.png)
当然，我们BasePopup在抛弃了手动测量高度而将其交回给系统后，也出现了这个情况：
![微信截图_20200629151237](https://user-images.githubusercontent.com/11629986/85984044-25d7bb80-ba1b-11ea-8de7-d3008a774e05.png)
为了验证，我分别使用了系统自身的Popup和Dialog分别进行验证：

| PopupWindow | Dialog |
| - | - | 
| ![微信截图_20200629152026](https://user-images.githubusercontent.com/11629986/85984869-6552d780-ba1c-11ea-9740-69c12307f6e6.png) | ![微信截图_20200629152111](https://user-images.githubusercontent.com/11629986/85984898-700d6c80-ba1c-11ea-86be-7bc18d6fec9e.png) |

我们可以发现，系统的PopupWindow一样有问题，而Dialog并没有。

考虑到Dialog是拥有自己的Window的，而PopupWindow依附于Parent的Window，所以Dialog在这一方面表现的确较好，不过咱们是BasePopup（也许以后会提供一个Dialog模式~），那么解决问题当然是以PopupWindow为准。

## 问题根源

其实看到这个小白条，我第一时间就想到曾经也有三星手机相关的issue，也是这种缩小型的navigationbar：

https://github.com/razerdp/BasePopup/issues/184

于是打开LayoutInspector查看了一下，果不其然，这个小白条 **根本就不是ios那样的沉浸式** ，而是单纯的修改了NavigationBar

![微信图片_20200629152612](https://user-images.githubusercontent.com/11629986/85985183-f1fd9580-ba1c-11ea-8c50-e0808c060728.png)

而PopupWindow是不应该覆盖navigationbar的，因为覆盖的话会造成事件拦截，navigationbar的事件被抢先消耗了。

## BasePopup的解决方案

目前BasePopup的确有解决方案，但是这套方案依然会有上面所说的**覆盖navigationbar**的问题，在此我提供了一些方案选择，或者如果大家有更好的方式也请在issue提出并讨论：

目前BasePopup覆盖navigationbar问题不大，但是就覆盖的问题提出两种方案：

1. BasePopup统筹整体布局，对BasePopup内的根布局进行底部 **padding** ，为了更好的扩展，将提供开关让用户选择是否进行padding（默认应该是保留padding以保证不覆盖navigation）

2. BasePopup不处理布局，但是会提供回调给BasePopupWindow，用户可以在回调方法内自行处理

### 附录：方案展示及方案问题所在：
| 覆盖navigation| navigatin阻挡 |
| - | - | 
| ![微信图片_20200629153513](https://user-images.githubusercontent.com/11629986/85986020-29207680-ba1e-11ea-8d76-3df2bf145f6b.png) | ![微信图片_20200629153518](https://user-images.githubusercontent.com/11629986/85986045-30e01b00-ba1e-11ea-84af-a94689b30e9d.png) |

**Comment by razerdp** [comment]
适配diff：

https://github.com/razerdp/BasePopup/commit/075b264b5780b26aae59d5c64fde7468d9bdfee6

**Comment by DaveBoy** [comment]
希望能尽快发正式版 项目中遇到了此类问题

**Comment by razerdp** [comment]
@DaveBoy  
candy可以用。

**Comment by DaveBoy** [comment]
> @DaveBoy
> candy可以用。

好的

**Comment by eternallyjie** [comment]
你好，在更新2.2.7后，pop底部会多出来个跟导航栏高度相同的灰条。setOverlayNavigationBar方法默认是false，就会多出来一条，设置为true，布局也没有侵入到导航栏里。
手机：小米10
系统：miui12 内测版 20.9.8
效果如下图。
![false](https://user-images.githubusercontent.com/30895476/93034963-53252480-f66e-11ea-9281-33df8f823dc7.png)
![true](https://user-images.githubusercontent.com/30895476/93034969-56201500-f66e-11ea-936a-18f2476c8fe4.png)

**Comment by razerdp** [comment]
> 你好，在更新2.2.7后，pop底部会多出来个跟导航栏高度相同的灰条。setOverlayNavigationBar方法默认是false，就会多出来一条，设置为true，布局也没有侵入到导航栏里。
> 手机：小米10
> 系统：miui12 内测版 20.9.8
> 效果如下图。
> ![false](https://user-images.githubusercontent.com/30895476/93034963-53252480-f66e-11ea-9281-33df8f823dc7.png)
> ![true](https://user-images.githubusercontent.com/30895476/93034969-56201500-f66e-11ea-936a-18f2476c8fe4.png)

我的测试机就是MIUI12，Android 10哦~

你可以提供一下你的布局以及代码吗（最好用个简单的布局尝试复现）【ps，另外开个issue单独讨论吧】

**Comment by philip2016** [comment]
你好，miui12  20.7.6 内测版本，这个手势提示线遮挡了app底部的部分ui，例如底部tab等

许多应用包括手机系统应用，均有该问题

需要开发者做适配，还是后面会有全局修正？

![image](https://user-images.githubusercontent.com/14123330/99223734-08678a80-2820-11eb-9fe8-57bf7b1365f4.png)

**Comment by philip2016** [comment]
![image](https://user-images.githubusercontent.com/14123330/99223834-3a78ec80-2820-11eb-8775-bf07ee0b624f.png)

**Comment by DaveBoy** [comment]
> 手机系统应用，均有该问

手机系统也有  不应该是小米的问题吗。。。

**Comment by razerdp** [comment]
@philip2016 这。。你得跟小米反馈一下喔 = = 跟我弹窗这边好像没啥关系

**Comment by philip2016** [comment]
额，是小米系统问题，看花了，我以为这里是小米反馈渠道.... .... 尴尬了

**Comment by jxoday** [comment]
设置导航键不可见就行了

**Comment by RubinTry** [comment]
这个问题，小米官网也有相应的解决方案，当初我也找了好久

**Comment by razerdp** [comment]
> 这个问题，小米官网也有相应的解决方案，当初我也找了好久

请问有链接吗~毕竟我这里的解决方案可能不完美，看看官方的方案

**Comment by kyriej** [comment]
@razerdp 小米手势提示线 文档 https://dev.mi.com/console/doc/detail?pId=2229
