### ISSUE TITLE
#141 导航栏先弹出后立刻有隐藏的bug 在2.3.2 中回归了。2.2.2.2中正常

### ISSUE THREAD

**Issue by br3ant** [razerdp/BasePopup#308]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：
   android 6.0
 - 库版本：
   2.3.2
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：

---

**Comment by razerdp** [comment]
我看了一下正在开发的：
https://www.yuque.com/razerdp/basepopup/woxkbm
发现有跟SystemUiVisibility相关的修改，你看看candy最新版能否复现吗
如果有，希望能提供demo，因为我这边无法复现

**Comment by br3ant** [comment]
2.2.4 修复
