### ISSUE TITLE
在popup1中弹出popup2 但是popup2是以popup1中的view为锚点弹出

### ISSUE THREAD

**Issue by open9527** [razerdp/BasePopup#309]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：miui7.0
 - 库版本：com.github.razerdp:BasePopup:2.2.3
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@c78e904 is not valid; is your activity running?

---

**Comment by razerdp** [comment]
popup因为没有windowtoken，因此popup不能以popup内的view作为锚点

**Comment by razerdp** [comment]
https://www.yuque.com/razerdp/basepopup/dgf6ry#4JeRr

**Comment by razerdp** [comment]
该问题在candy 2.2.8解决了~

【Candy】2.2.8.0817 (2020/08/17)
支持BasePopup使用BasePopup内的AnchorView弹窗
