### ISSUE TITLE
库添加在build.gradle老是拉取不下来

### ISSUE THREAD

**Issue by zhupengxiang** [razerdp/BasePopup#31]
根目录的gradle已经添加了jitpack，还是拉取不下来，Failed to resolve: com.github.razerdp:BasePopup:1.8.0
好郁闷

**Comment by yefl2064** [comment]
我也出现了同样的问题。 1.7.1可以， 1.7.2和1.8.0就不行

**Comment by zhupengxiang** [comment]
对啊   这个不知道为什么 要作者检查下

**Comment by yefl2064** [comment]
@razerdp 麻烦抽空看下问题， 感激

**Comment by yefl2064** [comment]
@zhupengxiang  com.github.razerdp:BasePopup:v1.8.0  这样可以

**Comment by zhupengxiang** [comment]
@yefl2064  我天 原来比以前的版本多了个vvvvv啊   thanks  那我关掉issue了

**Comment by razerdp** [comment]
@zhupengxiang 你好。。。不知何时起，jitpack就对这个"v"不过滤了，所以请加上v1.8.0

**Comment by zhupengxiang** [comment]
@razerdp   嗯好的
