### ISSUE TITLE
能否公开QuickPopupConfig的contentViewLayoutid方法

### ISSUE THREAD

**Issue by DaveBoy** [razerdp/BasePopup#311]
我想自己进行扩展相关的类，实现如下代码：
BaseQuickPop(this,0,0,QuickPopupConfig()
                        .contentViewLayoutid(R.layout.v3_pop_browser_more)
                        .gravity(Gravity.BOTTOM)
                        .withClick(R.id.cl_more_report, { v: View? -> showErrorReport() }, true)
                        .withClick(R.id.iv_more_close, null, true)
                        .withClick(R.id.cl_more_browser_type, { v: View? -> showMode() }, true)).showPopupWindow()
但是contentViewLayoutid方法为私有

**Comment by DaveBoy** [comment]
已通过其他方式解决,凑合吧：
```
class BaseQuickPop:QuickPopup {
    private val contentViewLayoutid:Int
    constructor(layoutId:Int,fragment: Fragment, width: Int, height: Int, config: QuickPopupConfig) :super(fragment, width, height,config){
        contentViewLayoutid=layoutId
    }

    constructor(layoutId:Int,dialog: Dialog, width: Int, height: Int, config: QuickPopupConfig) :super(dialog, width, height,config){
        contentViewLayoutid=layoutId
    }

    constructor(layoutId:Int,context: Context, width: Int, height: Int, config: QuickPopupConfig) :super(context, width, height,config){
        contentViewLayoutid=layoutId
    }
   
    override fun onCreateContentView(): View? {
        return createPopupById(contentViewLayoutid)
    }
  //其他扩展代码
}
```

**Comment by razerdp** [comment]
开放contentViewLayoutid的目的是为了什么呢。

quickpopup一直以来不提倡复杂的使用，复杂的使用我更加建议自定义，通过继承BasePopupWindow来解决。

quickpopup存在的目的是为了显示一些简单的弹窗（也许包含一些简单的点击事件）时不用创建多个实现，将它写成链式调用实际上是为了让开发者意识到可以通过自行封装达到这种效果~

**Comment by DaveBoy** [comment]
我只是想在所有弹窗的里面加入一点简单的共有逻辑（在我项目中我想添加的是屏幕旋转dismiss全部pop和dialogfragment等弹窗，我又不想每个new都持然后dismiss，所以通过eventbus发送的通知）。
复杂的弹窗我可以继承统一的父类实现这一需求，但是quickpopupbuilder返回的pop却无法加入这一功能。所以我需要稍许的封装，却又不想因为这点改动让每个都继承重写。
我不确定其他人是否会有这种需求，我现在已经通过上述方式解决了这个问题。

**Comment by razerdp** [comment]
在以前的版本中，quickpopupbuilder是允许传入自己的config（继承quickpopupconfig），最终返回也是泛型的，后面发现基本没啥人用也没有提过相关issue，因此就被我取消掉了，强制返回quickpopup。。。

**Comment by razerdp** [comment]
关于这块，我看看如何迭代吧，可以考虑放开quickpopupbuilder的限制，允许自定义（比如创建的popup回调给用户自己创建quickpopup子类来返回）

**Comment by razerdp** [comment]
如果有更好的方案也可以一起提出来哦

**Comment by razerdp** [comment]
尝试过一轮改动，最后还是决定先不放开了（因为我发现我拓展开放了各种东西后，我并不怎么想去用BasePopupWindow了），我怕放开后写了文档会让更多的人去使用或拓展QuickPopupBuilder。。。。这并不是我的初衷，我不想为了维护QuickPopupBuilder而去写BasePopup。

**Comment by razerdp** [comment]
实际上，这部分更懒的特性

如：一句话完成弹窗、链式调用等，我是不太希望集成在BasePopup的，而是希望把它集成到扩展库里。扩展库会像QuickPopupBuilder一样封装一些常见弹窗，而且基本都会考虑到使用上的优雅性并尽量保留最大的扩展性，能满足一句话完成这种懒人需求。。

所以最后我还是决定不放开权限了，以后在扩展库慢慢补充

扩展库：https://github.com/razerdp/BasePopup-Extension
