### ISSUE TITLE
2.2.3下 相对位置无效

### ISSUE THREAD

**Issue by macleo** [razerdp/BasePopup#313]
## 提issue前请务必参考以下格式填写，否则该问题可能会【被忽略】

 - 系统版本（必须）：android 7.0
 - 库版本（必须）：2.2.3
 - 问题描述/重现步骤（必须）：2.2.3下 相对位置无效 ，2.2.1 ok
 - 问题代码/截图（可选）：
//为 layout中的一个ImageView
  AppCompatImageView iv_supervise =(AppCompatImageView) findViewById(R.id.iv_supervise); 
demoPop = new DemoPop(this);
        demoPop.setPopupGravity(BasePopupWindow.GravityMode.RELATIVE_TO_ANCHOR, Gravity.BOTTOM);
        demoPop.showPopupWindow(iv_supervise);
 - 报错信息（可选）：
没有
---

**Comment by razerdp** [comment]
是否继承的BaseLazyPopup

**Comment by macleo** [comment]
> 是否继承的BaseLazyPopup



> BaseLazyPopup



> 是否继承的BaseLazyPopup

BasePopupWindow 

[code]
public class DemoPop extends BasePopupWindow {
    private ImageView mIvArrow;
    public DemoPop(Context context) {
        super(context);
    }

    // 必须实现，这里返回您的contentView
    // 为了让库更加准确的做出适配，强烈建议使用createPopupById()进行inflate
    @Override
    public View onCreateContentView() {
        return createPopupById(R.layout.popup_tip);
    }

    @Override
    protected Animation onCreateShowAnimation() {
        AnimationSet set=new AnimationSet(false);
        Animation shakeAnima=new RotateAnimation(0,15,Animation.RELATIVE_TO_SELF,0.5f,Animation.RELATIVE_TO_SELF,0.5f);
        shakeAnima.setInterpolator(new CycleInterpolator(5));
        shakeAnima.setDuration(400);
        set.addAnimation(getDefaultAlphaAnimation());
        set.addAnimation(shakeAnima);
        return set;
    }
}
[/code]
.showPopupWindow时位置会跑到Activity的最左上角，同样的东西，换成2.2.1，一起OK，先用2.2.1了。谢谢。

**Comment by razerdp** [comment]
2.2.3与2.2.1貌似在layout这一块没怎么改动过。而且每次发布前都会经过demo内所有内容的测试的说。。。

能提供复现demo吗

**Comment by macleo** [comment]
> 2.2.3与2.2.1貌似在layout这一块没怎么改动过。而且每次发布前都会经过demo内所有内容的测试的说。。。
> 
> 能提供复现demo吗

我发你的邮箱么？可以的

**Comment by razerdp** [comment]
> > 2.2.3与2.2.1貌似在layout这一块没怎么改动过。而且每次发布前都会经过demo内所有内容的测试的说。。。
> > 能提供复现demo吗
> 
> 我发你的邮箱么？可以的

ok，或者你直接拖进来评论这里，应可以上传的

**Comment by macleo** [comment]
demo

> > > 2.2.3与2.2.1貌似在layout这一块没怎么改动过。而且每次发布前都会经过demo内所有内容的测试的说。。。
> > > 能提供复现demo吗
> > 
> > 
> > 我发你的邮箱么？可以的
> 
> ok，或者你直接拖进来评论这里，应可以上传的
发到你gmail.com邮箱了，
步骤 1. 2.2.1 跑一遍
再2.2.3 跑一遍，就能复现。辛苦了。 
 implementation 'com.github.razerdp:BasePopup:2.2.1'

**Comment by razerdp** [comment]
问题已确认。

请更新到 **candy 2.2.4.0705** 尝试，正式版本暂时还没发布。

 - [diff](https://github.com/razerdp/BasePopup/commit/51fb9dc4a1f455ebed7d80b5c46f5523d91ac371#diff-a35c6952a89538968c329dfbd8fd39e8L882)
 - [日志](https://github.com/razerdp/BasePopup/tree/dev#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97-%E5%8E%86%E5%8F%B2%E6%9B%B4%E6%96%B0)

【问题产生原因】：
在onCreate时，view是并没有完成测量过程的，此时弹窗并关联anchorView时会导致BasePopup无法弹窗并等待DecorView（即Activity）AttachToWindow。

在attach之后，此时可以弹窗（因为有windowToken），但是锚点view依然没有进行测量，因此无法获取该view位置，所以在左上角弹出（位置：0,0）

【问题解决方案】：
在AttachToWindow后，重新弹窗的时候放到post后，因为post的消息是在完成一系列操作后才会去处理的（view#attachToWindow），能保证在测量过后弹出。

【问题解决版本】：

candy 2.2.4.0705

【回归记录】：

![ezgif-4-93c2a793592a](https://user-images.githubusercontent.com/11629986/86529589-62585b00-bee4-11ea-9799-6968d95c2ae1.gif)

**Comment by razerdp** [comment]
release 2.2.4 已经发布，本issue修复已被包含。
具体信息请到README或文档查阅新版本更新内容
