### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by angcyo** [razerdp/BasePopup#314]
`razerdp.basepopup.BasePopupHelper#applyToPopupWindow`

源码如下:

```java
 private void applyToPopupWindow() {
     if (mPopupWindow == null || mPopupWindow.mPopupWindowProxy == null) return;
     mPopupWindow.mPopupWindowProxy.setSoftInputMode(isAutoShowInputMethod() ? WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE : WindowManager.LayoutParams.SOFT_INPUT_STATE_UNCHANGED
     mPopupWindow.mPopupWindowProxy.setSoftInputMode(mSoftInputMode);
     mPopupWindow.mPopupWindowProxy.setAnimationStyle(animationStyleRes);
 }
```

这里调用了2次`setSoftInputMode`, 是否有问题?

**Comment by razerdp** [comment]
确实有问题。。。我看看修改记录

![image](https://user-images.githubusercontent.com/11629986/87500689-ba832000-c68f-11ea-943e-8606160c7622.png)

5月7号时就已经遗留了。。。。蛋疼- -，我这边的锅，感谢指出~

**Comment by razerdp** [comment]
相关提交：
https://github.com/razerdp/BasePopup/commit/2ee32270b34045c39e88ee02d5c7bdcc5dd845e2#diff-9cc906d83de4f0db339b77d70c78c7dfL715
