### ISSUE TITLE
关于Issue277问题的讨论

### ISSUE THREAD

**Issue by razerdp** [razerdp/BasePopup#315]
【link】：https://github.com/razerdp/BasePopup/issues/277#issuecomment-658724674
【问题描述】：关于BasePopupHelper#GlobalLayoutListener#onGlobalLayout中，键盘判断的问题
【最新进展】：无法复现

@hunter524

**Comment by hunter524** [comment]
发起了一个 [Pull Request](https://github.com/razerdp/BasePopup/pull/316)  你看一下这样你能不能复现

**Comment by razerdp** [comment]
嗯，已经确认。。。

不过为啥这么蛋疼，BaseActivity其实也没做关于inputmode的修改

**Comment by hunter524** [comment]
我也正想不明白原因，明显继承BaseActivity之后 Issue277TestActivity 的展示状态和设置了 adjustPan 是一样的。

**Comment by razerdp** [comment]
我看了一下，其实重点就是在screenHeight这一块，受到adjustResize的影响。
你发一封邮件到我邮箱吧（razerdp123@gmail.com），我给你发我们聊天群的二维码，在那交流快点。

**Comment by hunter524** [comment]
邮件已发 guyuesh2@gmail.com
