### ISSUE TITLE
点击popup之外的区域无法关闭

### ISSUE THREAD

**Issue by q88qaz** [razerdp/BasePopup#317]
## 提issue前请务必参考以下格式填写，否则该问题可能会【被忽略】

 - 系统版本（必须）：6.0
 - 库版本（必须）：2.2.3
 - 问题描述/重现步骤（必须）：
 - 问题代码/截图（可选）：
 - 报错信息（可选）：

---

 new RulePopup(BaseDialog.this).showPopupWindow();

当我传入的是dialog时，点击popup之外的区域无法关闭，但不是全部， popup之外的区域如果落在这个dialog区域内，就无法关闭popup，如果落在dialog区域外，就可以关闭popup

**Comment by razerdp** [comment]
在demo中就有在Dialog中弹窗的api，经过测试，无法复现。

测试模拟器版本：api23（android 6.0）
请留意gif图中的鼠标位置：

![1233](https://user-images.githubusercontent.com/11629986/87854123-1b398380-c942-11ea-9589-809d0bbcdba0.gif)

**Comment by q88qaz** [comment]
已解决，是因为点击的区域落在margin里面，建议大家布局的时候尽量使用wrant_content或者固定的dp大小，根布局尽量不要使用margin和padding属性以免触控关闭的有效区域失效，谢谢作者

**Comment by razerdp** [comment]
padding我无法控制，但margin我觉得有必要做下优化。

**Comment by razerdp** [comment]
已修复 

* **【Candy】2.2.7.3** (2020/08/20)
  * 修复存在Margin的情况下，点击ContentView外无法传递到MaskLayout的问题 [#317](https://github.com/razerdp/BasePopup/issues/317)
