### ISSUE TITLE
根布局设置margin导致方法setOutSideTouchable(true);失效

### ISSUE THREAD

**Issue by q88qaz** [razerdp/BasePopup#318]
根布局设置margin导致方法setOutSideTouchable(true);失效
点击区域落在margin间距内，则popup不会消失！！！
点击区域落在margin间距内，则popup不会消失！！！
点击区域落在margin间距内，则popup不会消失！！！

**Comment by razerdp** [comment]
请补充完整信息，不是感叹号多了我就重视的，你不给多点信息我是没法追踪。

**Comment by razerdp** [comment]
另外，margin其实也算是在popupwindow内的，对于你来说，仍然是点击在popup内，所以不会触发消失，这不是bug。
