### ISSUE TITLE
NullPointerException: 无法从context处获得Activity，请确保您的Context是否为Activity

### ISSUE THREAD

**Issue by yasaman93** [razerdp/BasePopup#319]
I have a class (TranslationPopup) that extends BasePopupWindow, and I inject that class to the fragments that want to use popup window. Here is TranslationPopup's constructor:

`

@Inject

    public TranslationPopup(@Named(AppModule.BASE_CONTEXT) Context context,
                                  WordTranslationFinder wordTranslationFinder) {

        super(context);
        this.context = context;
        this.wordTranslationFinder = wordTranslationFinder;
        setPopupGravity(Gravity.CENTER)
                .setOutSideTouchable(false)
                .setOutSideDismiss(true)
                .setAutoLocatePopup(true)
                .setMinHeight((int) context.getResources().getDimension(R.dimen.category_header))
                .setBlurBackgroundEnable(false)
                .setShowAnimation(null)
                .setDismissAnimation(null);
    }
`

I don't have any problem with this in my devices and emulators. But I've gotten hundreds of this crash errors in my Firebase:

> Fatal Exception: java.lang.RuntimeException
> Unable to start activity ComponentInfo{MainActivity}: java.lang.NullPointerException: 无法从context处获得Activity，请确保您的Context是否为Activity

I want to know why I get this error and how can I fix this?

The context that I inject into TranslationPopup constructor is my application's context; is it wrong? Can I fix this error by changing the app context to my fragment's activity context?

Thanks for your help

**Comment by razerdp** [comment]
Please follow ISSUE_TEMPLATE for additional information. This issue requires more information, such as library version and system version.

**Comment by yasaman93** [comment]
- System versions according to firebase：
Android 9: 28%
Android 10: 23%
Android 8: 22%
Android 7: 14%
Other : 13%

 - Library version：2.2.3

- Additional information:
It seems that all of the users that got this crash, were in the same situation: We have a media notification in our app for listening music, and users got this crash when they clicked on the media notification and by clicking the notification, they went to our app's fragment which TranslationPopup(extends BasePopupWindow) was injected in it.

**Comment by razerdp** [comment]
When passing in a non-Activity context, BasePopup will try to find the top activity.

code here:
https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/BasePopupWindow.java#L410

It will eventually be called here.
https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/BasePopupSDK.java#L34

We use `ActivityLifecycleCallbacks#onActivityResumed` to get the top Activity, so your crash may be because the top Activity was not found when the Application Context was passed in.

So it is recommended that you replace the Activity's Context, and for Fragment, you can pass in the `fragment.getContext()`

**Comment by yasaman93** [comment]
I think I realized why I got that error. We Inject objects in onAttach event of fragments, but onAttach occurs before onActivityCreated, So when we wanted to create TranslationPopup in onAttach, sometimes it doesn't have the activity context. In order to solve this problem, I decide to create TranslationPopup by calling "new TranslationPopup" instead of injecting.

**Comment by razerdp** [comment]
I noticed that the log is in Chinese, I will replace it with a multilingual one in the next version.

https://github.com/razerdp/BasePopup/blob/dev/lib/src/main/java/razerdp/basepopup/BasePopupWindow.java#L416
