### ISSUE TITLE
在popupwindow中给EditText添加监听事件报错

### ISSUE THREAD

**Issue by q88qaz** [razerdp/BasePopup#320]
报错原因：.beforeTextChanged(java.lang.CharSequence, int, int, int)' on a null object
相关代码：edtKeyBuyNum.addTextChangedListener(new TextWatcher() {
                @Override
                public void beforeTextChanged(CharSequence s, int start, int count, int after) {

                }

                @Override
                public void onTextChanged(CharSequence s, int start, int before, int count) {
                    int i = 0;
                    try {
                        String str = s.toString();
                        if (!Utils.isEmpty(str)) {
                            i = Integer.parseInt(str);
                        }
                    } catch (Exception e) {
                        i = 1;
                    }
                    if (i > MAX_KEY_NUM) {
                        setEdtNum(MAX_KEY_NUM);
                    }
                }

                @Override
                public void afterTextChanged(Editable s) {

                }
            });

**Comment by razerdp** [comment]
请提供完整代码，。

**Comment by razerdp** [comment]
经过我在demo中测试，无法复现你的问题。

所以请你提供详细代码，否则我也不知道你在哪里设置。

![微信截图_20200721155347](https://user-images.githubusercontent.com/11629986/88027958-93828d80-cb6a-11ea-8e38-fc4c1d677b18.png)

**Comment by q88qaz** [comment]
> 经过我在demo中测试，无法复现你的问题。
> 
> 所以请你提供详细代码，否则我也不知道你在哪里设置。
> 
> ![微信截图_20200721155347](https://user-images.githubusercontent.com/11629986/88027958-93828d80-cb6a-11ea-8e38-fc4c1d677b18.png)

作者你好，你试试把 new TextWatcher单独拿出来放在外面定义这种情况，我就是把TextWatcher放在外部才引起这个Exception的

**Comment by razerdp** [comment]
仍然无法重现
![123](https://user-images.githubusercontent.com/11629986/88040038-eb28f500-cb7a-11ea-9227-0622f68f3acd.png)

**Comment by razerdp** [comment]
你是不是继承lazypopup的，如果是继承lazypopup，只有在show的时候才开始inflateview哦

**Comment by q88qaz** [comment]
不是继承lazypopup
你的写法和我说的不一样，你在最外面  TextWatcher mText =  new TextWatcher();
然后在onViewCreated()方法中,ButterKnife.bind(this, contentView);之后，使用edtInput.setTextWatcher(mText);
这个样子，你试试，一定炸！

**Comment by razerdp** [comment]
。。。所以我才说请提供详细代码demo = =同个东西来回描述三次

**Comment by razerdp** [comment]
demo就是butterknife的.

**Comment by razerdp** [comment]
![1](https://user-images.githubusercontent.com/11629986/88044811-cb94cb00-cb80-11ea-9267-11e3ab03b2ee.png)
![2](https://user-images.githubusercontent.com/11629986/88044831-ccc5f800-cb80-11ea-9807-fb1aba5a5e1f.png)

**Comment by q88qaz** [comment]
public class TestPopup extends BasePopupWindow{

   @BindView(R.id.edt_key_buy_num)
    EditText edtKeyBuyNum;

private TextWatcher textWatcher = new TextWatcher() {
                @Override
                public void beforeTextChanged(CharSequence s, int start, int count, int after) {
log.e();
                }

                @Override
                public void onTextChanged(CharSequence s, int start, int before, int count) {
                    log.e();
                }

                @Override
                public void afterTextChanged(Editable s) {
log.e();
                }
            }



 @Override
    public void onViewCreated(@NonNull View contentView) {
        super.onViewCreated(contentView);
        ButterKnife.bind(this, contentView);
edtKeyBuyNum.addTextChangedListener(textWatcher );
}
}

**Comment by razerdp** [comment]
onViewCreated是在父类的构造器中执行的，你的textwatcher是在子类中作为成员变量new的，根据类加载机制，在onViewCreated中，textWatcher是并没有初始化的，也就是你的edittext单纯的addTextChangedListener(null)，由于arraylist确实可以add(null)，所以当你的edittext在回调的时候就会回调给空指针。

这个问题之前我们群里也有人问过，我好像还解释了。

**Comment by razerdp** [comment]
文档已补充：

[onViewCreated(View)](https://www.yuque.com/razerdp/basepopup/yvlq1s)

官方文档参考：

https://docs.oracle.com/javase/specs/jls/se8/html/jls-12.html#jls-12.5

**Comment by q88qaz** [comment]
链接已失效，请问我应该如何解决？

**Comment by razerdp** [comment]
。。隔了大半年才来问= =
你直接升级最新版本吧
