### ISSUE TITLE
setMaxWidth无效

### ISSUE THREAD

**Issue by aowoWolf** [razerdp/BasePopup#321]
>  描述：再popwindow的展示方法之前或者之后调用`setMaxWidth()`方法都无效，宽度始终是和屏幕一样宽  
 
## 分析
现在使用的版本是Release 2.2.4， debug到getLayoutParams方法（下面有代码片段），发现layoutParams的默认宽度一直是-1，match_parent，导致我这里设置的最大宽度并没有实际 变换上去，然后看github上的BasePopupHelper类里面（下面有代码片段加链接），发现虽然width做了一个正数的校验，可是如果默认是matchParent或者wrapParent，还是小于0，那岂不是最大宽度maxWidth又失效了，不知道这算是一个bug还是作者对弹窗在matchParent或者wrapParent的两个场景的时候，不考虑设置maxWidth属性。

---

## Release 2.2.4的版本
以下代码片段
```
    @NonNull
    ViewGroup.MarginLayoutParams getLayoutParams() {
        if (layoutParams == null) {
            int w = popupViewWidth == 0 ? ViewGroup.LayoutParams.MATCH_PARENT : popupViewWidth;
            int h = popupViewHeight == 0 ? ViewGroup.LayoutParams.WRAP_CONTENT : popupViewHeight;
            layoutParams = new ViewGroup.MarginLayoutParams(w, h);
        }
        if (minWidth > 0) {
            layoutParams.width = Math.max(layoutParams.width, minWidth);
        }
        if (minHeight > 0) {
            layoutParams.height = Math.max(layoutParams.height, minHeight);
        }
        if (maxWidth > 0) {
            layoutParams.width = Math.min(layoutParams.width, maxWidth);
        }
        if (maxHeight > 0) {
            layoutParams.height = Math.min(layoutParams.height, maxHeight);
        }
        return layoutParams;
    }

```

## 当前github仓库上版本，
下面这个是Github上的代码片段，[链接](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/BasePopupHelper.java#L587)
```
  ViewGroup.MarginLayoutParams getLayoutParams() {
        if (layoutParams == null) {
            int w = popupViewWidth == 0 ? ViewGroup.LayoutParams.MATCH_PARENT : popupViewWidth;
            int h = popupViewHeight == 0 ? ViewGroup.LayoutParams.WRAP_CONTENT : popupViewHeight;
            layoutParams = new ViewGroup.MarginLayoutParams(w, h);
        }
        if (layoutParams.width > 0) {
            if (minWidth > 0) {
                layoutParams.width = Math.max(layoutParams.width, minWidth);
            }
            if (maxWidth > 0) {
                layoutParams.width = Math.min(layoutParams.width, maxWidth);
            }
        }
```

**Comment by razerdp** [comment]
首先很感谢你的发现，而且追溯到源码简直不要太赞哈哈

其次这个问题在昨晚已经被发现，所以昨晚就发布2.2.4.1了，，readme上也有说明哦~

**Comment by razerdp** [comment]
这个问题是对于群里有位朋友问 width = 20000dp的时候，在dialog中展示是完整的，在basepopup中展示是被裁剪的。

后来在修复的时候就只想着对给定数值的进行修复，从而忘了match\wrap这两个小于0的值，昨晚有人反馈后我连夜修正回来了，感谢提出-V-

**Comment by aowoWolf** [comment]
好的，我刚换成最新的，测试一下，都正常了-。-

**Comment by razerdp** [comment]
另外，对于match_parent/wrap_content的最大、最小限制其实之前的版本都有的，2.2.4改为layoutparam里面判断后我就删掉了，昨晚修复后又加回去了。。。

连接：https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/PopupDecorViewProxy.java#L268

现在对于给定准确值以及match/wrap都可以准确测量

**Comment by aowoWolf** [comment]
哈哈，我一开始只是看代码猜测的，刚刚测试发现正常了，我就正好调试到这里，知道运作正常的原因了。

**Comment by razerdp** [comment]
ya，basepopup最核心的代码其实就是这个decorviewproxy了~

有兴趣可以研读一下，发现bug也欢迎讨论哈哈
