### ISSUE TITLE
showPopup时会使界面进入全屏，dismiss时会退出全屏

### ISSUE THREAD

**Issue by leanderli** [razerdp/BasePopup#322]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively ignored by me!

 - 系统版本（必须）/ System version (required)：android10
 - 库版本（必须）/ Library version (required)：最新
 - 问题描述/重现步骤（必须）/ Problem description or reproduction steps (required)：创建一个自定义popup，showpopup，导航栏和状态栏都将消失类似进入了全屏的状态，dismiss后退出全屏。这样做很不友好。
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 描述请写在这里
> Please write the description here.

**Comment by razerdp** [comment]
你好，我新建了一个工程进行测试，无法复现你说的问题哦，下面是gif

![12342](https://user-images.githubusercontent.com/11629986/88483468-bd88e500-cf9a-11ea-95b4-7c4d33f9430f.gif)

**Comment by razerdp** [comment]
为了重现出你的场景，我特意在onshowing中修改activity的flag，也许能实现你所说的问题。。但是默认情况下是没有问题的，所以你可以检查下activity中是否在焦点变化的时候进行了修改等等。


![55555](https://user-images.githubusercontent.com/11629986/88483559-41db6800-cf9b-11ea-8f4d-9e7b5994e41f.gif)

**Comment by razerdp** [comment]
如果还有疑问，欢迎提供可复现的demo

**Comment by leanderli** [comment]
![image](https://user-images.githubusercontent.com/23739932/88500649-df668400-cffb-11ea-86af-2f01077eba8a.png)
在我的Activity中确实有设置windows 全屏的 flag，但这个是我本身 activity 需要这么做，没理解为啥用你的 popup 会导致这个问题？

**Comment by leanderli** [comment]
![QQ截图20200727112703](https://user-images.githubusercontent.com/23739932/88500737-1f2d6b80-cffc-11ea-97a8-1f311c1705aa.jpg)
在我的Activity中确实有设置windows 全屏的 flag，但这个是我本身 activity 需要这么做，没理解为啥用你的 popup 会导致这个问题？

**Comment by razerdp** [comment]
在全屏下，popup弹出会抢夺焦点，而全屏activity下失去焦点会导致navigationbar或者状态栏弹出来。
因此popup需要先失焦，在弹出后再夺回焦点，此时为了保证popup的windowmanager.layoutparams.flag于宿主（activity）同步，我会读取宿主的flag，设置到自身。

也就是说，你的windowflag会被设置到basepopup中，但不会影响到activity（宿主）的

![微信截图_20200727121803](https://user-images.githubusercontent.com/11629986/88503089-3f145d80-d003-11ea-944a-98b1113db041.png)

**Comment by leanderli** [comment]
那么该如何解决这个问题，我的Activity虽然设置了fullscreen但是由于是stable的状态其实是不会隐藏状态栏和导航栏的只是讲view 显示在了导航栏和状态栏之下，但是Popup貌似没有保持一个stable的状态，而是直接隐藏了导航栏和状态栏，我是想Popup应该保持状态栏和导航栏的

**Comment by razerdp** [comment]
你能抽出一个demo来吗，我想测试一下，有没有必要popup保持跟activity一样的flag。

islight那里随便给个变量就行，不需要那个thememanager，最重要的是activity的theme和flag相关代码需要验证。

**Comment by leanderli** [comment]
可以，等会传上来 1838487641 邮箱：1838487641@qq.com 签名由 网易邮箱大师 定制 在2020年07月27日 12:34，WeiChaoFeng 写道： 你能抽出一个demo来吗，我想测试一下，有没有必要popup保持跟activity一样的flag。 islight那里随便给个变量就行，不需要那个thememanager，最重要的是activity的theme和flag相关代码需要验证。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by leanderli** [comment]
可以，等会传上来

**Comment by leanderli** [comment]
![Screen_Recording_20200727-135950_BasePopupTest_1.gif](https://user-images.githubusercontent.com/23739932/88508547-a0432d80-d011-11ea-9b45-c1c2ffe0deb7.gif)这是demo在我设备的效果

**Comment by leanderli** [comment]
[BasePopupTest.zip](https://github.com/razerdp/BasePopup/files/4980195/BasePopupTest.zip)
这是demo，如上gif，在我的设备上显示popup后是直接隐藏了状态栏和导航栏，在模拟器上貌似是先隐藏了然后马上又显示了

**Comment by razerdp** [comment]
额，看你的问题描述库版本是最新版，我就在我的开发版本上尝试复现，发现无法复现。。。

最后看了你的demo发现你依赖的是2.2.3，实际上最新版是2.2.4.1

**Comment by razerdp** [comment]
在更新日志中bug修复有一项就是针对这个问题的修复的。请更新到最新版

**Comment by razerdp** [comment]
附（本地测试结果，依赖版本 2.2.4.1）：

![ezgif-4-d50fcf06dca5](https://user-images.githubusercontent.com/11629986/88511477-7260e780-d017-11ea-8223-2855d4c84b72.gif)

**Comment by leanderli** [comment]
噗 你更新这么快吗 我也就不久前更新的版本 我先试试

**Comment by razerdp** [comment]
release更新频率一般是在2~6个月
candy更新频率取决于我懒的程度和issue bug的数量

所以可以多点留意开发手册和git的readme哦

**Comment by leanderli** [comment]
感谢！确实已经解决了

**Comment by razerdp** [comment]
ok
