### ISSUE TITLE
【已解决】大家遇到popup窗口无法显示出来的时候可以看看我的解决方法

### ISSUE THREAD

**Issue by q88qaz** [razerdp/BasePopup#325]
【大家遇到popup窗口无法显示出来的时候可以看看我的解决方法】
我的情况是是这样的：
在dialog页面上点击按钮后，popup窗口没有显示出来，但里面的逻辑是正常走的
检查后发现是因为我在dialog里面使用了以下这个方法：
// 内容扩展到导航栏
window.setType(WindowManager.LayoutParams.TYPE_APPLICATION_PANEL);
将这行代码注释后，popup窗口就正常显示出来了
以上，感谢作者

**Comment by razerdp** [comment]
WindowManager.LayoutParams.TYPE_APPLICATION_PANEL
是PopupWindow使用的windowType，如果dialog强行改为这个type，会导致系统识别为subWindow，因此不会给windowToken，没有windowToken，则popupwindow是无法弹出来的。

如无意外，在你现实的时候会被basepopup捕捉到这个exception，你可以覆写onShowError捕捉所有basepopup遇到的异常。

**Comment by razerdp** [comment]
问题已补充。
https://www.yuque.com/razerdp/basepopup/dgf6ry#8Va0z

**Comment by razerdp** [comment]
另外，希望你以后提issue能根据issue要求提交，一般情况下，我对于没有按照issue模板要求提交的issue都会直接忽略并关闭。
