### ISSUE TITLE
隐藏沉浸式状态栏，basepop布局底部有edittext，点击edittext无法弹出软键盘

### ISSUE THREAD

**Issue by huwencheng** [razerdp/BasePopup#327]
- 系统版本：android 10
 - 库版本：2.2.3
 - 问题描述/重现步骤：隐藏沉浸式状态栏，basepop布局底部有edittext，点击edittext无法弹出软键盘

**Comment by razerdp** [comment]
candy分支已经修过了哦

https://github.com/razerdp/BasePopup/tree/dev#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97-%E5%8E%86%E5%8F%B2%E6%9B%B4%E6%96%B0

**Comment by huwencheng** [comment]
隐藏沉浸式状态栏方法采用BlankJ工具类的方法： BarUtils.setStatusBarVisibility(this, false)  ，Blankj工具类git地址：https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/README-CN.md

**Comment by huwencheng** [comment]
好的，我先试下哦，没问题的话我一会关掉该提问

**Comment by huwencheng** [comment]
试了下不行哦，看了下你修复的是隐藏底部的导航栏导致的问题，我描述的是头部的沉浸式状态栏导致的问题

**Comment by huwencheng** [comment]
@razerdp 有空帮忙看下****

**Comment by razerdp** [comment]
请提供demo。

**Comment by huwencheng** [comment]
@razerdp 麻烦提供下邮箱地址，一会发到你邮箱哦

**Comment by razerdp** [comment]
文件拖到github issue这就行了。

**Comment by huwencheng** [comment]
[PopApplication.zip](https://github.com/razerdp/BasePopup/files/4993344/PopApplication.zip)
@razerdp 辛苦帮忙看下问题，感谢

**Comment by razerdp** [comment]
那个，，你用candy试试吧，我上面已经说了candy已经修复了，demo中你依然用2.2.4.1测试当然是有问题的、

**Comment by razerdp** [comment]
附测试过程：
![ezgif-4-289bf048a353](https://user-images.githubusercontent.com/11629986/88775699-99eeb600-d1b7-11ea-86cb-771facc421d2.gif)

**Comment by huwencheng** [comment]
麻烦作者了，确实可以

**Comment by huwencheng** [comment]
引入candy的时候项目会报错，但是在自己建的demo引入不会报错，自己的项目引入2.2.3不会报这个问题，报错信息：ERROR: Failed to resolve: BasePopup_Candy
Affected Modules: Login, app, im, libservice, libtcbeauty, libtcugckit, module_base_pay, module_base_share, module_buz_tencent_live, modulebuzcollege, modulebuzshop, modulebuztcvideo

**Comment by razerdp** [comment]
请查看readme->注意事项

其次请检查candy依赖是否写错了

**Comment by huwencheng** [comment]
对比确认了下，写法没错，implementation 'com.github.razerdp:BasePopup_Candy:2.2.5.0725'，但是com.github.razerdp:BasePopup:2.2.3是没问题的，奇怪，不过demo引用确实没啥问题，不知道哪里影响到了，更新到candy就不行

**Comment by huwencheng** [comment]
项目已经支持androidx

**Comment by razerdp** [comment]
这就要看看你的工程配置了，尽量吧mavenCentral挪到jcenter之前

**Comment by huwencheng** [comment]
确实是maven顺序问题，感谢
