### ISSUE TITLE
在软键盘显示的时候，弹出popup会导致软键盘消失

### ISSUE THREAD

**Issue by smileToWxm** [razerdp/BasePopup#329]
在页面点击输入框弹起软键盘，此时点击其他地方弹起popup会导致软键盘消失，而导致定位到某个view的位置错乱，有没有好的方式解决？

**Comment by razerdp** [comment]
请按照issue规范提issue，该问题先被忽略。

**Comment by palorotolo** [comment]
同样遇到

**Comment by razerdp** [comment]
> 同样遇到

请看最新版本的更新日志

**Comment by kanfRUI** [comment]
使用了最新版本的3.2.0，使用了这个api，hideKeyboardOnShow（false）；如果点击输入框弹起软键盘，这时再点击其他地方弹起popup，会出现一个先关闭键盘，再打开键盘的问题？
