### ISSUE TITLE
setBackPressEnable(true)  没用

### ISSUE THREAD

**Issue by NikoSoftware** [razerdp/BasePopup#33]
我想返回键不取消 popwindow 设置了这个参数但是没用

**Comment by flyjiang2014** [comment]
好像设定true 和 false 都没效果

**Comment by NikoSoftware** [comment]
模拟器设置了，也没用

**Comment by razerdp** [comment]
@NikoSoftware 

有没有具体的代码，或者其实您可以进行调试。。。

以及是否会是特定的api或系统版本导致的，如果您能帮忙排查，万分感谢-V-

**Comment by Mr-PolarBear** [comment]
@razerdp   你好     setBackPressEnable(false)  无效   
我在红米6.0   华为6.0  魅族5.1系统上测试不能拦截返回按钮

**Comment by razerdp** [comment]
@Mr-PolarBear 
@NikoSoftware 
@flyjiang2014 

对于Android M以上暂时无法修复呢。。。残念（首页README已经补充）

https://github.com/razerdp/BasePopup/blob/master/%E5%85%B3%E4%BA%8EAndorid%20M%E4%BB%A5%E4%B8%8AsetBackPressEnable()%E5%A4%B1%E6%95%88%E7%9A%84%E9%97%AE%E9%A2%98%E7%9A%84%E5%88%86%E6%9E%90.md

**Comment by zl277287818** [comment]
@Override
    public boolean onBeforeDismiss() {
        return false;
    }

**Comment by zl277287818** [comment]
@Override
    public boolean onBeforeDismiss() {
        if (canBack) {
            return true;
        } else {
            return false;
        }
    }

自己用一个变量去控制，完美解决

**Comment by razerdp** [comment]
@zl277287818 

啊哈，也可以的（虽然不太完美）。。。我都忘了我写过这个回调了- -我现在就加到readme里面

**Comment by razerdp** [comment]
@zl277287818 

不过这个方法有个问题，因为beforeDismiss会直接影响到完整的dismiss()流程，如果我只需要返回键不dismiss而点其他地方可以dismiss，这个方法就可能需要一个方法来提前把canBack改变以适应不同的需要，所以并不是非常完美哦

**Comment by zl277287818** [comment]
是的，不是很完美，现在finish页面的时候，我就是先set成true再dismiss... 不然泄露。不过可以临时解决一下项目需求。

**Comment by lapDog** [comment]
![image](https://user-images.githubusercontent.com/11813246/34042763-2b0cfe8e-e1d9-11e7-954a-8f4991b3dc4c.png)
这么解决也是可以的。。。(ง •_•)ง

**Comment by razerdp** [comment]
@lapDog 是的，在activity下捕捉是可以的哈哈，只是如果想从popu内部捕捉，目前来说除非能拿到popup内部的那个framelayout，否则似乎没啥办法呢

**Comment by JadynChan** [comment]
同时加多一个条件　mPopupWindow.setFocusable(true);就可以按返回键关闭了

**Comment by zhupengxiang** [comment]
这个onBrforeDismiss怎么解决的返回键问题 没怎么看懂

**Comment by razerdp** [comment]
@zhupengxiang 在activity给beforeDismiss回调，在activity捕捉keyevent,或者backpress从而决定popupwindow是否返回关闭

**Comment by razerdp** [comment]
@NikoSoftware 
@flyjiang2014 
@Mr-PolarBear 
@zl277287818 
@JadynChan 
@zhupengxiang 

感谢你们的讨论和idea~在1.8.9里面我用了一种新的思路去解决这个问题，建议大家升级到1.8.9

具体解决方式：[1.8.9 解决方案](https://github.com/razerdp/BasePopup/blob/master/%E5%85%B3%E4%BA%8EAndorid%20M%E4%BB%A5%E4%B8%8AsetBackPressEnable()%E5%A4%B1%E6%95%88%E7%9A%84%E9%97%AE%E9%A2%98%E7%9A%84%E5%88%86%E6%9E%90.md#189-%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)

如果大家有更完美的解决方案，欢迎继续探讨哦~

本issue不关闭。

**Comment by xxxifan** [comment]
这个设置在SDK 36又无效了，pull request中有热心开发者提交了https://github.com/razerdp/BasePopup/pull/517，希望早日能修复。

**Comment by razerdp** [comment]
> 这个设置在SDK 36又无效了，pull request中有热心开发者提交了[https://github.com/razerdp/BasePopup/pull/517，希望早日能修复。](https://github.com/razerdp/BasePopup/pull/517%EF%BC%8C%E5%B8%8C%E6%9C%9B%E6%97%A9%E6%97%A5%E8%83%BD%E4%BF%AE%E5%A4%8D%E3%80%82)

感谢您的提醒，我已经处理了pr，最近看到github提示消息我才意识到我还有个项目好久没维护了！之前的一些issue也处理一下。

不过我脱离安卓圈一段时间了，可能只能处理一些大家要求的api公开等问题。包括maven发布还得重新看一下。。。

**Comment by zhupengxiang** [comment]
@razerdp  终于看到更新了 不容易

**Comment by razerdp** [comment]
> [@razerdp](https://github.com/razerdp) 终于看到更新了 不容易

说实话，确实很少看git，所以一直都给忽略了，我的锅。。。不过现在回来更新我可能都不如你们熟悉这个项目了。。。
