### ISSUE TITLE
【急】在手机红米8A上，背景阴影无法覆盖全屏幕

### ISSUE THREAD

**Issue by q88qaz** [razerdp/BasePopup#330]
### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：9.0
 - 库版本（必须）/ Library version (required)：2.2.3
 - 手机机型（必须）/ phone model(required)：红米手机8A
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：无
 - 报错信息（可选）/ Error reporting information (optional)：无

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
页面采用的是Activity放置ViewPager嵌套三个Fragment的布局
点击Fragment中的按钮后弹出Dialog，再点击Dialog中的按钮后弹出BasePopup
发现的问题是：弹出BasePopup阴影背景不能全屏覆盖，仅能覆盖到Fragment所在区域

**Comment by q88qaz** [comment]
BasePopup无法延伸至全屏

**Comment by razerdp** [comment]
麻烦上图，以及你的basepopup构造器用的哪个

**Comment by razerdp** [comment]
另外，最新版本是 2.2.4.1 ，更新后再试试？

**Comment by q88qaz** [comment]
公司的项目不方便上图，感谢作者理解，我画一下吧

**Comment by q88qaz** [comment]
[https://ftp.bmp.ovh/imgs/2020/08/a88bb37c909b6732.png](url)

**Comment by q88qaz** [comment]
我发现当我把Dialog高度设置为MATCH_PARENT后，弹出的BasePopup阴影可以全屏覆盖
但是当Dialog为固定高度时，弹出的BasePopup阴影无法全屏覆盖，背景阴影没有延伸至activity内容区以及状态栏

**Comment by razerdp** [comment]
是的，popup会依赖宿主的window，dialog有自己的window，所以popup最大可显示范围也就是你的window大小了，所以如果你的dialog固定宽高，那么window宽高也就固定了，所以basepopup无法全覆盖

**Comment by q88qaz** [comment]
如果我把Activity实例传递给BasePopup能否实现全屏覆盖并且层级置于Dialog上方？

**Comment by razerdp** [comment]
能覆盖，但不能置于dialog上方。

还是那句，你得知道你的宿主是谁，如果是activity，那么宿主是act所在的层级，而dialog位于act层级之上，所以无法覆盖dialog。

而如果宿主是dialog，则受dialog所在window的限制，所以你最好的做法应该是dialog matchparent，然后内容显示自行限制大小。

**Comment by razerdp** [comment]
这个问题挺无解的，毕竟popup没有自己的window，如果我强行写了window，那么我这个就不是popup而是dialog了。

当然，不排除以后提供dialog模式

**Comment by q88qaz** [comment]
感谢解答，我再找找能否曲线救国的法子

**Comment by razerdp** [comment]
嗯嗯，这个问题我关闭了~

稍后补充到文档里

**Comment by q88qaz** [comment]
后续有任何解决方案我会在这里补充，请作者先不要关闭此问题

**Comment by razerdp** [comment]
更新到candy最新版试试？

普通dialog的wm其实仍然是activity的wm。
