### ISSUE TITLE
部分手机在dialog中使用basePopup，无法全屏，导致弹窗位置下移

### ISSUE THREAD

**Issue by xxjy** [razerdp/BasePopup#331]
- 系统版本（必须）/ System version (required)：vivo Y83A 8.1.0
 - 库版本（必须）/ Library version (required)：2.2.4
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：![Screenshot_20200805_150918](https://user-images.githubusercontent.com/8044264/89383498-29074b00-d72f-11ea-9766-4d7504c1fa59.jpg)
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
示例代码，CommonBottomSheetDialogInfo类中的代码
`mDemoPopup.showPopupWindow();`
改为
`mDemoPopup.setPopupGravity(BasePopupWindow.GravityMode.ALIGN_TO_ANCHOR_SIDE, Gravity.TOP | Gravity.CENTER_HORIZONTAL);
 mDemoPopup.showPopupWindow(tvShow);`
如图所示，弹窗位置下移了状态栏的高度。

**Comment by razerdp** [comment]
emmm

这种特殊机子，，特别是华为、ov这三家的奇葩ROM，并不好适配，，其次我没有这台机子= =没法去debug的说

但模拟器8.1莫得问题

**Comment by xxjy** [comment]
> emmm
> 
> 这种特殊机子，，特别是华为、ov这三家的奇葩ROM，并不好适配，，其次我没有这台机子= =没法去debug的说
> 
> 但模拟器8.1莫得问题

是的，找不到全屏的办法，我这边测的也是只有这台vivo有问题；
针对这种不能全屏的问题，DecorView在layout的时候可以考虑相对屏幕的问题，因为AnchorView的位置计算也是相对屏幕的，我这边改了一下是可以解决弹窗位置下移的问题。

**Comment by razerdp** [comment]
pr已经回复。

另外，我希望你能提供你修复之前出现问题的layoutinspector的文件，直接拖到评论框上传即可，我想看看具体的ui、参数问题

**Comment by xxjy** [comment]
> pr已经回复。
> 
> 另外，我希望你能提供你修复之前出现问题的layoutinspector的文件，直接拖到评论框上传即可，我想看看具体的ui、参数问题

压缩了，不然不给上传
[razerdp.basepopup_2020.08.05_16.54.zip](https://github.com/razerdp/BasePopup/files/5027247/razerdp.basepopup_2020.08.05_16.54.zip)

**Comment by razerdp** [comment]
那个，你加下微信 razerdp_test，然后我拉你进群讨论一下》

**Comment by razerdp** [comment]
无法铺满屏幕是由于宿主的window无法铺满导致的，位置下移同理。

不过在2.2.5中已经优化了获取anchor的位置，保证两者参考系一致

**Comment by razerdp** [comment]
详见candy 2.2.5.0806

**Comment by razerdp** [comment]
release 2.2.5已经发布，请更新到最新版
