### ISSUE TITLE
横屏模式下的popupwindow跳转竖屏返回后ui会被放大

### ISSUE THREAD

**Issue by androiddream** [razerdp/BasePopup#333]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：andorid 6.0
 - 库版本（必须）/ Library version (required)：2.2.4.1
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：横屏模式下的popupwindow，点击里面的view 跳转一个竖屏activity，返回之后再显示popup，ui会变大
![aWEvvQ.png](https://s1.ax1x.com/2020/08/07/aWEvvQ.png)
![aWEzuj.png](https://s1.ax1x.com/2020/08/07/aWEzuj.png)

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

**Comment by razerdp** [comment]
点击跳转前会dismiss popup吗，以及popup内部是否有其他逻辑

**Comment by androiddream** [comment]
> 点击跳转前会dismiss popup吗，以及popup内部是否有其他逻辑

点击跳转已经调用dismiss，popup内部还设置了一些点击事件的回调，
    @Override
    public View onCreateContentView() {
    	if (contextView==null){
			contextView = createPopupById(R.layout.popup_live_user_info);
			initView();
		}
    	return contextView;
    }

**Comment by androiddream** [comment]
谢谢大佬我改好了，不要每次去new就行了 @razerdp ，开始用构造方法传值，现在set传值就好了

**Comment by razerdp** [comment]
噢，你是不是还用了类似头条的适配，因为density导致的。

**Comment by androiddream** [comment]
> 噢，你是不是还用了类似头条的适配，因为density导致的。

没有
