### ISSUE TITLE
关于databinding的tips

### ISSUE THREAD

**Issue by SmallDream** [razerdp/BasePopup#334]
查了下历史issue, 由于要使用createPopupById，暂不支持databinding。
但其实目前的项目已经可以通过一些其他方法来支持databinding.  
使用DataBindingUtil.bind(getContentView())就可以使用databinding了。
```
public MyPop(Context context, Goods goods) {
        super(context);
        PopMyBinding binding = DataBindingUtil.bind(getContentView());

        ...
    }

    @Override
    public View onCreateContentView() {
        return createPopupById(R.layout.pop_my);
    }
```

**Comment by razerdp** [comment]
ya，其实很早之前就加了 创建view之后的回调方法了：
`onViewCreated()`

demo中我的butterknife也是在那绑定的，所以databinding也可以

相关issue：

https://github.com/razerdp/BasePopup/issues/232

相关文档：

https://www.yuque.com/razerdp/basepopup/yvlq1s
