### ISSUE TITLE
OPPO R9使用会崩溃

### ISSUE THREAD

**Issue by xiongxiangdong** [razerdp/BasePopup#335]
- 系统版本（必须）/ System version (required)：OPPO R9s Plus
 - 库版本（必须）/ Library version (required)：2.2.4.1
 - 报错信息如下
   Runtime(26212): Shutting down VM
08-08 15:05:38.689 E/AndroidRuntime(26212): FATAL EXCEPTION: main
08-08 15:05:38.689 E/AndroidRuntime(26212): Process: me.jessyan.mvparms.demo, PID: 26212
08-08 15:05:38.689 E/AndroidRuntime(26212): java.lang.IncompatibleClassChangeError: Couldn't find me.jessyan.mvparms.demo.mvp.ui.activity.UserActivity.lambda$initData$0[class android.view.View]
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at libcore.reflect.AnnotationAccess.indexToMethod(AnnotationAccess.java:608)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at libcore.reflect.AnnotationAccess.getEnclosingMethodOrConstructor(AnnotationAccess.java:405)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at java.lang.Class.isLocalClass(Class.java:1533)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at java.lang.Class.getCanonicalName(Class.java:363)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at androidx.lifecycle.Lifecycling.resolveObserverCallbackType(Lifecycling.java:152)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at androidx.lifecycle.Lifecycling.getObserverConstructorType(Lifecycling.java:145)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at androidx.lifecycle.Lifecycling.lifecycleEventObserver(Lifecycling.java:82)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.<init>(LifecycleRegistry.java:354)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:170)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at razerdp.basepopup.BasePopupWindow.bindLifecycleOwner(BasePopupWindow.java:434)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:420)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:378)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:374)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at me.jessyan.mvparms.demo.mvp.ui.popup.BottomPopup.<init>(BottomPopup.java:13)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at me.jessyan.mvparms.demo.mvp.ui.activity.UserActivity$1.<init>(UserActivity.java:111)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at me.jessyan.mvparms.demo.mvp.ui.activity.UserActivity.lambda$initData$0$UserActivity(UserActivity.java:111)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at me.jessyan.mvparms.demo.mvp.ui.activity.-$$Lambda$UserActivity$TW_nnbrR8TY4_4IkECWIUrz5q2k.onClick(lambda)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at android.view.View.performClick(View.java:4848)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at android.view.View$PerformClick.run(View.java:20300)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at android.os.Handler.handleCallback(Handler.java:815)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at android.os.Handler.dispatchMessage(Handler.java:104)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at android.os.Looper.loop(Looper.java:210)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at android.app.ActivityThread.main(ActivityThread.java:5809)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at java.lang.reflect.Method.invoke(Native Method)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at java.lang.reflect.Method.invoke(Method.java:372)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
08-08 15:05:38.689 E/AndroidRuntime(26212): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
08-08 15:05:38.693 W/ActivityManager(  898):   Force finishing activity 1 me.jessyan.mvparms.demo/.mvp.ui.activity.UserActivity
08-08 15:05:38.704 V/WindowManager(  898): Changing focus from Window{1346b3bd u0 me.jessyan.mvparms.demo/me.jessyan.mvparms.demo.mvp.ui.activity.UserActivity} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:4752 com.android.server.am.ActivityManagerService.setFocusedActivityLocked:2990 com.android.server.am.ActivityStack.adjustFocusedActivityLocked:3125 com.android.server.am.ActivityStack.finishActivityLocked:3436 
08-08 15:05:38.705 D/DropBoxManagerService(  898): file :: /data/system/dropbox/data_app_crash@1596870338705.txt
08-08 15:05:38.706 I/WindowManager(  898): Losing focus: Window{1346b3bd u0 me.jessyan.mvparms.demo/me.jessyan.mvparms.demo.mvp.ui.activity.UserActivity}

**Comment by razerdp** [comment]
basepopup 2.2.2.2 之后只支持androidx哦

**Comment by xiongxiangdong** [comment]
用了那个MVPArms框架,估计有冲突吧.我直接安装BasePopup没问题

**Comment by razerdp** [comment]
单独使用没问题就妥妥的~其他框架我这边没有义务去适配哦-V-
