### ISSUE TITLE
部分华为手机 横屏状态无法弹出pop

### ISSUE THREAD

**Issue by SmallDream** [razerdp/BasePopup#336]
- 系统版本（必须）/ System version (required)：Android9 / Android 8.10
 - 库版本（必须）/ Library version (required)：2.2.4.1
- 手机 ：华为畅享9plus、荣耀8C

activity横屏时，无法弹起pop(有背景阴影，但看不见pop). 
2.2.3无此问题， 其他手机暂未发现此问题

**Comment by SmallDream** [comment]
在固定位置，在底部，archorview的方式都无法显示

**Comment by razerdp** [comment]
我看看

**Comment by SmallDream** [comment]
> 我看看

我看了下，没有错误日志。 背景阴影显示了。 就是看不见弹窗内容。
点空白处阴影也会正常消失。

**Comment by razerdp** [comment]
问题已查明，谁能想到。。。navigationbar的问题：

![微信截图_20200811112645](https://user-images.githubusercontent.com/11629986/89854107-9ac71500-dbc5-11ea-8d52-6161ae52a153.png)

**Comment by razerdp** [comment]
但这是模拟器的情况，真实情况下大多数navigationbar在横屏后，都是在下方而非左右。

**Comment by razerdp** [comment]
这块我看看做下适配吧

**Comment by SmallDream** [comment]
多谢解决问题。我这边暂时先回退到旧版本了。
等更新后我再来升级。

这个库用起来很方便，期待越来越好

**Comment by razerdp** [comment]
candy修复已发布，请查验：

  * **2.2.5.0811** (2020/08/11)
    * 重构layout逻辑，针对NavigationBar奇怪的方向适配 [#336](https://github.com/razerdp/BasePopup/issues/336)
    * 修复键盘GlobalListener提前被remove，导致popup在第二次弹出才能适配键盘的问题 [#338](https://github.com/razerdp/BasePopup/issues/338)

**Comment by SmallDream** [comment]
> candy修复已发布，请查验：
> 
> * **2.2.5.0811** (2020/08/11)
>   
>   * 重构layout逻辑，针对NavigationBar奇怪的方向适配 [#336](https://github.com/razerdp/BasePopup/issues/336)
>   * 修复键盘GlobalListener提前被remove，导致popup在第二次弹出才能适配键盘的问题 [#338](https://github.com/razerdp/BasePopup/issues/338)

弹窗内容无法显示的问题修复了。
不过以前的一个旧bug出现了，横屏pop位置有偏移(archor, Gravity.TOP | Gravity.CENTER_HORIZONTAL,  实际弹窗位置偏左 )。
不知道是不是是刘海引起的，之前2.2.3也有这个Bug，2.2.4.1修复了。 这个补丁 2.2.5.0811 又出现这个问题了

**Comment by razerdp** [comment]
这个版本重构了这一块的定位问题，所以可能会有些bug，不过candy就是为了放出来测试的，测试完成后才发的release，所以需要及时反馈~

**Comment by razerdp** [comment]
当navigationbar在右侧的时候是正常的：

![微信截图_20200811175940](https://user-images.githubusercontent.com/11629986/89884885-c3b6cc80-dbfc-11ea-8fb2-74ad0d72566c.png)
![微信截图_20200811180042](https://user-images.githubusercontent.com/11629986/89884890-c4e7f980-dbfc-11ea-94b0-ea868b5e3b50.png)


在左侧的时候就体现出你所说的偏左：
![微信截图_20200811180137](https://user-images.githubusercontent.com/11629986/89884908-cd403480-dbfc-11ea-9178-a763c54cd94d.png)

**Comment by razerdp** [comment]
candy版本：2.2.5.0811.1

再次修复。

![111](https://user-images.githubusercontent.com/11629986/89885495-bbab5c80-dbfd-11ea-9694-d59880052d32.png)
![222](https://user-images.githubusercontent.com/11629986/89885496-bcdc8980-dbfd-11ea-9938-dc48cf4a9643.png)

**Comment by SmallDream** [comment]
> candy版本：2.2.5.0811.1
> 
> 再次修复。

测试机型：华为畅享9plus
测试版本：2.2.5.0811.1
API版本：28

最新版还是存在横屏状态pop向左偏移的情况。（archor , Gravity.TOP | Gravity.CENTER_HORIZONTAL）。
测试机为刘海机型，横屏时左侧刘海部分不显示UI（包括刘海旁边可显示区域也是黑的）。应该是系统为了适配横屏，干脆把整个左侧留黑了。  右侧为三大金刚虚拟按键（可在系统设置里改为全面屏手势），不过无论是否显示三大金刚键，都会存在偏移问题。

**Comment by SmallDream** [comment]
![20200812094654](https://user-images.githubusercontent.com/6036660/89967125-3b2f3f00-dc83-11ea-9650-8eb941792ba9.png)
红框区域为avtivity界面显示区域

**Comment by razerdp** [comment]
经过检查。。。发现在横屏状态下，刘海屏在左边，而且系统居然就一条大黑边。。。。也是醉了= =

现在已经针对横屏和竖屏情况进行适配。

请更新到 candy 2.2.5.0812查验

**Comment by SmallDream** [comment]
> 经过检查。。。发现在横屏状态下，刘海屏在左边，而且系统居然就一条大黑边。。。。也是醉了= =
> 
> 现在已经针对横屏和竖屏情况进行适配。
> 
> 请更新到 candy 2.2.5.0812查验

已在问题机型测试，无偏移，一切正常，感谢作者

**Comment by razerdp** [comment]
ok，请勿关闭，待发布release后会统一回复并关闭问题。

这个问题影响较大，今天再测试后就会发布release

**Comment by razerdp** [comment]
release 2.2.5已经发布，请更新到最新版
