### ISSUE TITLE
布局ui中存在NestedScrollView 时  高度会被强制全屏 做不到显示在设置的anchorView关联位置

### ISSUE THREAD

**Issue by wuxuebai** [razerdp/BasePopup#337]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ 9.0：
 - 库版本（必须）/ 2.2.4.1:
![Screenshot_2020-08-11-11-55-53-609_com yishi [](cars](https://user-images.githubusercontent.com/17443101/89855705-d368ed80-dbc9-11ea-96f1-d24f37080381.png))

 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

 #布局ui中存在NestedScrollView 时  高度会被强制全屏 做不到显示在设置的anchorView关联位置
以下是代码截取片段
        CarFilterPopup filterPopup = new CarFilterPopup(mContext);
        filterPopup.setRecyclerView();
        filterPopup.showPopupWindow(ancherView);
        filterPopup.setPopupGravity(BasePopupWindow.GravityMode.RELATIVE_TO_ANCHOR, Gravity.BOTTOM | Gravity.RIGHT);

**Comment by razerdp** [comment]
可以上图吗。。。仅凭代码我不知道你具体说的是什么。。。

**Comment by wuxuebai** [comment]
![Screenshot_2020-08-11-11-55-53-609_com yishi cars](https://user-images.githubusercontent.com/17443101/89857404-8d625880-dbce-11ea-8888-b790162c5fbe.png)

**Comment by wuxuebai** [comment]
标题栏所在的view是anchorView  在布局中没有scrollerview时  显示的位置和高度是正常的 但是如果存在scrollerview  高度就会被强制全屏

**Comment by wuxuebai** [comment]
@razerdp

**Comment by razerdp** [comment]
0.0 怎么close了

**Comment by wuxuebai** [comment]
我把xml文件中的根本局的layout_height设置成match_parent就没有那种情况了,所以就关闭了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "razerdp/BasePopup"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 下午2:10
收件人:&nbsp;"razerdp/BasePopup"<BasePopup@noreply.github.com&gt;;
抄送:&nbsp;"飘飘吹雪"<283028193@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [razerdp/BasePopup] 布局ui中存在NestedScrollView 时  高度会被强制全屏 做不到显示在设置的anchorView关联位置 (#337)





 
0.0 怎么close了

**Comment by razerdp** [comment]
噢噢，其实我猜测到原因是什么了。。

因为NestedScrollView 的测量模式是UNSPECIFIED，所以它会不断的填充下去，导致高度超过了。

而由于你是跟anchor关联，当现实超过屏幕后，就会尝试往反方向进行位移修正以保证完整显示，但是由于实在超过太多了，所以就把相反方向的位移全部用完了，因此就是你所看到的“match_parent”

而把高度改为match_parent的话，basepopup会填充剩余可用的空间。


事实上，wrap_content的话还有一个api可以用：

```java
    /**
     * 是否允许BasePopup自动调整大小
     * <p>
     * 在{@link #setClipToScreen(boolean)}为true的情况下，BasePopup会针对剩余空间来调整Popup的大小，因此可能出现实际显示过小的情况
     */
    public BasePopupWindow setFitSize(boolean canResize)
```

**Comment by wuxuebai** [comment]
哈哈，谢谢解答，虽然不是太懂，但是知道原因和解决方法了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "razerdp/BasePopup"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 下午2:16
收件人:&nbsp;"razerdp/BasePopup"<BasePopup@noreply.github.com&gt;;
抄送:&nbsp;"飘飘吹雪"<283028193@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [razerdp/BasePopup] 布局ui中存在NestedScrollView 时  高度会被强制全屏 做不到显示在设置的anchorView关联位置 (#337)





 
噢噢，其实我猜测到原因是什么了。。
 
因为NestedScrollView 的测量模式是UNSPECIFIED，所以它会不断的填充下去，导致高度超过了。
 
而由于你是跟anchor关联，当现实超过屏幕后，就会尝试往反方向进行位移修正以保证完整显示，但是由于实在超过太多了，所以就把相反方向的位移全部用完了，因此就是你所看到的“match_parent”
 
而把高度改为match_parent的话，basepopup会填充剩余可用的空间。
 
事实上，wrap_content的话还有一个api可以用：
     /**      * 是否允许BasePopup自动调整大小      * <p&gt;      * 在{@link #setClipToScreen(boolean)}为true的情况下，BasePopup会针对剩余空间来调整Popup的大小，因此可能出现实际显示过小的情况      */     public BasePopupWindow setFitSize(boolean canResize)
