### ISSUE TITLE
输入法适配，弹出pop后，点击外部取消pop,然后再点，弹出时pop就会被输入法就会遮挡住。只有先手动关闭软键盘，再关闭pop,下次才能弹出才不会被遮挡。

### ISSUE THREAD

**Issue by xiayuyu** [razerdp/BasePopup#338]
- 系统版本（必须）/ System version (required)：魅族16X android 8.1.0  魅族16S android9 vivoZ3X android9
 - 库版本（必须）/ Library version (required)：:2.2.4.1

**Comment by razerdp** [comment]
got

demo已经复现，应该是某个标志位没给我复原的问题，稍后修复

**Comment by xiayuyu** [comment]
嗯，好的

**Comment by razerdp** [comment]
candy修复已发布，请查验：

  * **2.2.5.0811** (2020/08/11)
    * 重构layout逻辑，针对NavigationBar奇怪的方向适配 [#336](https://github.com/razerdp/BasePopup/issues/336)
    * 修复键盘GlobalListener提前被remove，导致popup在第二次弹出才能适配键盘的问题 [#338](https://github.com/razerdp/BasePopup/issues/338)

**Comment by razerdp** [comment]
release 2.2.5已经发布，请更新到最新版
