### ISSUE TITLE
横屏fragment不能全屏，Activity可以

### ISSUE THREAD

**Issue by androiddream** [razerdp/BasePopup#339]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：vivo X20  andorid8.1
 - 库版本（必须）/ Library version (required)：   2.2.4.1
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：![123](http://chuantu.xyz/t6/740/1597285945x992249049.jpg)

 - 报错信息（可选）/ Error reporting information (optional)： 不能拉满全屏

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

activity横屏可以拉满，fragment里面不能铺满，底部有空缺

**Comment by razerdp** [comment]
请更新到 candy 2.2.5.0812 试试

近期针对横屏的各种蛋疼的问题进行过修复

**Comment by androiddream** [comment]
呜呜，我自己瞎改了一下好了
