### ISSUE TITLE
activity 的OnCreate 里面初始化popWindows并实现报错

### ISSUE THREAD

**Issue by NikoSoftware** [razerdp/BasePopup#34]
07-22 09:06:27.340 12139-12139/com.westarsoft.subway E/BasePopupWindow: show error
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err:     at android.view.ViewRootImpl.setView(ViewRootImpl.java:567)
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err:     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err:     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err:     at android.widget.PopupWindow.invokePopup(PopupWindow.java:1258)
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err:     at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1032)
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err:     at android.widget.PopupWindow.showAtLocation(PopupWindow.java:995)
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err:     at com.example.framelib.basepopup.BasePopupWindow.tryToShowPopup(BasePopupWindow.java:297)
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err:     at com.example.framelib.basepopup.BasePopupWindow.showPopupWindow(BasePopupWindow.java:256)
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err:     at com.example.framelib.activtiy.BaseActivity.showProgressDialog(BaseActivity.java:190)
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err:     at com.example.framelib.activtiy.BaseActivity.showProgressDialog(BaseActivity.java:176)
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err:     at com.westarsoft.subway.activity.education.DailyQuestionActivity.setupViews(DailyQuestionActivity.java:76)
07-22 09:06:27.340 12139-12139/com.westarsoft.subway W/System.err:     at com.example.framelib.activtiy.BaseActivity.onCreate(BaseActivity.java:38)

**Comment by razerdp** [comment]
onCreate中，activity并不一定已经显示出来，也就是windowToken不一定有，所以如果要在onCreate中show出popup，建议延迟。
ps，这个错误是被捕捉的，不会导致崩溃

**Comment by NikoSoftware** [comment]
你好你的问题我帮你解决了，希望能帮助你解决activity 没完全启动的问题。
 mProgressDialog = new PopProgressDialog((Activity) mContext);
            mProgressDialog.setBackPressEnable(false);
            mProgressDialog.setPopupWindowFullScreen(true);
            this.findViewById(android.R.id.content).post(new Runnable() {
                @Override
                public void run() {
                    mProgressDialog.showPopupWindow();
                }
            });
