### ISSUE TITLE
请问想要在自定义application弹出全局的dialog该怎么做呢?

### ISSUE THREAD

**Issue by roybill** [razerdp/BasePopup#340]

**Comment by razerdp** [comment]
你好，传入application的context即可，弹出的时候会获取栈顶activity弹出的。

**Comment by roybill** [comment]
这样怎么改才可以弹出来呢?
`public class BaseApplication extends Application {

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

    @Override
    public void onCreate() {
        super.onCreate();
        sApp = this;
        application = this;
        UserManager.init(this);

        new DemoPopup(getApplicationContext()).showPopupWindow();//这两行都不行
//        new DemoPopup(getContext()).showPopupWindow();
    }

	//...简化代码

}
`
控制台错误提示:
java.lang.RuntimeException: Unable to create application com.lj.lanfanglian.base.BaseApplication: java.lang.NullPointerException: 无法从context处获得Activity，请确保您的Context是否为Activity

**Comment by razerdp** [comment]
噢，如果你是在Application中弹窗的话，因为没有栈顶Activity，所以确实无法弹出来。。。至少得有一个Activity才能弹窗。

**Comment by roybill** [comment]
如果想要在application内弹出来该怎么做呢?

**Comment by razerdp** [comment]
PopupWindow的特性限制了这种情况，，，因为必须要有宿主，所以没有办法实现哦~

**Comment by threedeer** [comment]
想要在application里面弹窗，在application里面获得栈顶activity再去弹。
ActivityLifecycleCallbacks 通过这个监听就可以了

**Comment by razerdp** [comment]
目前的版本已经是这样了的

> 想要在application里面弹窗，在application里面获得栈顶activity再去弹。
> ActivityLifecycleCallbacks 通过这个监听就可以了
