### ISSUE TITLE
最新2.2.6版本方法找不到.

### ISSUE THREAD

**Issue by lydlovezjr** [razerdp/BasePopup#341]
<img width="561" alt="微信截图_20200817110059" src="https://user-images.githubusercontent.com/19246347/90353525-06532b80-e079-11ea-86e6-2b630be14061.png">

**Comment by lydlovezjr** [comment]
替代方法是???

**Comment by razerdp** [comment]
请看2.2.5更新日志，以及文档日志。都有写明的

**Comment by razerdp** [comment]
另外，该issue不符合规范，先关闭了哈

**Comment by razerdp** [comment]
说错，请看2.2.4的更新日志。
