### ISSUE TITLE
2.2.6 ,在非全屏dialog上弹PopupWindow，弹出的位置和关联的AnchorView之间会多出状态栏的高度。

### ISSUE THREAD

**Issue by yan885283** [razerdp/BasePopup#342]
在很多品牌上都试过，只在两台Vivo上出现这个问题。之前更新到2.2.5之后，弹窗会相对全屏dialog的位置出现，更新到2.2.6之后又回到2.2.4出现的位置，如下：

- 系统版本（必须）/ System version (required)：vivo.Y83，android版本8.1
 - 库版本（必须）/ Library version (required)：2.2.6
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
![image](https://user-images.githubusercontent.com/25768605/90753965-d5d6f000-e30b-11ea-8710-cb313062de99.png)

 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
>  mIpoNumPopWindow = new IPOChangeNumPopWindow(mDialog.getDialog());
                mIpoNumPopWindow.setPopupGravity(BasePopupWindow.GravityMode.ALIGN_TO_ANCHOR_SIDE, Gravity.LEFT)
                        .setBackgroundColor(android.R.color.transparent)
                        .showPopupWindow(mView);

**Comment by razerdp** [comment]
对于dialog在candy中已经重新适配过了。

请更新到candy最新版

**Comment by yan885283** [comment]
已经是最新的2.2.6啦

**Comment by razerdp** [comment]
我指的是【Candy】版本哦

**Comment by yan885283** [comment]
好的好的

**Comment by razerdp** [comment]
已经可以了吗？

**Comment by yan885283** [comment]
> 已经可以了吗？

可以了
