### ISSUE TITLE
无法调节背景模糊度

### ISSUE THREAD

**Issue by fasheng9595** [razerdp/BasePopup#343]
- 系统版本（必须）/ System version (required)：MIUI 11.0.5  Android9
 - 库版本（必须）/ Library version (required)：2.2.7
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
        DemoPopup demoPopup = new DemoPopup(this);
        demoPopup.setBackgroundColor(0);

        PopupBlurOption popupBlurOption = new PopupBlurOption();
        popupBlurOption.setBlurRadius(0);
        popupBlurOption.setBlurPreScaleRatio(1.0f);

        demoPopup.setBlurOption(popupBlurOption);
        demoPopup.setBlurBackgroundEnable(true);
        demoPopup.showPopupWindow();
 - 报错信息（可选）/ Error reporting information (optional)：
无
---

> 问题描述/重现步骤请写在这里
> Please write the description here.

设置了PopupBlurOption 但是模糊程度没有改变 想设置的清洗一些。

**Comment by razerdp** [comment]
如果你在最后设置了setBlurBackgroundEnable，你的option会被覆盖的，setBlurBackgroundEnable有一个带callback方法返回其option

**Comment by fasheng9595** [comment]
好的，使用了带callback方法的setBlurBackgroundEnable，现在可以了，谢谢。

**Comment by razerdp** [comment]
文档已经补充

https://www.yuque.com/razerdp/basepopup/udccdq#12bedc89
