### ISSUE TITLE
设置了showPopupWindow(Gravity.RIGHT),还是从底部弹出来,虽然已经居右了,但是不是从右侧弹出来的

### ISSUE THREAD

**Issue by lv823063712** [razerdp/BasePopup#344]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：
 - 库版本（必须）/ Library version (required)：
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
设置了showPopupWindow(Gravity.RIGHT),还是从底部弹出来,虽然已经居右了,但是不是从右侧弹出来的

**Comment by lv823063712** [comment]
问题补充使用了screenPop.setPopupGravity(Gravity.RIGHT);设置完后依然还是从底部弹出

**Comment by razerdp** [comment]
请提供完整代码。。。

**Comment by razerdp** [comment]
另，补充一下版本信息等等

**Comment by lv823063712** [comment]
public ScreenPop(Context context) {
        super(context);
        setPopupGravity(Gravity.END);
        this.context = context;
        initView();
    }
以上是POPWindow的
 ScreenPop screenPop = new ScreenPop(mActivity);
                screenPop.showPopupWindow();
这里是activity的
版本是2.2.2.190912

**Comment by lv823063712** [comment]
补充,在activity中的showPopupWindow()中设置过Gravity.END (参照的手册提示),但是未生效;不知道是需要升级版本还是怎么办

**Comment by razerdp** [comment]
请更新到最新版本吧，现在都2.2.7了。。。。另外Gravity.END其实一般给RTL用的，而RTL适配也是最近才有。

**Comment by lv823063712** [comment]
版本升级解决了,应该是你之前的版本动画导致的,其实应该生效了,但是那个之前的动画好像只支持从下到上,或者从上到下;

**Comment by razerdp** [comment]
https://www.yuque.com/razerdp/basepopup/loo539

我看了下2.2.2版本的日志，好像没有重构动画相关的。。

不过如果商用尽量不要用candy版本，因为那个是开发版，有可能存在我还没完善的包，因为发出去测试。

**Comment by lv823063712** [comment]
行吧,不过蟹蟹了;之前的版本,看了动画好像只能写参数;也可能是我没有深入看动画的代码

**Comment by razerdp** [comment]
现在的动画建议用AnimationHelper

https://www.yuque.com/razerdp/basepopup/zcgtm5

这个问题我先关了哈
