### ISSUE TITLE
在toolbar的menu点击想弹出在menu按钮下方怎么实现呢？

### ISSUE THREAD

**Issue by czl0325** [razerdp/BasePopup#345]
override fun onOptionsItemSelected(item: MenuItem?): Boolean {
       
}

在这里面showPopupWindow必须传入anchorView，但是我获取不到menu的view，
我希望点击右上角的图标，弹窗的图标下方有提示。

有什么好的解决方法吗？

**Comment by razerdp** [comment]
https://github.com/razerdp/BasePopup/blob/ee3c0172d2/app/src/main/java/razerdp/demo/DemoActivity.java#L79
https://github.com/razerdp/BasePopup/blob/ee3c0172d2/app/src/main/java/android/support/v7/app/BasePopupDemoHooker.java

请看旧版本的 commit中的demo

**Comment by razerdp** [comment]
另外，请按issue规范提交，本问题先关闭了
