### ISSUE TITLE
BasePopWindow 在 Dialog 中显示某些机型布局被切掉的问题

### ISSUE THREAD

**Issue by fankes** [razerdp/BasePopup#346]
## 提issue前请务必参考以下格式填写，否则该问题会被直接关闭。

 - 系统版本（必须）：OPPO A9 的 ColorOS 6 Android 9.0
 - 库版本（必须）：Candy:2.2.5.0725
 - 问题代码/截图（可选）：

![device-2020-09-04-233202](https://user-images.githubusercontent.com/37344460/92257492-e1c7d200-ef07-11ea-88b4-f9eb03e43720.png)
（图1 MIUI12 显示正常）

![device-2020-09-04-233319](https://user-images.githubusercontent.com/37344460/92257494-e42a2c00-ef07-11ea-89ce-e88c4f558ad6.png)
（图2 OPPO ColorOS 6 Android 9.0 显示不正常）

> 问题描述/重现步骤请写在这里
 使用 Dialog 中的 View 创建 popwindow 导致不能完全显示，经过测试 MIUI12 Android 10 显示正常（如图1）
我自己测试的一台 oppo A9 显示不正常，上面的布局被对话框的半屏布局切掉了（如图2）
根据群友调试指明 vivo 的手机 安卓9系统也存在这个问题，但是没有具体提供型号
由于没有在常见问题中找到这种错误，所以来提一个issues

尝试使用了**setClipChildren(true)** **setClipChildren(false)** 都是无效的。

**Comment by razerdp** [comment]
你好，请更新到最新版本，2.2.5已经有点旧了，而且是candy版本。

2.2.7的更新日志中有跟裁剪相关的修复：

https://www.yuque.com/razerdp/basepopup/ebgrr9

**Comment by fankes** [comment]
好的，我去试一下

**Comment by fankes** [comment]
> 你好，请更新到最新版本，2.2.5已经有点旧了，而且是candy版本。
> 
> 2.2.7的更新日志中有跟裁剪相关的修复：
> 
> https://www.yuque.com/razerdp/basepopup/ebgrr9

你好，更新到 2.2.7.1 的 Candy 版本问题依旧

**Comment by fankes** [comment]
> 你好，请更新到最新版本，2.2.5已经有点旧了，而且是candy版本。
> 
> 2.2.7的更新日志中有跟裁剪相关的修复：
> 
> https://www.yuque.com/razerdp/basepopup/ebgrr9

这是我在显示Pop类的核心代码定义
`class MenuPopDialog(context: Context) : BasePopupWindow(context) {

    private lateinit var root: LinearLayout
    private var view: View? = null
    private var x = -1
    private var y = -1

    override fun onCreateContentView(): View {
        val layout = createPopupById(R.layout.menu_float)
        root = layout.findViewById(R.id.menu_float_lin)
        return layout
    }

    init {
        setClipChildren(true)
    }
}`

**Comment by fankes** [comment]
> 你好，请更新到最新版本，2.2.5已经有点旧了，而且是candy版本。
> 
> 2.2.7的更新日志中有跟裁剪相关的修复：
> 
> https://www.yuque.com/razerdp/basepopup/ebgrr9
这是一个简单使用方法的实例
创建对话框 在对话框点击按钮后弹出自定义的 BasePopWindow
`
val dialogTest = Dialog(context)
        dialogTest.setContentView(R.layout.dia_txt_chapter_config)
        dialogTest.show()
        val buttonTest = dialogTest.findViewById<Button>(R.id.dia_tbcc_button_1)
        buttonTest.setOnClickListener {
            MenuPopDialog(context).showPopupWindow(buttonTest)
        }
`

**Comment by razerdp** [comment]
为何要更新到2.2.7.1。。。release 2.2.7不好么

**Comment by razerdp** [comment]
2.2.7.1是2.2.7这个版本中的第一个开发版，你应该更新到2.2.7这个正式版，candy不应该商用的

**Comment by razerdp** [comment]
另外，如果是特殊机型问题，比如蛋疼的ov以及华为这些魔改了ROM的话，我这边好像也没什么很好的办法呢，毕竟底层他们说了算，改乱了我也没法给他弄回来对吧

**Comment by fankes** [comment]
> 另外，如果是特殊机型问题，比如蛋疼的ov以及华为这些魔改了ROM的话，我这边好像也没什么很好的办法呢，毕竟底层他们说了算，改乱了我也没法给他弄回来对吧

遇到ov这种机型也是很蛋疼的，真的懒得修复

**Comment by razerdp** [comment]
暂时无解。。。
