### ISSUE TITLE
在 anchorView 模式下 如何调节左右边距 距离屏幕左右的位置 设置margin没有作用

### ISSUE THREAD

**Issue by xiansenxuan** [razerdp/BasePopup#348]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：
 - 库版本（必须）/ Library version (required)：
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

**Comment by razerdp** [comment]
不是很明白你的需求，跟anchor相关时为何还要关心跟屏幕的距离

**Comment by razerdp** [comment]
另外请补充下issue格式要求，由于不是bug反馈，该issue不会被主动忽略。

**Comment by xiansenxuan** [comment]
系统版本（必须）/ System version (required)：9.0
库版本（必须）/ Library version (required)：2.1.6'
问题代码/截图（可选）/ Problem code or screenshot (optional)：无
报错信息（可选）/ Error reporting information 

![2020-09-10_090922](https://user-images.githubusercontent.com/11705011/92670039-b39e2400-f345-11ea-8128-c648dd3a1d5e.png)

**Comment by razerdp** [comment]
版本请更新到最新版。2.1.6太旧了。【不过如果您没升级到androidX则不要更新喔。。。当然，没升级到androidX我也无解】

**Comment by razerdp** [comment]
无后续反馈，关闭。
