### ISSUE TITLE
在Android11的模拟器上，从底部弹出的位置多了底部虚拟导航栏的高度

### ISSUE THREAD

**Issue by yan885283** [razerdp/BasePopup#349]
在Android10的手机上弹出正常，最近适配11的时候发现底部弹出会多了虚拟导航栏的高度。

 - 系统版本（必须）/ System version (required)：Android 11 - AndroidStudio模拟器
 - 库版本（必须）/ Library version (required)：2.2.7
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
![image](https://user-images.githubusercontent.com/25768605/93050709-f0e01a00-f695-11ea-8b8c-bbc36e161ecb.png)

 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
>

**Comment by razerdp** [comment]
我看看

**Comment by yan885283** [comment]
> 我看看
好的，谢谢

**Comment by razerdp** [comment]
嗯。。问题找到了，android 11有一些windowflag弃用了，部分API修改过，因此导致了这个问题

**Comment by yan885283** [comment]
> 嗯。。问题找到了，android 11有一些windowflag弃用了，部分API修改过，因此导致了这个问题

麻烦老哥有空修复一下哈

**Comment by razerdp** [comment]
嗯嗯，不过目前basepopup最高支持api也只是到29，还没到30哈

**Comment by yan885283** [comment]
> 嗯嗯，不过目前basepopup最高支持api也只是到29，还没到30哈
嗯嗯，就刚好看到了，我这个项目也不着急适配30的

**Comment by razerdp** [comment]
* **【Candy】2.2.8.0916** (2020/09/16)
  * 适配Api30 [#349](https://github.com/razerdp/BasePopup/issues/349)

已适配，目前来看，模拟器表现上可能模糊在非overlayt statusbar下有点问题（主要是大小不好搞）。

![微信截图_20200916121143](https://user-images.githubusercontent.com/11629986/93291693-5c50f580-f816-11ea-9732-f945a81569f9.png)

**Comment by razerdp** [comment]
2.2.8已发布
