### ISSUE TITLE
能设置阴影显示位置吗

### ISSUE THREAD

**Issue by yong396040003** [razerdp/BasePopup#350]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：
 - 库版本（必须）/ Library version (required)：
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> 比如从某一个view底部弹出，而我想让他顶部无阴影，而底部有阴影怎么做呢。

**Comment by razerdp** [comment]
能去看文档吗。。。
