### ISSUE TITLE
在 onCreateShowAnimator/onCreateDismissAnimator 中创建针对contentView中不同子view的animator时无效，创建的animator总是全部作用于contentView。

### ISSUE THREAD

**Issue by leanderli** [razerdp/BasePopup#352]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：Android Q
 - 库版本（必须）/ Library version (required)：2.2.4.1
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

在 onCreateShowAnimator/onCreateDismissAnimator 中创建针对contentView中不同子view的animator时无效，创建的animator总是全部作用于contentView。

`@Override
    protected Animator onCreateShowAnimator() {
        ObjectAnimator alphaAnimator = ObjectAnimator.ofFloat(getDisplayAnimateView(), View.ALPHA, 0f, 1f);
        ObjectAnimator showScaleXAnimator = ObjectAnimator.ofFloat(iconView, View.SCALE_X, 0.9f, 1f);
        ObjectAnimator showScaleYAnimator = ObjectAnimator.ofFloat(iconView, View.SCALE_Y, 0.9f, 1f);
        AnimatorSet showAnimatorSet = new AnimatorSet();
        showAnimatorSet.playTogether(alphaAnimator, showScaleXAnimator, showScaleYAnimator);
        return showAnimatorSet;
    }`

如上述代码，alphaAnimator 创建的是针对当前contentView的Alpha动画，其他的scaleAnimator都是针对contentView中的某一个子view：iconView创建的缩放动画，但在popup show/dismiss时，这些动画全部作用在了contentView上，scaleAnimator并没有单独作用在iconView。希望可以改进。

**Comment by razerdp** [comment]
onCreateShowAnimator/onCreateShowAnimation 这两个api本身就是获取针对getDisplayAnimateView()的动画，因此内部会强行被我 **setTarget()**（[代码](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/BasePopupHelper.java#L251)）所以框架需要你提供A，但我就是想提供B，那可能会达到不一样的效果。

建议子控件动画在onShow()中执行，不过在此之前你可能需要先升级版本，我忘了2.2.4.1是否有该api。。

更新日志请查看手册：https://www.yuque.com/razerdp/basepopup/uyrsxx

**Comment by leanderli** [comment]
> onCreateShowAnimator/onCreateShowAnimation 这两个api本身就是获取针对getDisplayAnimateView()的动画，因此内部会强行被我 **setTarget()**（[代码](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/BasePopupHelper.java#L251)）所以框架需要你提供A，但我就是想提供B，那可能会达到不一样的效果。
> 
> 建议子控件动画在onShow()中执行，不过在此之前你可能需要先升级版本，我忘了2.2.4.1是否有该api。。
> 
> 更新日志请查看手册：https://www.yuque.com/razerdp/basepopup/uyrsxx

嗯，如果提供了onShow/onDismiss的接口也是可以的。目前我只能在showPopupWindows中加入格外的针对子view的动画，但是onDismiss接口目前是在dismiss以后才调用的，所有动画是不会展示的，不知道新版本里面有没有增加类似beforeShow/beforeDismiss的方法?

**Comment by razerdp** [comment]
OnDismissListener一直都有onBeforeDismiss()哦

**Comment by razerdp** [comment]
同时也有onPreShow()

**Comment by razerdp** [comment]
不过你的建议挺好，我加一个内部的onBeforeDismiss吧，同时onPreShow也更名为onBeforeShow，统一一下

**Comment by leanderli** [comment]
> 不过你的建议挺好，我加一个内部的onBeforeDismiss吧，同时onPreShow也更名为onBeforeShow，统一一下

我的意思就是增加继承方法，有的逻辑不一定都在外部实现

**Comment by razerdp** [comment]
ya，我明白你的意思，OnDismissListener本身是有onBeforeDismiss的，其实可以内部setOnDismissListener，不过有时候想在内部直接实现，因此我下个版本会加一个内部的onBeforeDismiss()

**Comment by leanderli** [comment]
> ya，我明白你的意思，OnDismissListener本身是有onBeforeDismiss的，其实可以内部setOnDismissListener，不过有时候想在内部直接实现，因此我下个版本会加一个内部的onBeforeDismiss()

嗯，直接继承重写会更好。那我等下一个版本咯 🌚

**Comment by razerdp** [comment]
Candy 2.2.9.0919已发布，该版本没有大改，基于2.2.8 Release，因此可以商用。

* **【Candy】2.2.9.0919** (2020/09/19)
  * 方法更名：`onPreShow`-> `onBeforeShow`
  * 增加方法：`onBeforeDismiss`，作用同OnDismissListener#onBeforeDismiss()
  * 增加方法：`setTouchable`，该方法用于设置是否允Popup是否响应事件，如果不响应，则事件会穿透Popup
  * BasePopupUnsafe增加方法：
    * `getWindowManager`：获取BasePopup的WindowManager代理
    * `getBasePopupDecorViewProxy`：获取BasePopup最终的DecorView代理
    * `getDecorViewLayoutParams`：获取BasePopup最终DecorView的LayoutParams

**Comment by razerdp** [comment]
问题先不要关闭哈，等我发了2.2.9 release再统一关闭。

**Comment by leanderli** [comment]
> 问题先不要关闭哈，等我发了2.2.9 release再统一关闭。

ok，谢谢了！

**Comment by leanderli** [comment]
> 问题先不要关闭哈，等我发了2.2.9 release再统一关闭。

我用了candy的确实可以了，只是有个问题就是如果不设置setDismissListener / setBeforeShowListener 内部继承的 onBeforeShow/onBeforeDismiss不会调用

**Comment by razerdp** [comment]
我看看。。可能忽略了啥

**Comment by razerdp** [comment]
![image](https://user-images.githubusercontent.com/11629986/93962108-924d2700-fd8c-11ea-9437-0aa2ffb3234e.png)

噗，这里dismisslistenlistener优先了。。。我改一下

**Comment by razerdp** [comment]
* **【Candy】2.2.9.0923** (2020/09/23)
  * 优化onBeforeDismiss()判断顺序 [#352](https://github.com/razerdp/BasePopup/issues/352)

更新到candy新版~

diff：[#diff](https://github.com/razerdp/BasePopup/commit/18db870ef80a95351721f98e37fd1949ae18b48a#diff-a35c6952a89538968c329dfbd8fd39e8R853)

**Comment by razerdp** [comment]
release 2.2.9 已发布
