### ISSUE TITLE
链式调用怎么用Glide加载图片

### ISSUE THREAD

**Issue by Tangyongh** [razerdp/BasePopup#353]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：
 - 库版本（必须）/ Library version (required)：
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

 void showWjPopup() {
        QuickPopupBuilder.with(this)
                .contentView(R.layout.popup_wj)
                .config(new QuickPopupConfig()
                                .withShowAnimation(AnimationHelper.asAnimation().withScale(ScaleConfig.CENTER).toShow())
                                .withDismissAnimation(AnimationHelper.asAnimation().withScale(ScaleConfig.CENTER).toDismiss())
                                .withClick(R.id.tv_go, view -> {

                                }, true)
                                .withClick(R.id.image, view -> {

                                }, true)
                                .blurBackground(true)
                                .outSideDismiss(false))
                .show();
    }

**Comment by razerdp** [comment]
QuickPopupBuilder只提供最基本的东西，如点击什么的，不提倡复杂用法，因此建议你自行依赖BasePopup实现，或者依赖后自行实现链式调用。

https://www.yuque.com/razerdp/basepopup/ob329t
