### ISSUE TITLE
archorView不是一个view，是使用canvas画的一个个RectF,但又想使用gravity这些功能

### ISSUE THREAD

**Issue by malonecoder** [razerdp/BasePopup#355]
- 系统版本（必须）/ System version (required)：7.1
 - 库版本（必须）/ Library version (required)：2.2.8
> 问题描述/重现步骤请写在这里
   大神你好，看了你的库真的很强大，也在多个地方用到了你的库
   这次有一个场景，archorView是使用canvas画出来的一个矩形，点击矩形想显示我们的pop, 如果只有矩形的四个边位置值，怎么处理才能绑定POP,  因为想通过设置gravity可以控制POP的位置。如果自己传入x,y固定显示的话 ，因为我们要根据矩形在屏幕上的位置，点击的时候可以动态在矩形的上下左右显示，自己计算就麻烦些了。

![image](https://user-images.githubusercontent.com/26137185/94325864-2f999c80-ffd3-11ea-90be-e8e6ee508a51.png)
就是在点击某一个Event的时候想显示pop，横屏模式下

**Comment by razerdp** [comment]
有矩形位置其实就等同于有了矩形内任意一个点的x,y了的说。。。

比如 rect.centerX  rect.centerY这样，，

basepopup本身就支持传入坐标。

**Comment by razerdp** [comment]
ps，x,y也支持gravity的。

**Comment by malonecoder** [comment]
感谢大神 ~已经可以了
