### ISSUE TITLE
自定义popup继承自BasePopup，布局内使用SmartRefreshLayout获得它的刷新头部为空

### ISSUE THREAD

**Issue by q88qaz** [razerdp/BasePopup#356]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

系统版本（必须）/ System version (required)：9.0
库版本（必须）/ Library version (required)：2.2.3
手机机型（必须）/ phone model(required)：红米手机8A
问题代码/截图（可选）/ Problem code or screenshot (optional)：无
报错信息（可选）/ Error reporting information (optional)：无

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
自定义popup继承自BasePopup，布局内使用SmartRefreshLayout获得它的刷新头部为null
> 相关代码：
ClassicsHeader header = (ClassicsHeader) smartRefreshLayout.getRefreshHeader();
        ClassicsFooter footer = (ClassicsFooter) smartRefreshLayout.getRefreshFooter();
        if (header != null) { // 这里获得的header是null
            header.setPrimaryColors(Color.TRANSPARENT, Color.WHITE);
        }
        if (footer != null) { // 这里获得的footer 是null
            footer.setPrimaryColor(Color.TRANSPARENT);
            footer.setAccentColor(Color.WHITE);
        }

**Comment by razerdp** [comment]
三方库你应该去找对应库提issue。。。找我没啥用的。

**Comment by q88qaz** [comment]
阿西巴

**Comment by razerdp** [comment]
basepopup上提供的是view，你的布局相当于addview进来而已，所以三方控件有问题基本上来说跟basepopup没有很大关系。建议你先查验自己的写法，然后在activity上同样尝试复现，接着去断点调试。
