### ISSUE TITLE
多个edittext在pop中，让键盘跟随要输入的那一行。

### ISSUE THREAD

**Issue by pbaiyy** [razerdp/BasePopup#357]
我的弹窗中，有一个recyclerview，recyclerview的每一行都是一个edittext，点击某一行的时候，弹出键盘，整个布局都往上顶了。有没有办法设置键盘跟随点击的recyclerview中的那一行呢？

**Comment by razerdp** [comment]
1 - 请查看文档
2 - 请按照issue规范提问

本问题因不满足issue规范，将被我主动关闭
