### ISSUE TITLE
让键盘跟随recyclerview中的edittext

### ISSUE THREAD

**Issue by pbaiyy** [razerdp/BasePopup#358]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：10.0
 - 库版本（必须）/ Library version (required)：2.2.3
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：无
 - 报错信息（可选）/ Error reporting information (optional)：无

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
我的弹窗中，有一个recyclerview，recyclerview的每一行都是一个edittext，点击某一行的时候，弹出键盘，整个布局都往上顶了。有没有办法设置键盘跟随点击的recyclerview中的那一行呢？

**Comment by razerdp** [comment]
目前来说，popup允许跟随到某个viewid的方法或者布局到整个popup底部，不过确实没有给定跟随到view，这是一个需求，可以考虑添加。

https://www.yuque.com/razerdp/basepopup/hxd29e#234fb92b

**Comment by razerdp** [comment]
另外，建议更新一下库，2.2.3有点旧了，建议查看下更新日志

https://www.yuque.com/razerdp/basepopup/uyrsxx

**Comment by pbaiyy** [comment]
所以现在是不支持跟随到recyclerview中的某一行是吗？

**Comment by razerdp** [comment]
> 所以现在是不支持跟随到recyclerview中的某一行是吗？

暂不支持。

**Comment by razerdp** [comment]
> 所以现在是不支持跟随到recyclerview中的某一行是吗？

这个需求急吗？急的话我现在去candy加

**Comment by pbaiyy** [comment]
如果能现在加上当然最好了。麻烦了

**Comment by pbaiyy** [comment]
如果pop中是一个netscrollview包含两个recyclerview，是不是也不能滑动呢？在pop中

**Comment by razerdp** [comment]
> 如果pop中是一个netscrollview包含两个recyclerview，是不是也不能滑动呢？在pop中

什么意思

**Comment by razerdp** [comment]
@pbaiyy 

* **【Candy】2.2.9.0928** (2020/09/28)
  * 添加键盘对齐View的方法 `setAdjustInputMode(View,flag)` [#358](https://github.com/razerdp/BasePopup/issues/358)

文档已补充：
https://www.yuque.com/razerdp/basepopup/hxd29e#234fb92b

**Comment by pbaiyy** [comment]
就是指我的弹窗，可能会很长，所以需要他是能上下滑动的情况，这时候，弹窗会超出屏幕的范围吗？还有能有上下滑动的效果吗？

**Comment by razerdp** [comment]
> 就是指我的弹窗，可能会很长，所以需要他是能上下滑动的情况，这时候，弹窗会超出屏幕的范围吗？还有能有上下滑动的效果吗？

弹窗不会超范围的，最大会被我限制在屏幕内，所以你仍然可以滑动。

**Comment by pbaiyy** [comment]
哦哦，刚这candy我用了下，是要传view才行是吗？不能传入viewid？我是这么写的，没有效果。
.setAdjustInputMode(R.id.et_task_detail_bottom_name,BasePopupWindow.FLAG_KEYBOARD_ALIGN_TO_VIEW)

**Comment by pbaiyy** [comment]
如果是放在edittext点击的时候在去setAdjustInputMode，会出现第一次无效，第二次才会生效的情况。

**Comment by razerdp** [comment]
贴代码

**Comment by pbaiyy** [comment]
dqbhTaskCommitPopWindow
                    .setPopupGravity(Gravity.BOTTOM). showPopupWindow();
上面是pop显示，下面是点击输入框的时候，setAdjustInputMode，显示键盘

edittextAdapter.setOnItemChildClickListener(new BaseQuickAdapter.OnItemChildClickListener() {
                @Override
                public void onItemChildClick(BaseQuickAdapter adapter, final View view, int position) {
                  if (view.getId() == R.id.et_task_detail_bottom_name) {
                        setAdjustInputMode(view, FLAG_KEYBOARD_ALIGN_TO_VIEW | FLAG_KEYBOARD_ANIMATE_ALIGN);
                    }
                }
            });

**Comment by razerdp** [comment]
你需要先set再show，show了之后set是没用的，任何set的参数在show调用的那一刻就以及固定了

**Comment by pbaiyy** [comment]
dqbhTaskCommitPopWindow.setAdjustInputMode(R.id.et_task_detail_bottom_name, BasePopupWindow.FLAG_KEYBOARD_ALIGN_TO_VIEW | BasePopupWindow.FLAG_KEYBOARD_ANIMATE_ALIGN)
            .setPopupGravity(Gravity.BOTTOM).showPopupWindow();
view我在show的时候，是拿不到的，只有viewid，我这么写也没用，键盘只跟随第一行edittext。

**Comment by razerdp** [comment]
噢对，，，想起来set的时候是不行的= = set完你update试试？

这个我得想个办法了，走入了一个胡同

**Comment by pbaiyy** [comment]
你是指在点击edittext的时候set，然后update是吗？

**Comment by razerdp** [comment]
是的，，不过我想了想，好像也不好搞

**Comment by razerdp** [comment]
键盘对齐触发时机是键盘弹起的那一刻

**Comment by razerdp** [comment]
所以理论上来说，我应该在适配之前回调给你才对

**Comment by pbaiyy** [comment]
调用set，然后update，也是不行。。。会出现第二次打开才正确的情况。第一次都是不对的。

**Comment by razerdp** [comment]
是的，应该是无法做到的，因为对齐是弹起的那一刻= =  你先加一下微信 razerdp_test  注明一下备注，我拉你进群，稍后我想想怎么解决这种问题，然后群里探讨一下？

**Comment by pbaiyy** [comment]
OK

**Comment by razerdp** [comment]
release 2.2.9 已发布

**Comment by Roy1994419** [comment]
让键盘跟随recyclerview中的edittext 这个问题解决了吗  我的要点击两次才可以正常

**Comment by razerdp** [comment]
> 让键盘跟随recyclerview中的edittext 这个问题解决了吗 我的要点击两次才可以正常

请查看2.2.9更新日志，提供了updateKeyboardAlign api让您通知basepopup对齐inputmode中的view
