### ISSUE TITLE
不能在BottomSheetDialog之上显示，会被覆盖遮挡

### ISSUE THREAD

**Issue by SheepYang1993** [razerdp/BasePopup#359]
应该是和这个issues一样的问题吧？
https://github.com/li-xiaojun/XPopup/issues/153

版本是2.2.7

**Comment by SheepYang1993** [comment]
已找到解决方法
![image](https://user-images.githubusercontent.com/15150244/95641732-883e5e80-0ad6-11eb-8f3e-1d4ad4429dfc.png)

**Comment by razerdp** [comment]
请使用带dialog的构造器，另外，跟xpopup不一样的~
他们之前是基于decorview#addview，后面是dialog，而我们是基于popupwindow，所以不一样的哦~
