### ISSUE TITLE
怎么引用老兄？

### ISSUE THREAD

**Issue by zhangchun123** [razerdp/BasePopup#36]
![oobh52pu nn4 mn431b _rp](https://user-images.githubusercontent.com/13727654/29305009-de7c9fcc-81c8-11e7-80e6-f282b0b642c3.png)

**Comment by razerdp** [comment]
@zhangchun123 

compile 'com.github.razerdp:BasePopup:v1.8.0'

如果还是不能的话，可能需要翻墙。。。最近我引用别的库（jitpack的），很多时候都是要翻墙才能引用。。。。

如果你那边不方便翻墙，可以下载整个库，把lib当作module导入再引用

**Comment by zhangchun123** [comment]
好的谢谢

**Comment by yigepang** [comment]
一样的问题，没法引用，至于利用module，如果本身项目module比较多了的话，感觉还是不太好，项目整体看起来就比较臃肿了

**Comment by zhao-mingjian** [comment]
后面的版本号建议作者不要添加字母v

**Comment by razerdp** [comment]
@zhangchun123 好的，我也留意到这个问题，后面的版本我会留意的

**Comment by zhouyunr** [comment]
翻墙都引用不了

**Comment by razerdp** [comment]
1.8.0之后就没有v了。
