### ISSUE TITLE
系统版本28，库版本2.2.8，setAlignBackground(true)无效果

### ISSUE THREAD

**Issue by shallowlight** [razerdp/BasePopup#361]
- 系统版本（必须）28
 - 库版本（必须）2.2.8
 - 问题代码/截图（可选）

`public class ProductConditionPopup extends BasePopupWindow {

    private List<ProductCondition> data;
    private ConditionAdapter adapter;

    public ProductConditionPopup(Context context, List<ProductCondition> data) {
        super(context);
        this.data = data;
        List<Condition> conditionTags = new ArrayList<>();
        if (data != null) {
            for (ProductCondition condition : data) {
                for (ConditionTag conditionListEx : condition.getConditionListEx()) {
                    if (conditionListEx.isChecked()) {
                        conditionTags.add(new Condition(condition.getId(), conditionListEx.getName()));
                    }
                }
            }
        }
        setAlignBackground(true);
        setAlignBackgroundGravity(Gravity.RIGHT);
    }

    @Override
    public View onCreateContentView() {
        return createPopupById(R.layout.pop_product_condition2);
    }

    @Override
    public void onViewCreated(@NonNull View contentView) {
        super.onViewCreated(contentView);

        RecyclerView recyclerView = findViewById(R.id.recyclerView);
        LinearLayoutManager layoutManager = new LinearLayoutManager(getContext());
        recyclerView.setLayoutManager(layoutManager);
        adapter = new ConditionAdapter(R.layout.item_product_condition);
        recyclerView.setAdapter(adapter);
        adapter.setList(data);
    }
}`

- 在调用的地方
`ProductConditionPopup(this.getLContext(),prodConditions).showPopupWindow(v_author_pop)`
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> setAlignBackground(true);setAlignBackgroundGravity(Gravity.RIGHT);在两个Api没有预期的效果，背景色遮罩还是满屏。
> 此外为什么有时会有构造函数执行会在 onViewCreate之后执行呢？怎么解决这个问题？

**Comment by razerdp** [comment]
你好，这里有两个问题我分开给你解答哈。。

Q1：【alignbackground】问题

首先看到您是仅对齐右边，但是根据描述依然是满屏，api经过demo复现无法复现，因此我觉得很有可能存在下面这种情况：
您的popup contentview就是满屏的，因此背景哪怕对齐右边，也依然是满屏的。
您可以通过以下步骤检查：
  - 检查根布局是否match parent
  - 通过Layout Inspector检查PopupDecorView大小

![image](https://user-images.githubusercontent.com/11629986/96100686-3b5bed00-0f07-11eb-8829-78c18071c8bc.png)

Q2：【为什么有时会有构造函数执行会在 onViewCreate之后执行】

请查看文档：https://www.yuque.com/razerdp/basepopup/yvlq1s

**Comment by shallowlight** [comment]
多谢大神，耐心检查，关于onViewCreate的问题，已经弄明白了，没仔细分析看源代码，不好意思。
关于那个设置背景的问题也可以了，多谢耐心解答。

**Comment by razerdp** [comment]
好的，如有疑问，欢迎留言issue，我会尽快回应
