### ISSUE TITLE
请问下如何同时存在两个PopupView啊,总是会相互顶掉!

### ISSUE THREAD

**Issue by zhukai123** [razerdp/BasePopup#362]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：
 - 库版本（必须）/ Library version (required)：
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

**Comment by razerdp** [comment]
请按issue规范提问，补充相关信息，详细描述问题。

**Comment by zhukai123** [comment]
系统版本（必须）/ System version (required)：AndroidSdk=28
库版本（必须）/ Library version (required)：2.2.9_release
问题代码/截图（可选）/ Problem code or screenshot (optional)：当页面上有一个popupView时,此时再显示第二个popupView,会将第一个自动隐藏,请问如何让多个popupView同时存在
报错信息（可选）/ Error reporting information (optional)：
如何让其他popupView显示时不影响之前的popupView的显示?

**Comment by razerdp** [comment]
默认情况下，popup点击背景蒙层是会dismiss的

如果希望点击背景蒙层不dismiss，可以设置setOutSideDismiss(false)
如果希望点击背景蒙层透传，让下层响应事件，可以设置setOutSideTouchable(true)

**Comment by razerdp** [comment]
这部分文档似乎缺失，这周末我补上

**Comment by zhukai123** [comment]
这些我都设置了, 我现在是问题是界面上不能同时存在两个以上的PopupView,
每当我用定时器去显示第二个PopuoView时,就会"自动"的触发第一个PopupView的dismiss,
我的需求是想要让这多个Popup同时共存在界面上! 

非常急,请教作者大人有没什么好的思路,再次感谢

**Comment by razerdp** [comment]
如果不是自己触发dismiss，那么不会自动dismiss的

要不你写个复现demo上来看看吧

**Comment by razerdp** [comment]
无后续反馈，关闭。
