### ISSUE TITLE
软键盘不会自动展示

### ISSUE THREAD

**Issue by pengjunhong** [razerdp/BasePopup#363]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：华为9.0
 - 库版本（必须）/ Library version (required)：2.2.9.0930
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
1.demo中将PopupInput继承为BaseLazyPopupWindow，就会出现首次软键盘不自动展示。

**Comment by razerdp** [comment]
有没有按照文档设置模式

**Comment by pengjunhong** [comment]
直接跑demo，可以复现的，就改下继承

**Comment by pengjunhong** [comment]
BasePopupWindow就没有问题

**Comment by razerdp** [comment]
好的，我带回去查验。。。

**Comment by razerdp** [comment]
bug确认，修复好后我会在这边同步一下

**Comment by pengjunhong** [comment]
好的，感谢！

**Comment by razerdp** [comment]
已修复，Candy版本：2.2.10.1030

**Comment by pengjunhong** [comment]
好的
