### ISSUE TITLE
setOutSideTouchable  点击POP外部的可点击区域(外部设置了ClickListener事件的按钮) 有时候点击不上

### ISSUE THREAD

**Issue by malonecoder** [razerdp/BasePopup#364]
- 系统版本（必须）/ System version (required)：9.0 
 - 库版本（必须）/ Library version (required)：2.2.8

---

> 问题描述/重现步骤请写在这里

setBackgroundColor(Color.TRANSPARENT)
                    .setPopupGravity(Gravity.BOTTOM | Gravity.RIGHT)
                    .setOutSideDismiss(false)
                    .setOutSideTouchable(true)
                    .setOffsetX(-35)
                    .setOffsetY(-90)
                    .setShowAnimation(AnimationHelper.asAnimation()
                            .withTranslation(TranslationConfig.FROM_BOTTOM)
                            .toShow())
                    .setDismissAnimation(AnimationHelper.asAnimation()
                            .withTranslation(TranslationConfig.TO_BOTTOM)
                            .toDismiss());
使用这个配置，点击POP以外的可点击区域，有的时候得点好几下才可以点击到。
因为是在平板上使用，点击的时候有声音，点击POP以外的可点击区域，如果点击上了会有两下声音，但是有的时候只有一下声音，也就是只点击到了POP的声音。

**Comment by razerdp** [comment]
布局是怎样的，更新到2.2.9试试？

**Comment by razerdp** [comment]
无后续反馈，关闭。
