### ISSUE TITLE
dev版本代码拉取不了

### ISSUE THREAD

**Issue by pengjunhong** [razerdp/BasePopup#365]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：
 - 库版本（必须）/ Library version (required)：2.2.10.1030
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
build.gradle，jcenter()换成maven { url 'https://maven.aliyun.com/repository/public' }就拉不了代码。但是同样的 拉取release版本的就可以。

**Comment by razerdp** [comment]
是不是拼错了，，，ps，不需要换maven.
