### ISSUE TITLE
输入法关闭，update()更新不起效果

### ISSUE THREAD

**Issue by android-xiao-jun** [razerdp/BasePopup#366]
问题描述：activity 默认有一个输入法显示（开启，呈现输入状态），然后弹出popupwindow，此时activity的输入法会自动关闭，弹出的popupwindow 位置还是之前位置，，实际背景位置已经变化（调用update()无效）

这是初始化popupwindow的代码
![image](https://user-images.githubusercontent.com/39174748/98654042-c13d4d80-2378-11eb-9b84-320680c40f00.png)

**Comment by razerdp** [comment]
请按issue规范描述。本issue将被主动忽略。
