### ISSUE TITLE
在showPopupWindow前，如何获取contentView的高度

### ISSUE THREAD

**Issue by Yetland** [razerdp/BasePopup#367]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：8.0.0
 - 库版本（必须）/ Library version (required)：2.2.7
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
需求：点击一个按钮，显示可以执行的操作，默认显示在按钮的上方；但是当上方高度超过PopupWindow高度时，显示在下方
操作步骤：点击按钮->获取popupWindow的高度->根据popupWindow的高度设置显示的位置->showPopupWindow
问题：第一次点击按钮后，获取到的popupWindow高度为0，所以无法设置实际要显示的位置

**Comment by razerdp** [comment]
你可以直接设置setAutoLocatePopup(true)来完成自动定位

如果希望自行测量，在contentview内容**不是recyclerview**的情况下，分为两个版本：
 version > 2.2.9：
   先执行preMeasure()，再调用getPreMeasureWidth()/getPreMeasureHeight()
 version < 2.2.9：
   直接调用getWidth()、getHeight()即可

如果contentView是recyclerview或包含recyclerview，在设置adapter之前无法获取。
