### ISSUE TITLE
有一个疑问，在kotlin中，为什么全局变量会在onViewCreated之后才被初始化呢

### ISSUE THREAD

**Issue by fansangg** [razerdp/BasePopup#368]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：29
 - 库版本（必须）/ Library version (required)：lastrelease
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

在onViewCreated之后对某个全局变量赋值，然后全局变量开始初始化赋值

a = "hahaha"
a = ""

```
class TestPopup(c:Context) :BasePopupWindow(c){

 var a = ""

override fun onViewCreated(contentView: View) {
  a = "hahah"
}

```

**Comment by razerdp** [comment]
这关乎到类加载机制，请看文档。

https://www.yuque.com/razerdp/basepopup/yvlq1s

**Comment by MrDon94** [comment]
感觉不够人性化，kotlin的默认参数直接无效了，虽然有个BaseLazyPopupWindow类可以解决，但是可能会有卡顿的缺点。

**Comment by razerdp** [comment]
这是没办法的事…我也尝试解决过，但效果很差。

这个问题根本原因在于默认情况下的view在父类构造器中inflate，而view却是依靠子类传过来，然而此时子类类加载流程还没到他的初始化，构造器中的值和成员变量的值都无效。

这方面我也头疼了很久，如何在不改变现有使用方式下完成这些。你有什么好的建议吗…

**Comment by razerdp** [comment]
@MrDon94 @fansangg  您好，在3.0版本中，我们特意针对该问题进行了修改，由于会破坏到原有api，因此建议您先查阅一下升级提示：[关于BasePopup 3.0的破坏性更新说明](https://github.com/razerdp/BasePopup/blob/dev/Update_3.0.md)

以后都不会再有这些限制了。
