### ISSUE TITLE
已经弹出键盘的情况下，点击其他地方弹出pop 会导致键盘收起 这个可以不影响键盘吗？怎么设置

### ISSUE THREAD

**Issue by zguop** [razerdp/BasePopup#369]
- 库版本（必须）：2.2.9
---

> 问题描述/重现步骤请写在这里
> 键盘是已经打开的的时候，长按item会触发pop弹出，会影响键盘自动收起。
使用原生的popwindow，宽高使用WRAP_CONTENT，弹出是不会影响的，希望此库也能支持。谢谢作者

**Comment by razerdp** [comment]
我去跟踪一下

**Comment by razerdp** [comment]
另外，请补充详细issue信息

**Comment by razerdp** [comment]
这个问题暂时无解。

**Comment by zguop** [comment]
计划解决么？  我看内部也是使用popwindow  是什么影响了

**Comment by razerdp** [comment]
貌似是窗口焦点的问题。不过不太好定位，目前basepopup在dismiss的时候会close键盘，但我尝试过哪怕没有dismiss，也是会消失。

而且我也试过弹dialog，也是一样会消失，所以这个问题真不太好解决的说

**Comment by zguop** [comment]
popwindow 不会影响 = = 不过我目前是用popwindow直接实现的

**Comment by razerdp** [comment]
你好，该问题已经修复，增加了一个api：`hideKeyboardOnShow(boolean dismiss)`

请更新到 **3.1.0-SNAPSHOT**


由于您反馈的版本是2.2.9，因此更新前请务必注意以下两个事项：

- 由于Jcenter已经停止服务，请阅读readme进行新的依赖迁移
- 3.0版本+的更新请阅读 [关于BasePopup 3.0的破坏性更新说明](https://github.com/razerdp/BasePopup/blob/dev/Update_3.0.md)

**Comment by razerdp** [comment]
release 3.1.0已经发布

**Comment by zguop** [comment]
您好，测试了一下这个问题，虽然不会收起，但是重新打开键盘体验还不是很好

**Comment by kanfRUI** [comment]
> 您好，测试了一下这个问题，虽然不会收起，但是重新打开键盘体验还不是很好

我用了3.2.0，还是会重新打开键盘；有什么解决方法不？
