### ISSUE TITLE
2.2.10版本存在setMaxHeight后 会固定这个高度的Bug

### ISSUE THREAD

**Issue by ChawLoo** [razerdp/BasePopup#371]
popupGravity = Gravity.BOTTOM
setMaxHeight(DisplayUtil.dip2px(300F))
showAnimation = AnimationUtils.loadAnimation(context, R.anim.pop_bottom_show)
dismissAnimation = AnimationUtils.loadAnimation(context, R.anim.pop_bottom_dismiss)
setOverlayNavigationBar(true).setOverlayNavigationBarMode(BasePopupFlag.OVERLAY_MASK)
setOverlayStatusbar(true).setOverlayStatusbarMode(BasePopupFlag.OVERLAY_MASK)
以上是PopupWindow类的设置的参数代码，设置setMaxHeight后会使得整个Popupwindow固定高度为300
内部包含一个recyclerview和在此之上的title，当Rv的Item不足时会导致底部缺失一块
![image](https://user-images.githubusercontent.com/26214519/99925425-174ac180-2d79-11eb-8a62-68d98fa8b89f.png)

**Comment by razerdp** [comment]
我复现看看

**Comment by razerdp** [comment]
噢，确实会有这个问题。我待会修复

**Comment by razerdp** [comment]
问题已修复，请到更新到Candy 2.2.11.1123进行测试

本次问题产生原因在于maxheight中，强行将measure mode设置为Exactly，实际上应该跟随原来的mode

**Comment by ChawLoo** [comment]
问题已修复，万分感谢

**Comment by razerdp** [comment]
请暂时不要关闭~发布正式版后我会回来关闭issue的~
