### ISSUE TITLE
(点击事件)如何让BasePopupView与外部view同时可点击

### ISSUE THREAD

**Issue by zhukai123** [razerdp/BasePopup#372]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：安卓10
 - 库版本（必须）/ Library version (required)：Candy:2.2.10
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
   ===>以下是我设置的属性
        setOutSideDismiss(false);//点击外部不消失
        setTouchable(true);
        setOutSideTouchable(true); //true外部可点击, false外部不可点击! 感觉无效,会被touchable影响
  

 - 报错信息（可选）/ Error reporting information (optional)：
外部view和pop两者不可同时点击, 会相互冲突
---

> 问题描述/重现步骤请写在这里
  我的目的想让外部和pop两者同时可点击,不冲突!!
   当我设置如下的pop属性后,:
        setOutSideDismiss(false);//点击外部不消失
        setTouchable(true);
        setOutSideTouchable(true); //true外部可点击, false外部不可点击! 感觉无效,会被touchable影响

  结果为但setTouchable设置为true时外部点击事件被屏蔽了,只有设置为false外部才能点击,但pop不能点击了
  请问我如何让popView和外面view同时可点击

> Please write the description here.

**Comment by razerdp** [comment]
。。我觉得你应该看下文档
https://www.yuque.com/razerdp/basepopup/yyu138#AIjfL

**Comment by razerdp** [comment]
对于你的需求，仅仅需要
setOutSideTouchable(true); 
如果希望点击蒙层不dismiss，再加上
setOutSideDismiss(false);

**Comment by zhukai123** [comment]
确实可以了,十分感谢,我应该去除:setTouchable(true);
但现在有个严重的问题就是,我是魅族(android8系统)手机上,
将状态栏字体设置为黑色了,但每次显示pop时都会将状态栏和导航栏的字体变白,
很困扰,希望能略微指点下,感谢

**Comment by razerdp** [comment]
basepopup不会更改你的宿主主题，出现这种问题就跟小米的底部指示线一样，他们的view会自行感应背景色去更改。

如果你需要强制设置，可以在popup的onShow()中去设置宿主的主题。

**Comment by zhukai123** [comment]
那我可以通过修改我pop的背景色,让其不变更嘛,我目前是设置的setBackground(0);
我先试下在onShow更改下

**Comment by zhukai123** [comment]
试了下不行, 我想通过有在popView中设置back的方式让系统在pop显示时不更改我的主题
