### ISSUE TITLE
展示动画过程中被Dismiss问题

### ISSUE THREAD

**Issue by q88qaz** [razerdp/BasePopup#373]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

系统版本（必须）/ System version (required)：9.0
库版本（必须）/ Library version (required)：2.2.10
手机机型（必须）/ phone model(required)：红米手机8A
问题代码/截图（可选）/ Problem code or screenshot (optional)：无
报错信息（可选）/ Error reporting information (optional)：无

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
展示动画使用TranslationConfig.FROM_TOP
实际操作过程中发现，展示动画还没播放完毕时，去点击popup窗体，会触发dismiss事件，最终结果就是窗体闪了一下，没有展示出来，有没有什么方法可以在动画过程中不被dismiss？？？

**Comment by razerdp** [comment]
你可以override dismiss()方法，内部判断一下动画是否执行完毕。至于动画是否已经end，这个你可以给动画添加listener去完成。

**Comment by razerdp** [comment]
伪代码：

canDismiss = False

animation.listenre{
  onEnd(){
     canDismiss  = True
   }
｝

override 
dismiss(){
  if !canDismiss  return
  else super.dismiss()

}
