### ISSUE TITLE
请问能在popupwindow里面播放视频吗？

### ISSUE THREAD

**Issue by liuxusuifeng** [razerdp/BasePopup#374]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：
 - 库版本（必须）/ Library version (required)：
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

**Comment by liuxusuifeng** [comment]
我试过在popupwindow里面直接添加一个视频的view，但是视频无法正常播放，一直处于黑屏

**Comment by razerdp** [comment]
请补全信息。

**Comment by liuxusuifeng** [comment]
我在popuwindow里面初始化了一个ijkplayer播放视频，但是弹窗弹出时视频一直无法加载，黑屏，请问是不能加载视频的view吗？

**Comment by razerdp** [comment]
我查阅了一番，定位到的原因大概是因为PopupWindow没有WindowToken，因此创建surfaceview的时候是没法创建的，。。。。所以应该不能够塞入VideoView，。也就是不能播放视频。
