### ISSUE TITLE
弹窗重复出现的问题

### ISSUE THREAD

**Issue by pope77** [razerdp/BasePopup#375]
- 系统版本：Android10
 - 库版本：2.2.11
 
当弹窗处于展示阶段时，回到桌面再重新打开APP，之前展示的弹窗虽然还在，但是会再次打开一遍就存在了两个。Demo貌似不保留后台所以无法复现

**Comment by razerdp** [comment]
什么意思，回到桌面重新打开。。。我刚刚试了一下貌似没有这种情况

**Comment by pope77** [comment]
抱歉 搞错了
