### ISSUE TITLE
如何判断当前activity中是否存在popup

### ISSUE THREAD

**Issue by zwping** [razerdp/BasePopup#376]
- 系统版本：android 11
 - 库版本：2.2.11

如题

**Comment by razerdp** [comment]
这个你自己管理就好了- -

**Comment by zwping** [comment]
router模式，不好管理

是否有类似SupportFragmentManager反向判断
或者basepopup有特定id通过window去判断
或者其它方法呢？

**Comment by razerdp** [comment]
有是有，但是并没有开放给用户使用，因为这个本就不是我们库需要提供的需求。

目前popup显示的时候都会放到PopupWindowQueueManager里，理论上可以通过queue传入String.valueof(Activity)就可以获取该act显示的popup列表了。

参考：
https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/BasePopupUnsafe.java#L36

但我们并不会开放这个，因为basepopup生成后的对象该怎么被外部使用这不应该由我们去管理。

**Comment by zwping** [comment]
意思是必须本地化才能实现想要的方法？

**Comment by razerdp** [comment]
我加个到unsafe吧

**Comment by zwping** [comment]
如果自建manager，basepopup有没有合适的切入点做为入口
如`registerActivityLifecycleCallbacks`

**Comment by zwping** [comment]
> unsafe

感谢

**Comment by razerdp** [comment]
【Candy】 2.2.12.1222

增加方法：

```java
  /**
     * 获取显示中Popup的队列
     * 【注意】：该操作会直接返回WindowManagerProxy.PopupWindowQueueManager.sQueueMap，您修改该对象可能会造成不可挽回的bug，请慎重修改。
     */
    @Deprecated
    @Nullable
    public HashMap<String, LinkedList<WindowManagerProxy>> getPopupQueueMap(){
        return WindowManagerProxy.PopupWindowQueueManager.sQueueMap;
    }

/**
     * 获取WindowManagerProxy中的popupwindow
     */
    @Deprecated
    @Nullable
    public BasePopupWindow getPopupFromWindowManagerProxy(WindowManagerProxy proxy) {
        if (proxy == null) return null;
        if (proxy.mPopupHelper != null) {
            return proxy.mPopupHelper.mPopupWindow;
        }
        return null;
    }
```

获取回来是个map：key=string.valueof(activity)
