### ISSUE TITLE
> 输入法默认横屏不适配，如何配置才能适配横屏所有输入框呢

### ISSUE THREAD

**Issue by 05youxi** [razerdp/BasePopup#377]
> 输入法默认横屏不适配，如何配置才能适配横屏所有输入框呢

你可以自己继承BasePopup，里面设置横屏输入法适配的flag，然后所有此类popup都继承你实现的就可以了

我已经尝试设置你文档上所有的flag，都没有任何效果，我用回2.1.9的版本，就没有这种问题

**Comment by razerdp** [comment]
库版本多少，补充下详细信息

**Comment by 05youxi** [comment]
> 库版本多少，补充下详细信息

2.2.10

**Comment by razerdp** [comment]
代码和截图给一下？

**Comment by 05youxi** [comment]
> 代码和截图给一下？

![image](https://user-images.githubusercontent.com/74637254/102968978-d1c41480-452f-11eb-9586-c10dee7c38fb.png)

**Comment by razerdp** [comment]
![image](https://user-images.githubusercontent.com/11629986/102969051-fb7d3b80-452f-11eb-83c7-72f0d450e2f6.png)

没设置这个？

**Comment by 05youxi** [comment]
> 代码和截图给一下？

![Uploading 微信截图_20201223150308.png…]()

**Comment by 05youxi** [comment]
设置这个不是横屏不适配吗

**Comment by razerdp** [comment]
。。。默认横屏不适配，设置这个强制适配输入法的意思

**Comment by razerdp** [comment]
可能描述有点问题- - 我改一下

**Comment by 05youxi** [comment]
哦哦。我理解错了，刚试了有效果，但是这样，只能把整个布局顶上去，如果布局位置不够，输入框看不到的

**Comment by razerdp** [comment]
> 哦哦。我理解错了，刚试了有效果，但是这样，只能把整个布局顶上去，如果布局位置不够，输入框看不到的

你可以仔细看文档。。。对齐有两种模式的

**Comment by 05youxi** [comment]
如果可以，把软键盘定位到获取焦点的输入框下面可能更合理

**Comment by 05youxi** [comment]
好的

**Comment by 05youxi** [comment]
我刚尝试加入setAdjustInputMode(FLAG_KEYBOARD_FORCE_ADJUST|FLAG_KEYBOARD_ALIGN_TO_VIEW)，这两个值，但是还是整个布局顶上去，而不是只顶到编辑框

**Comment by razerdp** [comment]
aligntoview得你传入view的。。没有view那依然是align to root

![image](https://user-images.githubusercontent.com/11629986/102970200-09cc5700-4532-11eb-859d-40959478904e.png)

**Comment by 05youxi** [comment]
> aligntoview得你传入view的。。没有view那依然是align to root
> 
> ![image](https://user-images.githubusercontent.com/11629986/102970200-09cc5700-4532-11eb-859d-40959478904e.png)

那如果我布局有多个编辑框，那就不能实现对不同的编辑的进行适配对吧

**Comment by razerdp** [comment]
有多个编辑框就没办法知道对齐哪个了。。。。

不过该问题也考虑到了，在2.2.9中加入了允许您手动调用通知basepopup执行对齐逻辑的方法

![image](https://user-images.githubusercontent.com/11629986/102970800-24530000-4533-11eb-8071-37a0f269f142.png)

你可以通过setAdjustInputMode(view,flag)后调用该方法来通知basepopup重新对齐

**Comment by razerdp** [comment]
该方法忘了写入文档。。。后面我再补一下

**Comment by 05youxi** [comment]
好的，谢谢，大神
