### ISSUE TITLE
关联anchor，高match，下面空白的点击事件怎么设置?

### ISSUE THREAD

**Issue by TianGuisen** [razerdp/BasePopup#378]
![image](https://user-images.githubusercontent.com/19662707/103199939-03215380-4927-11eb-8328-e20ad42c15f4.png)
想要点击下面空白处关闭，尝试 getContentView().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                
                dismiss();
            }
        });
无效

**Comment by razerdp** [comment]
目前contentview是被我设置了clicklistener，为了防止事件传递到蒙层

具体可以看这里：
https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/PopupDecorViewProxy.java#L46

不过后面迭代过之后好像没有这个必要了，我待会去看看

**Comment by razerdp** [comment]
* **【Candy】2.2.13.210105.1** (2021/01/05)
  * 优化decorview事件拦截 [#378](https://github.com/razerdp/BasePopup/issues/378)

**Comment by razerdp** [comment]
新的candy版本已修复，您按照当前用法保持不变即可

**Comment by TianGuisen** [comment]
'com.github.razerdp:BasePopup:2.2.13.210105.1'
下载不了啊

**Comment by razerdp** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        candy版本，不是release
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                razerdp123
                            
                    
                        
                            
                                    razerdp123@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年1月6日 11:32，TianGuisen<notifications@github.com> 写道： 




'com.github.razerdp:BasePopup:2.2.13.210105.1'

下载不了啊



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
