### ISSUE TITLE
分屏模式弹窗显示不全怎么适配

### ISSUE THREAD

**Issue by eternallyjie** [razerdp/BasePopup#379]
- 系统版本（必须）：Android 7.1.1
 - 库版本（必须）：2.2.11
 - 问题代码/截图（可选）：
 - 报错信息（可选）：
![Screenshot_20201230-105316](https://user-images.githubusercontent.com/30895476/103327022-d0459f80-4a8d-11eb-98e7-18bbacc94a44.png)

---

> 问题描述/重现步骤请写在这里
手机分屏的时候，使用basePopup弹窗显示的是在整个屏幕，但是由于分屏无法显示全。请问怎么适配分屏呢？

**Comment by razerdp** [comment]
分屏目前没有去适配哦~这个得以后再看看了

**Comment by razerdp** [comment]
查验了一下，popup分屏下其实依然靠系统允许显示的窗口大小，如果window size没变化，那么popup也不会存在变化。

也就是说，如果act变了popup也跟变化，否则不会跟随。

**Comment by razerdp** [comment]
强行手动适配只会适得其反

**Comment by eternallyjie** [comment]
> 查验了一下，popup分屏下其实依然靠系统允许显示的窗口大小，如果window size没变化，那么popup也不会存在变化。
> 
> 也就是说，如果act变了popup也跟变化，否则不会跟随。

那就是说分屏其实并没有引起activity的变化是吗？所以window size也没有变化，就导致popup还是按照全屏方式展现的是吗？

**Comment by razerdp** [comment]
是的，popup永远跟随宿主的。他没有自己的window，宿主能占多少大它就占多大。
