### ISSUE TITLE
无法全屏

### ISSUE THREAD

**Issue by ShrimpBlackNight** [razerdp/BasePopup#38]
### 该问题是怎么引起的？
Android4.4版本下，布局里加入liseview或者recyclerview，背景无法覆盖状态栏

### 重现步骤
Android4.4版本下，4.4布局里加入liseview或者recyclerview

**Comment by razerdp** [comment]
@ShrimpBlackNight 

请使用`setPopupWindowFullScreen(true)`方法

（不过理论上来说，5.0才会有这个问题，上述方法也是针对5.0进行调整的，不知道4.4是否也会出现这个问题。。。）

如果布局不是listview或者recyclerview是否会出现这个问题？

[#12](https://github.com/razerdp/BasePopup/issues/12)

**Comment by razerdp** [comment]
#12
