### ISSUE TITLE
在oncreate调用showPopupWindow后立马调用dismiss，会导致弹窗不消失

### ISSUE THREAD

**Issue by Jiang00** [razerdp/BasePopup#381]
- 系统版本：Android 9
 - 库版本：2.2.11

 在oncreate调用showPopupWindow后立马调用dismiss，会导致弹窗不消失

**Comment by Jiang00** [comment]
@Override
    public void showPopupWindow() {
        isDismiss = false;
        super.showPopupWindow();
    }

    @Override
    public void onShowing() {
        super.onShowing();
        if (isDismiss) {
            dismiss();
        }
    }
    

    @Override
    public void dismiss() {
        isDismiss = true;
        super.dismiss();
    }


暂时用这种方式处理的

**Comment by razerdp** [comment]
* **【Candy】2.2.13.210105** (2020/01/05)
  * 修复onCreate下弹窗后立马dismiss不执行的问题 [#381](https://github.com/razerdp/BasePopup/issues/381)

**Comment by SelectSex** [comment]
此bug依然存在，发现是改版优化了下图的代码
![image](https://user-images.githubusercontent.com/90268640/180452848-29459766-d457-4583-8a0e-4b82a1f95584.png)
导致用户第一次调用show后立即dismiss，会因为窗口未准备妥当，所以将show任务延后执行了，但是dismiss并没有延后执行，所以此次dismiss是无效执行，然后延后执行的show任务执行成功，导致弹窗依旧存在，
