### ISSUE TITLE
使用kotlin，然后创建多个不同的popupwindow会直接崩溃，且无法捕获异常，用adb调试测出一场是找不到反射？？

### ISSUE THREAD

**Issue by DuZhengLin17** [razerdp/BasePopup#382]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：android10  miui12.0.9
 - 库版本（必须）/ Library version (required)：com.github.razerdp:BasePopup:2.2.1
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
多个popupwindow，使用单例模式创建(或者每次都创建)  创建第二个的时候就会崩溃
> Please write the description here.

**Comment by razerdp** [comment]
请更新到最新版，期间某个版本已经放弃了反射操作了。
