### ISSUE TITLE
最新版本 demo中输入法适配 点击发送，不会走点击事件

### ISSUE THREAD

**Issue by pengjunhong** [razerdp/BasePopup#386]

**Comment by razerdp** [comment]
请按照规范提出issue，本issue将被忽略。

**Comment by pengjunhong** [comment]
### 提issue前请去[**WIKI#常见问题**](https://www.yuque.com/razerdp/basepopup/dgf6ry)查询相关问题，避免重复提问
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### 提issue前请务必参考以下格式填写，否则该问题会被直接关闭。
### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：这边测试华为p10plus 9.0 红米3s6.0还有vivo10.0都会有这个问题
 - 库版本（必须）/ Library version (required)：2.2.13最新版本
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
Demo中输入法适配，点击发送。不会触发点击事件
