### ISSUE TITLE
如何优雅支持viewbinding

### ISSUE THREAD

**Issue by zwping** [razerdp/BasePopup#387]
- 系统版本：android 11
 - 库版本：2.2.13

如题

**Comment by razerdp** [comment]
如demo所示，onViewCreate中绑定。

**Comment by razerdp** [comment]
噢噢噢，当时好像是群里讨论来着，没弄到demo上，不过demo是onViewCreate中绑定butterknife，你也可以在那inflate你的viewbinding

**Comment by zwping** [comment]
ok

**Comment by zhifeiji1994** [comment]
怎么使用viewbinding阿   能否给个demo

**Comment by razerdp** [comment]
> 怎么使用viewbinding阿   能否给个demo

使用手册有
