### ISSUE TITLE
最新版本bug

### ISSUE THREAD

**Issue by pengjunhong** [razerdp/BasePopup#388]
提issue前请去WIKI#常见问题查询相关问题，避免重复提问
Please go to WIKI#FAQ for relevant questions before commit your issue to avoid repetitive questions.

提issue前请务必参考以下格式填写，否则该问题会被直接关闭。
Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!
系统版本（必须）/ System version (required)：这边测试华为p10plus 9.0 红米3s6.0还有vivo10.0都会有这个问题
库版本（必须）/ Library version (required)：2.2.13最新版本
问题代码/截图（可选）/ Problem code or screenshot (optional)：
报错信息（可选）/ Error reporting information (optional)：
问题描述/重现步骤请写在这里
Demo中输入法适配，点击发送。不会触发点击事件

**Comment by razerdp** [comment]
已经验证。

不过很奇怪的是。。。ui上显示在上方，但实际上还在下方。。这是个神奇的问题（我用的是属性动画）

![微信截图_20210119165301](https://user-images.githubusercontent.com/11629986/105010575-dcae8e00-5a76-11eb-9229-62808eba32ae.png)

**Comment by pengjunhong** [comment]
但是点击的时候 记录的 xy坐标是在软键盘弹出之后，PopupDecorViewProxy类中dispatchTouchEvent（）方法，!touchableRect.contains(x, y)判断点击的xy坐标不属于可触摸的区域，执行了mMaskLayout.dispatchTouchEvent(ev)导致被底部阴影消耗点击事件。

**Comment by razerdp** [comment]
嗯嗯，刚刚试了下，发现单纯位移没触发layout，所以导致你所说的地方会出现这个bug，我修复一下~

**Comment by razerdp** [comment]
这是个严重bug，我会先上candy，然后测试一下更多类似场景，也希望待会您可以提供一下修复版本的测试情况·

**Comment by pengjunhong** [comment]
好的

**Comment by razerdp** [comment]
* **【Candy】2.2.14.0119** (2021/01/19)
  * 修复一个严重bug：适配键盘后导致触摸事件分发错误 [#388](https://github.com/razerdp/BasePopup/issues/388)

同时demo已经更新，重新打开或者主界面右上角检查更新即可更新demo

**Comment by pengjunhong** [comment]
好

**Comment by pengjunhong** [comment]
经测试 bug已修复
