### ISSUE TITLE
显示位置

### ISSUE THREAD

**Issue by meihuali** [razerdp/BasePopup#39]
那个点击 某个按钮的时候 到底那个显示 popwup 那个坐标到底是怎么计算的啊·可不可以说的详细点啊·其他的都还比较好用·就是这个 计算这个坐标 写的 不够详细·我根本 搞不明白·

**Comment by razerdp** [comment]
@meihuali 

调用showPopupWindow(View v)时，会有跟showAsDropDown一样的效果，就是在目标View的下方，此时你需要进行便宜的话，比如我显示在这个View的左边同时中间对齐。

那么这个offsetX就是目标View（也就是你所说的显示在某个按钮下面的按钮）的宽度
offsetY就是你的popup自身高度的一半（getHeight()/2）

具体看wiki中的示例代码，里面有链接到仿微信评论弹框的源码

see link:[展示到某个View的相对位置](https://github.com/razerdp/BasePopup/wiki/5.-%E5%B1%95%E7%A4%BA%E5%88%B0%E6%9F%90%E4%B8%AAView%E7%9A%84%E7%9B%B8%E5%AF%B9%E4%BD%8D%E7%BD%AE)

**Comment by razerdp** [comment]
ps   :默认显示在下方一般指popup的锚点（即布局的左上角）对齐目标View的左下角。（当popup是wrap_content时）
