### ISSUE TITLE
我这的情况是有3个弹窗的时候调用 BasePopupUnsafe.INSTANCE.dismissAllPopup(false);的时候崩溃

### ISSUE THREAD

**Issue by tianchenxingzi** [razerdp/BasePopup#391]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：android 10 MIUI12.0.4
 - 库版本（必须）/ Library version (required)：2.2.4.1
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：
java.util.ConcurrentModificationException
at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
at java.util.LinkedList$ListItr.next(LinkedList.java:888)
at razerdp.basepopup.BasePopupUnsafe.dismissAllPopup(BasePopupUnsafe.java:38)
---

> 问题描述/重现步骤请写在这里
情况是这样的，我这有一个弹窗A是显示3秒后关闭的，点击A的逻辑也是关闭弹窗。
在弹窗A出现的时候有个正常的弹窗B出来，点击A执行 BasePopupUnsafe.INSTANCE.dismissAllPopup(false);可以关闭两个弹窗没有问题。
当有两个弹窗A和一个弹窗B出现的时候点击A执行  BasePopupUnsafe.INSTANCE.dismissAllPopup(false);的时候报上述错误

> Please write the description here.

**Comment by razerdp** [comment]
11，这是因为我在for循环里进行了remove，我改一下

**Comment by razerdp** [comment]
【Candy】2.2.30.210205 已修复

**Comment by razerdp** [comment]
release 2.2.30已发布
