### ISSUE TITLE
View.setVisibility()方法无效了

### ISSUE THREAD

**Issue by eternallyjie** [razerdp/BasePopup#392]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：Android 11 miui12.5 21.1.29
 - 库版本（必须）/ Library version (required)：2.2.18
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
在从2.2.11更新到2.2.18后，本来在一个弹窗里会有几个button，然后根据状态改变button的visible和gone。但是更新之后View.setVisibility()方法失效了。

**Comment by razerdp** [comment]
本质上你的view只是我的子控件……我不会干预这一块地方的哦。

请检查下是否有别的地方修改过visibility

**Comment by eternallyjie** [comment]
> 本质上你的view只是我的子控件……我不会干预这一块地方的哦。
> 
> 请检查下是否有别的地方修改过visibility

代码没有动过的，2.2.11是好的，升级到2.2.18还是一样的代码，就失效了。

**Comment by eternallyjie** [comment]
我上传一下demo，你看一下
[PopupTest.zip](https://github.com/razerdp/BasePopup/files/5915646/PopupTest.zip)

**Comment by eternallyjie** [comment]
> 本质上你的view只是我的子控件……我不会干预这一块地方的哦。
> 
> 请检查下是否有别的地方修改过visibility

我上传一下demo，你看一下
[PopupTest.zip](https://github.com/razerdp/BasePopup/files/5915648/PopupTest.zip)

**Comment by razerdp** [comment]
噢~这个问题实际上是跟这个问题一样的 https://github.com/razerdp/BasePopup/issues/389

candy最新版其实已经修复了。。我一直忘了发布release，您稍等

**Comment by razerdp** [comment]
问题原因在这里：
https://github.com/razerdp/BasePopup/issues/389#issuecomment-767276852

跟visible没啥关系哈~

**Comment by razerdp** [comment]
【Release】2.2.20 (2021/02/03)
请更新到该版本~
修复PopupDecorProxy多次测量时出现的测量取值问题#389
修复适配键盘后触发requestLayout()导致触摸判断错误的问题#390
