### ISSUE TITLE
点击pop阴影区域穿透了底层事件

### ISSUE THREAD

**Issue by kimiangel** [razerdp/BasePopup#393]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：29
 - 库版本（必须）/ Library version (required)：2.2.9
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

我设置了 pop.setOutSideTouchable(true);这个属性，让外部和pop都能点击，但是我想让点击阴影区域关闭pop，结果却是点击阴影部分穿透了点击事件，进行了跳转。
![image](https://user-images.githubusercontent.com/10664586/106727779-c7288f00-6646-11eb-8197-988b964c67f8.png)

**Comment by razerdp** [comment]
setOutSideTouchable(true)这个函数就是除了popup内容区域外的地方全部透传。。。那肯定会穿透哇= =

**Comment by razerdp** [comment]
你可以override onOutSideTouch() 去实现针对不同区域有不同的逻辑

**Comment by kimiangel** [comment]
这一整块区域，那我怎么知道点击的是什么区域，有方法吗？

**Comment by kimiangel** [comment]
我点击了阴影部分，没有回调这个onOutSideTouch

**Comment by kimiangel** [comment]
问题解决了，谢谢

**Comment by razerdp** [comment]
如何解决的。。我还想着要不要加个api= =

**Comment by razerdp** [comment]
不过不管如何，针对您的这个需求，我优化了onOutSideTouch

* **【Candy】2.2.30.210205** (2021/02/05)
    * 针对[issue#393](https://github.com/razerdp/BasePopup/issues/393)所述需求，onOutSideTouch增加两个参数：
        * MotionEvent event：触摸事件
        * boolean touchInMask：是否点击在蒙层

**Comment by kimiangel** [comment]
我去掉了系统自带的蒙层，自己加了个蒙层然后设置了点击事件，就没有穿透了，还有一个办法就是在穿透事件的时候判断dailog是否关闭，这两种办法都可以实现

**Comment by razerdp** [comment]
噢~用自己的background，确实可以。你不说我都忘了这个api了

**Comment by razerdp** [comment]
candy新版也增加了outsidetouch的api，能更轻松的完成你的需求了。

**Comment by razerdp** [comment]
release 2.2.30已发布

**Comment by guodonghuang** [comment]
设置setOutSideTouchable(true);后并不能真正穿透，比如蒙层外边有个Button，当显示蒙层的时候点击Button，Button虽然被点击了，实际上没有执行，感觉并没有走ACTION_UP,只走了ACTION_DOWN,为什么呀;

**Comment by razerdp** [comment]
> 设置setOutSideTouchable(true);后并不能真正穿透，比如蒙层外边有个Button，当显示蒙层的时候点击Button，Button虽然被点击了，实际上没有执行，感觉并没有走ACTION_UP,只走了ACTION_DOWN,为什么呀;

什么版本。

**Comment by razerdp** [comment]
> 设置setOutSideTouchable(true);后并不能真正穿透，比如蒙层外边有个Button，当显示蒙层的时候点击Button，Button虽然被点击了，实际上没有执行，感觉并没有走ACTION_UP,只走了ACTION_DOWN,为什么呀;

噢，确实会有这个问题，我刚刚查了下。

![微信截图_20210603165737](https://user-images.githubusercontent.com/11629986/120617607-dd2b4c80-c48c-11eb-86b2-34817bf7f5c7.png)

问题在图中红框位置，down事件时，basepopup的onOutSideTouch是返回false的，这时候事件传递到底层（即anchorview）。而up的时候是返回true，此时被拦截了，所以效果就是你所说的。

这是个bug，outsidetouch的时候事件理应是先给外部再给内部。

我这边修复一下

**Comment by razerdp** [comment]
> 设置setOutSideTouchable(true);后并不能真正穿透，比如蒙层外边有个Button，当显示蒙层的时候点击Button，Button虽然被点击了，实际上没有执行，感觉并没有走ACTION_UP,只走了ACTION_DOWN,为什么呀;

fixed in 3.1.1-SNAPSHOT

**Comment by guodonghuang** [comment]
> > 设置setOutSideTouchable(true);后并不能真正穿透，比如蒙层外边有个Button，当显示蒙层的时候点击Button，Button虽然被点击了，实际上没有执行，感觉并没有走ACTION_UP,只走了ACTION_DOWN,为什么呀;
> 
> fixed in 3.1.1-SNAPSHOT

好的，收到

**Comment by ruiyong-lee** [comment]
3.2.0似乎又不行了，demo上面的试了也是不行

**Comment by razerdp** [comment]
> 3.2.0似乎又不行了，demo上面的试了也是不行

请不要在已经关闭的issue下回复。。。最好提出新issue并ref到这里

另外我试了下demo，好像没啥毛病
