### ISSUE TITLE
6.0系统上显示异常

### ISSUE THREAD

**Issue by itsgm** [razerdp/BasePopup#394]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：6.0
 - 库版本（必须）/ Library version (required)：2.2.20
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
根布局用的 android:layout_width="match_parent"
    android:layout_height="match_parent"
我的popup代码里面用到了测量，定位箭头的位置
   LinearLayout.LayoutParams layoutParams = (LinearLayout.LayoutParams) iv_arrow.getLayoutParams();
        layoutParams.rightMargin = SizeUtils.dp2px(21) + widthOrder + widthCart / 2;
        iv_arrow.setLayoutParams(layoutParams);
使用android6.0系统，2.2.10版本上显示正常，升级到2.2.20以后显示不正常
使用android10的系统是正常的

**Comment by razerdp** [comment]
有demo吗

ps，尽量用offset或layout，param会导致request进而导致重新测量，从而触发popup整个定位。

详情可以看看demo或者文档里关于箭头的描述

**Comment by itsgm** [comment]
> 有demo吗
> 
> ps，尽量用offset或layout，param会导致request进而导致重新测量，从而触发popup整个定位。
> 
> 详情可以看看demo或者文档里关于箭头的描述

@razerdp 描述一下我的使用场景，是横屏的购物车弹窗占满屏幕的三分之二靠右显示，我pop布局宽高都是用的match_parent
我让布局靠右显示，箭头也是靠最右底部，由于我这边箭头固定在一个底部按钮的正上面，按钮的长度不固定，每次显示弹窗计算一下箭头的位置
2.2.20关于测量这块改了什么，为什么在6.0系统上不适配了啊，很奇怪2.2.10就是正常

**Comment by razerdp** [comment]
有demo吗。。我无法复现

**Comment by razerdp** [comment]
无后续反馈，关闭。
