### ISSUE TITLE
怎么确保构造方法传入参数实例化完成后，再进行后续动作

### ISSUE THREAD

**Issue by RealMoMo** [razerdp/BasePopup#395]
### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：Android8.0
 - 库版本（必须）/ Library version (required)：2.2.7
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 
![image](https://user-images.githubusercontent.com/22723389/109374349-bc80b300-78ef-11eb-9d2c-eda48a499ad6.png)

 - 报错信息（可选）/ Error reporting information (optional)：
devicebean 空指针导致，怎么确保构造方法传入参数实例化完成后，再进行后续动作？
---

**Comment by razerdp** [comment]
继承BaseLazyPopupWindow

其他问题请查阅文档：
https://www.yuque.com/razerdp/basepopup/thgnsi
