### ISSUE TITLE
[help wanted]popup 弹出的时候有没有办法让背景不变暗

### ISSUE THREAD

**Issue by fantasyado** [razerdp/BasePopup#396]
文档里没找到，求助

**Comment by razerdp** [comment]
。。文档里就有

https://www.yuque.com/razerdp/basepopup/gscx3g

**Comment by fantasyado** [comment]
> 。。文档里就有
> 
> https://www.yuque.com/razerdp/basepopup/gscx3g

多谢多谢，有点着急，提测了之后qa突然搞人
