### ISSUE TITLE
安卓10 app小窗模式下显示popupwindow尺寸异常

### ISSUE THREAD

**Issue by FlyMantou** [razerdp/BasePopup#397]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：安卓10
 - 库版本（必须）/ Library version (required)：2.2.20
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
切换app为小窗模式，弹出popupwindow

![QQ图片20210305183218](https://user-images.githubusercontent.com/15058342/110103664-23670600-7de1-11eb-8d0b-280d013eb1bb.jpg)

**Comment by FlyMantou** [comment]
使用 resources.configuration.screenWidthDp 获取到宽度给pop设置之后，pop宽度正常了，但是半透明背景还是全屏状态
![581AA1781473A4787A2D823044C5B2A4](https://user-images.githubusercontent.com/15058342/110192529-8ac89880-7e69-11eb-8a12-fcbc1e0cfdb0.jpg)

**Comment by razerdp** [comment]
目前basepopup暂未适配分屏、小窗这类显示。。。等我有空后我去康康

**Comment by razerdp** [comment]
我重新试了下，在我的小米上是正常的，也是Android 10。。。

感觉是系统的锅？

![device-2021-04-28-145428](https://user-images.githubusercontent.com/11629986/116359706-b183c980-a831-11eb-91ae-56d55b7f9833.png)

**Comment by razerdp** [comment]
无法复现&无后续反馈，关闭。
