### ISSUE TITLE
关于是否覆盖状态栏和导航栏的问题

### ISSUE THREAD

**Issue by eternallyjie** [razerdp/BasePopup#398]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：Android 11
 - 库版本（必须）/ Library version (required)：2.2.20
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

请问是否可以开放在弹出popup的时候设置导航栏和状态栏的颜色呢？因为现在设置Mask覆盖导航栏和状态栏，contentView不覆盖的情况下，导航栏的颜色是蒙层的颜色，跟contentView底部的颜色可能会不一样，总看起来怪怪的。

**Comment by razerdp** [comment]
这个建议你在onShow中拿到activity进行设置哦~如果弹窗修改宿主颜色的话就是越界了，会越来越乱的。
