### ISSUE TITLE
能否动态修改文字

### ISSUE THREAD

**Issue by AnmLobby** [razerdp/BasePopup#399]
QuickPopupBuilder.with(getBaseFragmentActivity())
                .contentView(R.layout.popup_updata)
                .config(new QuickPopupConfig()
                        .withShowAnimation(AnimationHelper.asAnimation()
                                .withScale(ScaleConfig.CENTER)
                                .toShow())
                        .withDismissAnimation(AnimationHelper.asAnimation()
                                .withScale(ScaleConfig.CENTER)
                                .toDismiss())
                        .withClick(R.id.tv_go, null, true)
                        .blurBackground(true)
                        .outSideDismiss(false))
                .show();

能否获取到layout的textview id来动态修改文字？

**Comment by razerdp** [comment]
可以考虑~

**Comment by razerdp** [comment]
思考了一下，没有一个很好的方案解决。因为这次是文字修改，下次是图片修改，，我也不可能把这堆api都集合在一起吧。。。
