### ISSUE TITLE
是否可以新增一个方法让popupwindow覆盖在状态栏上

### ISSUE THREAD

**Issue by ForgetAll** [razerdp/BasePopup#4]
is it possible to create a new method to make the popupwindow cover the statusbar

**Comment by ForgetAll** [comment]
昨天我找了一点资料，没发现有直接让popupwindow覆盖在状态栏上的办法，有一个隐藏的api可以setLayoutType但是是api23加入的，就算通过反射能拿到使用兼容性也太差了。有一个可行的办法是在activity里getWidnow().addFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);让布局可以延伸到状态栏，这的确解决了popupwindow覆盖状态栏的问题，但是你的顶部布局也会延伸到状态栏，所以还需要做一些调试的工作。

**Comment by razerdp** [comment]
@ForgetAll 这个问题我当初也遇到过，在编译版本>21时会出现popup在状态栏以下的问题，当时去sof找了一下但没有一个确切的解决方案，所以一直放着没解决，近期我会去尝试解决一下，如果有进展我会在这里回复你的。

**Comment by razerdp** [comment]
@ForgetAll 刚刚再次看了一下源码，其实跟一个参数有关：mAttachedInDecor，他影响到的是windowmanager的一个Flag:WindowManager.LayoutParams.FLAG_LAYOUT_ATTACHED_IN_DECOR，虽然直接有暴露api是setAttachedInDecor，但在api>22以上才有

**Comment by ForgetAll** [comment]
涉及到状态栏的东西弄起来都有点蛋疼

**Comment by razerdp** [comment]
@ForgetAll 我修正了一下，刚刚push了(master分支)，解决方案稍微粗暴了一点，直接反射mClippingEnabled这个东东，你试试，如果有更好的方案也可以讨论一下-V-

**Comment by razerdp** [comment]
@ForgetAll demo增加了full screen pop这个frag，背景是红色的，方便测试。。。

**Comment by razerdp** [comment]
@ForgetAll 已经增加了方法setPopupWindowFullScreen(boolean)了

**Comment by haohaozaici** [comment]
我在视频播放过程中显示popup时退出了沉浸状态，观察到`PopupCompatManager`类中`initSystemBar()`方法被注释了，不知道现在有没有解决这个问题，不过我找到了比较好的解决办法。

参考了这篇文章，[沉浸式中显示 PopupWindow](http://relex.me/show-popupwindow-in-immersive-mode/)
> 退出沉浸式的原因是因为 Activity 的 Window 焦点被抢走了，Window 中的 DecorView 状态改变导致了退出。

解决办法：先在失焦的状态，弹出 PopupWindow ， 再对 PopupWindow 的 DecorView 设置 setSystemUiVisibility ，最后获取焦点即可。
具体代码：
``` java
public static void fullScreen(View view) {
    if (Build.VERSION.SDK_INT >= 19) {
        view.setSystemUiVisibility(
                View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                        | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                        | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                        | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                        | View.SYSTEM_UI_FLAG_FULLSCREEN
                        | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
    }
}

private void showPopupWindow(PopupWindow popupWindow) {
    popupWindow.setFocusable(false);
    popupWindow.update();
    popupWindow.showAtLocation(ivMenu, Gravity.RIGHT, 0, 0);
    popupWindow.setFocusable(true);
    popupWindow.update();
}
```

最终实现了类似哔哩哔哩播放器设置界面的效果

**Comment by razerdp** [comment]
@haohaozaici  initSystemBar其实跟你展示的代码差不多的，因为发现这个方法目前有bug，因此暂时弃用。这些在2.0会修复的。

目前2.0基本完工，但等待android P正式版发布来决定是否需要native来适配P，因此一直没有更新。

**Comment by haohaozaici** [comment]
@razerdp 感谢回复~ 期待更新
