### ISSUE TITLE
能解决popupwindow里面无法使用viewpager的问题么

### ISSUE THREAD

**Issue by baiyulinlin** [razerdp/BasePopup#40]
加载viewpager的时候无法获取到它的id

**Comment by razerdp** [comment]
理论上是可以的，我待会查一下

**Comment by Wade-Cai** [comment]
popupwindow好像是不能使用viewpager+fragment的，我在用的时候直接布局出不来，可以使用的方式是viewpager+view的方式，如果要使用viewpager+fragment我看是用DialogFragment就能解决

**Comment by razerdp** [comment]
@Wade-Cai 你说得对，popupwindow理论上来说是不可以用vp+fragment的，其中最主要的原因是：
`FragmentPagerAdapter`需要`FragmentManager`，而popupwindow根本上来说是往windowmanager添加一个生成的View，所以是不可以用viewpager+fragment，换成view就可以

@baiyulinlin
