### ISSUE TITLE
弹窗内View的点击事件被outside拦截无法触发

### ISSUE THREAD

**Issue by ozyl** [razerdp/BasePopup#400]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：Android10
 - 库版本（必须）/ Library version (required)：release2.2.20、candy2.2.30.0319 
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
新版本在部分手机（小米8、小米9cc）上偶现弹窗内View的点击事件被outside拦截无法触发，内部是recyclerView。2.2.7版本没有问题

```
   BasePopupWindow(final Object ownerAnchorParent, final int width, final int height, int flag) {
        this.ownerAnchorParent = ownerAnchorParent;
        checkActivity();
        mHelper = new BasePopupHelper(this);
        initRunnable = new Runnable() {
            @Override
            public void run() {
//这里如果执行的慢了，就会出现这个问题。打个断点必现
                onCreateConstructor(ownerAnchorParent, width, height);
                initView(width, height);
            }
        };
        if (getContext() == null) return;
        initRunnable.run();
        initRunnable = null;
    }
```

**Comment by razerdp** [comment]
额，啥意思。。。有demo吗，

**Comment by ozyl** [comment]
adapter的itemClick不执行。事件没分发到。没demo

**Comment by razerdp** [comment]
不能复现诶。。。demo中issue #230 就有recyclerview的测试，按钮一切正常

**Comment by razerdp** [comment]
无后续反馈，关闭。
