### ISSUE TITLE
弹窗闪一下马上dismiss掉了

### ISSUE THREAD

**Issue by Gavin-arod** [razerdp/BasePopup#401]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：Android 10
 - 库版本（必须）/ Library version (required)：2.2.9
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
前提：PopWindow dismiss或者show都会显示动画效果；
前一个PopWindow调用dismiss，在其动画还没执行完毕的时候，后一个PopWindow调用show显示，但是后一个PopWindow此时有可能闪烁一下就消失了，请问下这个问题要怎么优化？

**Comment by razerdp** [comment]
你可能调用了同一个对象。

**Comment by Gavin-arod** [comment]
> 你可能调用了同一个对象。

是同一个PopWindow对象，这种情况有什么办法可以避免吗？

**Comment by razerdp** [comment]
有复现demo或者代码片段吗？

showpopup的时候会判断是否showing的，如果执行了dismiss，在完全dismiss之前isshowing是true的，此时show的话会return掉，所以理论上来说popup会无法执行showpopup

**Comment by Gavin-arod** [comment]
> 有复现demo或者代码片段吗？
> 
> showpopup的时候会判断是否showing的，如果执行了dismiss，在完全dismiss之前isshowing是true的，此时show的话会return掉，所以理论上来说popup会无法执行showpopup

这种情况很难复现，只出现一次，后面怎么都测不出来

**Comment by razerdp** [comment]
我也试了好多下，还是没法弄出来= =这个问题等稳定复现才去解决吧~暂时关闭先
