### ISSUE TITLE
实现类似AutoCompleteTextView弹窗的效果

### ISSUE THREAD

**Issue by 287138531** [razerdp/BasePopup#402]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：
 - 库版本（必须）/ Library version (required)：最新版
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

能实现AutoCompleteTextView那种弹窗的效果吗，输入完弹出pop，不抢占输入框的焦点，还有和et同宽度

**Comment by razerdp** [comment]
duplicate #224

**Comment by razerdp** [comment]
不过这个issue只是临时测试用的，我迟点弄个demo塞到popup的demo里面吧
