### ISSUE TITLE
点击弹窗子View触发dismiss

### ISSUE THREAD

**Issue by dzq0906** [razerdp/BasePopup#405]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：API29，AP30
 - 库版本（必须）/ Library version (required)：2.2.20
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：偶现底部弹窗点击弹窗里面的子view 触发dismiss 只有第一次的时候会这样，重新打开就正常了
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

布局：
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom"
    android:background="@drawable/popup_gd_bg">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp_80"
        android:orientation="horizontal"
        android:layout_marginTop="@dimen/dp_20">

        <LinearLayout
            android:id="@+id/zwz_bt"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:gravity="center"
            android:visibility="gone">

            <ImageView
                android:layout_width="@dimen/dp_40"
                android:layout_height="@dimen/dp_40"
                android:src="@mipmap/zwz_icon"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="转文字"
                android:textSize="@dimen/sp_12"
                android:textColor="#4d4b4c"
                android:layout_marginTop="@dimen/dp_5"/>

        </LinearLayout>

        <LinearLayout
            android:id="@+id/jianji_bt"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:gravity="center">

            <ImageView
                android:layout_width="@dimen/dp_40"
                android:layout_height="@dimen/dp_40"
                android:src="@mipmap/jz_icon"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="剪辑"
                android:textSize="@dimen/sp_12"
                android:textColor="#4d4b4c"
                android:layout_marginTop="@dimen/dp_5"/>

        </LinearLayout>

        <LinearLayout
            android:id="@+id/tomp3_bt"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:gravity="center">

            <ImageView
                android:layout_width="@dimen/dp_40"
                android:layout_height="@dimen/dp_40"
                android:src="@mipmap/zgs_icon"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="转格式"
                android:textSize="@dimen/sp_12"
                android:textColor="#4d4b4c"
                android:layout_marginTop="@dimen/dp_5"/>

        </LinearLayout>

        <LinearLayout
            android:id="@+id/cmm_bt"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:gravity="center">

            <ImageView
                android:layout_width="@dimen/dp_40"
                android:layout_height="@dimen/dp_40"
                android:src="@mipmap/cmm_icon"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="重命名"
                android:textSize="@dimen/sp_12"
                android:textColor="#4d4b4c"
                android:layout_marginTop="@dimen/dp_5"/>

        </LinearLayout>

        <LinearLayout
            android:id="@+id/delect_bt"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="match_parent"
            android:orientation="vertical"
            android:gravity="center">

            <ImageView
                android:layout_width="@dimen/dp_40"
                android:layout_height="@dimen/dp_40"
                android:src="@mipmap/sc_icon"/>

            <TextView
                android:id="@+id/sc_bt"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="删除"
                android:textSize="@dimen/sp_12"
                android:textColor="#4d4b4c"
                android:layout_marginTop="@dimen/dp_5"/>

        </LinearLayout>

    </LinearLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp_0_5"
        android:background="#61cacaca"
        android:layout_marginHorizontal="@dimen/dp_10"/>

    <RelativeLayout
        android:id="@+id/dismiss_bt"
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp_50"
        android:layout_marginBottom="@dimen/dp_40">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:textColor="#262626"
            android:textSize="@dimen/sp_15"
            android:text="取消"/>

    </RelativeLayout>

</LinearLayout>

不知道是不是设置底部边距的问题，更换2.2.13 就没有这个问题了

**Comment by dzq0906** [comment]
在vivo手机上  底部弹窗会被底部虚拟按键遮挡

**Comment by razerdp** [comment]
我试了一下，没有重现哦，是不是代码写过什么= =

**Comment by dzq0906** [comment]
if (AppUtils.getNavigationBarHeight(getContext()) > 0){
                    LinearLayout.LayoutParams layoutParams = (LinearLayout.LayoutParams)submitRl.getLayoutParams();
                    layoutParams.bottomMargin = SizeUtils.dp2px(40);
                    submitRl.setLayoutParams(layoutParams);
                }

**Comment by dzq0906** [comment]
if (AppUtils.getNavigationBarHeight(getContext()) > 0){
                    LinearLayout.LayoutParams layoutParams = (LinearLayout.LayoutParams)submitRl.getLayoutParams();
                    layoutParams.bottomMargin = SizeUtils.dp2px(40);
                    submitRl.setLayoutParams(layoutParams);
}
之前判断了是否有虚拟按键  加了底部的边距 后面又把这个代码删掉了 我以为是这个代码的问题  但是删掉了也还是偶现了这个问题

**Comment by dzq0906** [comment]
&nbsp;if (AppUtils.getNavigationBarHeight(getContext()) &gt; 0){
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; LinearLayout.LayoutParams layoutParams = (LinearLayout.LayoutParams)submitRl.getLayoutParams();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; layoutParams.bottomMargin = SizeUtils.dp2px(40);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; submitRl.setLayoutParams(layoutParams);
}
之前判断了是否有虚拟按键&nbsp; 加了底部的边距 后面又把这个代码删掉了 我以为是这个代码的问题&nbsp; 但是删掉了也还是偶现了这个问题







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月19日(星期一) 上午10:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [razerdp/BasePopup] 点击弹窗子View触发dismiss (#405)





 
我试了一下，没有重现哦，是不是代码写过什么= =

**Comment by mtj956052456** [comment]
VIVO确实会出现这个问题

**Comment by razerdp** [comment]
我近期找群里有vivo手机的人试试

**Comment by razerdp** [comment]
群里没有vivo手机。。。你们可以加readme的小号进群看看

**Comment by razerdp** [comment]
@dzq0906 

根据你的布局，真的没法重现。。。

![ezgif-3-e6175c3c3d86 (1)](https://user-images.githubusercontent.com/11629986/116361536-ab8ee800-a833-11eb-9629-533f99ffe24a.gif)

**Comment by dzq0906** [comment]
不行就算了吧&nbsp; 这个也是偶现&nbsp; 问题不大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月28日(周三) 下午3:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [razerdp/BasePopup] 点击弹窗子View触发dismiss (#405)




 
@dzq0906
 
根据你的布局，真的没法重现。。。

**Comment by razerdp** [comment]
ok，关闭啦~
