### ISSUE TITLE
dialogFragment显示问题

### ISSUE THREAD

**Issue by yong396040003** [razerdp/BasePopup#407]
public static class TestDialogFragment extends DialogFragment {
        View.OnClickListener mOnClickListener;

        @Nullable
        @Override
        public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
            View contentView = inflater.inflate(R.layout.dialog_fragment_api_constructor, container, false);
            View tvShow = contentView.findViewById(R.id.tv_show);
            tvShow.setOnClickListener(v -> {
                //if (mOnClickListener != null) {

                    DemoPopup curPopup = new DemoPopup(this);
                    curPopup.setPopupGravity(Gravity.BOTTOM);
                    //测试demo中，这个curPopup无法显示到tvShow的底部
                    curPopup.showPopupWindow(tvShow);
               // }
            });
            return contentView;
        }

        @Override
        public void onStart() {
            super.onStart();
            Window dialogWindow = getDialog().getWindow();
            if (dialogWindow != null) {
                WindowManager.LayoutParams lp = dialogWindow.getAttributes();
                lp.width = Math.round(UIHelper.getScreenWidth() * 0.8f);
                lp.height = ViewGroup.LayoutParams.WRAP_CONTENT;
                lp.gravity = Gravity.CENTER;
                dialogWindow.setAttributes(lp);
            }
        }

        public TestDialogFragment setOnClickListener(View.OnClickListener onClickListener) {
            mOnClickListener = onClickListener;
            return this;
        }
    }
//测试demo中，这个curPopup无法显示到tvShow的底部

**Comment by yong396040003** [comment]
![image](https://user-images.githubusercontent.com/40829642/115201196-a04b0680-a127-11eb-8057-003ee282b5a6.png)
最后显示结果是这样的

**Comment by razerdp** [comment]
这是因为popup要超出屏幕了，所以会顶回来

**Comment by yong396040003** [comment]
![image](https://user-images.githubusercontent.com/40829642/115201868-5ca4cc80-a128-11eb-95d0-446c9920fdb8.png)
请问一下，如何把下面的popupWindow放在上面《请点击我弹出basePopup》文字下面呢？

**Comment by razerdp** [comment]
textview改为wrap_content咯。。。demo中我写了300dp，所以才会离文字那么远

**Comment by razerdp** [comment]
![微信截图_20210419163259](https://user-images.githubusercontent.com/11629986/115206221-f4a4b500-a12c-11eb-96c8-60e932dfdf56.png)

**Comment by yong396040003** [comment]
不好意思，是我的问题，我当前用的版本是2.2.3的，当我升级到2.2.20的时候问题就解决了，感谢。
