### ISSUE TITLE
申请成为开发者

### ISSUE THREAD

**Issue by liruixing** [razerdp/BasePopup#408]
目前库不允许  contentView() 函数不支持传递View ；
导致一些比较复杂的view，需要根据外部逻辑控制pop中的view；

**Comment by razerdp** [comment]
这种情况我更建议内聚到popup内部，只提供需要的api给外部调用。

**Comment by razerdp** [comment]
另外可以加一下readme的小号进群聊聊，很欢迎一起迭代这个库。

**Comment by razerdp** [comment]
无后续反馈，关闭
