### ISSUE TITLE
VIVO  9.0系统 弹窗叠加弹窗点击事件失效 库版本2.2.20

### ISSUE THREAD

**Issue by mtj956052456** [razerdp/BasePopup#409]
华为10.0一切正常，测试人员在测试的时候发现的这个问题
弹窗叠加弹窗点击事件失效，在进入新的activity，网络请求数据异常时会弹出一个POP，里面TextView的点击事件不能用。

**Comment by razerdp** [comment]
有测试代码吗。

**Comment by razerdp** [comment]
另外请按照格式提问。

**Comment by razerdp** [comment]
能加一下readme所说小号进群聊一下吗，我发现群里没有人有vivo。。。

**Comment by razerdp** [comment]
无后续反馈，关闭。
