### ISSUE TITLE
setBackPressEnable 返回键的问题

### ISSUE THREAD

**Issue by Wade-Cai** [razerdp/BasePopup#41]
手机nexus6 版本6.0， 

1.8.0版本setBackPressEnable有效

1.8.4版本setBackPressEnable无效

**Comment by razerdp** [comment]
@Wade-Cai 收到-V- 待会我测试一下

**Comment by razerdp** [comment]
@Wade-Cai 

暂时无法修复呢。。。残念（首页README已经补充）

https://github.com/razerdp/BasePopup/blob/master/%E5%85%B3%E4%BA%8EAndorid%20M%E4%BB%A5%E4%B8%8AsetBackPressEnable()%E5%A4%B1%E6%95%88%E7%9A%84%E9%97%AE%E9%A2%98%E7%9A%84%E5%88%86%E6%9E%90.md

**Comment by razerdp** [comment]
#33
