### ISSUE TITLE
JCenter要关闭了何时迁移到maven啊

### ISSUE THREAD

**Issue by hyl87** [razerdp/BasePopup#410]
2.2.30我这里拉不下来了

**Comment by suojiang** [comment]
Could not find com.github.razerdp:BasePopup:2.2.30.
Searched in the following locations:
  - https://dl.bintray.com/umsdk/release/com/github/razerdp/BasePopup/2.2.30/BasePopup-2.2.30.pom
  - https://dl.google.com/dl/android/maven2/com/github/razerdp/BasePopup/2.2.30/BasePopup-2.2.30.pom
  - https://jcenter.bintray.com/com/github/razerdp/BasePopup/2.2.30/BasePopup-2.2.30.pom
  - https://repo.maven.apache.org/maven2/com/github/razerdp/BasePopup/2.2.30/BasePopup-2.2.30.pom
  - https://jitpack.io/com/github/razerdp/BasePopup/2.2.30/BasePopup-2.2.30.pom
最新版 2.2.30 添加依赖拉不下来

**Comment by razerdp** [comment]
噢，可能已经gg了，我迟点迁移到maven吧

**Comment by razerdp** [comment]
您好，仓库发布初步已经迁移到maven了，刚发布，估计等几个小时后才能在maven搜到。
https://search.maven.org/search?q=BasePopup

目前只是初步尝试，后续会更新readme和手册，本次迁移将会修改依赖的地址，具体请留意readme的更新，迁移完成后我也会在这里跟进。

**Comment by hyl87** [comment]
可以拉下来了

**Comment by razerdp** [comment]
已经迁移，请查看readme
