### ISSUE TITLE
点击弹窗外的按钮弹窗无法更新位置，而是关掉了

### ISSUE THREAD

**Issue by GodOfChen** [razerdp/BasePopup#412]
- 系统版本:Android 10
 - 库版本:2.2.20
> 问题描述/重现步骤请写在这里
我设置了弹窗点击外面可以触发dismiss，在已显示弹窗的情况下，我点击另一个按钮去更新弹窗位置和信息，但是弹窗直接关掉了，没有更新位置而是关掉了，我有点懵。想请教一下大佬，这是什么情况呢？

**Comment by razerdp** [comment]
如你第一句话所说。。。点击外面触发dismiss，那如果你点击外面不触发dismiss。。。这才是bug呀= =

**Comment by GodOfChen** [comment]
嗯！setAllowInterceptTouchEvent(false)&nbsp; &nbsp; &nbsp;setOutSideDismiss(true)，我设置了这两行代码。我点击了弹窗外另一个按钮是触发了dismiss，但是我这个按钮的点击事件也调用了showPopupWindow
，但是这个showPopupWindow方法不生效，没有弹出来，我要在这个按钮的事件里加个两秒的延时再调showPopupWindow它才会出来的！我个人感觉这样体验不是很好，所以冒昧打扰，提出这个问题。
（老版本是没有这种情况出现的）
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "razerdp/BasePopup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [razerdp/BasePopup] 点击弹窗外的按钮弹窗无法更新位置，而是关掉了 (#412)





 
如你第一句话所说。。。点击外面触发dismiss，那如果你点击外面不触发dismiss。。。这才是bug呀= =

**Comment by razerdp** [comment]
dismiss后立马show是无效的，因为真正dismiss是等主线程handler处理的时候才完成，此时弹窗实际上仍然是show的状态，此时你立刻show会直接return，所以就无效了。

**Comment by GodOfChen** [comment]
好的！谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "razerdp/BasePopup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [razerdp/BasePopup] 点击弹窗外的按钮弹窗无法更新位置，而是关掉了 (#412)





 
dismiss后立马show是无效的，因为真正dismiss是等主线程handler处理的时候才完成，此时弹窗实际上仍然是show的状态，此时你立刻show会直接return，所以就无效了。
