### ISSUE TITLE
如何让Popup边缘根据锚点自动调整?

### ISSUE THREAD

**Issue by kolyneh** [razerdp/BasePopup#413]
- 系统版本（必须）/ System version (required)：Android Emulator Pixel 3a API 30
 - 库版本（必须）/ Library version (required)：2.3.0 
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里

> Please write the description here.

如何让Popup边缘根据锚点自动调整，使得Popup 左边缘可以对齐锚点左边，或Popup 右边缘可以对齐锚点右边。

目前使用 `setPopupGravityMode(GravityMode.ALIGN_TO_ANCHOR_SIDE)` 没有达到期望效果，
截图如下：
锚点view边缘：
![Screenshot_1620896681](https://user-images.githubusercontent.com/13062910/118108048-1c2c2c00-b412-11eb-9183-7fe99839a7f3.png)
锚点view在左边时，popup可以对齐左边缘：
![Screenshot_1620896689](https://user-images.githubusercontent.com/13062910/118108082-251cfd80-b412-11eb-9b26-7b6b7807e71f.png)
锚点view在右边时，popup没有对齐右边缘：
![Screenshot_1620896693](https://user-images.githubusercontent.com/13062910/118108099-29491b00-b412-11eb-85e7-84c0de608ac1.png)

**Comment by razerdp** [comment]
anchor为左边的时候，gravity设置为left，anchor为右边的时候gravity设置为right。模式保持对边模式。

**Comment by kolyneh** [comment]
非常感谢！

但是依然会有点小问题，左右两个锚点复用同一个popup时，切换点击两个锚点弹出popup，在切换时会出现一次对齐到屏幕左或右边缘。
如果不复用Popup则没有问题。

步骤如下：
1. 点击左边view：
 
![微信图片_20210513181045](https://user-images.githubusercontent.com/13062910/118111803-c6a64e00-b416-11eb-9b94-0f5828b3631e.png)

2. 点击右边view：
![微信图片_20210513181051](https://user-images.githubusercontent.com/13062910/118111831-d1f97980-b416-11eb-87b3-168aa22ac8dd.png)

3. 再次点击右边view：
![微信图片_20210513181054](https://user-images.githubusercontent.com/13062910/118111858-d9208780-b416-11eb-8ab3-d929eec7db3b.png)

切换的代码如下:
```
 override fun onPopupLayout(popupRect: Rect, anchorRect: Rect) {
     ... 
     val gravity = computeGravity(popupRect, anchorRect)
     horizontal = when (gravity and Gravity.HORIZONTAL_GRAVITY_MASK) {
            Gravity.START,
            Gravity.LEFT -> {
                Direction.RIGHT
            }
            Gravity.END,
            Gravity.RIGHT -> {
                Direction.LEFT
            }
            Gravity.CENTER_HORIZONTAL -> {
                Direction.CENTER_HORIZONTAL
            }
            else -> {
                Direction.CENTER_HORIZONTAL
            }
        }

      setPopupGravityMode(GravityMode.ALIGN_TO_ANCHOR_SIDE, GravityMode.RELATIVE_TO_ANCHOR)
      if (horizontal == Direction.RIGHT) {
            popupGravity = Gravity.RIGHT
      } else if (horizontal == Direction.LEFT) {
            popupGravity = Gravity.LEFT
      }
}
```

**Comment by razerdp** [comment]
不建议在onPopupLayout中处理，因为onPopupLayout的回调时机是onLayout，此时已经计算完popup的位置了。所以才会出现你所说的先对齐上一次的，再回来定位（因为measure/layout不止一次）。

在show之前完成设置，点击什么view你是知道的，根据id设置左右即可。

**Comment by kolyneh** [comment]
嗯，明白了。
那其实我想要的效果跟 setOverlayStatusbarMode 和 setOverlayNavigationBarMode 类似，不允许 OVERLAY_CONTENT 内容覆盖到系统栏:  可以调整contentview 的水平方向边缘margin，使其不会贴到屏幕边缘。

**Comment by razerdp** [comment]
水平方向的话可以在xml设置margin，或者利用offsetX。但是提供api的话我觉得意义不大，因为这个可拓展性需求很多，因此理应由开发者完成。

**Comment by razerdp** [comment]
该问题先关闭了。
