### ISSUE TITLE
showPopupWindow(View anchorView)内的执行方法 为什么不用回2.2.3 release的

### ISSUE THREAD

**Issue by qwe260123123** [razerdp/BasePopup#415]
- 系统版本（必须）/ System version (required)：Android 8.0
 - 库版本（必须）/ Library version (required)：2.3.0 release

> 问题描述/重现步骤请写在这里
> Please write the description here.
在 2.3.0的
mHelper.onShow();
//这里传参没啥意义的，，反正代理类会解决
mPopupWindowProxy.showAtLocation(decorView, Gravity.NO_GRAVITY, 0, 0);

在2.2.3 release中 是有做锚点判断并传入代理
//传递了view
            if (v != null) {
                mPopupWindowProxy.showAtLocation(v, getPopupGravity(), 0, 0);
            } else {
                mPopupWindowProxy.showAtLocation(decorView, Gravity.NO_GRAVITY, 0, 0);
            }
少了这个  就会出现在 Dialog 上再弹出PopUp 会出现在dialog下一层的View上
而且这个2.2.3的 还挺好用的，能在盏底的 activity 弹出popup 到最顶层activity

**Comment by razerdp** [comment]
现在更改为构造器传参了哦

**Comment by qwe260123123** [comment]
哦哦 dialog 这个 才看到有新构造，
但是这个只适用到  同一页面的 显示吗
假如我A页面  是在  D页面下几层的Activity，而A会监听一些错误需要里面弹出PopUp到最顶层显示，这时候这个构造应该是实现不到的吗，不然这里就要做多一步传递事件到D页面了

**Comment by qwe260123123** [comment]
还有个很奇怪现象，在OPPO手机，有概率性会出现 弹窗出现了，处理了一些网络请求操作（处理前会dissmiss PopUp），但是该popUp的确走了dissmiss了，但是View还显示在那里，而且点击事件还穿透了popUp  触摸到popUp 下层的View 点击事件

**Comment by razerdp** [comment]
> 哦哦 dialog 这个 才看到有新构造，
> 但是这个只适用到 同一页面的 显示吗
> 假如我A页面 是在 D页面下几层的Activity，而A会监听一些错误需要里面弹出PopUp到最顶层显示，这时候这个构造应该是实现不到的吗，不然这里就要做多一步传递事件到D页面了

popup本身就是跟他的anchor挂钩的，理论上来说显示到顶层这种是属于越权了。不过我也留了后门，context给appcontext就会默认获取顶层activity了

**Comment by razerdp** [comment]
> 还有个很奇怪现象，在OPPO手机，有概率性会出现 弹窗出现了，处理了一些网络请求操作（处理前会dissmiss PopUp），但是该popUp的确走了dissmiss了，但是View还显示在那里，而且点击事件还穿透了popUp 触摸到popUp 下层的View 点击事件

rom魔改的问题我这里也处理不了哈，说不定他们改的wms导致的

**Comment by razerdp** [comment]
另外建议升级到新版哦

**Comment by qwe260123123** [comment]
感谢啦~
