### ISSUE TITLE
设置宽度之后，显示的是充满宽度

### ISSUE THREAD

**Issue by weilglg** [razerdp/BasePopup#416]
- 系统版本（必须）/ System version (required)：Android10
 - 库版本（必须）/ Library version (required)：3.1.0
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 在xml布局中设置了布局的宽度，运行之后发现布局宽度是填充模式

**Comment by razerdp** [comment]
有代码吗

**Comment by weilglg** [comment]
通过查找以前的issue已解决，构造器中传入WRAP_CONTENT即可，建议API说明中加入相关说明

**Comment by weilglg** [comment]
> 有代码吗

**Comment by razerdp** [comment]
不是。。xml写了宽度，构造器不需要处理的。demo中就是这样

**Comment by razerdp** [comment]
demopopup:

https://github.com/razerdp/BasePopup/blob/master/app/src/main/java/razerdp/demo/popup/DemoPopup.java

https://github.com/razerdp/BasePopup/blob/master/app/src/main/res/layout/popup_demo.xml

**Comment by weilglg** [comment]
> 不是。。xml写了宽度，构造器不需要处理的。demo中就是这样
>pop
class CustomerDetailMenuPopupWindow(context: Context) :
    BasePopupWindow(context) {

    private val binding = DialogCustomerDetailMenuBinding.inflate(LayoutInflater.from(context))

    init {
        setBackground(0)
        popupGravity = Gravity.BOTTOM and Gravity.END
        showAnimation = AnimationHelper.asAnimation().withTranslation(TranslationConfig.FROM_TOP).toShow()
        dismissAnimation = AnimationHelper.asAnimation().withTranslation(TranslationConfig.TO_TOP).toDismiss()
        contentView = binding.root
    }
}
>xml布局
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:gravity="center"
    android:background="@drawable/shape_10_white"
    android:orientation="vertical">

    <TextView
        style="@style/text_style_12"
        android:layout_width="match_parent"
        android:paddingHorizontal="@dimen/dp_15"
        android:paddingVertical="@dimen/dp_14"
        android:text="@string/go_appointment" />

    <View style="@style/line_style" />

    <TextView
        style="@style/text_style_12"
        android:layout_width="match_parent"
        android:paddingHorizontal="@dimen/dp_15"
        android:paddingVertical="@dimen/dp_14"
        android:text="@string/track" />

    <View style="@style/line_style" />

    <TextView
        style="@style/text_style_12"
        android:layout_width="wrap_content"
        android:paddingHorizontal="@dimen/dp_15"
        android:paddingVertical="@dimen/dp_14"
        android:text="@string/setting_return_visit" />

</LinearLayout>

这是代码，运行之后宽度是填充模式

**Comment by razerdp** [comment]
xml布局根呢

**Comment by weilglg** [comment]
完整xml代码
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:gravity="center"
    android:background="@drawable/shape_10_white"
    android:orientation="vertical">

    <TextView
        style="@style/text_style_12"
        android:layout_width="match_parent"
        android:paddingHorizontal="@dimen/dp_15"
        android:paddingVertical="@dimen/dp_14"
        android:text="@string/go_appointment" />

    <View style="@style/line_style" />

    <TextView
        style="@style/text_style_12"
        android:layout_width="match_parent"
        android:paddingHorizontal="@dimen/dp_15"
        android:paddingVertical="@dimen/dp_14"
        android:text="@string/track" />

    <View style="@style/line_style" />

    <TextView
        style="@style/text_style_12"
        android:layout_width="wrap_content"
        android:paddingHorizontal="@dimen/dp_15"
        android:paddingVertical="@dimen/dp_14"
        android:text="@string/setting_return_visit" />

</LinearLayout>

**Comment by weilglg** [comment]
![image](https://user-images.githubusercontent.com/16534262/120892097-11466f00-c63f-11eb-98bf-e8906188f71b.png)

**Comment by razerdp** [comment]
我看到你也是wrap_content并没有设置具体高宽喔

**Comment by weilglg** [comment]
需要设定一个具体的宽度才可以限定宽度吗？

**Comment by razerdp** [comment]
不需要

**Comment by razerdp** [comment]
噢~我明白了。。。你的问题在于contentview是你自己inflate出来的，没有用我们的方法。因此导致popuphelper里面获取不到layoutparam，所以最后取了默认值，默认宽度就是match_parent

**Comment by razerdp** [comment]
手册有写建议用createPopupById()进行inflate，3.1.0+建议setcontentview(layout)，至于您用viewbinding，可以在onViewCreated中bind

**Comment by weilglg** [comment]
好的，非常感谢
