### ISSUE TITLE
有没有办法在不够位置展示popupwindow时自动在反方向显示？

### ISSUE THREAD

**Issue by qinxianyuzou** [razerdp/BasePopup#417]
- 系统版本（必须）/ System version (required)：Android 10
 - 库版本（必须）/ Library version (required)：3.1.0
---
请问有没有办法自适应位置，超出屏幕时不要直接贴着屏幕显示，而是改为在绑定的anchorView的反方向显示，比如本来是在anchorView下方显示的，但是因为下方不够位置显示完整的popup，于是自动变为在anchorView上方显示，在anchorView右侧显示的就自动变成左侧显示

**Comment by razerdp** [comment]
setAutoLocatePopup

**Comment by razerdp** [comment]
autolocate只针对上下，不针对左右哦

**Comment by qinxianyuzou** [comment]
> autolocate只针对上下，不针对左右哦

左右有没有办法做呢？还是所只能自己实现？

**Comment by razerdp** [comment]
左右目前应该无法自行实现的。。。这个我可以补一下。

**Comment by razerdp** [comment]
这个地方涉及到popup的layout以及各种点击范围，所以并不能提供给外部去修改，否则可能会乱套了。

**Comment by qinxianyuzou** [comment]
> 这个地方涉及到popup的layout以及各种点击范围，所以并不能提供给外部去修改，否则可能会乱套了。

那就只能麻烦你以后有空补充一下了，其实这种自适应的，最常用的场景可能还是在根据坐标来展示popup的情况，比如贴着屏幕边缘来弹个popup。根据anchorView的话确实可能大部分情况下只要适配上下就行了。

**Comment by razerdp** [comment]
是的，绝大多数场景都是上下，左右的话很少。。所以就没写了。

这部分代码在这里：https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/PopupDecorViewProxy.java#L516

某种意义上对着上下的方法撸一遍就可以了。

**Comment by qinxianyuzou** [comment]
> 是的，绝大多数场景都是上下，左右的话很少。。所以就没写了。
> 
> 这部分代码在这里：https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/PopupDecorViewProxy.java#L516
> 
> 某种意义上对着上下的方法撸一遍就可以了。

我想问一下，这个setAutoLocatePopup对根据坐标来显示有没有作用呢？就这么看代码的话号先只有根据anchorView来展示的时候才会生效是吗？如果根据触摸坐标来显示的话，左右自动还是比较多的，比如长按文字显示个菜单什么的

**Comment by razerdp** [comment]
触摸坐标实际上就是复用了anchorview的，相当于anchorview大小为0，左上角原点在指定的坐标点。

https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/BasePopupWindow.java#L735

**Comment by qinxianyuzou** [comment]
> 触摸坐标实际上就是复用了anchorview的，相当于anchorview大小为0，左上角原点在指定的坐标点。
> 
> https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/BasePopupWindow.java#L735

那可能还是要加一下左右相反的功能，因为触摸的很多会在边缘触摸。其实我也可以在外部自己计算位置偏移，我是在想如果你这里提供的话，那就更加方便了

**Comment by razerdp** [comment]
嗯嗯，待会我弄弄，顺便写个demo测试

**Comment by razerdp** [comment]
预览版已经更新：3.1.3-SNAPSHOT

由于原来的`setAutoLocatePopup`有点歧义，因此增加个新的api代替这个。请用`setAutoMirrorEnable`代替

demo已经更新，请留意demo的更新推送。

![device-2021-06-18-155234](https://user-images.githubusercontent.com/11629986/122527412-de907380-d04d-11eb-9033-7c4ac34f7f4f.png)

**Comment by razerdp** [comment]
release 3.1.4已发布，请更新
