### ISSUE TITLE
context 不是 Activity，将 Activity 替换为Context+LifeCycleOwner+ContainerView可以吗

### ISSUE THREAD

**Issue by LinXueyuanStdio** [razerdp/BasePopup#418]
> 问题描述/重现步骤请写在这里
> Please write the description here.

启动一个Service，放一个悬浮窗按钮，点击弹出popup，crash

popup获得的是service 的 context，我们实现了service上的 LifeCycleOwner

直接使用PopupWindow是可以弹出来的

**Comment by razerdp** [comment]
版本？

**Comment by LinXueyuanStdio** [comment]
"com.github.razerdp:BasePopup:2.2.1"

**Comment by LinXueyuanStdio** [comment]
由于Service在独立进程中，ContentProvider貌似没有初始化成功
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'razerdp.basepopup.BasePopupWindow razerdp.basepopup.BasePopupSupporterManager$BasePopupSupporterProxy.attachLifeCycle(razerdp.basepopup.BasePopupWindow, java.lang.Object)' on a null object reference
        at razerdp.basepopup.BasePopupWindow.attachLifeCycle(BasePopupWindow.java:1741)
        at razerdp.basepopup.BasePopupWindow.initView(BasePopupWindow.java:415)
        at razerdp.basepopup.BasePopupWindow.delayInit(BasePopupWindow.java:410)
```
利用ContentProvider自动初始化，貌似不成功
```java
public final class BasePopupRuntimeTrojanProvider extends ContentProvider {
    @Override
    public boolean onCreate() {
        BasePopupSupporterManager.getInstance().init(getContext());
        return true;
    }
   ...
}
```

**Comment by razerdp** [comment]
版本太老了，更新到最新吧…这些都修复过了

**Comment by LinXueyuanStdio** [comment]
换 3.1.0 了
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.app.Activity.getDrawable(int)' on a null object reference
        at razerdp.basepopup.BasePopupWindow.setBackground(BasePopupWindow.java:1193)
```
在悬浮窗中，不存在top activity，所以getContext为空
```java
    public BasePopupWindow setBackground(int drawableIds) {
        if (drawableIds == 0) {
            return setBackground(null);
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            return setBackground(getContext().getDrawable(drawableIds));
        } else {
            return setBackground(getContext().getResources().getDrawable(drawableIds));
        }
    }
```

**Comment by razerdp** [comment]
我明天看看

**Comment by razerdp** [comment]
嗯嗯，问题get，这是因为在application中或者service中弹出，可能没有activity栈。basepopup将会在activity创建时弹出，而此时context并没有赋值，所以这些api会报npe错误。我稍后修复一下并检查所有相关api。

**Comment by razerdp** [comment]
> 换 3.1.0 了
> 
> ```
> java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.app.Activity.getDrawable(int)' on a null object reference
>         at razerdp.basepopup.BasePopupWindow.setBackground(BasePopupWindow.java:1193)
> ```
> 
> 在悬浮窗中，不存在top activity，所以getContext为空
> 
> ```java
>     public BasePopupWindow setBackground(int drawableIds) {
>         if (drawableIds == 0) {
>             return setBackground(null);
>         }
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
>             return setBackground(getContext().getDrawable(drawableIds));
>         } else {
>             return setBackground(getContext().getResources().getDrawable(drawableIds));
>         }
>     }
> ```

fixed in 3.1.4-SNAPSHOT

由于不是很重要的更新，所以就不写到readme了。

**Comment by razerdp** [comment]
release 3.1.4已发布，请更新

**Comment by LinXueyuanStdio** [comment]
3.1.4 还是没解决根本性问题
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.content.Context.getDrawable(int)' on a null object reference
        at razerdp.basepopup.BasePopupWindow.setBackground(BasePopupWindow.java:1201)
```

**Comment by razerdp** [comment]
噢，我再看回issue，知道了你的问题了= =你的service在独立进程，我的provider不知为何没有对multiprocess生效。

暂时你先用setbackground(drawable)代替吧，setbackground(resid)里面拿不到context。

多进程问题很少有人这么用，所以留到下个版本我再去看看吧

**Comment by razerdp** [comment]
或者你提供一个demo工程，我有空了去跟一下
