### ISSUE TITLE
布局设置全屏后点击透明区域无法消失popupwindow

### ISSUE THREAD

**Issue by FrankLove** [razerdp/BasePopup#419]
作者你好，有个问题想请教下，我写了一个Popupwindow继承了basepopup，然后把布局文件的根布局宽高设置了matchparent,但是布局里面的内容没有全屏显示，所以当popup显示的时候，会有透明区域，但这时点击透明区域没法消失popupwindow，请问这种情况下有什么办法可以点击透明区域消失popupwindow呢？
`<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <androidx.constraintlayout.widget.ConstraintLayout

        android:background="@drawable/shape_dialog_bg"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintWidth_percent="0.75"
        app:layout_constraintHeight_percent="0.55"
        app:layout_constraintBottom_toBottomOf="parent"
        android:layout_width="0dp"
        android:layout_height="0dp">

    </androidx.constraintlayout.widget.ConstraintLayout>

</androidx.constraintlayout.widget.ConstraintLayout>`

**Comment by razerdp** [comment]
请按照要求提交issue
