### ISSUE TITLE
showPopupWindow 不显示的问题

### ISSUE THREAD

**Issue by anjroizs** [razerdp/BasePopup#42]
### 该问题是怎么引起的？

BasePopupWindow.showPopupWindow()方法有时候不弹出界面的问题。（就是什么反应都没有）
但是同样的代码在调试的时候，最后又能弹出来。

### 报错信息
没有报错

**Comment by razerdp** [comment]
@anjroizs  请复查一下，popup是否在onCreate调用（当activity没准备好【windowToken没准备好】，popup是无法弹出的）

**Comment by razerdp** [comment]
@anjroizs  针对这种情况，已经更新了，在1.8.5

**Comment by xushaun** [comment]
@razerdp 针对这种情况在1.8.5已经更新，但是我还是在1.9.4显示不出来，更新的处理方法我怎么看呢，没找到1.8.5的tag或者更改说明
