### ISSUE TITLE
popupwindow布局设置全屏后点击投屏区域无法消失

### ISSUE THREAD

**Issue by FrankLove** [razerdp/BasePopup#420]
- 系统版本（必须）/ System version (required)：android 9.0
 - 库版本（必须）/ Library version (required)：2.2.7
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

作者你好，有个问题想请教下，我写了一个Popupwindow继承了basepopup，然后把布局文件的根布局宽高设置了matchparent,但是布局里面的内容没有全屏显示，所以当popup显示的时候，会有透明区域，但这时点击透明区域没法消失popupwindow，请问这种情况下有什么办法可以点击透明区域消失popupwindow呢？
`
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
android:layout_width="match_parent"
android:layout_height="match_parent"
xmlns:app="http://schemas.android.com/apk/res-auto">
<androidx.constraintlayout.widget.ConstraintLayout

    android:background="@drawable/shape_dialog_bg"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintTop_toTopOf="parent"
    app:layout_constraintWidth_percent="0.75"
    app:layout_constraintHeight_percent="0.55"
    app:layout_constraintBottom_toBottomOf="parent"
    android:layout_width="0dp"
    android:layout_height="0dp">

</androidx.constraintlayout.widget.ConstraintLayout>
</androidx.constraintlayout.widget.ConstraintLayout>`

**Comment by razerdp** [comment]
给decorview设置个listener，里面执行dismiss即可。

**Comment by FrankLove** [comment]
decorview 请问指的是哪一个，怎么获取到这个decorview呢？

**Comment by razerdp** [comment]
getContentView()或者onViewCreated中的回调。

另外建议升级到新版，2.2.7太旧了，差了几十个版本了，详情请看手册

**Comment by FrankLove** [comment]
好的，已经升级到最新版了，在onViewCreated里面设置了这个监听，可以点击透明区域消失，但是点击布局界面的任意部分也会消失。想了下只能通过在new popuwindow的时候传递一个计算过后的高度进去，然后布局文件不能设置宽高比了。其他感觉没什么 办法了
        contentView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                dismiss();
            }
        });

**Comment by razerdp** [comment]
ya。。确实点击其他地方也会dismiss，毕竟相当于对rootview进行了click监听。

事实上，这种contentView是match_parent，实际上显示的内容并非填满的情况我们是没法去抽象的，因此哪怕是透明，那也是属于contentView，这部分的逻辑是完全交给用户解决的，对于库来说只能给你区分点击的是contentView还是masklayout，并不能区分点击contentView的那一块是否透明可透传。

对于这个问题，其实我更建议是透明区域用一个space去占位，然后对这个space做点击事件去dismiss，也就是说这个space写入布局中，它的作用就是占位透明区域。

**Comment by FrankLove** [comment]
确实这个问题只能用户自己去处理，我后面想在最底部加一个全屏的 View 
  <View
        android:id="@+id/cl_chart_root"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
然后对这个view进行点击监听，但是点击布局的实体部分也会执行到点击监听，很奇怪了。按理说不应该不应该穿透到底部的view的呀

**Comment by razerdp** [comment]
给个完整布局看看？

**Comment by razerdp** [comment]
或者demo工程

**Comment by FrankLove** [comment]
这个是布局文件
`<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">



    <View
        android:id="@+id/cl_chart_root"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <androidx.constraintlayout.widget.ConstraintLayout
        app:layout_constraintWidth_percent="0.75"
        app:layout_constraintHeight_percent="0.55"
        android:background="@drawable/shape_dialog_bg"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        android:layout_width="0dp"
        android:layout_height="0dp">

        <TextView
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            android:text="统计判断题"
            android:padding="10dp"
            android:textColor="#0099ff"
            android:id="@+id/tv_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>

        <View
            android:background="#e5e5e5"
            app:layout_constraintTop_toBottomOf="@id/tv_title"
            android:layout_width="match_parent"
            android:layout_height="1dp"/>

        <com.github.mikephil.charting.charts.PieChart
            app:layout_constraintTop_toBottomOf="@id/tv_title"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toStartOf="@id/barChart"
            app:layout_constraintBottom_toTopOf="@id/tv_right_percent"
            android:id="@+id/pieChart"
            app:layout_constraintWidth_percent="0.35"
            app:layout_constraintHeight_percent="0.45"
            android:layout_width="0dp"
            android:layout_height="0dp"/>

         <com.github.mikephil.charting.charts.BarChart
        app:layout_constraintTop_toTopOf="@id/tv_title"
        app:layout_constraintStart_toEndOf="@id/pieChart"
        android:layout_marginEnd="15dp"
        app:layout_constraintEnd_toStartOf="@id/tv_tip_right"
        app:layout_constraintBottom_toBottomOf="parent"
        android:layout_marginBottom="25dp"
        android:id="@+id/barChart"
        android:layout_width="0dp"
        android:layout_height="0dp"/>

        <TextView
            android:id="@+id/tv_right_percent"
            app:layout_constraintStart_toStartOf="@id/pieChart"
            app:layout_constraintEnd_toEndOf="@id/pieChart"
            android:layout_marginTop="0dp"
            android:layout_marginBottom="15dp"
            app:layout_constraintTop_toBottomOf="@id/pieChart"
            app:layout_constraintBottom_toBottomOf="parent"
            android:textColor="#666666"
            android:text="正确率"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>

        <TextView
            android:text="正确作答"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            android:layout_marginTop="50dp"
            android:layout_marginEnd="15dp"
            android:textSize="8dp"
            android:id="@+id/tv_tip_right"
            android:textColor="#999999"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>
        <TextView
            android:text="错误作答"
            app:layout_constraintStart_toStartOf="@id/tv_tip_right"
            app:layout_constraintTop_toBottomOf="@id/tv_tip_right"
            android:layout_marginTop="5dp"
            android:textSize="8dp"
            android:id="@+id/tv_tip_wrong"
            android:textColor="#999999"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>
    </androidx.constraintlayout.widget.ConstraintLayout>

</androidx.constraintlayout.widget.ConstraintLayout>`
然后我在onViewCreated 设置了监听
        rootview.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                dismiss();
            }
        });

**Comment by razerdp** [comment]
这是因为内容层没有view消耗事件导致传递到了底层（cl_chart_root）中触发了吧？

试试给内容层（即内层的ConstraintLayout）加上clickable=true?

**Comment by FrankLove** [comment]
这样做确实可以，多谢大佬赐教
