### ISSUE TITLE
在输入法弹起时,关闭pop,软键盘关闭无动画效果

### ISSUE THREAD

**Issue by maomaomaomiao** [razerdp/BasePopup#421]
- 系统版本（必须）/ android11：
 - 库版本（必须）/ 3.1.4：
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

 setAdjustInputMode(FLAG_KEYBOARD_ALIGN_TO_ROOT | FLAG_KEYBOARD_ANIMATE_ALIGN); 底部上滑弹窗 适配软键盘. 
在输入法弹起时,关闭pop,软键盘关闭无动画效果

**Comment by razerdp** [comment]
软键盘关闭本身就是没有动画效果的噢，而且popup也无法控制键盘的动画，只能控制自身的动画。
