### ISSUE TITLE
edittext和popupwindow一起使用无法复制粘贴

### ISSUE THREAD

**Issue by QianHong** [razerdp/BasePopup#422]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：
 - 库版本（必须）/ Library version (required)：
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

**Comment by razerdp** [comment]
请看手册-常见问题。
该问题无解。

**Comment by QianHong** [comment]
如果类似需求 ，建议换用dialogfragment 
代码如下：
`public class InputDialogFragment extends BaseDialogFragment<Binding, NoViewModel> implements View.OnClickListener {
    OnPublishClickListener onPublishClickListener;

    @Override
    public int initVariableId() {
        return 0;
    }

    @Override
    protected int getLayoutId() {
        return R.layout.layout_edit_view;
    }

    @Override
    public void setUpWindow() {
        if (getDialog() == null) {
            return;
        }
        Window window = getDialog().getWindow();
        if (window == null) {
            return;
        }
        window.setBackgroundDrawableResource(android.R.color.transparent);
        WindowManager.LayoutParams params = window.getAttributes();
        params.gravity = Gravity.BOTTOM;
        params.width = WindowManager.LayoutParams.MATCH_PARENT;
        window.setAttributes(params);
        window.setWindowAnimations(R.style.dialog_bottom_anim);
    }

    @Override
    public void initView() {
        super.initView();
        UIUtils.setTypeface(mBinding.tvTitle).setIncludeFontPadding(false);
        EditText mEditText = mBinding.customEditText.findViewById(R.id.review_input);
        mBinding.tvPublish.setOnClickListener(this);
        mBinding.tvPublish.setEnabled(false);
        mBinding.cancelEdit.setOnClickListener(this);
        mBinding.tvRatingDesc.setText(RatingBarLevel.getRatingLevelText((int) mBinding.ratingBar.getRating()));
        mBinding.ratingBar.setOnRatingBarChangeListener((ratingBar, rating, fromUser) -> {
            mBinding.tvRatingDesc.setText(RatingBarLevel.getRatingLevelText((int) rating));
        });
        mBinding.customEditText.setOnTextChangedListener(s -> mBinding.tvPublish.setEnabled(!TextUtils.isEmpty(s)));
        mEditText.setFocusable(true);
        mEditText.setFocusableInTouchMode(true);
        mEditText.requestFocus();
        mEditText.requestFocusFromTouch();
        getDialog().getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE);
    }

    @Override
    public void onClick(View v) {
        if (v.getId() == R.id.cancel_edit) {
            this.dismiss();
        } else if (v.getId() == R.id.tv_publish) {
            publish();
        }
    }

    private void publish() {
        String comment = mBinding.customEditText.getEditTextContent();
        float rating = mBinding.ratingBar.getRating();
        if (TextUtils.isEmpty(comment)) {
            ToastUtils.getInstance().showCustomToast("内容不能为空！");
            return;
        }
        if (rating == 0) {
            ToastUtils.getInstance().showCustomToast(RatingBarLevel.getRatingLevelText((int) rating));
            return;
        }
        if (onPublishClickListener != null) {
            onPublishClickListener.onPublishClick(comment, rating);
        }
    }

    @Override
    public void onDismiss(@NonNull DialogInterface dialog) {
        super.onDismiss(dialog);
        mBinding.customEditText.clearEditTextContent();
        mBinding.ratingBar.setRating(0);
    }

    public void setOnPublishClickListener(OnPublishClickListener onPublishClickListener) {
        this.onPublishClickListener = onPublishClickListener;
    }

    public interface OnPublishClickListener {
        void onPublishClick(String comment, float rating);
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        if (onPublishClickListener != null) {
            onPublishClickListener = null;
        }
    }

    public void showDialog(FragmentManager supportFragmentManager, String tag) {
        //避免重复添加的异常 java.lang.IllegalStateException: Fragment already added
        Fragment fragment = supportFragmentManager.findFragmentByTag(tag);
        if (fragment != null) {
            FragmentTransaction fragmentTransaction = supportFragmentManager.beginTransaction();
            fragmentTransaction.remove(fragment);
            fragmentTransaction.commitAllowingStateLoss();
        }
        //避免状态丢失的异常 java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        try {
            super.show(supportFragmentManager, tag);
        } catch (IllegalStateException e) {
            e.printStackTrace();
        }
    }
}`
