### ISSUE TITLE
BasePopup手册新增案例参考栏目

### ISSUE THREAD

**Issue by razerdp** [razerdp/BasePopup#424]
为了帮助新使用BasePopup框架的开发者快速上手，本手册特意新增【案例参考】栏目。

本栏目将会收集一些具体的案例，评估后进入需求池并逐步完成。

欢迎您提出弹窗需求，我们将会定期收集并实现

如果您有部分需求的实现源码并乐于分享，我们也非常欢迎您参与分享，我们会标记作者及感谢~

---

请在下面两种方式中二选一进行提交：

1. 前往手册评论：https://www.yuque.com/razerdp/basepopup/sraxgx
2. 本Issue下评论

**Comment by yxyaxng** [comment]
还是之前的wiki直观，现在找个属性设置都要去翻源码看方法

**Comment by razerdp** [comment]
> 还是之前的wiki直观，现在找个属性设置都要去翻源码看方法

现在全在语雀文档吧
