### ISSUE TITLE
吐司被popupwindow覆盖怎么解决？

### ISSUE THREAD

**Issue by q88qaz** [razerdp/BasePopup#425]
吐司被popupwindow覆盖怎么解决？
吐司层级在popupwindow之下怎么解决？

**Comment by razerdp** [comment]
请按照issue规范提交

**Comment by q88qaz** [comment]
卧槽居然是我提交的
换了一个吐司方式解决了
简单做一下记录，使用最新版3.1
然后activity拉起basepopup，然后点击popup显示一个吐司，并没有出来，马上关闭popup后发现吐司在activity上层，在popup下层
大概就是这个问题，囧，也许吐司的上下文需要使用popup的吧

**Comment by razerdp** [comment]
理论上…不用，因为toast的context最终还是拿application的，实际上我的demo包括示例gif都有toast，他们是正常的。
