### ISSUE TITLE
希望添加软键盘弹出后控制软键盘和弹框的间距的接口

### ISSUE THREAD

**Issue by mayer500** [razerdp/BasePopup#426]
- 系统版本（必须）/ System version (required)：Android11
 - 库版本（必须）/ Library version (required)：2.2.20
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)： 
 -   
![微信图片_20210714162635](https://user-images.githubusercontent.com/16808990/125590236-1999e169-05ba-413b-ac62-49545665e5da.jpg)

> 问题描述/重现步骤请写在这里  
软键盘弹出后，弹框能上移，和软键盘保持一定间距或者弹框在剩余屏幕空间垂直居中显示。

**Comment by razerdp** [comment]
已发布预览版3.1.7-SNAPSHOT，详情请看
https://github.com/razerdp/BasePopup/tree/dev#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97-%E5%8E%86%E5%8F%B2%E6%9B%B4%E6%96%B0

图：
![1](https://user-images.githubusercontent.com/11629986/125929436-d6faa2fa-ac5e-4581-96c5-b4137555c79d.png)
![2](https://user-images.githubusercontent.com/11629986/125929442-6693d07b-3fab-48fe-94e1-e18fcf21a6d2.png)

**Comment by razerdp** [comment]
3.1.7 release已发布
