### ISSUE TITLE
状态栏的图标全变白 

### ISSUE THREAD

**Issue by AndyYw** [razerdp/BasePopup#427]
- 系统版本（必须）/ System version (required)：8.0
 - 库版本（必须）/ Library version (required)：3.1.6
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

> 问题描述/重现步骤请写在这里
弹出popupwindow ,状态栏字体全部变白，和#266一样问题，魅族16th手机，华为手机没有问题。

**Comment by razerdp** [comment]
这方面问题我跟166回复情况一样，很有可能跟小米的小白条一样读取像素颜色亮度去更改自己是显示白色还是黑色。很有可能是系统控件自身行为。
可以验证一下，设置basepopup不覆盖状态栏，此时状态栏应该没有蒙层覆盖了，查看这时候图标会不会变化。

建议您针对该系统进行状态栏的设置。
