### ISSUE TITLE
请教关于basepopup点击穿透的问题

### ISSUE THREAD

**Issue by FrankLove** [razerdp/BasePopup#428]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：android 7.0
 - 库版本（必须）/ Library version (required)：3.1.0
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

作者你好，请问我想实现popuwindow xml布局里面(包括蒙版透明区域)的事件不穿透，但是popuwindow之外的区域可以穿透进行点击操作，大概需求是这样，我的界面底部有一排按钮，点击其中一个然后在这个按钮上方弹出了popupwindow，这个时候popupwindow下方的所有按钮仍然可以点击，同时点击popupwindow背景透明区域可以消失以及触摸popupwindow布局区域事件不穿透，另外popupwindow下方这一排按钮不带蒙版层，按钮上方的popupwindow空白区域带蒙版层，请问这种操作有没有办法实现呢？

**Comment by razerdp** [comment]
你好，可以实现的，我这边给你详细描述下哈。
1. popup内不透传，外部透传，这个本来就支持的，可以设置 `setOutSideTouchable`。（如果你希望点击外部不dismiss，您还可以设置`setOutSideDismiss`，详情请看下方参考手册）

根据您的需求，您可能需要这几个api结合：
1. 蒙层不遮挡下排按钮，可以设置`setAlignBackground`和`setAlignBackgroundGravity(Gravity.BOTTOM)`，使得蒙层对齐popup底部
2. 针对事件控制，您可以override basepopup的onOutSideTouch，回调有是否在背景中触摸和是否点击等事件，返回true/false就可以了。

详情请参考手册：
1. 事件控制：[#setOutSideTouchable](https://www.yuque.com/razerdp/basepopup/yyu138#jwOcT)
2. 背景蒙层对齐：[#setAlignBackgound](https://www.yuque.com/razerdp/basepopup/gscx3g#N0wSv)
3. 事件回调：[#onOutSideTouch](https://www.yuque.com/razerdp/basepopup/yyu138#UywGJ)

**Comment by FrankLove** [comment]
@razerdp  very nice!! 非常感谢！刚才测试的时候还发现一个小问题，比如说我的popup xml布局是这样的，包含有:layout_constraintHeight_percent 这个属性的时候，在设置显示位置的时候offsety 的设置值无效，不知道是为啥？
`<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <View
        android:id="@+id/cl_chart_root"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/cl_content_root"
        app:layout_constraintHeight_percent="0.70"
        android:clickable="true"
        android:background="@color/white"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        android:layout_width="0dp"
        android:layout_height="0dp">
 </androidx.constraintlayout.widget.ConstraintLayout>`

**Comment by razerdp** [comment]
因为当你contentview都是match的时候，意味着它是占满整个屏幕的，此时你进行offset就会导致popup布局到了屏幕外，basepopup是对这个进行过针对操作的，当popup布局超出屏幕，它会反向位移以保证内容完整显示。在视觉上来看，就是“offset失效了”。

您可以通过内部padding或者根view加入margin来解决

**Comment by FrankLove** [comment]
嗯嗯，thank you so mush
