### ISSUE TITLE
作为menu的时候，如何为popupwindow添加阴影效果，譬如popupmenu

### ISSUE THREAD

**Issue by jeesezh** [razerdp/BasePopup#43]
### 该问题是怎么引起的？

![image](https://user-images.githubusercontent.com/19542480/32307869-b375857c-bfbd-11e7-9960-2b50f3aac366.png)

**Comment by razerdp** [comment]
@jeesezh 

您好，这类popup（大小：wrap_content）您可以自己定制背景

不过似乎也可以考虑写入popup里面，给您添加，谢谢你的建议

**Comment by razerdp** [comment]
@jeesezh 

最后还是觉得在库中添加阴影代码不太妥当，而且可能会影响到用户自定义的布局，并且生成的阴影并不是很美观，
所以需要阴影的话建议还是自行添加比较好，最后介绍一个网址生成.9阴影的

http://inloop.github.io/shadow4android/
