### ISSUE TITLE
在fragment中通过 by lazy 创建basepop,必现内存泄漏

### ISSUE THREAD

**Issue by br3ant** [razerdp/BasePopup#431]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：android 10
 - 库版本（必须）/ Library version (required)：2.3.0
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

在fragment中通过 by lazy 创建basepop,必现内存泄漏

┬───
│ GC Root: Global variable in native code
│
├─ android.database.ContentObserver$Transport instance
│    Leaking: NO (HomeWorkActivity↓ is not leaking)
│    ↓ ContentObserver$Transport.mContentObserver
├─ android.widget.Editor$HandleViewShowObserver instance
│    Leaking: NO (HomeWorkActivity↓ is not leaking)
│    mContext instance of com.datedu.pptAssistant.homework.HomeWorkActivity
│    with mDestroyed = false
│    ↓ Editor$HandleViewShowObserver.mContext
├─ com.datedu.pptAssistant.homework.HomeWorkActivity instance
│    Leaking: NO (Activity#mDestroyed is false)
│    mApplication instance of com.mukun.teacher.TeacherApp
│    mBase instance of androidx.appcompat.view.ContextThemeWrapper
│    ↓ ComponentActivity.mLifecycleRegistry
│                        ~~~~~~~~~~~~~~~~~~
├─ androidx.lifecycle.LifecycleRegistry instance
│    Leaking: UNKNOWN
│    Retaining 1.7 MB in 5289 objects
│    ↓ LifecycleRegistry.mObserverMap
│                        ~~~~~~~~~~~~
├─ androidx.arch.core.internal.FastSafeIterableMap instance
│    Leaking: UNKNOWN
│    Retaining 1.7 MB in 5280 objects
│    ↓ SafeIterableMap.mEnd
│                      ~~~~
├─ androidx.arch.core.internal.SafeIterableMap$Entry instance
│    Leaking: UNKNOWN
│    Retaining 56 B in 3 objects
│    ↓ SafeIterableMap$Entry.mKey
│                            ~~~~
├─ com.datedu.pptAssistant.homework.check.correction.view.
│  CorrectClassSelectPopupView instance
│    Leaking: UNKNOWN
│    Retaining 1.7 MB in 5249 objects
│    mContext instance of com.datedu.pptAssistant.homework.HomeWorkActivity
│    with mDestroyed = false
│    ownerAnchorParent instance of com.datedu.pptAssistant.homework.
│    HomeWorkActivity with mDestroyed = false
│    ↓ CorrectClassSelectPopupView.listener
│                                  ~~~~~~~~
├─ com.datedu.pptAssistant.homework.check.correction.
│  HomeWorkCorrectionMainFragment$mClassListPop$2$1 instance
│    Leaking: UNKNOWN
│    Retaining 16 B in 1 objects
│    Anonymous subclass of kotlin.jvm.internal.Lambda
│    ↓ HomeWorkCorrectionMainFragment$mClassListPop$2$1.this$0
│                                                       ~~~~~~
╰→ com.datedu.pptAssistant.homework.check.correction.
​  HomeWorkCorrectionMainFragment instance
​     Leaking: YES (ObjectWatcher was watching this because com.datedu.
​     pptAssistant.homework.check.correction.HomeWorkCorrectionMainFragment
​     received Fragment#onDestroy() callback and Fragment#mFragmentManager is
​     null)
​     Retaining 1.7 MB in 5066 objects
​     key = 0fa3c738-8714-446d-983f-0d56c9adee01
​     watchDurationMillis = 6545
​     retainedDurationMillis = 1545
​     _mActivity instance of com.datedu.pptAssistant.homework.HomeWorkActivity
​     with mDestroyed = false

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: Xiaomi
LeakCanary version: 2.7
App process name: com.mukun.teacher
Stats: LruCache[maxSize=3000,hits=6254,misses=115809,hitRate=5%]
RandomAccess[bytes=7174191,reads=115809,travel=55968191922,range=31078006,size=3
7204982]
Heap dump reason: 10 retained objects, app is visible
Analysis duration: 10023 ms

**Comment by razerdp** [comment]
3.0没有lazy了

**Comment by br3ant** [comment]
private val mClassListPop: CorrectClassSelectPopupView by lazy {}
使用的kotlin的lazy

**Comment by razerdp** [comment]
噢…我看版本2.3还以为你用的lazypopup。
这个看看代码，如果构造器传的context，那么basepopup跟随的是act的生命期，如果你想跟随fragment的生命期，你需要用fragment那个构造器

**Comment by br3ant** [comment]
改为绑定fragment暂时没有泄漏了
