### ISSUE TITLE
如何监听消失事件

### ISSUE THREAD

**Issue by BaiMingxu** [razerdp/BasePopup#432]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：
 - 库版本（必须）/ Library version (required)：
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

**Comment by razerdp** [comment]
跟系统一致，setondismisslistener

**Comment by BaiMingxu** [comment]
谢谢
