### ISSUE TITLE
关于popup高度问题

### ISSUE THREAD

**Issue by FrankLove** [razerdp/BasePopup#434]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：7.0
 - 库版本（必须）/ Library version (required)：3.1.0
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
作者你好，有个问题想请指教一下。我的basepopup布局里面包含一个recycleview，点击界面某个按钮后在这个按钮下方显示popup，但是recycleview里面的数据不是固定的，而basepopup 根布局用的wrap。如果数据的数量超过了basepopup显示的位置距离屏幕底部的高度，那么basepopup高度就变成了了屏幕高度，而无法显示在控件下方了。如果根布局写成math就不会，但是这样又没法根据recycleview的数量进行高度自适应了，一显示出来就直接到底部了，不管数据量是否超出范围。请问有什么办法禁止basepopup来做这种高度调整呢？或者有其他方式解决这个问题吗？

**Comment by razerdp** [comment]
首先解释下为什么wrap会逐步变成屏幕高度：

这个原因在于随着item数量的增多，高度逐渐增大，由于实现是在某个view下方，导致显示高度不足，因此会导致popup超出屏幕，而这在basepopup中是不允许的，因此会反向位移直到填满高度为止。

接着我给你说一下解决方法，有好几种方法解决：

1. setMaxHeight()来设置basepopup最大高度
2. setFitSize()来让basepopup自动调整大小【该功能目前有bug，我也在调整这个功能~因此不太建议】，近期我在把项目更新到viewbinding，后续修复好之后直接设置这个api即可，我会提供文档并回来这里留言的。
3. 【推荐】basepopup根布局给match_parent，里面有一个子控件recyclerview，高度为wrap_content。这样当rv逐渐增高时，最大也就只会填满按钮下方空间。
  - . 但是这个方案有个需要你处理的点，就是由于根布局是match_parent的，因此当rv没有填满时，是会显示出下方蒙层，但是你这时候点击蒙层实际上是无效的，因为点到的是contentView，而不是蒙层。因此这一块需要你来处理一下事件，我的建议是类似于下方的伪代码布局

```xml
<FrameLayout w=match;h=match>
  <Space w = match;h=match>
  <RecyclerView w = match;h=wrap_content>
</FrameLayout>
```

手册指引：
[布局](https://www.yuque.com/razerdp/basepopup/xlscog)

**Comment by FrankLove** [comment]
好的，多谢大佬，用第一种方式处理了，感觉第一种和第三种都不是太好，哈哈。

**Comment by razerdp** [comment]
> 好的，多谢大佬，用第一种方式处理了，感觉第一种和第三种都不是太好，哈哈。

其实最好的是第二种哈哈~不过那个得等我弄好后了，as更新后一堆麻烦

**Comment by razerdp** [comment]
3.1.8-SNAPSHOP已经更新

文档已经补充：https://www.yuque.com/razerdp/basepopup/aw4aq3#Xz568

**Comment by FrankLove** [comment]
666

**Comment by anjiuzhe** [comment]
basepop设置固定高度后，布局里面的recycleview item显示不全，且无法滑动
