### ISSUE TITLE
设置为底部弹出弹窗,但是距离导航键还有部分距离

### ISSUE THREAD

**Issue by lv823063712** [razerdp/BasePopup#436]
![image](https://user-images.githubusercontent.com/44794626/130551298-2a72d31e-6477-42f4-b90e-719515792266.png)
如图所示
是在三星手机上
![image](https://user-images.githubusercontent.com/44794626/130551345-767df396-6c60-4acc-922f-21509e969af8.png)
这个是代码设置

**Comment by razerdp** [comment]
请补充信息，本issue将被忽略。

**Comment by lv823063712** [comment]
> 请补充信息，本期将被忽略。

需要补充什么吗,手机是三星的gagalaxy F52 5G,幸好是 SM-E5260

**Comment by razerdp** [comment]
按issue规范提交。
