### ISSUE TITLE
设定为底部显示PopWindow,但是距离导航键有一点的距离

### ISSUE THREAD

**Issue by lv823063712** [razerdp/BasePopup#437]
手机系统版本 : android 11
使用依赖版本:com.github.razerdp:BasePopup:2.2.7
`public PhoneSelectPop(Activity context) {
        super(context);
        int width = context.getWindowManager().getDefaultDisplay().getWidth();//设置展示的宽度
        setWidth(width);
        setPopupGravity(Gravity.BOTTOM);//设定pop显示在最底部
        init();
    }`
这个是代码设置

显示效果如下,部分机型显现
![image](https://user-images.githubusercontent.com/44794626/130551298-2a72d31e-6477-42f4-b90e-719515792266.png)
如图所示
是在三星手机上

**Comment by razerdp** [comment]
更新到新版即可。

**Comment by razerdp** [comment]
库版本太旧了
