### ISSUE TITLE
5.0设备重大问题

### ISSUE THREAD

**Issue by FrankLove** [razerdp/BasePopup#440]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：android 5.0
 - 库版本（必须）/ Library version (required)：3.1
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
博主你好，在android 5.0 带虚拟导航栏的设备上，横屏状态下右侧显示basepopup会导致右侧显示不全，部分区域被虚拟导航栏遮住了，请问这种情况要怎么处理呢？

**Comment by razerdp** [comment]
升级到最新版试试呗

**Comment by FrankLove** [comment]
@razerdp 大佬，最新版还是有这个问题

**Comment by FrankLove** [comment]
@razerdp 大佬，3.1.8貌似还改出了一个新问题，在一个按钮下方显示一个popup，原来会布局的起始位置与按钮相同，现在直接显示在按钮的左侧了，这是为什么

**Comment by razerdp** [comment]
这一部分没有改动过哦，垂直方向上设置了Bottom，水平方向上由于没有设置gravity，因此默认取left，所以就会出现你说的情况了。

**Comment by FrankLove** [comment]
在3.1版垂直方向上设置了Bottom，即使不设置Gravity.CENTER也会自动居中，因此这部分逻辑应该是改动了吧？那在android 5.0 带虚拟导航栏的设备上，横屏状态下右侧显示basepopup会导致右侧显示不全，这个情况能处理么？

**Comment by razerdp** [comment]
噢，我去看看你说的右侧不全

**Comment by razerdp** [comment]
@FrankLove  请问你是在模拟器上测试吗？

**Comment by FrankLove** [comment]
@razerdp 不是哦，是在华为M2 平板上测试的。

**Comment by razerdp** [comment]
噢噢，我在模拟器上看android 5.0的系统，很神奇的是，横屏的时候根本找不到导航栏。。。

**Comment by razerdp** [comment]
你可以断点一下PopupUiUtils.getNavigationBarBounds()方法，这里实际上就是遍历decorview第一层child，找到背景资源为navigationbarbackground或immersion_navigation_bar_view的那个view，那个view就是导航栏。

如果可以的话，最好就是通过layout inspector，把你平板上的对应li文件导出来发到这里，这样我就能更准确的追踪一下问题所在。

**Comment by FrankLove** [comment]
大佬，我这点击layout inspector没有生成captures目录和li文件，这是为啥呢

**Comment by FrankLove** [comment]
试了下上面说的两种方式
1、断点的时候在getNavigationBarBounds方法的if判断里面就直接返回了
2、’layout inspector 我这个设备无法使用，总是提示失败
忧伤

**Comment by razerdp** [comment]
那有点难。。。要不你加群吧。。加我微信 razerdp
