### ISSUE TITLE
3.1.4升级到3.1.8页面展示问题

### ISSUE THREAD

**Issue by HelloAnyu** [razerdp/BasePopup#442]
- 系统版本（必须）/ System version (required)：10.0
 - 库版本（必须）/ Library version (required)：3.1.8
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
![image](https://user-images.githubusercontent.com/23192549/133048620-425af3d3-6eb5-4ab3-b5c3-faeec3e65a7b.png)
![image](https://user-images.githubusercontent.com/23192549/133048644-37c4d990-b1a5-4428-a189-4a3a741f8e3b.png)

> 问题描述/重现步骤请写在这里
作者您好：
我在使用basePopup的时候，项目从3.1.4升级到了3.1.8，页面左右的margin自动改变了，图1为3.1.4版本，图二为3.1.8版本

**Comment by razerdp** [comment]
这个问题似乎被修复过了
https://github.com/razerdp/BasePopup/issues/429

不过也有可能跟这个有关

https://github.com/razerdp/BasePopup/issues/435

**Comment by razerdp** [comment]
你可以更新到最新版的snapshot尝试下，我之前修复过一波
