### ISSUE TITLE
在 forceDismiss 时能不能不隐藏键盘

### ISSUE THREAD

**Issue by iztou** [razerdp/BasePopup#445]
系统版本（必须）/ System version (required)：10.0
库版本（必须）/ Library version (required)：3.1.8

因为一些业务需求，我们的页面会创建大量的弹窗，然后我使用了BasePopup ，在隐藏后我会主动的调用onDestory 以节省部分内存，结果发现会调用forceDismiss，里面调用了关闭键盘的逻辑，这里能不能做一个开关，来控制是否关闭键盘，因为我们的场景是不需要关闭键盘的
![image](https://user-images.githubusercontent.com/4177989/134802451-a6ab4e0d-42cb-4bfe-b0e0-4813e01a4443.png)

**Comment by razerdp** [comment]
可以，下一个版本我补一下

**Comment by razerdp** [comment]
implementation 'io.github.razerdp:BasePopup:3.2.0-SNAPSHOT

预览版已经添加

**Comment by razerdp** [comment]
2021/10/09
        * 修复旋转屏幕时update错误的问题
        * 修复事件分发问题 [#443](https://github.com/razerdp/BasePopup/issues/443)
        * 增加dismiss时不隐藏键盘的功能
        * 设置镜像时自动关闭fitSize并缓存原来的值

**Comment by razerdp** [comment]
对应api是 `hideKeyboardOnDismiss`

**Comment by razerdp** [comment]
3.2.0 release已发布，请查看更新日志
