### ISSUE TITLE
please make sure that context is instance of activity

### ISSUE THREAD

**Issue by doublehang** [razerdp/BasePopup#45]
### 该问题是怎么引起的？
我的activity 是继承了一个BaseActivityWithRecyclerView然后在上面传入当前activity.this 在华为matel 9上日志输出 
please make sure that context is instance of activity

我在另外一个界面 直接继承BaseActivity 就正常显示 

### 报错信息
E/PopupWindowProxy: please make sure that context is instance of activity

**Comment by razerdp** [comment]
请问是必现的吗，然后确认一下传入的context？

**Comment by doublehang** [comment]
好像是我代码不够规范，在传入依附在某个View上时候会显示该错误，我把依附的View换成最外层的FrameLayout 就解决了 之前传入的是 FrameLayout 下一级的 RelativeLayout 就出现该错误可能Android7.0的时候部分机型会出现 目前知道金立和华为matel9的会，还是我自己技术不够好，感谢大佬抽时间回复

**Comment by razerdp** [comment]
哈哈，没事

context的确认是在PopupWindowProxy代码中第[90~94行](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/PopupWindowProxy.java)

而遍历寻找代码是在第135行

事实上，这段代码不是我编写的，是热心网友提交的PullRequest，而我只是简单的加了一个重试次数`tryScanActivityCount`

然而我发现，我加了之后似乎并没有对其在重试成功后进行复位，所以可能是这里的原因。

你可以尝试debug，看看这个变量是否因为多次show，同时多次寻找activity从而导致了该问题的发生

谢谢你的回复
