### ISSUE TITLE
窗体外点击的监听事件

### ISSUE THREAD

**Issue by TFHtian** [razerdp/BasePopup#454]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：
 - 库版本（必须）/ Library version (required)：
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

**Comment by razerdp** [comment]
请查看文档，有关于onoutsidetouch的描述

**Comment by razerdp** [comment]
另外请按照模板提出issue~

**Comment by TFHtian** [comment]
当前有一种情况，页面中有输入框，弹窗中也有输入框，当点击popup中的弹窗弹起软键盘，点击窗体外关闭popup，软件盘关闭，再次弹起软键盘
