### ISSUE TITLE
Popup的显示和销毁，不会触发依赖的Activity的onPause和onResume

### ISSUE THREAD

**Issue by q88qaz** [razerdp/BasePopup#455]
Popup的显示和销毁，不会触发依赖的Activity的onPause和onResume
现在有一个需求
在popup弹出时，停止Activity的音乐播放
 在popup关闭后，恢复Activity的音乐播放

**Comment by razerdp** [comment]
basepopup本身实现了LifecycleObserver ，你可以自行实现@OnLifecycleEvent(Lifecycle.Event.ON_XXX)

另外这些功能不应该你的业务去控制么。

最后请按照issue模版提交issue。
