### ISSUE TITLE
setDismissWhenTouchOuside无效，小米系统7.0

### ISSUE THREAD

**Issue by NicodeLee** [razerdp/BasePopup#46]
### 重现步骤
` popup.setDismissWhenTouchOuside(false);`
方法无效点击外部还是会消失

**Comment by razerdp** [comment]
你好，我这里模拟器无法重现（没有上述问题）

请问您的布局方便贴出来吗？

**Comment by razerdp** [comment]
已修复。

请更新到-> 1.8.7
