### ISSUE TITLE
onOutSideTouch 会回调多次

### ISSUE THREAD

**Issue by github-tongchen** [razerdp/BasePopup#460]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：Android 多版本
 - 库版本（必须）/ Library version (required)：3.1.0
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)： 
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

onOutSideTouch方法会回调多次，且 touchInbackground 和 isPressed 值每次回调都不一样。我当前重写了此方法来实现外部点击穿透。

**Comment by razerdp** [comment]
只要触摸事件到contentview外部都会回调到这个方法，毕竟就叫outsidetouch~事件穿透你只需要设置outsidetouchable就可以了

**Comment by github-tongchen** [comment]
现在是有个这样的问题：我需要对点击阴影区域进行监听打点，打算通过这个方法的参数 touchInBackground 来判断处理。但是我点击1次阴影以后，会回调3次，其中touchInBackground有2次是true，这样会重复打点。而且这个过程中isPressed一直都是false。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月6日(星期四) 中午11:01
收件人: ***@***.***&gt;; 
抄送: "Chen ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [razerdp/BasePopup] onOutSideTouch 会回调多次 (Issue #460)





 
只要触摸事件到contentview外部都会回调到这个方法，毕竟就叫outsidetouch~事件穿透你只需要设置outsidetouchable就可以了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by razerdp** [comment]
如果回调了3次那肯定有一次是move事件，isPressed自然而然不会是true。

手册上的demo，仅回调2次：

https://www.yuque.com/razerdp/basepopup/yyu138#PxMpM

另外MotionEvent一同回调过来的，你可以对这个进行操作或者判断

**Comment by github-tongchen** [comment]
明白了，debug了下确实是这样，谢谢解答我的问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月6日(星期四) 中午11:15
收件人: ***@***.***&gt;; 
抄送: "Chen ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [razerdp/BasePopup] onOutSideTouch 会回调多次 (Issue #460)





 
如果回调了3次那肯定有一次是move事件，isPressed自然而然不会是true。
 
手册上的demo，仅回调2次：
 
https://www.yuque.com/razerdp/basepopup/yyu138#PxMpM
 
另外MotionEvent一同回调过来的，你可以对这个进行操作或者判断
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
