### ISSUE TITLE
QuickPopup创建弹框的混淆问题

### ISSUE THREAD

**Issue by iztou** [razerdp/BasePopup#462]
- 系统版本（必须）/ System version (required)：Android 11
 - 库版本（必须）/ Library version (required)：3.2.0
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
我看了 `QuickPopupConfig` 的源码，在设置属性时是通过Java反射获取`Method`来进行设置的，然后看到lib里面也没有相关的混淆设置，如果APP设置了混淆，这个是不是就不生效了，在我们实际应用中出现了设置Gravity为Center时不生效的现象

**Comment by razerdp** [comment]
哦对，在上一次优化的时候忘了补充混淆…下个版本添加@keep

**Comment by kanfRUI** [comment]
> 哦对，在上一次优化的时候忘了补充混淆…下个版本添加@keep

作者，您好，能说一下重新打开软键盘的的原因吗？我提了一个问题了#461

**Comment by razerdp** [comment]
> > 哦对，在上一次优化的时候忘了补充混淆…下个版本添加@keep
> 
> 作者，您好，能说一下重新打开软键盘的的原因吗？我提了一个问题了#461

噢噢，不好意思，我这边没提示，原来多了几个issue....我现在去看看

**Comment by razerdp** [comment]
fixed in 3.2.1
