### ISSUE TITLE
深色模式下，局部模糊有白边，看下是什么原因？

### ISSUE THREAD

**Issue by jansonjoan** [razerdp/BasePopup#464]
- 系统版本（必须）/ System version (required)：MIUI 12.5.8 Android 11
 - 库版本（必须）/ Library version (required)：3.2.0
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
  ```EventTagsPopup eventTagsPopup = new EventTagsPopup(getContext(), tagTextView);
        eventTagsPopup.setBackgroundColor(Color.TRANSPARENT);
        eventTagsPopup.setBlurBackgroundEnable(true);
        eventTagsPopup.setBlurOption(new PopupBlurOption().setBlurView(blurView));

        eventTagsPopup.setOnDismissListener(new BasePopupWindow.OnDismissListener() {
            @Override
            public void onDismiss() {
                userEvent.setTagId(Utils.getTagInfo(-1, tagTextView.getText().toString()).tagId);
            }
        });

        tagTextView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                eventTagsPopup.showPopupWindow(eventTitleEditText);
            }
        });
```
 - 报错信息（可选）/ Error reporting information (optional)：
  无
---

> 问题描述/重现步骤请写在这里
> Please write the description here.

设置的局部模糊，在系统浅色模式下没有问题，但是深色模式下，模糊区域四周会有白色突出
![iShot2022-01-13 16 54 18](https://user-images.githubusercontent.com/16145681/149297769-df38f646-9fad-413e-aa4b-215dd6b2c541.png)

**Comment by razerdp** [comment]
![image](https://user-images.githubusercontent.com/11629986/203577947-06cef83e-8100-4aab-9d97-3a4680a2fa63.png)

不排除是这段代码造成。背景如果拿不到drawable会填充FAFAFA
