### ISSUE TITLE
请问如何更换依附的window

### ISSUE THREAD

**Issue by Keryyyy** [razerdp/BasePopup#469]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：12
 - 库版本（必须）/ Library version (required)：3.1.7
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

现在有一个全局pop，在启动页初始化，构造方法传的application context，那么现在这个pop绑定的声明周期就是启动页的LifeCycle，然后我现在进入到MainActivity后，再show这个pop就会报错，已经找不到控件了（宿主启动页lifecycle已经onDestroy）

我尝试自己写个show方法，在执行业务逻辑前判断一下重新绑定声明周期，还是报错找不到控件...重新设置contentView也不行

```
 if (context == null || (context as LifecycleOwner).lifecycle.currentState == Lifecycle.State.DESTROYED){
            LogUtils.e("依附的activity已经被销毁，重新绑定")
            bindLifecycleOwner(ActivityUtils.getTopActivity() as ComponentActivity)
            contentView = createPopupById(R.layout.view_pop_system_new_msg)
            mIvHead = findViewById(R.id.iv_head)
        }
```

报错：findViewById(R.id.iv_head) 为 null

请问如何在整个app内可以复用这一个pop？主要想用来做全局的消息提示

**Comment by razerdp** [comment]
传入app context实际上拿的是top activity，由于popup的特性是依附于parent window的，所以目前其实没法更换的说
