### ISSUE TITLE
点击popwindow之外的地方，怎么让外部的立即响应事件，现在需要点2次

### ISSUE THREAD

**Issue by CLZ686** [razerdp/BasePopup#47]

**Comment by razerdp** [comment]
在M之前可以通过setFocusable(false)
但是在M之后似乎是不可以的。

我会在下个版本增加这个方法去修复。

谢谢反馈

**Comment by razerdp** [comment]
ps.

popupwindow出现时优先消化事件

目前因为`setBackpressEnable()`方法的原因，我也打算去研究怎么去解决

**Comment by razerdp** [comment]
更新到1.8.8，调用setOutsideTouchable()方法
