### ISSUE TITLE
摇杆 onGenericMotionEvent 无法响应

### ISSUE THREAD

**Issue by zl277287818** [razerdp/BasePopup#470]
您好，目前有个问题想讨论一下：

一直用的这个框架，最近的需求有摇杆操作。但是在popwindow弹出后，摇杆监听的方法onGenericMotionEvent就接受不到消息了，查了下，这应该是popwindow的机制。当然可以重新basepop里面的onDispatchKeyEvent方法，实现其他按键（KeyEvent）的响应，但是摇杆（MotionEvent）就是不行。

我该如何做才能让onGenericMotionEvent接受到消息呢？求解决方案，谢谢各位大神。

**Comment by razerdp** [comment]
我迟点看看，因为这个库目前比较稳定，收集的bug略少，因此我目前没有迭代计划

**Comment by razerdp** [comment]
新版本增加onGenericMotionEvent事件

**Comment by razerdp** [comment]
fixed in 3.2.1
