### ISSUE TITLE
是否支持类似BottomSheet的拖拽？

### ISSUE THREAD

**Issue by WhoIsAA** [razerdp/BasePopup#471]
你好，用了BasePopup好久了，非常强大的库，首先还是要感谢作者的贡献～
对于一些从底部滑出的弹窗，将来是否会加入拖拽隐藏的功能，类似BottomSheet
对比了另一个库：XPopup，它是支持拖拽的，但用起来并不如BasePopup好用，如果可以支持就太好了
再次感谢～

**Comment by razerdp** [comment]
这个实际上是draghelper实现的，basepopup并没有直接支持（因为我们把这些操作全部下放，我们只管抽象），你可以找个通用的draghelper工具类去实现一下。

**Comment by WhoIsAA** [comment]
谢谢，来信已收到，我会尽快回复你..

**Comment by WhoIsAA** [comment]
谢谢，来信已收到，我会尽快回复你..
