### ISSUE TITLE
新版本对于SystemBar覆盖不生效

### ISSUE THREAD

**Issue by ChawLoo** [razerdp/BasePopup#473]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：Android 11
 - 库版本（必须）/ Library version (required)：3.2.0
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里
> Please write the description here.
新版本对于SystemBar覆盖不生效，不起作用，我下载了你的demo试了一下也无效或者不正确的

**Comment by ChawLoo** [comment]
发现测试不出来了， 但是确实出现过问题，我一下子又复现不出来了

**Comment by ChawLoo** [comment]
![Uploading image.png…]()

**Comment by ChawLoo** [comment]
![image](https://user-images.githubusercontent.com/26214519/180172181-7c635c02-bed9-49a3-be06-e2e0eec29240.png)
![image](https://user-images.githubusercontent.com/26214519/180172328-426768e9-e78d-49f7-92e2-51ab89f282c6.png)

**Comment by razerdp** [comment]
模拟器能复现吗…我手上没有Android11的设备

**Comment by SelectSex** [comment]
> ![image](https://user-images.githubusercontent.com/26214519/180172328-426768e9-e78d-49f7-92e2-51ab89f282c6.png) 

看你的选择城市截图，是小白条没有适配吗，这个我和作者讨论过，在低版本红米出现过，
具体可以看 https://github.com/razerdp/BasePopup/issues/452

解决方案是，使用BasePopup-3.2.1-SNAPSHOT，然后**不要**再xml中使用android:fitsSystemWindows，自己通过
      setOverlayNavigationBarMode(BasePopupFlag.OVERLAY_CONTENT)   //设置内容区域沉浸到导航栏
            setOverlayStatusbarMode(BasePopupFlag.OVERLAY_MASK)
来控制是否限制内容扩充到，状态栏和导航栏小白条，

**Comment by ChawLoo** [comment]
刚看到回复，我明天尝试一下楼上的方案

**Comment by ChawLoo** [comment]
经测试可以，望早点发布3.2.1正式版吧

**Comment by razerdp** [comment]
开发版本修复了，新版本要稍后，我目前没啥时间去迭代。。

**Comment by ChawLoo** [comment]
补充一点，必须把xml的高度设置成wrap_content

**Comment by pichsy** [comment]
这个问题，我经常遇到，目前处理，弹窗弹起来以后，再次调用设置全屏的代码就可以了

**Comment by razerdp** [comment]
fixed in 3.2.1
