### ISSUE TITLE
调用update(anchorView) 后再调用 dismiss() 无效 无法关闭PopupWindow

### ISSUE THREAD

**Issue by daiwenbo88** [razerdp/BasePopup#476]
- 系统版本（必须）/ System version (required)：10.0
 - 库版本（必须）/ Library version (required)：3.2.0
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

> 问题描述/重现步骤请写在这里

调用update(anchorView) 后 再调用 dismiss() 无效 无法关闭PopupWindow

**Comment by razerdp** [comment]
问题已知，下个版本修复。

**Comment by razerdp** [comment]
fixed in 3.2.1
