### ISSUE TITLE
Activity主题设置为常规，弹窗xml中宽度高度 设置无效，唉，不是所见即所得吗

### ISSUE THREAD

**Issue by pichsy** [razerdp/BasePopup#477]

**Comment by pichsy** [comment]
class IdiomsHeroPopup(var context: Context, var message: String?) : BasePopupWindow(context) {

    private var binding: PopupIdiomsHeroBinding =
        PopupIdiomsHeroBinding.inflate(LayoutInflater.from(context))

    init {
        contentView = binding.root
    }

**Comment by pichsy** [comment]
我知道原因了，你没兼容 setContentView(view)只兼容了 setContentView(resId)

**Comment by pichsy** [comment]
所以我的viewbinding不能直接用

要这么写：
 private lateinit var binding: PopupIdiomsTipsBinding

    init {
        setContentView(R.layout.popup_idioms_tips)
    }

   
    override fun onViewCreated(contentView: View) {
        binding = PopupIdiomsTipsBinding.bind(contentView)

**Comment by pichsy** [comment]
作者大大， 啥时候兼容一下 

这么写就完美了，符合开发习惯

    private var binding: PopupIdiomsHeroBinding =
    PopupIdiomsHeroBinding.inflate(LayoutInflater.from(context))

   init {
        contentView = binding.root
   }

**Comment by pichsy** [comment]
@NonNull
    public ConstraintLayout getRoot() {
        return this.rootView;
    }

    @NonNull
    public static PopupIdiomsTipsBinding inflate(@NonNull LayoutInflater inflater) {
        return inflate(inflater, (ViewGroup)null, false);
    }

---->>这里可能有突破口，用这个方法创建，可以传入一个parent， 封装封装，是否能达到想要的？

    @NonNull
    public static PopupIdiomsTipsBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent) {
        View root = inflater.inflate(layout.popup_idioms_tips, parent, false);
        if (attachToParent) {
            parent.addView(root);
        }

        return bind(root);
    }

**Comment by razerdp** [comment]
xml的属性是inflate方法里赋予的，后期再addview是无效的= =
如果有别的方法读取到xml属性就好了，这个问题到目前为止我还没找到方法。。。

**Comment by razerdp** [comment]
暂时无解~如果有方法读取init后的view对应xml中的gravity，欢迎在这里留下idea~
