### ISSUE TITLE
更新到1.8.7后，setDismissWhenTouchOutside还是无效的问题

### ISSUE THREAD

**Issue by gaochunchun** [razerdp/BasePopup#48]
### 该问题是怎么引起的？
你好，我在调用mInterpolatorPopup.setDismissWhenTouchOutside(false);
或在CustomInterpolatorPopup的构造方法中调用setDismissWhenTouchOutside(false);
依然无效果，还是可以触摸外部后弹窗消失。

测试机型：华为荣耀v8 ，系统版本7.0
Genymotion模拟器，系统版本7.1

**Comment by razerdp** [comment]
@gaochunchun 

您好，CustomInterpolatorPopup中并没有触摸外部的地方。

下面是布局的图和代码截图：

![xml.png](https://moetu.fastmirror.org/images/2017/12/06/1c0346606243de43e.png)


![java.png](https://moetu.fastmirror.org/images/2017/12/06/22351f1b65494b334.png)

因为点击的View正是返回了那个蒙层，所以无论`setDismissWhenTouchOutside`怎么设置，其实都是点了Popup的内部

事实上，`setDismissWhenTouchOutside`针对的是wrap_content的popup，比如[MenuPopup](https://github.com/razerdp/BasePopup/blob/master/app/src/main/java/razerdp/demo/popup/MenuPopup.java)

**Comment by gaochunchun** [comment]
好的 ， 我去看看源码，谢谢。

**Comment by tpnet** [comment]
@razerdp  你好，我setDismissWhenTouchOutside为true了，，，利用mAreaPopup.showPopupWindow(mLayoutArea)这个方法显示在指定的view下面，，然后点击poopu以外的地方，例如mLayoutArea这个view，但是popup并没有收缩，这是什么回事呢

**Comment by razerdp** [comment]
@tpnet 系统版本是多少？

**Comment by tpnet** [comment]
小米2，android5.0.2   ，miui9.7.11.16开发版 @razerdp

**Comment by razerdp** [comment]
@tpnet 好的，我马上修复

**Comment by razerdp** [comment]
@tpnet 今晚发布1.8.9-beta2，应该可以修复诸多隐藏问题了。。。hackdecorview几乎完全代理了

**Comment by razerdp** [comment]
@tpnet 请升级到1.8.9-beta2
