### ISSUE TITLE
请问弹窗支持跟随吗

### ISSUE THREAD

**Issue by zl277287818** [razerdp/BasePopup#480]
你好，我是在Recycleview列表里弹的窗。
Dialog设置如下
setBackground(0);
setOutSideDismiss(false);
setTouchable(false);

dialog.showPopupWindow(view);

请问如何才能在滑动Recycleview的时候，让这个弹窗也跟随view移动？

**Comment by razerdp** [comment]
支持，请看文档
https://www.yuque.com/razerdp/basepopup/kufkxc

**Comment by zl277287818** [comment]
多谢灯泡哥
