### ISSUE TITLE
ContentView区域的背景上如何支持事件穿透？

### ISSUE THREAD

**Issue by qq908323236** [razerdp/BasePopup#491]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：Android 12
 - 库版本（必须）/ Library version (required)：3.2.1

---

> 问题描述/重现步骤请写在这里
> Please write the description here.

contentView区域的背景能否穿透事件，因为我的contentView的背景是透明，也想事件进行穿透

**Comment by razerdp** [comment]
contentView穿透的话目前只能override touch事件把它抛给act的rootView了。
