### ISSUE TITLE
使用showPopupWindow(view)的方式显示，动画效果无效

### ISSUE THREAD

**Issue by Matcha-xiaobin** [razerdp/BasePopup#498]
- 系统版本（必须）/ System version (required)：13
 - 库版本（必须）/ Library version (required)：3.2.1
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

---

使用showPopupWindow(view)的方式显示，动画效果无效

    override fun onViewCreated(contentView: View) {
        super.onViewCreated(contentView)
        setPopupGravityMode(GravityMode.ALIGN_TO_ANCHOR_SIDE, GravityMode.RELATIVE_TO_ANCHOR)
        popupGravity = Gravity.START or Gravity.TOP
    }

    override fun onCreateShowAnimation(): Animation {
        return AnimationHelper.asAnimation().withTranslation(TranslationConfig.FROM_BOTTOM).toShow()
    }

    override fun onCreateDismissAnimation(): Animation {
        return AnimationHelper.asAnimation().withTranslation(TranslationConfig.TO_BOTTOM).toShow()
    }

**Comment by razerdp** [comment]
我本地运行了一次，好像没有问题= =
