### ISSUE TITLE
远程库无法倒入

### ISSUE THREAD

**Issue by ZhouKanZ** [razerdp/BasePopup#5]
compile 'com.github.razerdp:BasePopup:v1.2.0'
无法导入，一直停留在Gradle：Resolve dependencies  'app_debugCompile' , 本来以为是我网络的问题，试了一下别的库 能导入 ，麻烦检查一下  远程库为什么不能使用了

**Comment by razerdp** [comment]
@ZhouKanZ 请检查一下工程的gradle下的allprojects块里面有没有添加  maven { url "https://jitpack.io" }

**Comment by ZhouKanZ** [comment]
确实是这个原因，粗心了

**Comment by razerdp** [comment]
好的，那我关闭了

**Comment by ZhouKanZ** [comment]
好的
