### ISSUE TITLE
更新到1.8.8之后  输入框点击调不出键盘   ,按返回 没dismiss 

### ISSUE THREAD

**Issue by Mr-PolarBear** [razerdp/BasePopup#50]
### 该问题是怎么引起的？
原来用的是1.8.7 
更新到1.8.8之后  输入框点击调不出键盘   ,按返回 没dismiss  
大佬这要怎么搞

### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
啊，收到~我去查查

**Comment by tpnet** [comment]
是的，我也是这样子的情况

**Comment by razerdp** [comment]
@tpnet @Mr-PolarBear 建议暂时用着1.8.7，1.8.8我今天修复好了，待会我再自测下看看有没有其他问题再发布1.8.9。。。。如果还有什么问题欢迎提交issue~

**Comment by razerdp** [comment]
@tpnet @Mr-PolarBear 

请更新到1.8.9，1.8.8已经废弃

解决方案可以查看：[1.8.9 解决方案](https://github.com/razerdp/BasePopup/blob/master/%E5%85%B3%E4%BA%8EAndorid%20M%E4%BB%A5%E4%B8%8AsetBackPressEnable()%E5%A4%B1%E6%95%88%E7%9A%84%E9%97%AE%E9%A2%98%E7%9A%84%E5%88%86%E6%9E%90.md#189-%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)

**Comment by tpnet** [comment]
@razerdp  我从1.8.7 更新到1.8.9,,按返回，，popupWindows没有dismiss，，

**Comment by razerdp** [comment]
@tpnet 哈0.0

你的系统版本是多少

我从4.3测试到7.1.1 都是通过了的。。。你贴出你的设置来看看？

**Comment by razerdp** [comment]
@tpnet 噗，，大概，，我懂了- -因为默认helper是backpressedenable=false.....我忘记设置为true了。。。你可以直接调用`setBackPressEnable(true)`。。。我现在去改一下默认设置哈。。仍然是1.8.9

**Comment by razerdp** [comment]
@tpnet 已经重新更新，

**Comment by tpnet** [comment]
好的，我重新下载可以了。大佬牛逼
