### ISSUE TITLE
当Context是Activity的时候找不到DecorView

### ISSUE THREAD

**Issue by SnailMyth** [razerdp/BasePopup#500]
### Please go to [**WIKI#FAQ**](https://www.yuque.com/razerdp/basepopup/dgf6ry) for relevant questions before commit your issue to avoid repetitive questions.

<br>

### Please be sure to follow the format below before submitting the issue, otherwise the question will be actively closed!

 - 系统版本（必须）/ System version (required)：
 - 库版本（必须）/ Library version (required)：v3.2.1
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
--BasePopupHelper:

    static View findDecorView(Object parent) {
        View decorView = null;
        Window window = null;
        if (parent instanceof Dialog) {
            window = ((Dialog)parent).getWindow();
        } else if (parent instanceof DialogFragment) {
            if (((DialogFragment)parent).getDialog() == null) {
                decorView = ((DialogFragment)parent).getView();
            } else {
                window = ((DialogFragment)parent).getDialog().getWindow();
            }
        } else if (parent instanceof Fragment) {
            decorView = ((Fragment)parent).getView();
        } else if (parent instanceof Context) {
            Activity act = PopupUtils.getActivity((Context)parent);
            decorView = act == null ? null : act.findViewById(16908290);
        }

        if (decorView != null) {
            return decorView;
        } else {
            return window == null ? null : window.getDecorView();
        }
    }
---

> 问题描述/重现步骤请写在这里
当parent是activity的时候window 没有被赋值 导致DecorView 为null

**Comment by razerdp** [comment]
请问是什么activity
