### ISSUE TITLE
隐藏导航栏+ 任意位置显示： 弹窗无法放到最低，底部永远留着一个导航栏的高度

### ISSUE THREAD

**Issue by zhouhanbing1990** [razerdp/BasePopup#501]
使用系统popupwindow没有此问题，甚至可以超出屏幕显示，但是因为显示的时候，会弹出一下导航栏再隐藏，体验不好，才找到这个轮子，然后就是遇到现在这个问题

 - 系统版本（必须）/ System version (required)：Android 11
 - 库版本（必须）/ Library version (required)：3.2.1
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
 - 报错信息（可选）/ Error reporting information (optional)：

**Comment by razerdp** [comment]
请查看手册，有关于能否先是在导航栏上的说明

**Comment by zhouhanbing1990** [comment]
光看位置控制去了，没注意到标题：SystemBar覆盖控制
