### ISSUE TITLE
如何让Popup显示出后不获取焦点

### ISSUE THREAD

**Issue by lelouch0823** [razerdp/BasePopup#54]
### 该问题是怎么引起的？
现在的场景是上部有个EditText,然后EditText中输入文字会实时在下方用pop显示出搜索到的数据的pop,但现在如果pop显示后EditText就会失去焦点,之前使用自带的PopupWindow设置setFocusable(false)就可以了,请问这个库这个问题怎么解决?

### 报错信息/系统版本

```java

```

**Comment by razerdp** [comment]
你好，`setInterceptTouchEvent(false);`设置popup不拦截事件，同时类似的api还提供：

  -  setDismissWhenTouchOutside(boolean)//设置是否点击popup外部时dismiss
  - setBackPressEnable(boolean)//设置是否允许back键dismiss
  - setInterceptTouchEvent(boolean)//popup是否拦截事件

这三个api都可以分开独立使用的

**Comment by lelouch0823** [comment]
感谢回复问题解决了
