### ISSUE TITLE
求解，怎么在你建的popupWindow下打开相册，然后返回到启动window的页面？就是startActivityForResult

### ISSUE THREAD

**Issue by OathkeeperDL7** [razerdp/BasePopup#55]
### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
应该跟 popup无关，因为popup本身不参与到intent操作中，可能是你中间操作一些代码导致的异常吧，能具体贴出代码或者logcat吗，你现在这么问我也无法了解是否popup的问题

**Comment by OathkeeperDL7** [comment]
谢谢，我解决了，但是我想问一下如何取消蒙灰层覆盖到状态栏呢？

**Comment by razerdp** [comment]
setFullScreen(false);
