### ISSUE TITLE
Android 8.0后特殊操作 SlideFromTopPopup还是存在被顶到到 屏幕最上方的问题

### ISSUE THREAD

**Issue by wangxiangping** [razerdp/BasePopup#56]
### 该问题是怎么引起的？
经测试有三种情况会引起（只针对SlideFromTopPopup）：
1.在SlideFromTopPopup显示的时候   切换App并返回
2.在SlideFromTopPopup显示的时候   将App切换到后台并返回
3.在SlideFromTopPopup显示的时候   手机插入数据线，系统弹出插入作用的提示框的时候

### 重现步骤
1.在SlideFromTopPopup显示的时候   切换App并返回
2.在SlideFromTopPopup显示的时候   将App切换到后台并返回
3.在SlideFromTopPopup显示的时候   手机插入数据线，系统弹出插入作用的提示框的时候

### 报错信息/系统版本
系统版本Android8.0 华为nova2s

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
8.0暂时没去针对优化，不排除谷歌又改了showAsDropDown的原因。。。

说实话，我考虑干脆把这个show方法给hook掉，改为自己的windowManager来添加好了。。。

**Comment by wangxiangping** [comment]
谷歌PopupWindow坑太深，7.0自己优化没问题了，8.0出现的问题就更奇葩了

**Comment by razerdp** [comment]
是的，，，下一个版本去优化8.0的

**Comment by razerdp** [comment]
其实相关类可以看

[PopupCompatManager](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/PopupCompatManager.java)

这里面我暂时有三个IMPL，可能以后还会有更多，所以提前挖好坑了嘿嘿

**Comment by razerdp** [comment]
@wangxiangping 针对8.0的问题我年后回来研究哈，暂时先标注一下

**Comment by razerdp** [comment]
查到问题了，因为在切换回来时，update很莫名其妙的把layoutparams.y设置为了顶部状态栏的高度。。。导致整个popup被顶回去了

**Comment by jiancao** [comment]
大神解决了吗？我也碰到这个问题，华为mate9

**Comment by yxyaxng** [comment]
我也碰到了 @jiancao也是mate9 @razerdp 什么时候能解决呀

**Comment by jiancao** [comment]
@yxyaxng  我没用这个了，用了原生的popupwindow

**Comment by razerdp** [comment]
暂时未针对8.0进行解决优化，预计近2个月。

**Comment by razerdp** [comment]
@wangxiangping 
@jiancao 
@yxyaxng 

你好，已经发布了预览版本，请更新到Candy版本。

**Comment by razerdp** [comment]
@wangxiangping
@jiancao
@yxyaxng

ps，**Candy**版本并不是**稳定版**，问题反馈收集后修正并验证过才发布的正式版，如果您使用过程中发现有无法接受的问题，可以先更换到上一个正式版使用并反馈到github issue
