### ISSUE TITLE
使用ListPopWindow 如何设置Listpopup显示的高度呢

### ISSUE THREAD

**Issue by coolBreezes** [razerdp/BasePopup#57]
###  我的问题

您好，我想问下，使用ListPopWindow 如何设置Listpopup显示的高度呢
另外我有一个横向滚动的listview，我想实现点击列表中的item，让popupwindow显示在对应item的下方，
想问下该如何实现呢，当前一直显示在中间，且蒙层只有横向滚动的listview下方才有
![device-2018-02-02-164704](https://user-images.githubusercontent.com/8476068/35724470-c9fcbdb0-0838-11e8-954c-87a1ae00aa4d.png)

请问有qq群可以交流么，谢谢哈

### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
qq群你可以到朋友圈交流群，暂时popup不提供交流群。。。（不过可以考虑。。。）

然后，显示到下方有几个方法。。

1 - 你算好offsetX和offsetY
2 - 你如果能获取到点击的View，直接用showPopupWindow(View)，然后给一定的offsetY和x，让其对齐就好了。
