### ISSUE TITLE
全屏时弹出basePop封装的会强制显示虚拟按键,直接用popWindow不会

### ISSUE THREAD

**Issue by Chihiro23333** [razerdp/BasePopup#59]
### 该问题是怎么引起的？

视频全屏横屏播放虚拟键隐藏,弹出basePop强制弹出了三大金刚键

### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
收到，大概是因为适配了systembar的问题，这个下一版本修复

**Comment by razerdp** [comment]
你好，已经发布了预览版本，请更新到Candy版本。

**Comment by razerdp** [comment]
ps，**Candy**版本并不是**稳定版**，问题反馈收集后修正并验证过才发布的正式版，如果您使用过程中发现有无法接受的问题，可以先更换到上一个正式版使用并反馈到github issue

**Comment by littleylv** [comment]
@razerdp Candy:2.0.0-alpha2 仍然存在问题

我的MainActivity默认是全屏的（没有状态栏和虚拟按键），但showPopupWindow时候会显示虚拟按键。

`MainActivity.java:`

        @Override

        protected void onCreate(Bundle savedInstanceState) {

                super.onCreate(savedInstanceState);

                requestWindowFeature(Window.FEATURE_NO_TITLE);

                getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);

                setContentView(R.layout.activity_main);

                ........
        }
        @Override
        public void onWindowFocusChanged(boolean hasFocus) {
                super.onWindowFocusChanged(hasFocus);
                if (hasFocus) {
                    // Standard Android full-screen functionality.
                    getWindow()
                            .getDecorView()
                            .setSystemUiVisibility(
                                    View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                                            | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                                            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                                            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                                            | View.SYSTEM_UI_FLAG_FULLSCREEN
                                            | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
                    getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
                }
        }

**Comment by Chihiro23333** [comment]
我发现好像是因为popwindow获取焦点的问题  焦点设为false就好了

**Comment by littleylv** [comment]
@razerdp 您好，Candy:2.0.1-alpha 1 还是存在这个问题。这个可以解决吗？

**Comment by razerdp** [comment]
@littleylv  0.0还是存在吗，，，好神奇- -我上次测试的时候已经不存在了。。。我明天看看

**Comment by littleylv** [comment]
@razerdp  我建了个demo，你可以试一下：[https://github.com/littleylv/BasePopupDemo](https://github.com/littleylv/BasePopupDemo)

我使用的是 Google Pixel + 8.1.0

**Comment by ParfoisMeng** [comment]
mark

**Comment by razerdp** [comment]
@littleylv 
@Chihiro23333 

candy 2.1.8-beta1 修复了这个问题，目前还在测试中，如果出现了问题请务必反馈一下哈~

**Comment by lly7690** [comment]
@razerdp 弹出POPUPWINDOW的时候还是会弹出导航栏（虚拟键），是要做什么设置吗？

**Comment by razerdp** [comment]
@lly7690 不会了吧，我这里已经测试过了。。。。你的版本以及你的代码，单独提个issue
