### ISSUE TITLE
java.lang.NoClassDefFoundError: razerdp.basepopup.BasePopupWindow$4 在自己的项目中使用遇到的错误

### ISSUE THREAD

**Issue by William-Kaiser** [razerdp/BasePopup#6]
![image](https://cloud.githubusercontent.com/assets/17757880/20128428/e04ea63c-a682-11e6-85bd-79038e4e8977.png)

**Comment by razerdp** [comment]
@William-Kaiser 目前看起来只能知道找不到类，但原因尚不清楚。。。可以从下面几个方向找一下：JDK版本是否一致？或者是否混淆过（实际上，我自测过混淆无影响的）？系统版本等（最低11）
