### ISSUE TITLE
Android 8.0 蒙层背景只是包裹内容，没有填充屏幕

### ISSUE THREAD

**Issue by PiYun01** [razerdp/BasePopup#61]
### 重现步骤

必现

### 报错信息/系统版本

Android 8.0  华为Mate9

### 建议或优化点

**Comment by razerdp** [comment]
你好，已经发布了预览版本，请更新到Candy版本。

**Comment by razerdp** [comment]
ps，**Candy**版本并不是**稳定版**，问题反馈收集后修正并验证过才发布的正式版，如果您使用过程中发现有无法接受的问题，可以先更换到上一个正式版使用并反馈到github issue
