### ISSUE TITLE
demo 中的CommonPopup 在 8.0系统中崩溃

### ISSUE THREAD

**Issue by weitto** [razerdp/BasePopup#63]
### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
api 27没有报错。请查证

**Comment by mppy1** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void razerdp.basepopup.HackWindowManager.bindPopupHelper(razerdp.basepopup.BasePopupHelper)' on a null object reference
        at razerdp.basepopup.BasePopupWindowProxy.bindPopupHelper(BasePopupWindowProxy.java:85)
        at razerdp.basepopup.BasePopupWindow.initView(BasePopupWindow.java:280)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:264)

**Comment by mppy1** [comment]
8.0的模拟器中崩溃了。日志如上所示。

**Comment by mppy1** [comment]
是Android P里面崩的。27是正常的。

**Comment by manburenshenglu** [comment]
android 9.0华为手机崩溃，相同的错误日志： Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void razerdp.basepopup.HackWindowManager.bindPopupHelper(razerdp.basepopup.BasePopupHelper)' on a null object reference

**Comment by razerdp** [comment]
更新到最新，android p是2.1版本后支持的，另，请不要再close的issue里提issue.

**Comment by manburenshenglu** [comment]
好的，谢谢
