### ISSUE TITLE
大神要解决7.0以上屏幕铺满的问题哦

### ISSUE THREAD

**Issue by controlFate** [razerdp/BasePopup#64]
### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
8.0的优化仍在进行~近期会推出一个版本的。。。

**Comment by razerdp** [comment]
你好，已经发布了预览版本，请更新到**Candy**版本。

**Comment by razerdp** [comment]
ps，**Candy**版本并不是**稳定版**，问题反馈收集后修正并验证过才发布的正式版，如果您使用过程中发现有无法接受的问题，可以先更换到上一个正式版使用并反馈到github issue
