### ISSUE TITLE
求助，Service里无法弹出

### ISSUE THREAD

**Issue by 893193074** [razerdp/BasePopup#65]
### 该问题是怎么引起的？
实例化的时候传Service自带的context(就是this),getApplicationContext(),和我自己记录在application里的activity，都无法使popupwindow弹出。

### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
applicationcontext因为没有windowtoken，所以是无法弹出的。

你需要一个activity的window

**Comment by 893193074** [comment]
实例化的时候传activity也不行呀，window需要在哪设置呢

**Comment by razerdp** [comment]
activity也不行么？

你的代码可以贴上来看看

**Comment by razerdp** [comment]
是的，因为context是applicationcontext，这个是不可以显示popup的。因为popup的window type原因，必须依附在某个window下面，所以service里面不可以直接show哦，你可以在service里面发出一个事件，在activity里面处理事件并显示popup

**Comment by 893193074** [comment]
谢谢解答，我需要做一个全局不依赖activity的弹窗，我去试试dialog或者activity

**Comment by razerdp** [comment]
ya，建议用dialog，不过记得加权限
