### ISSUE TITLE
Candy版本反馈(Report)

### ISSUE THREAD

**Issue by razerdp** [razerdp/BasePopup#66]
如果使用Candy版本出现问题，请在这里反馈。
集中处理后将会发布正式版本（一般经历2个preview版本后发布）

**反馈格式请遵循以下格式，格式不对的话不优先处理。**

**Comment by razerdp** [comment]
2.1.3-alpha暂无问题，发布release

**Comment by lly7690** [comment]
库版本 'com.github.razerdp:BasePopup_Candy:2.1.8-beta7'
系统版本 4.4.2
问题详情、异常提示
锁屏再进来 NAVIGATIONBAR又出现了
4.4.2下 弹出POPUPWINDOW后底部还是有一小段原色区域（比导航栏矮3/4）
代码定位 无

**Comment by lly7690** [comment]
库版本 'com.github.razerdp:BasePopup_Candy:2.1.8-beta7'
系统版本 4.4.2
问题详情、异常提示
POPUPWINDOW 设置MATCH_PARENT MATCH_PARENT 后下面会有一小块原色区域  点击原来导航栏的区域，POPUPWINDOW关闭（此时POPUPWINDOW应该为全屏）  即使设了POPUPWINDOW FULLSCREEN为TRUE还是一样有这个问题
代码定位 无

**Comment by razerdp** [comment]
上述问题皆已解决

**Comment by 869339820** [comment]
库版本BasePopup_Candy:2.2.2.190816
系统版本 Android7.0
调用update方法修改宽高或修改xy轴会触发APP ANR

代码定位
![image](https://user-images.githubusercontent.com/32284859/63313081-e5f17380-c335-11e9-8618-bb3f2b14c355.png)

**Comment by razerdp** [comment]
@869339820 收到，目前最新版的candy尚在重构中~感谢您提供的反馈-V-

**Comment by razerdp** [comment]
@869339820 新版已经修复了，不过暂时没有发版~下一个candy发布后可以更新到下一个candy哈
