### ISSUE TITLE
module里如何使用

### ISSUE THREAD

**Issue by zl277287818** [razerdp/BasePopup#67]
### 该问题是怎么引起的？
module里面引入这个库
会报这个错误。目测和#8 问题一样
java.lang.NoClassDefFoundError: Failed resolution of: Lrazerdp/library/R$style;
                      at razerdp.basepopup.BasePopupHelper.setNeedPopupFadeAnima(BasePopupHelper.java:172)

**Comment by zl277287818** [comment]
定位到这里了
popupWindow.setAnimationStyle(needPopupFadeAnima ? R.style.PopupAnimaFade : 0);

**Comment by zl277287818** [comment]
目前我把源码直接导入到Moudle里了，是可以的，不知道为啥引用的形式 报找不到style的错误。
求解答，求增长知识

**Comment by razerdp** [comment]
你好，这个错误本不应该会产生的，因为style是封装到库里面的。

如果遇到这个问题：
1 - 尝试clean或rebuild
2 - 更新到新的版本或者candy版（candy版需要你clean一次，否则会跟正式版的冲突）

module里面引用，在我的朋友圈工程也是module引用。

https://github.com/razerdp/FriendCircle/blob/master/circle_base_library/build.gradle#L45

你可以看一下，我这边是没有任何问题的

**Comment by zl277287818** [comment]
好的 谢谢。

**Comment by razerdp** [comment]
另外,请附带版本以及确认下有没有发生冲突

比如
anim下的basepopup_fade_in，如果有同样的资源名，可能会冲突。

**Comment by zl277287818** [comment]
用的是 1.9.3 版本，同名问题我专门检查了，没有问题的。

**Comment by zl277287818** [comment]
我怀疑可能是 fat-aar 的问题
