### ISSUE TITLE
老哥 提个需求你帮忙看下有没办法实现

### ISSUE THREAD

**Issue by zzjian** [razerdp/BasePopup#68]
popupWindow里有edittext需要获取焦点，并且popupWindow外的控件也需要可以直接点击。
现在设置`setFocusable(true);`后popupWindow外的控件就没办法点击了。 有没办法兼容两者

**Comment by razerdp** [comment]
[#54](https://github.com/razerdp/BasePopup/issues/54)

**Comment by zzjian** [comment]
谢谢大佬确实能解决我的问题。不过我现在用`setTouchInterceptor` 也能大致解决我的需求。反射hack `PopupDecorView` 的话感觉代价有点大
