### ISSUE TITLE
请问activity开启一个popupwindow然后点击如何把值传回activity？

### ISSUE THREAD

**Issue by OathkeeperDL7** [razerdp/BasePopup#69]
请问activity开启一个popupwindow然后点击如何把值传回activity？

**Comment by razerdp** [comment]
你好，你可以自己实现接口和回调的。

例如：[commentpopup](https://github.com/razerdp/BasePopup/blob/master/app/src/main/java/razerdp/demo/popup/CommentPopup.java#L153)
