### ISSUE TITLE
2.0新版不能响应点击事件

### ISSUE THREAD

**Issue by Damon-wei** [razerdp/BasePopup#7]
更新2.0新版后不能响应点击事件，你可以看下你的demo里的menu popup里text 的点击也是没有反应的。

**Comment by razerdp** [comment]
@Damon-wei 谢谢反馈，刚刚试了一下确实是这样，我现在去看看

**Comment by razerdp** [comment]
@Damon-wei  

您好，现在可以了，是我的锅，修改方法名字的时候没有仔细检查了。。。。非常抱歉

请更新到1.3.0版本，另外这次的改动是大规模改动方法名字的，以前的方法将会被改变或者拥有别的功能，如果您工程里大量使用了，可能改动较大，对此造成不便，深表歉意

**Comment by razerdp** [comment]
@Damon-wei 如果没什么大问题的话，这个issue由您来关闭如何。

**Comment by Damon-wei** [comment]
好的，我先回退为老版本了，随后改下。辛苦啦！
