### ISSUE TITLE
android7.1.1小米6手机使用继承自BasePopupwindow的子类做加载等待进度条出现,popupwind调用dissmiss()方法无效

### ISSUE THREAD

**Issue by xuefeiyao** [razerdp/BasePopup#72]
### 该问题是怎么引起的？
E/BasePopupWindow: catch an exception on showing popupwindow ...now retrying to show ... retry count  >>  0

### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
你好，请贴一下代码，。
