### ISSUE TITLE
setAutoLocatePopup(true);无效，

### ISSUE THREAD

**Issue by wang869755676** [razerdp/BasePopup#74]
### 重现步骤

当popupWindow里面是RecyclerView，无效

### 报错信息/系统版本

```java

```

### 建议或优化点
     应该是getHegith 的问题

**Comment by razerdp** [comment]
您好，请问有具体的布局参数吗，。

**Comment by t2314862168** [comment]
@razerdp @wang869755676  我试了下RecyclerView,如果RecyclerView的高度是根据child确定的,断点看了下calculateOffset这个方法里面onTop是false,下面是布局文件
```java
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/rv_popup"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scrollbars="none" />
</LinearLayout>
```
RecyclerView的item布局用的是你的demo里面布局文件就不粘贴了;原因是
```java
 boolean onTop = this.getScreenHeight() - (this.mHelper.getAnchorY() + offset[1]) < this.getHeight();
```
这里的 this.getHeight()为0；请教下有没有相关的解决办法呢

**Comment by razerdp** [comment]
@t2314862168 是的，实际上popupwindow本来在没展示之前是无法获取宽高的，在库里我强制measure了一次，因此可以获得一个接近实际的宽高，但是因为recyclerview在绑定adapter之后才开始measure，因此我提前measure实际上是没有效果的。

如果要解决这个问题。。。。emmmmm，实际上我好像没有一个特别好的方案，无论是回调还是什么，因为autoLocated必须得在展示前完成所有计算。而用户绑定adapter或者更新adapter是随机的，没有按照证明周期来。

这个问题我先标记下，reopen，如果以后有新的想法我再回来通知。

**Comment by SageLu** [comment]
@razerdp  setAutoLocatePopup(true)  recyclerview 这个问题有好的解决方案吗？

**Comment by razerdp** [comment]
有，下一个版本已经解决了。但是还没发布，2.1.0-alpha2（candy）可以尝试下。

**Comment by razerdp** [comment]
稳定版的话可能会挺久，因为需要candy经过了考验才会发布的稳定版。。。。建议你可以尝试开个demo来进行candy版本的测试~然后有bug的话可以提出-V- 这样可以尽快找到一些别的问题。

**Comment by razerdp** [comment]
@SageLu  可以尝试下2.1.0-beta4，明天我完善下文档，到时候可能会更直观。

2.1.0相比之前的有重大升级，，使用更方便

**Comment by razerdp** [comment]
@SageLu @t2314862168 @wang869755676  2.1.1-release已修复，2.1.1版本是对2.0的全面优化，wiki和readme有详细说明，升级后遇到可能存在的适配问题请记得看哦~BasePopup将会越来越好用-V-
