### ISSUE TITLE
2.0版本，不能设置背景为drawable，只能设置颜色

### ISSUE THREAD

**Issue by tpnet** [razerdp/BasePopup#79]
### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
你好，你可以设置背景颜色为透明，然后自己布局内背景给drawable

**Comment by razerdp** [comment]
或者我在下一个版本添加这个功能

**Comment by tpnet** [comment]
@razerdp  嗯，你第一种办法就没办法分开设置动画了

**Comment by razerdp** [comment]
代码已添加，等正式版发布，，现在还在beta，下一个版本就发布release

**Comment by tpnet** [comment]
设置背景好像只能在初始化的时候设置，不能在初始化之后再单独设置？？？

**Comment by razerdp** [comment]
你好，可以的，不过在下一次show的时候才会生效，。因为目前并不打算允许即刻变更。

**Comment by razerdp** [comment]
2.0.1-alpha1已经发布（Candy）
