### ISSUE TITLE
遇到一个错误

### ISSUE THREAD

**Issue by wenchaosong** [razerdp/BasePopup#8]
java.lang.NoClassDefFoundError: razerdp.library.R$style 
    at razerdp.basepopup.BasePopupWindow.initView(BasePopupWindow.java:70)
    at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:51)

this.mPopupWindow.setAnimationStyle(style.PopupAnimaFade);

找不到这个 style

我依赖的是 compile 'com.github.razerdp:BasePopup:v1.1.7'  
我前几分钟还可以点，过了会就报这个错

**Comment by razerdp** [comment]
@wenchaosong 如果您在工程使用不多，可以考虑更新到1.3.0或者1.4.0（1.3.0版本开始有些方法名字和成员变量权限修饰改动了，如果短时间内无法进行大面积重构，可以考虑更新到1.2.0），style文件是在lib下的，尝试一下clean然后rebuild工程试试。

**Comment by razerdp** [comment]
@wenchaosong 请问现在还出现这个问题吗
