### ISSUE TITLE
隐藏的底部导航栏被popup自动唤起（返回键、音量键那栏）

### ISSUE THREAD

**Issue by breakoutcat** [razerdp/BasePopup#80]
### 该问题是怎么引起的？
activity和popup里都没edittext
1.activity中先把底部导航栏隐藏掉，
2.启动popup ，然后底部导航栏就自动弹出来

### 报错信息/系统版本
5.1.1

**Comment by razerdp** [comment]
2.0我去解决，。进去开始更新2.0

**Comment by breakoutcat** [comment]
好像跟隐藏底部导航栏的方式有关，如果用厂商提供的方法就不会再弹出，否则就属于上滑显示底部导航栏

**Comment by razerdp** [comment]
#59
