### ISSUE TITLE
BasePopup 没有设置pop 具体位置的方法吗?

### ISSUE THREAD

**Issue by OpenSourceMIUI** [razerdp/BasePopup#81]
需求:  toolbar上有个按钮, 点击弹出pop, 是需要在toolbar下方的与toolbar 水平平行

BasePopup 没有设置pop 具体位置的方法吗?

**Comment by razerdp** [comment]
你好，请查看wiki
https://github.com/razerdp/BasePopup/wiki/%E4%BD%8D%E7%BD%AE%E7%AF%87
