### ISSUE TITLE
默认是从下往上弹窗 怎么从下网上弹呀

### ISSUE THREAD

**Issue by androidJiam** [razerdp/BasePopup#82]
### 该问题是怎么引起的？
例如最下面有个button  我要popupwindow从button往上弹
现在默认是往下弹的

### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
showPopupWindow(View v)，把button传进去，另外popup里面的动画修正一下

**Comment by androidJiam** [comment]
![w 7 775y lx75 0dfxmvio](https://user-images.githubusercontent.com/13191567/45133698-48a33b00-b1c9-11e8-95d1-7e30df634e76.png)

麻烦看下图上内容  各种调属性还是没达到效果

**Comment by androidJiam** [comment]
![w 7 775y lx75 0dfxmvio](https://user-images.githubusercontent.com/13191567/45137531-a771b000-b1db-11e8-950e-b89e3b0cbbc2.png)
应该是位置问题  麻烦看下怎么解决  试了不少方法都不行

**Comment by razerdp** [comment]
你好，我写了个新的demo
https://github.com/razerdp/BasePopup/blob/HEAD/app/src/main/java/razerdp/demo/fragment/LocatePopupFrag.java

同时您也可以下载工程查看示例
