### ISSUE TITLE
稳定版版本过低过旧   input PopupWindow  会卡在屏幕中间下不来

### ISSUE THREAD

**Issue by androidJiam** [razerdp/BasePopup#86]
### 该问题是怎么引起的？
设置底部弹出的 PopupWindow
弹出输入框后   PopupWindow 会卡在输入框弹出的位置  不会重新回到底部
参考过demo的做法  仍然无效
![Uploading 84FB9DFDB759EFDAAE2459C54130D47C.png…]()
![Uploading 40F58102CF8DB7A0C3CDC402B4AAECF4.png…]()
![Uploading 5965FD48362E9BD118A54EE159E823F5.png…]()

### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
你好，图片失效。。。。

**Comment by androidJiam** [comment]
![default](https://user-images.githubusercontent.com/13191567/46589819-c7e5a080-cae0-11e8-9132-975429c02bfd.png)
![default](https://user-images.githubusercontent.com/13191567/46589835-e3e94200-cae0-11e8-9d94-93526f282d2d.png)
![default](https://user-images.githubusercontent.com/13191567/46589856-0d09d280-cae1-11e8-9670-d312186e4093.png)
以上是图片效果
你demo用的 2.0.1的Candy版， 我用的1.9.4正式版  现在改成你2.0.1的Candy版本  所有方法都要重新实现。。。

**Comment by razerdp** [comment]
可以参考 [1.x迁移2.x帮助文档](https://github.com/razerdp/BasePopup/blob/HEAD/1.x%E8%BF%81%E7%A7%BB2.x%E5%B8%AE%E5%8A%A9%E6%96%87%E6%A1%A3.md)

额。。。2.0开始是一个重构版本，所以对1.x不合理的地方进行了优化了，所以看起来多数方法你都要重新实现，实际上写的不多

**Comment by androidJiam** [comment]
只是介绍说1.9.4才是稳定版 才用的1.9.4   现在是可以更新到2.0了吗  是不是2.0已经是最新稳定版了

**Comment by razerdp** [comment]
是的，目前您可以通过jitpack渠道升级到2.0.5-alpha，因为bintray-release插件暂时失效，所以我一直没更新到maven，近期将会更新上去的了

**Comment by androidJiam** [comment]
好的。 那现在最新能引用的是哪个地址呀  只有 2.0.1-alpha1 可行  但是input 还是和图片问题一样  
引用2.0.5-alpha gradel不成功

**Comment by androidJiam** [comment]
就是如图上所示  dialog不会随着输入法隐藏而回到底部  弹出输入法  dialog就会卡在中间  下不来了

**Comment by razerdp** [comment]
你上面的图中，那个输入框（底下有个图片和发送按钮那里）就是popup吗

**Comment by razerdp** [comment]
。。。要不你加群说一下，，因为有点模糊
