### ISSUE TITLE
多个popupWindows叠加的时候，activity onPause然后重新onResume会导致popupWindows叠加顺序改变

### ISSUE THREAD

**Issue by tpnet** [razerdp/BasePopup#89]
### 该问题是怎么引起的？

显示了两个popupWindows，然后在popupWindows不消失的情况下新打开了另一个activity，然后关掉这个新的activity，会导致popupWindows叠加顺序改变，之前在底部的popupWindows到了最上层了

### 重现步骤

导入demo源码，在ScalePopup49行添加一行代码：
```
                new DialogPopup((Activity) getContext()).showPopupWindow();
```
运行之后，在缩放Popup 点击第一个，手机锁屏，然后解锁，可以看到这时候显示的是 test1 的列表

### 报错信息/系统版本

木有报错信息，魅蓝m1 note, Android版本5.1，flyme6.3.0.2A

```java

```

### 建议或优化点

不知道啥问题

**Comment by tpnet** [comment]
魅族16, Android8.1 没有问题，，好像是低版本的Android才会这样

**Comment by razerdp** [comment]
我明天看看

**Comment by razerdp** [comment]
已解决，请更新candy版： 2.0.8-alpha3

**Comment by razerdp** [comment]
2.1.0-beta (candy)解决。将在后续发布release

**Comment by tpnet** [comment]
@razerdp 卧槽 ，牛逼，怎么解决的，还没看到commit
