### ISSUE TITLE
OnDismissListener的一个BUG

### ISSUE THREAD

**Issue by ping999** [razerdp/BasePopup#9]
`public void onSuccess(String s, Call call, Response response) {
                        TL_info tl_info = GsonUtilsZcyke.GsonToBean(s, TL_info.class);
                        if (tl_info.isIsSuccessful()) {
                            netLoadingPopup.setOnDismissListener(new BasePopupWindow.OnDismissListener() {
                                @Override
                                public void onDismiss() {
                                    startActivityAnim(HWStreamActivity.class);
                                }
                            });
                        } else {
                            showToast("初始化失败，请重试");
                        }
                    }

                    @Override
                    public void onBefore(BaseRequest request) {
                        super.onBefore(request);
                        showNetLoading();
                    }

                    @Override
                    public void onAfter(@Nullable String s, @Nullable Exception e) {
                        super.onAfter(s, e);
                        dismissNetLoading();
                    }

                    @Override
                    public void onError(Call call, Response response, Exception e) {
                        super.onError(call, response, e);
                        showToast("网络异常");
                    }`
现象：网络请求未Error，startActivityAnim(HWStreamActivity.class);也会调用
粗略解释：在结合使用网络框架时，网络请求为Error，OnDismissListener也会强行调用

**Comment by razerdp** [comment]
@ping999  好的，我稍后看看

**Comment by razerdp** [comment]
@ping999 请问您用的是哪个版本

**Comment by ping999** [comment]
你好！用的是v1.3.0

**Comment by razerdp** [comment]
@ping999 ok了，更新到1.4.3试试

**Comment by razerdp** [comment]
@ping999 如果更新后没问题，这个issue由您关闭了哦

**Comment by ping999** [comment]
好的，感谢！

**Comment by razerdp** [comment]
不用-V- 如果有什么改进意见或者bug，欢迎继续提issue

**Comment by ping999** [comment]
_-_，还是有这个BUG额

**Comment by ping999** [comment]
_-_，还是有这个BUG额

**Comment by razerdp** [comment]
是这样的，setOnDismissListener在你设置过一次之后，该callback就被传递进去了，从你的代码上看，似乎是想tl_info.isIsSuccessful()的时候才执行。

但是，问题在于如果你有一次成功了，callback被设置进去了，但是下一次没有成功，如果popup被dismiss了，由于callback的存在，所以依然会回调回去的。

因此在你不需要的时候，你应该setOnDismissListener(null);

**Comment by ping999** [comment]
OK，感谢，这样可行

**Comment by ping999** [comment]
那我把这个issue关咯

**Comment by razerdp** [comment]
这里按照我的想法，提供两个方法，您可以试试

***方法1***

```java

    public void onSuccess(String s, Call call, Response response) {
        TL_info tl_info = GsonUtilsZcyke.GsonToBean(s, TL_info.class);
        netLoadingPopup.setOnDismissListener(new BasePopupWindow.OnDismissListener() {
            @Override
            public void onDismiss() {
                if (tl_info.isIsSuccessful()){
                    startActivityAnim(HWStreamActivity.class);
                }else{
                    showToast("初始化失败，请重试");
                }
            }
        });

    }
```

***方法2***
```java
    public void onSuccess(String s, Call call, Response response) {
        TL_info tl_info = GsonUtilsZcyke.GsonToBean(s, TL_info.class);
        if (tl_info.isIsSuccessful()) {
            netLoadingPopup.setOnDismissListener(new BasePopupWindow.OnDismissListener() {
                @Override
                public void onDismiss() {
                    startActivityAnim(HWStreamActivity.class);
                }
            });
        } else {
            netLoadingPopup.setOnDismissListener(null);
            showToast("初始化失败，请重试");
        }
    }
```

**Comment by razerdp** [comment]
好的
