### ISSUE TITLE
popup上在使用popup，第二层的不会在指定的控件下面

### ISSUE THREAD

**Issue by CotTan** [razerdp/BasePopup#92]
### 该问题是怎么引起的？
![default](https://user-images.githubusercontent.com/11958737/47543709-2ea6ee80-d916-11e8-9e38-3fbea24e81d7.png)

![default](https://user-images.githubusercontent.com/11958737/47543762-57c77f00-d916-11e8-8cbe-11a85e4ecebc.png)
![default](https://user-images.githubusercontent.com/11958737/47543785-7594e400-d916-11e8-8be4-0cca078c3db7.png)
![default](https://user-images.githubusercontent.com/11958737/47543796-7d548880-d916-11e8-8454-a6d777890f24.png)

### 报错信息/系统版本
稳定版
```java

```

### 建议或优化点

**Comment by tpnet** [comment]
最新测试版修复了

**Comment by razerdp** [comment]
@CotTan  你好，popup不可以以上一个popup的view作为anchorView的，否则会报BadToken异常。

**Comment by razerdp** [comment]
@CotTan 建议您用位移解决，为此我在scalePopup上进行了一丢丢的改动，希望能给你提供方向。

[](https://img.kuibu.net/temp/1810/5ade49f0bbb0c818.png)
