### ISSUE TITLE
back键和点击阴影部分有时候不dismiss

### ISSUE THREAD

**Issue by shoucanjun** [razerdp/BasePopup#94]
### 该问题是怎么引起的？
小米机子
back键和点击阴影部分有时候不dismiss

### 重现步骤
默认的构造方法
super(activity);
直接showPopupWindow();
有时候可以dismiss，有时候就失灵。
### 报错信息/系统版本
android 7.1
```java

```

### 建议或优化点

**Comment by razerdp** [comment]
show me your code

**Comment by shoucanjun** [comment]
public class DialogContactBox2 extends BasePopupWindow {

    private int direction = Direction_Bottom;
    public static final int Direction_Bottom = 0;
    public static final int Direction_Top = 1;


    public DialogContactBox2(Activity activity, int direction) {
        super(activity);
        this.direction = direction;
        initView();
        if (direction == Direction_Bottom) {
            layout.setGravity(Gravity.BOTTOM);
            setShowAnimation(createVerticalAnimation(1f, 0));
            setDismissAnimation(createVerticalAnimation(0, 1f));
            tipLayout.setVisibility(View.VISIBLE);
        } else {
            layout.setGravity(Gravity.START);
            setShowAnimation(createVerticalAnimation(-1f, 0));
            setDismissAnimation(createVerticalAnimation(0, -1f));
            tipLayout.setVisibility(View.GONE);
        }

    }

    @Override
    public View onCreateContentView() {
        return createPopupById(R.layout.dialog_contactbox2);
    }

    public void show(View v) {
        if (direction == Direction_Bottom) {
            showPopupWindow();
        } else {
            showPopupWindow(v);
        }
    }


    private Animation createVerticalAnimation(float fromY, float toY) {
        Animation animation = new TranslateAnimation(Animation.RELATIVE_TO_SELF,
                0f,
                Animation.RELATIVE_TO_SELF,
                0f,
                Animation.RELATIVE_TO_SELF,
                fromY,
                Animation.RELATIVE_TO_SELF,
                toY);
        animation.setDuration(400);
        animation.setInterpolator(new DecelerateInterpolator());
        return animation;
    }


    private ContactBoxAdapter adapter;
    private MaxHeightRecycleView rv;


    private List<ContactBean> datas = new ArrayList<>();

    public void loadDatas(List<ContactBean> datas) {
        this.datas = datas;
        adapter.replaceAllData(datas);
    }


    private TextView tip;

    private RelativeLayout layout;
    private LinearLayout tipLayout;

    private void initView() {
        tipLayout = findViewById(R.id.dialog_contactbox_tiplayout);
        layout = findViewById(R.id.dialog_contactbox_layout);
        tip = findViewById(R.id.dialog_contactbox_tip);
        rv = findViewById(R.id.dialog_contactbox_rv);
        rv.setHeightMax(300);
        layout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                dismiss();
            }
        });
        ArrayViewFactory.newInstance(getContext()).initVerticalRvBase(rv).setIsNeedLine(true).setHasFootLine(true);
        rv.setAdapter(adapter = new ContactBoxAdapter());
    }


}


xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/dialog_contactbox_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">


    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <LinearLayout
            android:id="@+id/dialog_contactbox_tiplayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <TextView

                android:id="@+id/dialog_contactbox_tip"
                style="@style/h_text_medium4_singleLine"
                android:layout_width="match_parent"
                android:background="@color/h_backgroud"
                android:padding="10dp"
                android:text="已选0人"
                android:textColor="@color/h_black" />

            <View style="@style/h_grey_line_horizontal" />
        </LinearLayout>

        <MaxHeightRecycleView
            android:id="@+id/dialog_contactbox_rv"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/white"
            android:paddingLeft="10dp" />
    </LinearLayout>
</RelativeLayout>

**Comment by razerdp** [comment]
收到，这里是我处理不当.，没有考虑popup是多个view组合的情况。

当前版本有两个处理方式（推荐第二个）：

1 - 布局里将两个子控件包裹多一层LinearLayout
2 - 构造方法里调用 setIgnoreDismissView()随便设一个view，这个用于指定触碰后非dismiss的view，当调用了该方法，在父类的404行[L404](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/BasePopupWindow.java#L404)就知道应该dismiss的范围.

这里的逻辑我需要再次斟酌，针对多个view的布局，下次更新在candy更新后我会在这里标注一下~

感谢您的反馈-V-

**Comment by shoucanjun** [comment]
thx! you save my time

**Comment by shoucanjun** [comment]
@razerdp 话说用了方法二还是会出现那个问题诶。
