### ISSUE TITLE
 从顶部下滑的Poup

### ISSUE THREAD

**Issue by KAICW** [razerdp/BasePopup#97]
### 该问题是怎么引起的？
在popup中有edittext,布局文件比较长，键盘弹出会盖住一部分布局，在隐藏键盘，底部控件会被切掉少一部分

### 重现步骤
在popup中有edittext,布局文件比较长，键盘弹出会盖住一部分布局，在隐藏键盘，底部控件会被切掉少一部分

### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
您好，截图和代码提供一下？

**Comment by KAICW** [comment]
![image](https://user-images.githubusercontent.com/10645583/48106884-5aac6300-e278-11e8-9e9e-5d920a6f0970.png)
这是未弹出键盘的样子
![image](https://user-images.githubusercontent.com/10645583/48106929-829bc680-e278-11e8-9982-1de7b65f40c6.png)
这是弹出键盘的样子
![image](https://user-images.githubusercontent.com/10645583/48106944-921b0f80-e278-11e8-8782-597b50f3a080.png)
这是键盘收回的样子
代码很简单只要是布局比较长，更具demo 非全屏Poup把布局文件替换了

**Comment by KAICW** [comment]
@razerdp 已经可以了，非常感谢
