### ISSUE TITLE
取消popwindow的背景

### ISSUE THREAD

**Issue by yishangfei** [razerdp/BasePopup#98]
### 该问题是怎么引起的？

![image](https://user-images.githubusercontent.com/15099278/48186476-0a65fb80-e373-11e8-9f67-8c7ce5ba9ddb.png)

![image](https://user-images.githubusercontent.com/15099278/48186788-11413e00-e374-11e8-9253-6130c21f1972.png)

想问一下怎么取消这个灰色的浮层      我看一下貌似只找到了背景模糊  设置setBackgroundColor 就变第二个了。。。

### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by tpnet** [comment]
setBackgroundColor(Color.TRANSPARENT)

**Comment by razerdp** [comment]
setBackground(0);
